// MP_04 — Rechtliche Ordnung von Unterricht und Erziehung
// PDF-Abschnitt 4 (Skript zum Schulrecht 2024 — Stephan Bauer):
//   Unterrichtsbetrieb · LNW/Noten/Zeugnisse · Vorrücken · Abschlüsse + Prüfungen · Hausaufgaben · Ordnungsmaßnahmen (→ mp03)
window.MODULE = {
  id: 'mp04',
  zalgm: 'ZALGM § 16 Nr. 4',
  schwerpunkt: ['4.1 Schullaufbahn-Trias', '4.2 LNW + Noten ({{Art. 52}})', '4.3 Vorrücken ({{Art. 53}} + § 12 MSO)', '4.4 Hausaufgaben + Förderplan', '4.5 MS-Abschlüsse + Prüfungen'],
  titel: 'Rechtl. Ordnung',
  titel2: 'Unterricht + Erziehung.',
  abriss:
    'Trias SuS/EB/Schule: Eltern wählen (Art. 44, gebunden an Eignung), Schule ' +
    'berät (Art. 78), Lehrerkonferenz entscheidet (Art. 53). Verfassungs-Anker ' +
    'BV Art. 132 Anlagen+Leistung+innere Berufung. Vier MS-Abschlüsse.',

  kurz: [
    'Trias SuS/EB/Schule: Eltern wählen Schulart ({{Art. 44 BayEUG}} — gebunden an **Eignung + Leistung** nach BV Art. 132). Schule **berät** strukturell ({{Art. 78 BayEUG}}). Lehrerkonferenz entscheidet über Vorrücken/Wiederholung ({{Art. 53 BayEUG}}).',
    'LNW-Grundlagen {{Art. 52 BayEUG}} Abs. 1: Art, Zahl, Umfang vorher bekanntgeben; Bewertung mit Notenstufe + Begründung eröffnen. **LNW dienen Bewertung UND Beratung.** Notenstufen Art. 52/2 verbatim — „in besonderem Maße / voll / im Allgemeinen / im Ganzen noch / Grundkenntnisse vorhanden".',
    '§ 12/3 MSO KRITISCH-Falle: **zwei Direktionalitäten** in einem Absatz — LK→SuS „**angemessene Frist**" (KEIN konkreter Wert), SuS→Schule „**innerhalb einer Woche unverändert**". Eltern-Kenntnisnahme als Zwischenschritt.',
    'M-Zug-Schwellen § 7 MSO: M7 ≤ **2,66** (D+M+E) · M8/M9/M10 ≤ **2,33**. M10 zusätzlich Quali-Voraussetzung. Rückkehr MS↔M-Zug jederzeit (§ 8 MSO). Art. 7a BayEUG ≠ 7b ≠ Art. 30a/4 (Profil Inklusion) — drei verschiedene Anker.',
    'Vier MS-Abschlüsse + Quabi: **ESA** (Ende 9., MSO §§19ff) · **Quali** (50% Jahr + 50% Prüfung + Projekt, KMBek QA-MS) · **MSA** (M10) · **Praxisklassen-Abschluss** ({{§ 22 MSO}} — 9. **Schulbesuchsjahr**, Projektnote DOPPELT) · **Quabi** ({{§ 34 MSO}} — Quali + Berufsabschluss ≥3,0 + Englisch „ausreichend").',
  ],

  deck: { cards: 8, normebenen: 5, hochprior: 8, fallen: 10 },

  kartografie: [
    { ebene: 'I', bez: 'Bay. Verfassung', kuerzel: 'BV', normen: ['Art. 128 BV', 'Art. 129 BV', 'Art. 132 BV', 'Art. 133 BV'], sub: 'Bildungsanspruch · Schulpflicht · **Anlagen+Leistung+innere Berufung** · Bildungsträger' },
    { ebene: 'II', bez: 'BayEUG', kuerzel: 'BayEUG', normen: ['Art. 7 BayEUG', 'Art. 7a BayEUG', 'Art. 7b BayEUG', 'Art. 35 BayEUG', 'Art. 41 BayEUG', 'Art. 43 BayEUG', 'Art. 44 BayEUG', 'Art. 52 BayEUG', 'Art. 53 BayEUG', 'Art. 76 BayEUG', 'Art. 78 BayEUG', 'Art. 86 BayEUG'], sub: 'MS/M-Zug · Schulpflicht · Lernort · Schulartwechsel · Elternwahl · LNW · Vorrücken · Beratung · OM' },
    { ebene: 'III', bez: 'Schulordnungen + LDO', kuerzel: 'VO', normen: ['§ 6 MSO', '§ 7 MSO', '§ 8 MSO', '§ 12 MSO', '§ 14 MSO', '§ 22 MSO', '§ 34 MSO', '§ 28 BaySchO', '§ 32 BaySchO', '§ 41/1 BaySchO', '§ 3 LDO'], sub: 'Gelenkklasse · M-Zug · Durchlässigkeit · LNW · Förderplan · Praxisklassen-Abschl. · Quabi · HA · Indiv. Unterstützung · Schülerakte · LNW-Aufbewahrung' },
    { ebene: 'IV', bez: 'KMBek', kuerzel: 'KMBek', normen: ['KMBek QA-MS', 'KMBek MSA', 'KMBek ext. Bewerbung'], sub: 'Quali · MSA · ext. Bewerbung (Volltext nicht öffentlich strukturiert)' },
    { ebene: 'V', bez: 'Bundesrecht', kuerzel: 'BUND', normen: ['Art. 12 GG', '§§ 1626 BGB'], sub: 'Berufswahl-Anker · Sorgerecht (Eltern-Antragsrecht)' },
  ],

  pflichtwissen: [
    { id: 'S01', titel: '§ 12/3 MSO Rückgabe — zwei Direktionalitäten',
      frage: 'Welche zwei Direktionalitäten regelt {{§ 12/3 MSO}} — und welcher Wortlaut gilt jeweils?',
      antwort: '**(a) LK → SuS** = **„angemessene Frist"** — KEIN konkreter Wert! „2 Wochen" wäre verbatim falsch. **(b) SuS → Schule** = **„innerhalb einer Woche unverändert"**. Eltern-Kenntnisnahme als Zwischenschritt (SuS → Eltern → Schule). „Unverändert" = keine Manipulation der Korrektur.',
      norm: '§ 12/3 MSO', status: 'open' },
    { id: 'S02', titel: 'Ankündigungs-Werte § 12/2 MSO',
      frage: 'Welche Frist-Werte regelt {{§ 12/2 MSO}}?',
      antwort: 'Ankündigung **1 Woche** vorher (bei größeren Lernabschnitten Pflicht). Max. **1 angekündigte LNW/Tag**. Max. **2 angekündigte LNW/Woche**. Nachtermin **1 Woche** vorher. Ersatzprüfung **2 Wochen** vorher. Ersatzprüfung **1×/Halbjahr**; kann gesamten bisherigen Stoff umfassen.',
      norm: '§ 12/2 MSO', status: 'open' },
    { id: 'S03', titel: 'Notenstufen Art. 52/2 BayEUG',
      frage: 'Wie lauten die Notenstufen-Definitionen verbatim?',
      antwort: '**1 sehr gut**: „in besonderem Maße". **2 gut**: „voll". **3 befriedigend**: „im Allgemeinen". **4 ausreichend**: „im Ganzen noch". **5 mangelhaft**: „nicht … jedoch trotz deutlicher Verständnislücken die notwendigen Grundkenntnisse vorhanden". **6 ungenügend**: „nicht … selbst die notwendigen Grundkenntnisse nicht erkennen".',
      norm: 'Art. 52 BayEUG', status: 'open' },
    { id: 'S04', titel: 'Förderplan § 14 MSO',
      frage: 'Wann ist Förderplan PFLICHT — und was sind die drei Pflicht-Inhalte?',
      antwort: 'Pflicht NUR wenn SuS „auf Grund ihres sonderpädagogischen Förderbedarfs voraussichtlich die Lernziele der Mittelschule **nicht erreichen**" — sonst optional („bei Bedarf"). **3 Pflicht-Inhalte**: Ziele · Fördermaßnahmen · Leistungserhebungen. **MSD-Einbeziehung Pflicht**. Erörterung Eltern **„soll"** (nicht muss). Mind. **jährlich fortzuschreiben**.',
      norm: '§ 14 MSO', status: 'open' },
    { id: 'S05', titel: 'M-Zug-Schwellen § 7 MSO',
      frage: 'Welche Schwellen gelten für die Aufnahme in den M-Zug (M7 bis M10)?',
      antwort: '**M7** ≤ **2,66** (D+M+E, aus Jahreszeugnis Jgst. 6). **M8 / M9 / M10** ≤ **2,33** (D+M+E). **M10** zusätzlich Quali-Voraussetzung aus 9. Klasse. **Rückkehr MS↔M-Zug jederzeit** ({{§ 8 MSO}}).',
      norm: '§ 7 MSO', status: 'open' },
    { id: 'S06', titel: 'Praxisklassen-Abschluss § 22 MSO',
      frage: 'Welche Struktur hat der Praxisklassen-Abschluss nach § 22 MSO?',
      antwort: '**9. Schulbesuchsjahr** (NICHT zwingend Jgst. 9 — wegen Wiederholern!) in Praxisklasse / Deutschklasse. Theorieentlastete Prüfung: **D/DaZ** schriftl. **75 Min.** + mündl. **15 Min.** · **M** schriftl. **60 Min.** · **Fächerverbund** schriftl. **45 Min.** · **Projektprüfung**. Bestehen Durchschnitt **≤ 4,0**. **Projektnote zählt doppelt**.',
      norm: '§ 22 MSO', status: 'open' },
    { id: 'S07', titel: 'Quabi § 34 MSO',
      frage: 'Welche Voraussetzungen hat der Quabi?',
      antwort: '(1) **Quali** als Vorbedingung. (2) **Berufsabschluss** mit Notendurchschnitt **mindestens 3,0** (= ≤ 3,0; nicht „besser als"). (3) **Englischkenntnisse** durch Note **„ausreichend"** (= mind. Note 4). **Quabi ≠ Quali ≠ MSA** — präzise trennen.',
      norm: '§ 34 MSO', status: 'open' },
    { id: 'S08', titel: 'Beratungs-Trias Art. 78 · Art. 44 · BV 132',
      frage: 'Wie verzahnen sich Beratung, Elternwahl und Verfassungs-Anker?',
      antwort: '**Schule berät** ({{Art. 78 BayEUG}}) — strukturell, keine Schulwahl-Entscheidung der LK. **Eltern wählen** ({{Art. 44 BayEUG}}) Schulart/Ausbildungsrichtung — **gebunden an Eignung + Leistung**. **BV Art. 132**: Maßstab = **Anlagen + Neigungen + Leistung + innere Berufung**, NICHT wirtschaftliche/gesellschaftliche Stellung der Eltern.',
      norm: 'Art. 78 BayEUG', status: 'open' },
    { id: 'S09', titel: '§ 3 LDO — LNW-Aufbewahrungsfrist (Schulrats-Lieblingsfalle)',
      frage: 'Wie lange müssen schriftliche Leistungsnachweise von der Schule aufbewahrt werden — und welche Norm regelt das?',
      antwort: '**{{§ 3 LDO}} Abs. 6**: schriftliche LNW sind **1 Jahr nach Ablauf des Schuljahres** aufzubewahren, in dem sie geschrieben wurden. Danach Vernichtung gemäß KMBek Schriftwesen. Abgrenzung: § 12/3 MSO regelt die **Rückgabe** an SuS („angemessene Frist") + die SuS-Pflicht zur Rückgabe an Schule („1 Woche unverändert"). Aufbewahrungs- + Rückgabefrist sind zwei verschiedene Anker. Klassische Schulrats-Frage.',
      norm: '§ 3 LDO', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: '§ 12/3 MSO Rückgabefrist als feste Wochen-Zahl?', antwort: 'NEIN. **„angemessene Frist"** (LK→SuS) bzw. **„einer Woche unverändert"** (SuS→Schule). Zwei Direktionalitäten! Kein konkreter Wochen-Wert für LK→SuS im Wortlaut.' },
    { id: 'FA02', frage: '„Mitarbeitsnote" als eigenständige Note?', antwort: 'NEIN. {{Art. 52 BayEUG}} Abs. 3: Zeugnis-Bewertung der **Gesamtleistungen**; daneben **soll**-Bemerkungen über **Anlagen, Mitarbeit und Verhalten** (Trias). Keine eigenständige Note.' },
    { id: 'FA03', frage: 'GS-Probearbeiten Jgst. 4 = „10/4/4 D/M/HSU" verbatim?', antwort: 'NEIN. GrSO § 10 sagt verbatim nur **„insgesamt 18"** + **„mind. 4 Wochen probearbeiten-frei"** in den drei Fächern; Verteilung 10/4/4 ist Sekundärliteratur. Cross-Ref MP_03 A.4.' },
    { id: 'FA04', frage: 'Projektprüfung § 12/4 MSO auch für M-Zug?', antwort: 'NEIN. Wortlaut: **„Regelklasse Jgst. 9"**. M-Zug hat eigene MSA-Prüfung in M10. Werte: Technik 240 Min · W+K 120 Min · E+S 150 Min · SL-Zeitzuschlag bis 20 Min für Gruppen-Komm.' },
    { id: 'FA05', frage: 'Förderplan immer Pflicht?', antwort: 'NEIN. {{§ 14 MSO}} Satz 1: Festschreibungs-Pflicht greift, wenn SuS aufgrund sonderpäd. Förderbedarfs die MS-Lernziele voraussichtlich nicht erreichen — sonst „bei Bedarf" zulässig.' },
    { id: 'FA06', frage: 'Quali = Quabi?', antwort: 'NEIN. **Quali** = freiwillige Ende-9-Prüfung (50% Jahresfortgang + 50% Prüfung + Projekt). **Quabi** ({{§ 34 MSO}}) = Quali + Berufsabschluss (≥ 3,0) + Englisch „ausreichend". MSA = M10-Abschluss.' },
    { id: 'FA07', frage: 'Praxisklassen-Abschluss = Jgst. 9?', antwort: 'NICHT zwingend. {{§ 22 MSO}}: **„9. Schulbesuchsjahr"** — kann wegen Wiederholung in einer anderen Jgst. eintreten.' },
    { id: 'FA08', frage: '{{Art. 84 BayEUG}} regelt Abschlüsse?', antwort: 'NEIN. Art. 84 BayEUG = **Werbung/Vertrieb in der Schule** (politische Werbung verboten). Abschluss-Werte stehen in MSO §§ 19 ff. bzw. § 22, § 34 MSO.' },
    { id: 'FA09', frage: 'M-Zug-Schwellen alle = 2,33?', antwort: 'NEIN. **M7 ≤ 2,66** · M8/M9/M10 ≤ **2,33** ({{§ 7 MSO}}). D+M+E-Mittel aus jeweiligem Jahreszeugnis.' },
    { id: 'FA10', frage: 'Elternwahlrecht {{Art. 44 BayEUG}} absolut?', antwort: 'NEIN. Gebunden an **Eignung + Leistung** ({{BV Art. 132}} + Art. 44). Spezial-Aufnahmeprüfungen (PU GS 4, M-Zug-Aufnahme, RS/Gym-Spezialprüfungen) zulässig.' },
    { id: 'FA11', frage: 'LNW-Aufbewahrung = 2 Jahre wie Zeugnisse?', antwort: 'NEIN. {{§ 3 LDO}} Abs. 6: **1 Jahr nach Ablauf des Schuljahres**. Zeugnisse + Schülerakte haben andere Fristen (10 J. → § 41 BaySchO). Schulrats-Lieblings-Falle.' },
  ],

  faelle: [
    { id: 'F1', titel: 'Sara — § 12/3 MSO Rückgabe-Frist (Hauptfall · KRITISCH)',
      sachverhalt: 'Sara (8. Kl. MS) hat eine Mathe-Schulaufgabe geschrieben. Die Mutter ruft nach gut anderthalb Wochen an: „Wo bleibt die Schulaufgabe?" Die LK antwortet, sie habe „noch reichlich Zeit zum Korrigieren — die Frist sei nicht starr".',
      knackpunkte: [
        '**{{§ 12/3 MSO}} Direktionalitäts-Falle**: LK→SuS-Frist ist **„angemessen"** (KEIN konkreter Wert!) — „2 Wochen" wäre verbatim falsch. Frist ist situations-/fach-/umfangs-abhängig.',
        '**SuS→Schule = „einer Woche unverändert"**: nach Rückgabe + Eltern-Kenntnisnahme; keine Manipulation der Korrektur.',
        '**Eltern-Kenntnisnahme** als Zwischenschritt (SuS → Eltern → Schule).',
        '**Beratungs-Pflicht ({{Art. 78 BayEUG}})**: Mutter sachlich aufklären über Direktionalitäten.',
      ],
      antwortkette: 'Direktionalitäten klären → konkrete Korrekturfortschritte transparent kommunizieren → bei Verzögerung: SL informieren (nicht in Anwesenheit der Mutter eskalieren) → präzise Wortlaut-Verwendung im Examen üben.',
    },
    { id: 'F2', titel: 'Tarek — Praxisklassen-Übergang § 22 MSO',
      sachverhalt: 'Tarek besucht das **9. Schulbesuchsjahr** in einer Praxisklasse (er hat in Jgst. 6 wiederholt). Die Mutter fragt: „Kann er trotzdem den MS-Abschluss machen?"',
      knackpunkte: [
        '{{§ 22 MSO}} Abs. 1: „Schüler ab dem **9. Schulbesuchsjahr** in Praxisklassen oder Deutschklassen können den erfolgreichen Abschluss der Mittelschule mit dem Bestehen einer theorieentlasteten Abschlussprüfung erlangen." → Tarek erfüllt den Anker.',
        '**9. Schulbesuchsjahr ≠ Jgst. 9** (wegen Wiederholung).',
        '**Prüfungsstruktur § 22/2**: D/DaZ schriftl. **75 Min.** + mündl. **15 Min.** · M schriftl. **60 Min.** · Fächerverbund schriftl. **45 Min.** · Projektprüfung. Bestehen Durchschnitt ≤ **4,0** · **Projektnote zählt doppelt**.',
        '**Beratungs-Pflicht {{Art. 78 BayEUG}}**: weitere Optionen (ESA über Regelweg) realistisch einschätzen; Quabi-Perspektive über Berufsausbildung.',
      ],
      antwortkette: 'Schulbesuchsjahr-Stand aus Schülerakte (Cross-Ref MP_09 {{§ 41/1 BaySchO}}) → theorieentlastete Prüfung erläutern → Projektnoten-Doppelgewichtung als Strategie → ggf. Quabi-Perspektive über Berufsausbildung.',
    },
    { id: 'F3', titel: 'Leonie — Quabi-Voraussetzungen § 34 MSO',
      sachverhalt: 'Leonie hat den Quali in Jgst. 9 mit 2,5 bestanden. Anschließend Berufsausbildung zur Friseurin mit Berufsabschluss-Notendurchschnitt **2,8**. Englisch-Note in der BS-Abschlussprüfung: **3**.',
      knackpunkte: [
        '{{§ 34 MSO}} Abs. 1: **Berufsabschluss Notendurchschnitt mindestens 3,0** → Leonie 2,8 ≤ 3,0 ✓.',
        '§ 34 Abs. 2: **Englisch „ausreichend"** (= Note 4 als Mindest-Note) → Leonie 3 (besser) ✓.',
        '**Quali** als Vorbedingung ✓ (KMBek QA-MS).',
        '**Quabi ≠ MSA** — Quabi öffnet Aufstieg, MSA wäre M10 gewesen.',
      ],
      antwortkette: 'Voraussetzungen prüfen (Quali ✓ · Berufsabschluss ≤ 3,0 ✓ · Englisch ≥ „ausreichend" ✓) → Antrag stellen (Schule bzw. KMBek-Verfahren) → Aufstiegsweg Quabi → BS+FOS-Brücke → Fachabi.',
    },
    { id: 'F4', titel: 'Arda — Förderplan-Pflicht § 14 MSO',
      sachverhalt: 'Arda (Jgst. 7 MS) zeigt erhebliche Lese-Rechtschreib-Schwierigkeiten + Konzentrationsprobleme. Eltern erwarten „endlich einen Förderplan", LK fragt sich, ob ein Förderplan zwingend ist.',
      knackpunkte: [
        '{{§ 14 MSO}} Pflicht-Tatbestand: nur wenn SuS „auf Grund ihres sonderpädagogischen Förderbedarfs voraussichtlich die Lernziele der Mittelschule **nicht erreichen**" — sonst optional („bei Bedarf").',
        '**Diagnostik-Vorstufe**: sonderpäd. Gutachten ({{Art. 41 BayEUG}} Abs. 4) für Förderbedarfs-Feststellung.',
        '**Drei Pflicht-Inhalte** (§ 14 S. 2): Ziele · Fördermaßnahmen · Leistungserhebungen.',
        '**MSD-Einbeziehung Pflicht** (§ 14 S. 4); Erörterung Eltern **„soll"** (S. 5 — nicht „muss"). **Jährlich fortzuschreiben** (S. 3).',
        '**{{§ 32 BaySchO}}** Individuelle Unterstützung parallel zulässig — ABER nur „**soweit nicht die Leistungsfeststellung berührt wird**" (Abgrenzung Nachteilsausgleich, Cross-Ref MP_05).',
      ],
      antwortkette: 'Sonderpäd. Verdacht → MSD-Anbindung → ggf. Gutachten {{Art. 41 BayEUG}} → bei voraussichtl. Nicht-Erreichen der MS-Ziele: Förderplan PFLICHT mit MSD; sonst „bei Bedarf" zulässig + {{§ 32 BaySchO}} Individuelle Unterstützung als Sofort-Maßnahme.',
    },
    { id: 'F5', titel: 'Familie Çelik — M-Zug-Wechsel § 7 MSO + Art. 78 BayEUG',
      sachverhalt: 'Aylin (Jgst. 6 MS) hat im Jahreszeugnis D **2** · M **3** · E **2** = D+M+E-Schnitt 2,33. Eltern wollen, dass Aylin in M7 wechselt.',
      knackpunkte: [
        '**{{§ 7 MSO}} M7-Schwelle**: ≤ **2,66** (D+M+E) → Aylin (2,33) erfüllt **uneingeschränkt** aus Jgst. 6 Jahreszeugnis ✓.',
        '**{{Art. 78 BayEUG}} Beratungs-Pflicht**: Schule berät über Anlagen + Fähigkeiten.',
        '**{{§ 8 MSO}} Durchlässigkeit**: Rückkehr M-Zug → Regelklasse jederzeit möglich, falls Anforderungen nicht passen.',
        '**{{Art. 44 BayEUG}} Elternwahlrecht**: Eltern entscheiden, gebunden an Eignung/Leistung (Schwelle erfüllt → Wahl frei).',
      ],
      antwortkette: 'Notenbild prüfen → Schwelle bestätigen → Beratung über M-Zug-Anforderungen + Aufstiegsweg (M7 → M10 + MSA → FOS 11/12 → Fachabi) → Anmeldung am M-Zug; Hinweis auf {{§ 8 MSO}}-Rückkehrmöglichkeit als Sicherheitsnetz.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'Schullaufbahn-Trias SuS · EB · Schule',
      anriss: 'BV Art. 132 Anlagen+Leistung+innere Berufung. Eltern wählen (Art. 44 + Art. 76), Schule berät (Art. 78), Lehrerkonferenz entscheidet (Art. 53). Lernort FöS Art. 41 = Eltern.',
      norm: 'Art. 78 BayEUG', status: 'open', cards: 3,
      subblocks: [{ label: 'BV 132 + Drei-Akteure-Tabelle', cards: 1 }, { label: 'Art. 76 Eltern-Mitwirkungspflicht (Wortlaut)', cards: 1 }, { label: 'Art. 44 Elternwahlrecht + Art. 41 Lernort', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'Vorrücken/Wiederholung Art. 53 + § 12 MSO',
      anriss: 'Art. 52/1 LNW-Grundsatz + Bewertungs-Eröffnung. Art. 52/2 Notenstufen Wortlaut. Art. 52/3 Zeugnis. § 12/1 MSO Lehrerkonferenz-Festlegungen. Bestehensformel ESA ≥ 4,00.',
      norm: 'Art. 53 BayEUG', status: 'open', cards: 4,
      subblocks: [{ label: 'Art. 52/1 LNW-Grundsatz Wortlaut', cards: 1 }, { label: 'Art. 52/2 Notenstufen verbatim', cards: 1 }, { label: 'Art. 52/3 Zeugnis + § 12/1 MSO', cards: 1 }, { label: 'Vorrücken-Logik + ESA-Bestehensformel', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: 'Übertritt zwischen Schularten',
      anriss: 'GS 4 → Sek I (MP_03 A.4). MS 5 → Gelenkklasse § 6 MSO (Gym 2,0 / RS 2,5). M-Zug § 7 MSO (M7 ≤ 2,66, M8-10 ≤ 2,33). WS 4-stufig. Aufstiegswege A/B/C zur Hochschulreife.',
      norm: 'Art. 44 BayEUG', status: 'open', cards: 4,
      subblocks: [{ label: 'GS 4 → Sek I Schwellen', cards: 1 }, { label: 'MS 5 Gelenkklasse § 6 MSO', cards: 1 }, { label: 'M-Zug § 7 MSO Schwellen', cards: 1 }, { label: 'Aufstiegswege Hochschulreife', cards: 1 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Probearbeiten + LNW + HA',
      anriss: '§ 12/2 MSO Werte (1W vorher / 1×Tag / 2×Woche / Nachtermin 1W / Ersatzpr. 2W). § 12/3 KRITISCH zwei Direktionalitäten. § 12/4 Projektprüfung Regelklasse. § 28 BaySchO HA.',
      norm: '§ 12/3 MSO', status: 'open', cards: 4,
      subblocks: [{ label: '§ 12/2 Ankündigung — Werte verbatim', cards: 1 }, { label: '§ 12/3 KRITISCH zwei Direktionalitäten', cards: 1 }, { label: '§ 12/4 Projektprüfung Jgst. 9 Regelklasse', cards: 1 }, { label: '§ 28 BaySchO HA + § 32 Differenzierung', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'MS-Abschlüsse: ESA · Quali · MSA · Praxisklassen · Quabi',
      anriss: 'ESA (Schnitt ≥ 4,00). Quali 50/50 + Projekt (KMBek). MSA M10. § 22 Praxisklassen-Abschluss (9. Schulbesuchsjahr, Projekt doppelt). § 34 Quabi (Quali + Berufsabschl. ≥3,0 + Englisch). § 14 Förderplan.',
      norm: 'Art. 7 BayEUG', status: 'open', cards: 4,
      subblocks: [{ label: 'Vier Abschlüsse + Quabi — Übersichtstabelle', cards: 1 }, { label: '§ 22 MSO Praxisklassen-Abschluss Wortlaut', cards: 1 }, { label: '§ 34 MSO Quabi Wortlaut', cards: 1 }, { label: '§ 14 MSO Förderplan + § 32 BaySchO', cards: 1 }],
    },
  ],

  glossar: {
    'BV Art. 132': { titel: 'BV Art. 132 — Bildungsweg-Maßstab', wortlaut: 'Verfassungs-Anker: Anlagen + Neigungen + Leistung + innere Berufung. NICHT wirtschaftliche/gesellschaftliche Stellung der Eltern. Konkretisierung über {{Art. 44 BayEUG}} (Elternwahlrecht-Schranke).', karten: ['S08'] },
    'Art. 7 BayEUG': { titel: 'Art. 7 BayEUG — Mittelschule (Aufgaben)', wortlaut: 'Definiert die Mittelschule als Schulart und ihre Aufgaben (Allgemeinbildung + Berufsorientierung). Verweist auf MSO §§ 19 ff. für Abschlüsse.', karten: [] },
    'Art. 7a BayEUG': { titel: 'Art. 7a BayEUG — M-Zug (Mittlere-Reife-Klassen)', wortlaut: 'KERN-NORM für M-Zug-Übertritt. Detail-Schwellen in {{§ 7 MSO}}. NICHT verwechseln mit {{Art. 7b BayEUG}} (Schulen besonderer Art) oder Art. 30a/4 (Profil Inklusion).', karten: [] },
    'Art. 7b BayEUG': { titel: 'Art. 7b BayEUG — Schulen besonderer Art', wortlaut: 'Modellprojekte. NICHT M-Zug ({{Art. 7a BayEUG}}). NICHT Profil Inklusion (Art. 30a/4).', karten: [] },
    'Art. 35 BayEUG': { titel: 'Art. 35 BayEUG — Schulpflicht', wortlaut: 'Abs. 2: „zwölf Jahre, soweit dieses Gesetz nichts anderes bestimmt." Verkürzung durch Überspringen möglich; keine Verlängerung durch Streckung.', karten: [] },
    'Art. 41 BayEUG': { titel: 'Art. 41 BayEUG — Lernort bei sonderpäd. Förderbedarf', wortlaut: 'Abs. 1: „Die Erziehungsberechtigten entscheiden, an welchem der … schulischen Lernorte ihr Kind unterrichtet werden soll." Abs. 4: FöS-Aufnahme setzt sonderpäd. Gutachten voraus. Abs. 6: Bei Nicht-Einvernehmen entscheidet die Schulaufsichtsbehörde. Cross-Ref MP_08.', karten: [] },
    'Art. 43 BayEUG': { titel: 'Art. 43 BayEUG — Schulartwechsel', wortlaut: 'Rahmen-Norm für Schulartwechsel zwischen MS / RS / Gym / WS / FöS.', karten: [] },
    'Art. 44 BayEUG': { titel: 'Art. 44 BayEUG — Elternwahlrecht', wortlaut: 'Eltern wählen Schulart / Ausbildungsrichtung / Fachrichtung — **gebunden an Eignung + Leistung** ({{BV Art. 132}}). Spezial-Aufnahmeprüfungen (Gym-PU, M-Zug, RS-Spezial) zulässig.', karten: ['S08'] },
    'Art. 52 BayEUG': { titel: 'Art. 52 BayEUG — LNW + Notenstufen + Zeugnis', wortlaut: '**Abs. 1** Wortlaut: SuS erbringen schriftliche / mündliche / praktische Leistungen; Art und Weise der Erhebung vorher bekannt geben; Bewertung mit Notenstufe + Begründung eröffnen. **LNW dienen Bewertung UND Beratung**. **Abs. 2**: 6 Notenstufen verbatim — 1 „in besonderem Maße", 2 „voll", 3 „im Allgemeinen", 4 „im Ganzen noch", 5 „Grundkenntnisse vorhanden", 6 „selbst die … Grundkenntnisse nicht erkennen". **Abs. 3**: Zeugnis-Bewertung der Gesamtleistungen; daneben **soll**-Bemerkungen über Anlagen, Mitarbeit und Verhalten (Trias).', karten: ['S03'] },
    'Art. 53 BayEUG': { titel: 'Art. 53 BayEUG — Vorrücken / Wiederholen (KERN-NORM)', wortlaut: 'Rechtsanker für Vorrücken / Wiederholen. Detail-Regelungen in den Schulordnungen ({{§ 12 MSO}} + MSO §§ 19 ff.).', karten: [] },
    'Art. 76 BayEUG': { titel: 'Art. 76 BayEUG — Eltern-Mitwirkungspflicht', wortlaut: 'Abs. 1 (Wortlaut): „Die Erziehungsberechtigten sind verpflichtet, auf die gewissenhafte Erfüllung der schulischen Pflichten … durch die Schülerinnen und Schüler zu achten und die Erziehungsarbeit der Schule zu unterstützen." Abs. 2: regelm. Teilnahme + verbindliche Schulveranstaltungen.', karten: [] },
    'Art. 78 BayEUG': { titel: 'Art. 78 BayEUG — Schulberatung', wortlaut: 'Schule + Schulaufsicht **beraten** Eltern + SuS in Schullaufbahn-Fragen, geben Hilfen entsprechend **Anlagen + Fähigkeiten**. Beratung ist STRUKTURELL — keine Schulwahl-Entscheidung der LK. Cross-Ref MP_08 A.3 (5 Eskalationsstufen).', karten: ['S08'] },
    'Art. 84 BayEUG': { titel: 'Art. 84 BayEUG — Werbung/Vertrieb (NICHT Abschluss!)', wortlaut: 'Politische Werbung in der Schule verboten. **NICHT** Abschluss-Norm — Abschluss-Werte stehen in MSO §§ 19 ff. bzw. {{§ 22 MSO}} / {{§ 34 MSO}}. Falle FA08.', karten: [] },
    'Art. 86 BayEUG': { titel: 'Art. 86 BayEUG — Erziehungs-/Ordnungsmaßnahmen', wortlaut: 'Abs. 1: Erziehungsmaßnahmen ZUERST, dann Ordnungs-/Sicherungsmaßnahmen. Maßnahmen werden nach **Verhältnismäßigkeit** ausgewählt. Schullaufbahn-relevante OM Abs. 2: Punkt 8 Schul-Zuweisung · Punkt 9 Entlassungs-Androhung · Punkt 10 Entlassung · Punkt 11+12 Schulart-Ausschluss. Cross-Ref MP_05 A.4.', karten: [] },
    '§ 6 MSO': { titel: '§ 6 MSO — Gelenkklasse Jgst. 5', wortlaut: 'Jahreszeugnis Jgst. 5 MS: **D+M ≤ 2,0** Gymnasium · **D+M ≤ 2,5** Realschule (uneingeschränkt; sonst Härtefall Lehrerkonferenz).', karten: [] },
    '§ 7 MSO': { titel: '§ 7 MSO — M-Zug-Aufnahme', wortlaut: 'M-Zug-Schwellen (D+M+E aus Jahreszeugnis vorhergehende Klasse): **M7** ≤ **2,66** · **M8/M9/M10** ≤ **2,33**. **M10** zusätzlich Quali-Voraussetzung aus 9. Klasse. Cross-Ref {{Art. 7a BayEUG}}.', karten: ['S05'] },
    '§ 8 MSO': { titel: '§ 8 MSO — Durchlässigkeit', wortlaut: 'Rückkehr MS↔M-Zug **jederzeit** möglich. Sicherheitsnetz für M-Zug-Aufnahme.', karten: ['S05'] },
    '§ 12 MSO': { titel: '§ 12 MSO — LNW Mittelschule (Container)', wortlaut: 'Container-Norm für MS-LNW. Volltexte in {{§ 12/2 MSO}} (Ankündigung), {{§ 12/3 MSO}} (Rückgabe KRITISCH), § 12/4 (Projektprüfung Regelklasse).', karten: [] },
    '§ 12/2 MSO': { titel: '§ 12/2 MSO — Ankündigung LNW', wortlaut: 'Schriftliche LNW können angekündigt werden; **müssen** angekündigt werden bei größeren Lernabschnitten. Ankündigungs-Frist **1 Woche** vorher. Max. **1 angekündigte LNW/Tag**, max. **2 angekündigte LNW/Woche**. Nachtermin **1 Woche** vorher · Ersatzprüfung **2 Wochen** vorher. Ersatzprüfung **1×/Halbjahr** — gesamter bisheriger Stoff.', karten: ['S02'] },
    '§ 12/3 MSO': { titel: '§ 12/3 MSO — LNW-Rückgabe (KRITISCH!)', wortlaut: 'Wortlaut: „Schriftliche und praktische Leistungsnachweise sind den Schülerinnen und Schülern **innerhalb einer angemessenen Frist** zurückzugeben und mit ihnen zu besprechen. Schriftliche Leistungsnachweise werden den Schülerinnen und Schülern zur Kenntnisnahme durch die Erziehungsberechtigten mit nach Hause gegeben … Die schriftlichen Leistungsnachweise sind **innerhalb einer Woche unverändert** an die Schule zurückzugeben." **ZWEI Direktionalitäten**: (a) LK→SuS „angemessene Frist" (KEIN Wert!) · (b) SuS→Schule „1 Woche unverändert".', karten: ['S01'] },
    '§ 14 MSO': { titel: '§ 14 MSO — Individueller Förderplan', wortlaut: 'Wortlaut: „Die Lernziele der Schülerinnen und Schüler, die auf Grund ihres sonderpädagogischen Förderbedarfs voraussichtlich die Lernziele der Mittelschule **nicht erreichen**, sind in einem individuellen Förderplan festzuschreiben; ansonsten kann ein Förderplan **bei Bedarf** erstellt werden." Drei Pflicht-Inhalte: Ziele · Fördermaßnahmen · Leistungserhebungen. **MSD-Einbeziehung Pflicht**. Mind. jährlich fortzuschreiben. Erörterung mit EB **„soll"**.', karten: ['S04'] },
    '§ 22 MSO': { titel: '§ 22 MSO — Praxisklassen-Abschluss', wortlaut: 'Abs. 1: „Schüler ab dem **9. Schulbesuchsjahr** in Praxisklassen oder Deutschklassen können den erfolgreichen Abschluss der Mittelschule mit dem Bestehen einer theorieentlasteten Abschlussprüfung erlangen." Abs. 2: D/DaZ schriftl. **75 Min.** + mündl. **15 Min.** · M schriftl. **60 Min.** · Fächerverbund schriftl. **45 Min.** · Projektprüfung. Bestehen Durchschnitt **≤ 4,0** · **Projektnote zählt doppelt**.', karten: ['S06'] },
    '§ 34 MSO': { titel: '§ 34 MSO — Quabi', wortlaut: 'Abs. 1: „Für den qualifizierten beruflichen Bildungsabschluss [Quabi] ist ein **Berufsabschluss mit Notendurchschnitt von mindestens 3,0** erforderlich." Abs. 2: Englischkenntnisse durch Note **„ausreichend"** (= Note 4) — über MS-Abschlusszeugnis / Jgst. 9/10 Gym/RS/WS / mittlerer Abschluss / BS/BFS. Zusätzliche Vorbedingung: Quali.', karten: ['S07'] },
    '§ 28 BaySchO': { titel: '§ 28 BaySchO — Hausaufgaben', wortlaut: 'Abs. 1: HA in „**angemessener Zeit** bei durchschnittlichem Leistungsvermögen" — Berücksichtigung **Nachmittagsunterricht** + **berufliche Praktika**. Lehrerkonferenz legt Grundsätze fest. **Sonntage, Feiertage, Ferien** freizuhalten. Abs. 2: GS bis **eine Stunde** angemessen; an Förderschulen individuelle Leistungsfähigkeit. Cross-Ref MP_02.', karten: [] },
    '§ 32 BaySchO': { titel: '§ 32 BaySchO — Individuelle Unterstützung', wortlaut: '7-Maßnahmen-Katalog Abs. 2: Arbeitsmittel · Räumlichkeiten · Pausenregelung · Hand-/Lautzeichen · individuelle Arbeitsanweisungen · **HA-Differenzierung** · Visualisierung+Verbalisierung. **„Soweit nicht die Leistungsfeststellung berührt wird"** — Abgrenzung zu Nachteilsausgleich (§ 33 BaySchO, Cross-Ref MP_05).', karten: [] },
    '§ 41/1 BaySchO': { titel: '§ 41/1 BaySchO — Schülerakte-Einsicht (Cross-Ref MP_09)', wortlaut: 'Drei Personenkreise: SuS ab Vollendung 14. Lj. · aktuelle EB · frühere EB bis Vollendung 21. Lj. Vollzitat in MP_09 A.1.', karten: [] },
    '§ 3 LDO': { titel: '§ 3 LDO — LNW-Aufbewahrungsfrist', wortlaut: 'Abs. 6: Schriftliche Leistungsnachweise sind **mindestens 1 Jahr nach Ablauf des Schuljahres**, in dem sie geschrieben wurden, aufzubewahren. Danach Vernichtung gemäß KMBek Schriftwesen-Aktenführung. NICHT zu verwechseln mit Schülerakte-Aufbewahrung (§ 41 BaySchO — 10 Jahre) oder Zeugnis-Kopien (Schule-Archiv). Schulrats-Lieblingsfalle in der mündlichen Prüfung.', karten: ['S09', 'FA11'] },
  },
};
