// MP_09 — Datenschutz und Schülerakte im Schuldienst
window.MODULE = {
  id: 'mp09',
  zalgm: 'ZALGM § 16 Nr. 9',
  schwerpunkt: ['9.1 Schülerakte § 41 BaySchO', '9.2 Auskunfts-Trias', '9.3 § 14 LDO Abs. 3+4', '9.4 § 203 StGB', '9.5 KUG + Persönlichkeitsrecht'],
  titel: 'Datenschutz',
  titel2: '+ Schülerakte.',
  abriss:
    'Verbot ggü. Dritten (§ 14/4 LDO) vs. Recht der SuS/EB (§ 41/1 BaySchO + ' +
    'DSGVO Art. 15). Vor-Festlegungs-Verbot Zeugnisnoten (§ 14/3). § 203 StGB ' +
    'NUR Berufsgeheimnis-Träger:innen. KUG: 4 Ausnahmen, Klassenfoto nicht.',

  kurz: [
    '§ 41/1 BaySchO — DREI Personenkreise: SuS **ab Vollendung 14. Lj.** · aktuelle EB · frühere EB **bis Vollendung 21. Lj.** Lehrkräfte sind KEINE Berechtigten — Zugang qua Funktion.',
    'Auskunfts-Trias: (1) Notenauskunft § 14/3 LDO (NACH Festlegung) · (2) Akten-Einsicht § 41/1 BaySchO · (3) DSGVO Art. 15 (Daten-Auskunft, binnen 1 Monat). Drei Pfade getrennt halten — kumulativ.',
    '§ 14/4 LDO ist **Drittauskunfts-VERBOT** (Schule → Dritte) — NICHT „Notengeheimnis zwischen SuS". Ausnahmen: ausdrückliche EB-Zustimmung ODER „günstige Auswirkung" + Zustimmungs-Vermutung. Berufsschule-Sonderpfad S. 3 (Ausbildende/Arbeitgeber unberührt).',
    '§ 203 StGB greift NICHT pauschal — primär **Schulpsycholog:innen** (Abs. 1 Nr. 2) + Schul-Ärzt:innen (Abs. 1 Nr. 1). Reguläre LK + reine Beratungs-LK → § 14 LDO + Amtsverschwiegenheit + § 47 BeamtStG + BayDG + ggf. § 353b StGB.',
    'KUG: § 22 Einwilligung Pflicht; § 23 vier Ausnahmen (Zeitgeschichte / Beiwerk / Versammlung / Kunst). **Klassenfoto** fällt NICHT darunter. Verfassungs-Anker = **Art. 2/1 GG i.V.m. Art. 1/1 GG** (BVerfG Volkszählungsurteil 1983), NICHT BV Art. 100.',
  ],

  deck: { cards: 8, normebenen: 5, hochprior: 8, fallen: 10 },

  kartografie: [
    { ebene: 'I', bez: 'GG / Bund', kuerzel: 'BUND', normen: ['Art. 2/1 GG', 'Art. 1/1 GG', 'Art. 15 DSGVO', 'Art. 6 DSGVO', 'Art. 17 DSGVO', '§ 22 KUG', '§ 23 KUG', '§ 203 StGB', '§ 353b StGB'], sub: 'Persönlichkeitsrecht · DSGVO · KUG · Strafrecht' },
    { ebene: 'II', bez: 'BayEUG', kuerzel: 'BayEUG', normen: ['Art. 75 BayEUG', 'Art. 85 BayEUG', 'Art. 88 BayEUG'], sub: 'Unterrichtungspflicht · Datenschutz · Daten Ordnungsmaßnahmen' },
    { ebene: 'III', bez: 'BaySchO', kuerzel: 'BaySchO', normen: ['§ 41 BaySchO', '§ 41/1 BaySchO'], sub: 'Schülerakte (Container) · Einsichtsrecht (3 Personenkreise verbatim)' },
    { ebene: 'IV', bez: 'LDO', kuerzel: 'LDO', normen: ['§ 14 LDO', '§ 14/3 LDO', '§ 14/4 LDO'], sub: 'Verschwiegenheit (Cross-Ref MP_06) · Vor-Festlegung · Drittauskunfts-Verbot' },
    { ebene: 'V', bez: 'KMBek / Sek.', kuerzel: 'KMBek', normen: ['KMBek Schulberatung 29.10.2001'], sub: 'Datenaustausch MSD/SBPS · Cross-Ref MP_08' },
  ],

  pflichtwissen: [
    { id: 'D01', titel: '§ 41/1 BaySchO — drei Personenkreise',
      frage: 'Welche DREI Personenkreise haben Akten-/Leistungsnachweis-Einsicht — und welche zeitliche Grenze gilt jeweils?',
      antwort: '(1) **SuS ab Vollendung 14. Lj.** — auch nach Schulaustritt; (2) **aktuelle EB** — solange EB-Eigenschaft besteht; (3) **frühere EB** — nur **bis Vollendung 21. Lj.** des SuS, soweit BayEUG/Schulordnungen ihre Unterrichtung vorschreiben. **Drei** — nicht zwei (SuS+EB) oder vier (zzgl. LK). Lehrkräfte sind KEINE Berechtigten iSd § 41/1 — Aktenzugang qua Funktion.',
      norm: '§ 41/1 BaySchO', status: 'open' },
    { id: 'D02', titel: 'Auskunfts-Trias',
      frage: 'Welche drei Pfade umfasst die Auskunfts-Trias — und worin unterscheiden sie sich?',
      antwort: '**Pfad 1**: Notenauskunft {{§ 14/3 LDO}} — NACH endgültiger Festlegung; VOR Festlegung VERBOT. **Pfad 2**: Akten-/LN-Einsicht {{§ 41/1 BaySchO}} — Schülerakte + Leistungsnachweise. **Pfad 3**: DSGVO {{Art. 15 DSGVO}} — Daten-Auskunft (Zwecke, Empfänger, Speicherdauer), binnen 1 Monat. **Kumulativ** — § 41/1 ersetzt nicht Art. 15 und umgekehrt.',
      norm: 'Art. 15 DSGVO', status: 'open' },
    { id: 'D03', titel: '§ 14/4 LDO ist Drittauskunfts-Verbot',
      frage: 'Was regelt {{§ 14/4 LDO}} — und was NICHT?',
      antwort: 'Abs. 4 ist **Auskunfts-VERBOT-an-DRITTE** (Schule → Dritte). NICHT „Notengeheimnis zwischen SuS". Ausnahmen: (a) **ausdrückliche** Zustimmung EB, (b) „günstige Auswirkung" + Zustimmungs-Vermutung. **S. 3**: Auskunftspflicht ggü. Ausbildenden/Arbeitgebern (Berufsschule) UNBERÜHRT. **S. 5**: Behörden außerhalb Schulaufsicht nach besonderen Bestimmungen (StPO, BayPAG).',
      norm: '§ 14/4 LDO', status: 'open' },
    { id: 'D04', titel: '§ 14/3 LDO Vor-Festlegungs-Verbot',
      frage: 'Was sagt {{§ 14/3 LDO}} zur Notenauskunft VOR Festlegung?',
      antwort: 'Wortlaut: „Bis zur endgültigen Festlegung der Zeugnisnoten … dürfen Schülerinnen und Schülern oder Erziehungsberechtigten keine Auskünfte über das Vorrücken oder über Zeugnisnoten erteilt werden." **VOR** Festlegung KEINE Auskunft an SuS/EB. **NACH** Festlegung: § 6 Abs. 3 bleibt unberührt — Notenauskunft regulär möglich.',
      norm: '§ 14/3 LDO', status: 'open' },
    { id: 'D05', titel: '§ 203 StGB greift NUR berufsbezogen',
      frage: 'Welche Personenkreise unterliegen {{§ 203 StGB}} — und welche LK NICHT?',
      antwort: '**JA**: Schulpsycholog:innen (Abs. 1 Nr. 2 — Berufspsycholog:innen mit anerkannter Ausbildung) · Schul-Ärzt:innen (Abs. 1 Nr. 1 — Heilberuf). **Beratungs-LK NUR mit Doppel-Qualifikation** (zugleich staatl. anerkannte Sozialpädagog:in/Berufspsycholog:in). **NEIN für reguläre LK** → statt § 203: {{§ 14 LDO}} + Amtsverschwiegenheit + Disziplinar ({{§ 47 BeamtStG}} + BayDG, Cross-Ref MP_07) + ggf. § 353b StGB.',
      norm: '§ 203 StGB', status: 'open' },
    { id: 'D06', titel: 'Berufsschule-Sonderpfad',
      frage: 'Was gilt für Auskünfte ggü. Ausbildenden/Arbeitgebern (Berufsschule)?',
      antwort: '{{§ 14/4 LDO}} **S. 3** verbatim: „Die Auskunftspflicht gegenüber den Ausbildenden oder Arbeitgebern nach den schulrechtlichen Bestimmungen für die Berufsschulen bleibt hiervon **unberührt**." Datenfluss zur dualen Ausbildung ist gesetzlich gewollt — KEIN § 14/4-Verbot.',
      norm: '§ 14/4 LDO', status: 'open' },
    { id: 'D07', titel: 'KUG § 22/23',
      frage: 'Wann braucht Schule Einwilligung nach {{§ 22 KUG}} — und welche Ausnahmen kennt {{§ 23 KUG}}?',
      antwort: '**§ 22 KUG**: Verbreitung/Schaustellung von Bildnissen NUR mit Einwilligung. **§ 23 Abs. 1**: **vier** Ausnahmen — (1) Zeitgeschichte, (2) **Beiwerk** neben Landschaft/Örtlichkeit, (3) Versammlungen/Aufzüge, (4) Kunst-Interesse. **§ 23 Abs. 2**: Gegen-Ausnahme — berechtigtes Interesse des Abgebildeten kann die Befugnis sperren. **Klassenfoto** fällt NICHT unter eine § 23-Ausnahme — Einwilligung Pflicht.',
      norm: '§ 22 KUG', status: 'open' },
    { id: 'D08', titel: 'Persönlichkeitsrecht-Anker',
      frage: 'Wo steht der Persönlichkeitsrecht-Anker — Bund oder Bayern?',
      antwort: '**Bund**: Allgemeines Persönlichkeitsrecht aus {{Art. 2/1 GG}} **i.V.m.** {{Art. 1/1 GG}} (BVerfG Volkszählungsurteil 1983 — informationelle Selbstbestimmung). **NICHT** BV Art. 100/101 (stale Sekundärpfad). Konkretisierung durch DSGVO + BayEUG Art. 85.',
      norm: 'Art. 2/1 GG', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: '§ 14/4 LDO ist „Notengeheimnis" zwischen SuS?', antwort: 'NEIN. Abs. 4 regelt Auskunft Schule → **Dritte**. Vergleiche zwischen SuS sind NICHT durch § 14/4 verboten. Vor-Festlegungs-Verbot ist Abs. 3, NICHT Abs. 4.' },
    { id: 'FA02', frage: 'Jede LK fällt unter § 203 StGB?', antwort: 'NEIN. § 203 ist **berufsbezogen** (Abs. 1 Aufzählung). Reguläre LK i.d.R. NICHT erfasst — statt dessen {{§ 14 LDO}} + Amtsverschwiegenheit + Disziplinar + ggf. § 353b StGB.' },
    { id: 'FA03', frage: '§ 41/1 BaySchO sagt „ab 14 Lj."?', antwort: 'NEIN. Wortlaut: **„ab Vollendung des 14. Lebensjahres"** — also AB dem Tag nach dem 14. Geburtstag (sofortige Wirkung ab Vollendung).' },
    { id: 'FA04', frage: 'DSGVO Art. 15 ersetzt § 41/1 BaySchO?', antwort: 'NEIN. Beide bestehen **kumulativ**. § 41/1 = Akten-Einsicht (Papier/Datei). Art. 15 DSGVO = Daten-Auskunft (Zwecke, Empfänger, Speicherdauer). Getrennte Anspruchsgrundlagen.' },
    { id: 'FA05', frage: 'Klassenfoto auf Schul-Homepage = „Beiwerk" iSd § 23 Nr. 2 KUG?', antwort: 'NEIN. SuS sind **Hauptmotiv**, kein Beiwerk. {{§ 22 KUG}} Einwilligung erforderlich — schriftlich, freiwillig, widerrufbar (DSGVO Art. 7).' },
    { id: 'FA06', frage: '§ 14/4 erlaubt jede Auskunft mit irgendeiner EB-Zustimmung?', antwort: 'NEIN. **Ausdrückliche** Zustimmung pro Auskunfts-Anlass ODER „günstige Auswirkung" mit Zustimmungs-Vermutung. Pauschal-Einwilligungen sind heikel; DSGVO Art. 7 verlangt zudem Bestimmtheit + Widerrufbarkeit.' },
    { id: 'FA07', frage: 'Ausbildende erhalten wegen § 14/4 S. 1 LDO keine Auskünfte?', antwort: 'NEIN. {{§ 14/4 LDO}} **S. 3**: Auskunftspflicht ggü. Ausbildenden/Arbeitgebern (Berufsschule) UNBERÜHRT. Sonder-Datenfluss zur dualen Ausbildung.' },
    { id: 'FA08', frage: 'Kollegin darf alles über SuS erfahren — wir sind ja im selben Lehrerzimmer?', antwort: 'NEIN. § 14/1 LDO erlaubt Mitteilungen nur im **dienstlichen Verkehr** (erforderlich zur Aufgabenerfüllung). Off-topic-Plausch ist KEIN dienstlicher Verkehr — Verschwiegenheit gilt.' },
    { id: 'FA09', frage: '§ 41/1 BaySchO gewährt EB lebenslanges Einsichtsrecht?', antwort: 'NEIN. Aktuelle EB ja, solange EB-Eigenschaft besteht. **Frühere** EB nur **bis Vollendung 21. Lj.** des SuS. Volljährige SuS entscheiden selbst (§ 14/4 S. 4 LDO i.V.m. Art. 75/1 + 88/4/Nr. 3 BayEUG).' },
    { id: 'FA10', frage: 'Persönlichkeitsrecht-Anker für Datenschutz ist BV Art. 100?', antwort: 'NEIN. Robuster Anker = **{{Art. 2/1 GG}} i.V.m. {{Art. 1/1 GG}}** (BVerfG Volkszählungsurteil 1983). BV-Sekundärquellen sind stale.' },
  ],

  faelle: [
    { id: 'F1', titel: 'Oma will Noten der Enkelin Lara wissen',
      sachverhalt: 'Oma Frau Schmidt ruft die KL von Lara (12 J) an: „Lara hat nur eine 4 in Mathe — ist das ein Einzelfall?" KL überlegt, „im familiären Sinne" kurz Auskunft zu geben.',
      knackpunkte: [
        'Oma ist **kein EB** → fällt in {{§ 14/4 LDO}} S. 1 Drittauskunfts-Verbot.',
        'Ausnahme „ausdrückliche EB-Zustimmung"? NEIN. „Günstige Auswirkung + Zustimmungs-Vermutung"? Spekulativ — bei Notenauskünften kein Standardfall.',
        'Empfehlung: Auskunft **ablehnen**, Verweis auf EB; ggf. schriftliche Schweigepflichts-Entbindung der EB einholen.',
        'Bei Verstoß: {{§ 47 BeamtStG}} (Tatbestand) → BayDG Art. 6 ff. (Maßnahme — Cross-Ref MP_07 A.3); ggf. § 353b StGB.',
      ],
      antwortkette: 'Anfrage Drittperson → {{§ 14/4 LDO}} S. 1 Verbot → keine Ausnahme greift → Auskunft ablehnen → Verweis auf EB → bei Verstoß Disziplinar-Tatbestand erfüllt (Cross-Ref MP_07).',
    },
    { id: 'F2', titel: 'Tim (15 J) will Akte einsehen — EB sind dagegen',
      sachverhalt: 'Tim (15 J) bittet um Einsicht in seine Schülerakte. Der Vater telefoniert vorher und sagt: „Wir wollen nicht, dass Tim die Akte sieht — er soll sich auf die Schule konzentrieren."',
      knackpunkte: [
        '{{§ 41/1 BaySchO}} **Nr. 1**: SuS **ab Vollendung 14. Lj.** haben **eigenes** Recht auf Einsicht. Tim ist 15 → Vollendung 14. Lj. liegt vor.',
        'SuS-Recht und EB-Recht (§ 41/1 Nr. 2) bestehen **nebeneinander**, kumulativ.',
        'EB können das SuS-eigene Recht **NICHT blockieren** — subjektives Recht des SuS.',
        'Cross-Ref MP_05 (SuS-Rechte: Anhörungsrecht / Beteiligungsrechte).',
      ],
      antwortkette: 'SuS 15 J → {{§ 41/1 BaySchO}} Nr. 1 eigenes Einsichtsrecht → EB-Veto unzulässig → Termin gewähren → ggf. Hinweis an EB auf eigenes Recht aus Nr. 2.',
    },
    { id: 'F3', titel: 'Schulpsychologin und KL im Lehrerzimmer — Hannah',
      sachverhalt: 'Schulpsych. Dr. Berg hat in Beratung erfahren, dass SuS Hannah häuslicher Gewalt ausgesetzt ist. Im Lehrerzimmer fragt der KL: „Was ist mit Hannah los?" Dr. Berg möchte „sensibilisieren".',
      knackpunkte: [
        '{{§ 203 StGB}} greift für Schulpsychologin (Berufsgeheimnis-Trägerin, Abs. 1 Nr. 2).',
        '{{§ 14 LDO}} zusätzlich (Verschwiegenheit).',
        '**Keine Schweigepflichts-Entbindung** der EB / Hannah → Auskunft im Lehrerzimmer **strafbar** + Disziplinar.',
        'Ausnahme: Kindeswohl-Gefährdung — strukturiertes Verfahren § 8a SGB VIII / § 4 KKG (Datenübermittlung an JA bei gewichtigen Anhaltspunkten); KEIN pauschaler Lehrerzimmer-Plausch.',
        'Cross-Ref MP_08 (Datenaustausch MSD / Schulberatung KMBek 29.10.2001).',
      ],
      antwortkette: 'Berufsgeheimnis Schulpsych. {{§ 203 StGB}} → keine Schweigepflicht-Entbindung → Auskunft Lehrerzimmer strafbar → strukturiertes Verfahren § 8a SGB VIII / KKG erforderlich → JA als ggf. richtiger Adressat.',
    },
    { id: 'F4', titel: 'Klassenfoto auf Schul-Homepage — fehlende Einwilligungen',
      sachverhalt: 'SL möchte Klassenfotos der 7a auf die Schul-Homepage stellen. Zwei EB haben den Einwilligungs-Zettel nicht zurückgesendet.',
      knackpunkte: [
        '{{§ 22 KUG}}: Verbreitung von Bildnissen → Einwilligung erforderlich.',
        '{{§ 23 KUG}}-Ausnahme: Klassenfoto ist KEIN „Beiwerk", KEINE „Zeitgeschichte" → keine Ausnahme.',
        'Kinder ohne Einwilligung dürfen NICHT veröffentlicht werden — abschneiden / unkenntlich / nicht hochladen.',
        'DSGVO Art. 6/1/a + Art. 7: schriftlich, freiwillig, widerrufbar (DSGVO Art. 7/3).',
        'Minderjährige: EB-Einwilligung; ab Vollendung 14. Lj. Ko-Einwilligung der SuS empfohlen (Persönlichkeitsrechts-Reife — i.V.m. § 41/1 Nr. 1 BaySchO). Cross-Ref MP_05 K15-Falle.',
      ],
      antwortkette: 'Klassenfoto → {{§ 22 KUG}} Einwilligung → § 23 keine Ausnahme → fehlende Einwilligungen blockieren Veröffentlichung → DSGVO-Schriftform + Widerrufbarkeit → ab 14 Ko-Einwilligung SuS.',
    },
    { id: 'F5', titel: 'Polizei fordert Auskunft über SuS nach Schulhof-Vorfall',
      sachverhalt: 'Nach körperlicher Auseinandersetzung erscheint die Polizei am nächsten Tag und fordert Adresse + Kontaktdaten von SuS Mark.',
      knackpunkte: [
        '{{§ 14/4 LDO}} **S. 5**: Auskünfte an Behörden außerhalb Schulaufsicht nach **besonderen Bestimmungen** (StPO, BayPAG).',
        'Polizei als Strafverfolgungsbehörde mit konkretem Tatverdacht → Anfrage zulässig nach §§ 161, 163 StPO.',
        '**Verfahrensweg**: SL entscheidet (§ 14/2 LDO analog für Außenkommunikation).',
        'Bitte um **schriftliches** Auskunftsersuchen mit Rechtsgrundlage; Notruf-Konstellation prüfen; Datenschutzbeauftragte:r einbinden.',
        'DSGVO-Rechtsgrundlage: Art. 6/1/c (rechtliche Verpflichtung) + Art. 6/1/e (öffentliche Aufgabe).',
      ],
      antwortkette: 'Polizei-Anfrage → {{§ 14/4 LDO}} S. 5 Verweis auf StPO → SL-Entscheidung → schriftliches Ersuchen mit Rechtsgrundlage → Auskunft auf das Notwendige beschränkt.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'Schülerunterlagen-Terminologie + § 41 BaySchO',
      anriss: 'Drei Sub-Begriffe (Akte · Leistungsnachweise · Klassenbuch). § 41/1 BaySchO drei Personenkreise verbatim — Wortlaut „ab Vollendung 14. Lj." + „bis Vollendung 21. Lj." für frühere EB.',
      norm: '§ 41/1 BaySchO', status: 'open', cards: 3,
      subblocks: [{ label: 'Begriffs-Trias Schülerunterlagen', cards: 1 }, { label: '§ 41/1 BaySchO Wortlaut', cards: 1 }, { label: '3 Personenkreise — Tabelle + Fallen', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'Auskunfts-Trias — drei Pfade getrennt',
      anriss: 'Pfad 1 Notenauskunft § 14/3 LDO · Pfad 2 Akten-Einsicht § 41/1 BaySchO · Pfad 3 DSGVO Art. 15. Kumulativ.',
      norm: 'Art. 15 DSGVO', status: 'open', cards: 4,
      subblocks: [{ label: 'Drei-Pfad-Tabelle', cards: 1 }, { label: '§ 14/3 LDO Vor-Festlegung Wortlaut', cards: 1 }, { label: 'Art. 15 DSGVO Sinngehalt', cards: 1 }, { label: 'Trennschärfe-Merkhilfe + Fallen', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: '§ 14/4 LDO — Drittauskunfts-Verbot (KERN)',
      anriss: 'Schule → Dritte: VERBOT. Ausnahmen: ausdrückliche EB-Zustimmung; „günstige Auswirkung" + Zustimmungs-Vermutung. S. 3 Berufsschule-Sonderpfad. S. 5 Behörden-Pfad. Cross-Ref MP_06.',
      norm: '§ 14/4 LDO', status: 'open', cards: 3,
      subblocks: [{ label: '§ 14/4 LDO Wortlaut KERN', cards: 1 }, { label: 'Auflösungs-Tabelle Anfragender', cards: 1 }, { label: 'Fallen + Disziplinar-Konsequenz', cards: 1 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Strafrechts-Schnittstelle § 203 StGB',
      anriss: '§ 203 NUR Berufsgeheimnis-Träger:innen — Schulpsych. + Schul-Ärzt:in (Beratungs-LK nur Doppel-Qual.). Reguläre LK → § 14 LDO + Amtsverschwiegenheit + Disziplinar + ggf. § 353b StGB.',
      norm: '§ 203 StGB', status: 'open', cards: 3,
      subblocks: [{ label: '§ 203 StGB Sinngehalt + Wortlaut', cards: 1 }, { label: 'Reichweiten-Tabelle (kritisch!)', cards: 1 }, { label: 'Schweigepflichts-Entbindung', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'Bildrechte KUG + Persönlichkeitsrecht',
      anriss: 'Verfassungs-Anker Art. 2/1 + 1/1 GG (BVerfG Volkszählung). § 22 KUG Einwilligung. § 23 vier Ausnahmen. Klassenfoto nicht ausgenommen. Einwilligungs-Anatomie.',
      norm: '§ 22 KUG', status: 'open', cards: 3,
      subblocks: [{ label: 'Verfassungs-Anker Art. 2/1 + 1/1 GG', cards: 1 }, { label: '§ 22 + § 23 KUG Wortlaut + 4 Ausnahmen', cards: 1 }, { label: 'Schul-Anwendungstabelle + Einwilligungs-Anatomie', cards: 1 }],
    },
  ],

  glossar: {
    'Art. 2/1 GG': { titel: 'Art. 2/1 GG — Persönlichkeitsrecht (mit {{Art. 1/1 GG}})', wortlaut: 'Allgemeines Persönlichkeitsrecht / informationelle Selbstbestimmung folgen i.V.m. {{Art. 1/1 GG}} (BVerfG Volkszählungsurteil 1983 — Schutz vor unbegrenzter Datenerhebung). **Robuster Bundes-Anker**, NICHT BV Art. 100/101.', karten: ['D08'] },
    'Art. 1/1 GG': { titel: 'Art. 1/1 GG — Würde des Menschen', wortlaut: '„Die Würde des Menschen ist unantastbar. Sie zu achten und zu schützen ist Verpflichtung aller staatlichen Gewalt." Ergänzt {{Art. 2/1 GG}} als Anker für das allgemeine Persönlichkeitsrecht.', karten: ['D08'] },
    'Art. 15 DSGVO': { titel: 'Art. 15 DSGVO — Auskunftsrecht (kumulativ neben § 41/1)', wortlaut: 'Die betroffene Person hat das Recht, Bestätigung darüber zu erhalten, ob sie betreffende personenbezogene Daten verarbeitet werden, und Auskunft über diese Daten (Verarbeitungszwecke, Datenkategorien, Empfänger, geplante Speicherdauer, Rechte auf Berichtigung/Löschung, Beschwerderecht). Bearbeitungs-Frist: 1 Monat (Art. 12/3). Bund/EU-Anker, kumulativ neben {{§ 41/1 BaySchO}}.', karten: ['D02'] },
    'Art. 6 DSGVO': { titel: 'Art. 6 DSGVO — Rechtmäßigkeit der Verarbeitung', wortlaut: 'lit. a Einwilligung · lit. c gesetzliche Pflicht · lit. e öffentliche Aufgabe (Schul-Aufgabe).', karten: [] },
    'Art. 17 DSGVO': { titel: 'Art. 17 DSGVO — Recht auf Löschung', wortlaut: '„Recht auf Vergessenwerden". Schul-Akte ist durch BayEUG/BaySchO-Aufbewahrungspflichten weitgehend gebunden — Löschungsanspruch nur in den von Art. 17 vorgesehenen Konstellationen.', karten: [] },
    'Art. 75 BayEUG': { titel: 'Art. 75 BayEUG — Unterrichtungspflicht ggü. EB', wortlaut: 'Schule unterrichtet EB. Anker für § 14/4 S. 4 LDO (Auskünfte an frühere EB volljähriger SuS i.V.m. Art. 75/1 + 88/4 Nr. 3 BayEUG).', karten: [] },
    'Art. 75/1 BayEUG': { titel: 'Art. 75/1 BayEUG — Unterrichtungspflicht', wortlaut: 'Konkretisiert die Unterrichtung der Erziehungsberechtigten als Schul-Pflicht; bei volljährigen SuS treten Sonder-Regeln (§ 14/4 S. 4 LDO).', karten: [] },
    'Art. 85 BayEUG': { titel: 'Art. 85 BayEUG — Datenschutz Schulen', wortlaut: 'Datenschutz-Anker in Bayern; DSGVO-Konkretisierung für Schulen.', karten: [] },
    'Art. 88 BayEUG': { titel: 'Art. 88 BayEUG — Daten in Ordnungsmaßnahmen', wortlaut: 'Datenverarbeitung im Kontext von Ordnungsmaßnahmen. **Abs. 4 Nr. 3** ergänzt § 14/4 S. 4 LDO für Auskünfte an frühere EB volljähriger SuS.', karten: [] },
    'Art. 88/4 BayEUG': { titel: 'Art. 88/4 BayEUG — Auskünfte frühere EB volljähriger SuS', wortlaut: 'Sonder-Regelung für Auskünfte an frühere EB nach Volljährigkeit der SuS. Cross-Ref § 14/4 S. 4 LDO.', karten: [] },
    '§ 41 BaySchO': { titel: '§ 41 BaySchO — Schülerakte (Container)', wortlaut: '**Container-Norm** Schülerakte (Aufnahme, Personalien, Zeugnisse, Bescheide). Konkrete Norm im Container: {{§ 41/1 BaySchO}} Einsichtsrecht. Volltext-Anker abhängig von BaySchO-Ausgabe.', karten: ['D01'] },
    '§ 41/1 BaySchO': { titel: '§ 41/1 BaySchO — Einsichtsrecht in Schülerakte', wortlaut: 'Wortlaut: „Ein Recht auf Einsicht in die eigene Schülerakte nach § 37 Satz 2 Nr. 1 sowie – nach Abschluss des Aufnahmeverfahrens, der Abschlussprüfung oder anderer schulischer Leistungsfeststellungen – in die Leistungsnachweise nach § 37 Satz 2 Nr. 2 haben **(1)** die jeweiligen Schülerinnen und Schüler **ab Vollendung des 14. Lebensjahres**, auch wenn sie die Schule verlassen haben, **(2)** die Erziehungsberechtigten der jeweiligen Schülerinnen und Schüler und **(3)** die früheren Erziehungsberechtigten bei Schülerinnen und Schülern **bis zur Vollendung des 21. Lebensjahres**, soweit Vorschriften des BayEUG oder der Schulordnungen ihre Unterrichtung vorschreiben."', karten: ['D01'] },
    '§ 14 LDO': { titel: '§ 14 LDO — Verschwiegenheit (Cross-Ref MP_06)', wortlaut: 'Verschwiegenheits-Trias mit drei Bereichen — Vollzitat MP_06 A.3. **Abs. 3** Vor-Festlegung-Verbot Zeugnisnoten ({{§ 14/3 LDO}}). **Abs. 4** Drittauskunfts-Verbot ({{§ 14/4 LDO}}) = KERN MP_09. Verstoß = Dienstvergehen iSd {{§ 47 BeamtStG}}.', karten: [] },
    '§ 14/3 LDO': { titel: '§ 14/3 LDO — Vor-Festlegungs-Verbot Zeugnisnoten', wortlaut: 'Wortlaut: „Bis zur endgültigen Festlegung der Zeugnisnoten nach den für die einzelnen Schularten geltenden Bestimmungen dürfen Schülerinnen und Schülern oder Erziehungsberechtigten keine Auskünfte über das Vorrücken oder über Zeugnisnoten erteilt werden. § 6 Abs. 3 bleibt unberührt."', karten: ['D04'] },
    '§ 14/4 LDO': { titel: '§ 14/4 LDO — Auskunfts-Verbot ggü. Dritten (KERN MP_09)', wortlaut: 'S. 1: „Die Schule ist nicht berechtigt, anderen Personen als den Erziehungsberechtigten Auskunft über Schülerinnen und Schüler und ihre Leistungen zu geben." S. 2: Abweichung bei **ausdrücklicher Zustimmung EB** ODER bei „günstiger Auswirkung" mit Zustimmungs-Vermutung. S. 3: Auskunftspflicht ggü. Ausbildenden/Arbeitgebern (Berufsschule) **unberührt**. S. 4: für frühere EB volljähriger SuS gelten {{Art. 75/1 BayEUG}} + {{Art. 88/4 BayEUG}}. S. 5: Auskünfte an Behörden außerhalb Schulaufsicht nach besonderen Bestimmungen.', karten: ['D03', 'D06'] },
    '§ 22 KUG': { titel: '§ 22 KUG — Recht am eigenen Bild', wortlaut: 'Wortlaut (alte Rechtschreibung BEIBEHALTEN): „Bildnisse dürfen nur mit Einwilligung des Abgebildeten verbreitet oder öffentlich zur Schau gestellt werden. Die Einwilligung gilt im Zweifel als erteilt, wenn der Abgebildete dafür, **daß** er sich abbilden ließ, eine Entlohnung erhielt. Nach dem Tode des Abgebildeten bedarf es bis zum Ablaufe von **10 Jahren** der Einwilligung der Angehörigen des Abgebildeten." Konsequenz: Verbreitung / Schaustellung von Klassenfotos → Einwilligung Pflicht.', karten: ['D07'] },
    '§ 23 KUG': { titel: '§ 23 KUG — vier Ausnahmen + Gegen-Ausnahme', wortlaut: 'Abs. 1 (vier Ausnahmen): (1) Bildnisse aus dem Bereich der **Zeitgeschichte**; (2) Bilder, auf denen Personen nur als **Beiwerk** neben einer Landschaft / Örtlichkeit erscheinen; (3) Bilder von **Versammlungen**, Aufzügen und ähnlichen Vorgängen; (4) Bildnisse, die nicht auf Bestellung angefertigt sind, sofern die Verbreitung einem **höheren Interesse der Kunst** dient. Abs. 2 (Gegen-Ausnahme): Befugnis erstreckt sich NICHT auf Verbreitung/Schaustellung, durch die ein **berechtigtes Interesse** des Abgebildeten verletzt wird.', karten: ['D07'] },
    '§ 203 StGB': { titel: '§ 203 StGB — Verletzung von Privatgeheimnissen', wortlaut: 'Strafbar: unbefugtes Offenbaren eines fremden Geheimnisses (insb. zum persönlichen Lebensbereich), das in der Eigenschaft als Angehöriger bestimmter Berufe (Heilberufe, Berufspsycholog:innen u.a.) anvertraut oder bekannt geworden ist. Strafdrohung idR Freiheitsstrafe bis 1 Jahr oder Geldstrafe. **Berufsbezogen** — NICHT pauschal jede LK; primär Schulpsycholog:innen + Schul-Ärzt:innen. Reguläre LK statt dessen: {{§ 14 LDO}} + Amtsverschwiegenheit + Disziplinar ({{§ 47 BeamtStG}} + BayDG) + ggf. § 353b StGB.', karten: ['D05'] },
    '§ 353b StGB': { titel: '§ 353b StGB — Verletzung des Dienstgeheimnisses', wortlaut: 'Auffangtatbestand für reguläre LK ohne § 203-Berufseigenschaft. Strafbar das unbefugte Offenbaren eines amtlich anvertrauten Geheimnisses.', karten: [] },
    '§ 47 BeamtStG': { titel: '§ 47 BeamtStG — Dienstvergehen (Bund)', wortlaut: 'Verstöße gegen Verschwiegenheit ({{§ 14 LDO}}) erfüllen den Dienstvergehen-Tatbestand → Maßnahmen-Katalog BayDG Art. 6 ff. (Cross-Ref MP_07 A.3).', karten: [] },
  },
};
