// D Wirtschaft und Beruf — Fachdidaktik · 2. Staatsexamen MS Bayern · Mai 2026
window.MODULE = {
  id: 'd-wib',
  zalgm: 'Fachdidaktik · D Wirtschaft und Beruf',
  schwerpunkt: ['A.1 Kompetenzmodell WiB', 'A.2 Leitfach Berufsorientierung', 'A.3 Realbegegnungen', 'A.4 Projektorientiertes Arbeiten', 'A.5 Berufswahlkompetenz'],
  titel: 'Wirtschaft und Beruf.',
  titel2: 'Leitfach der Berufsorientierung.',
  abriss:
    'WiB als Leitfach des Lernfelds Berufsorientierung in der MS. ' +
    '5 Gegenstandsbereiche (Arbeit · Berufsorientierung · Wirtschaft · ' +
    'Technik · Recht) × 4 prozessbez. Kompetenzen. Realbegegnungen + ' +
    'Projektprüfung als Anker.',

  kurz: [
    '**WiB ist Leitfach Berufsorientierung** in der MS — integriert berufsorient. Wahlpflichtfächer (Technik · E+S · W+K) und weitere MS-Fächer interdisziplinär. Ziel: Vorbereitung auf von Arbeit geprägte Lebens-Bereiche.',
    'Kompetenzstrukturmodell WiB: **5 Gegenstandsbereiche** (Arbeit · Berufsorientierung · Wirtschaft · Technik · Recht) × **4 prozessbez. Kompetenzen** (Handeln · Analysieren · Kommunizieren · Beurteilen). Andere Achsen als Mathe/GPG.',
    '**Realbegegnungen** als zentrales didaktisches Prinzip: Betriebserkundung · Betriebspraktikum (Klasse 8/9) · Schülerfirma · Realhandeln am Arbeitsplatz. Theorie-Praxis-Verzahnung als Markenzeichen.',
    '**Projektorientiertes Arbeiten** ab Klasse 5 schrittweise aufgebaut; ab Klasse 7 **leittextgesteuerte vollständige Handlung** (Planen · Durchführen · Prüfen · Bewerten). Anschluss zur **Projektprüfung Jgst. 9 Regelklasse** (Cross-Ref Schulrecht MP_04 § 12/4 MSO).',
    'Berufswahlprozess wird ab **Klasse 7 dokumentiert** (Berufswahlpass). Kooperation mit Agentur für Arbeit + Berufsbildungswerken. Querschnittsthema durch alle Jgst.; verstärkte BO in Jgst. 8 (Regel) / 9 (M-Zug).',
  ],

  deck: { cards: 8, normebenen: 5, hochprior: 8, fallen: 7 },

  kartografie: [
    { ebene: 'I', bez: 'Verfassung + Bundesrecht', kuerzel: 'VERF', normen: ['BV Art. 131', 'GG Art. 12 Berufsfreiheit', 'BBiG Berufsbildungsgesetz', 'JArbSchG'], sub: 'Bildungsauftrag · Berufsfreiheit · Ausbildungsrahmen' },
    { ebene: 'II', bez: 'LehrplanPLUS Bayern', kuerzel: 'LP+', normen: ['Fachprofil WiB MS', 'Kompetenzstrukturmodell WiB', 'Lernbereiche WiB Jgst. 5–9'], sub: '5 Gegenstandsbereiche · 4 prozessbez. Komp.' },
    { ebene: 'III', bez: 'Didaktische Konzepte', kuerzel: 'DIDA', normen: ['Vollständige Handlung (Hacker/Aebli)', 'Realbegegnungs-Konzept (Dauenhauer)', 'Berufsorientierungskonzept Beinke', 'Projektmethode Dewey/Frey'], sub: 'Handlungstheorie · BO-Theorie' },
    { ebene: 'IV', bez: 'Schulordnung + KMBek', kuerzel: 'VO', normen: ['§ 12/4 MSO Projektprüfung', '§ 22 MSO Praxisklassen-Abschluss', 'KMBek Praktikum', 'KMBek BO MS'], sub: 'Projektprüfung · Praktikum · BO-Rahmen' },
    { ebene: 'V', bez: 'Externe Partner', kuerzel: 'KOOP', normen: ['BA Agentur für Arbeit', 'Berufsbildungswerke', 'IHK + HWK', 'KMBek Schulberatung'], sub: 'Kooperation Schule ↔ Wirtschaft + Arbeitsverwaltung' },
  ],

  pflichtwissen: [
    { id: 'W01', titel: 'Kompetenzstrukturmodell WiB',
      frage: 'Wie ist das Kompetenzstrukturmodell WiB aufgebaut?',
      antwort: 'Zwei Achsen: **4 prozessbez. Kompetenzen** (Handeln · Analysieren · Kommunizieren · Beurteilen) × **5 Gegenstandsbereiche** (Arbeit · Berufsorientierung · Wirtschaft · Technik · Recht). Andere Achsen als Mathe (6 prozessbez. × 4 Gegenstandsbereiche) und GPG (Methoden + Sach + 2 Urteilsbildungen + Handlung × Inhaltsbereiche). Doppeltagging je KE.',
      norm: 'LP+ Fachprofil WiB', status: 'open' },
    { id: 'W02', titel: 'WiB als Leitfach Berufsorientierung',
      frage: 'Welche Rolle hat WiB in der Mittelschule und welche Fächer integriert es?',
      antwort: 'WiB ist **Leitfach des Lernfelds Berufsorientierung**. Integriert die berufsorientierenden **Wahlpflichtfächer**: **Technik · Ernährung und Soziales (E+S) · Wirtschaft und Kommunikation (W+K)** + (in einzelnen Schulen) Buchführung, Werken und Gestalten. WiB liefert Theorie + Methodik, die WPFs die praktische Anwendung. Cross-Ref Projektprüfung Jgst. 9 Regelklasse: Fächerverbund WiB + ein WPF.',
      norm: 'LP+ Fachprofil WiB', status: 'open' },
    { id: 'W03', titel: 'Realbegegnungen — drei Anker',
      frage: 'Welche drei Realbegegnungs-Anker kennt das WiB-Fachprofil?',
      antwort: '(1) **Arbeitsplätze im Schul-Umfeld** (Pausenverkauf, Schul-Garten, Schülerfirma) — niederschwellig. (2) **Arbeit zu Hause** (Hauswirtschaft, Reparaturen, Familien-Wirtschaft) — Lebenswelt-Anker. (3) **Betriebe** (Betriebserkundung + Praktikum) — extern + intensiv. Verzahnung von Theorie und Praxis als Markenzeichen WiB. Quelle: Dauenhauer Realbegegnungs-Konzept.',
      norm: 'Dauenhauer', status: 'open' },
    { id: 'W04', titel: 'Vollständige Handlung — 6 Schritte',
      frage: 'Was sind die 6 Schritte der vollständigen Handlung — und ab welcher Jgst. greift sie verbindlich?',
      antwort: '**Vollständige Handlung** (Hacker/Aebli): **(1) Informieren · (2) Planen · (3) Entscheiden · (4) Durchführen · (5) Prüfen · (6) Bewerten/Reflektieren**. Ab **Klasse 7** im LP+ als **leittextgesteuertes Projekt** verbindlich. Bildungstheoretisch: kognitive Tätigkeit kompletter Handlungsformen — Antikorrelat zum kleinschrittigen Frontalunterricht.',
      norm: 'Hacker/Aebli', status: 'open' },
    { id: 'W05', titel: 'Projektprüfung MS Jgst. 9 (Cross-Ref Schulrecht MP_04)',
      frage: 'Wie ist die Projektprüfung der MS Regelklasse Jgst. 9 strukturiert?',
      antwort: '**{{§ 12/4 MSO}}** verbatim: Projektprüfung mit schriftlichen, mündlichen und praktischen Lerninhalten des Fachs **Wirtschaft und Beruf** + des jeweiligen in dieser Jgst. besuchten **berufsorientierenden Wahlpflichtfachs**. **Arbeitszeit**: Technik **240 Min** · W+K **120 Min** · E+S **150 Min** · SL-Zeitzuschlag bis **20 Min** für Gruppen-Kommunikation. **Gesamtnote** aus erbrachten Leistungen. Cross-Ref: NUR Regelklasse, NICHT M-Zug (dort eigene MSA-Prüfung).',
      norm: '§ 12/4 MSO', status: 'open' },
    { id: 'W06', titel: 'Berufswahlkompetenz + Berufswahlpass',
      frage: 'Wie wird die Berufswahlkompetenz im LP+ WiB aufgebaut — und welche Dokumentation gibt es?',
      antwort: 'Berufswahlkompetenz wird über alle Jgst. **schrittweise** aufgebaut: 5/6 = Berufe in Lebenswelt; 7 = Selbsteinschätzung + erste Erkundungen; 8 = **Betriebspraktikum** (Regel) + Bewerbungstraining; 9 = Vertiefung + zweites Praktikum; 10 (M-Zug) = MSA + erweiterte BO. **Berufswahlpass** dokumentiert den Prozess **ab Klasse 7**. Kooperationspartner: Agentur für Arbeit (Berufsberatung), Berufsinformationszentren BIZ, IHK/HWK.',
      norm: 'LP+ Jgst. 7-9', status: 'open' },
    { id: 'W07', titel: 'Berufsorient. Wahlpflichtfächer',
      frage: 'Welche berufsorientierenden Wahlpflichtfächer gibt es in der MS — und wie verzahnen sie sich mit WiB?',
      antwort: '**Drei Standard-WPFs**: **Technik** · **Ernährung und Soziales (E+S)** · **Wirtschaft und Kommunikation (W+K)**. SuS wählen ein WPF ab Jgst. 7 verbindlich. **WiB** liefert die theoretischen + methodischen Grundlagen; die WPFs entfalten die praktische Anwendung. Cross-Ref Projektprüfung Jgst. 9: Fächerverbund WiB + WPF mit gemeinsamer Gesamtnote.',
      norm: 'LP+ MS WPF', status: 'open' },
    { id: 'W08', titel: 'Methodik — Erkundung + Befragung + Interview',
      frage: 'Welche Forschungsmethoden sind im WiB zentral?',
      antwort: '**Feldforschungs-Methoden**: **Erkundung** (geplante Wirklichkeitsbegegnung mit Auswertung) · **Beobachten** (systematisch, mit Protokoll) · **Befragen** (Fragebogen mit Auswertung) · **Interviewen** (qualitative Tiefeninterviews). Werden ab Klasse 5 schrittweise eingeführt — Klasse 5: einfache Beobachtung; Klasse 8: strukturierte Betriebserkundung + Interview. Cross-Ref Sk (Erkundung GPG B4 §2.2.2).',
      norm: 'LP+ Methodik WiB', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: 'WiB ist „nur Theorie-Unterricht"?', antwort: 'NEIN. WiB ist **Leitfach Berufsorientierung** mit **Realbegegnungen** als zentralem Prinzip — Betriebserkundung, Praktikum, Schülerfirma. Theorie-Praxis-Verzahnung ist Markenzeichen.' },
    { id: 'FA02', frage: 'Projektprüfung Jgst. 9 auch im M-Zug?', antwort: 'NEIN. {{§ 12/4 MSO}} verbatim „Regelklasse Jgst. 9". M-Zug hat eigene MSA-Prüfung in M10 (Cross-Ref Schulrecht MP_04 A.5).' },
    { id: 'FA03', frage: 'Vollständige Handlung = kleinschrittige Anleitung?', antwort: 'NEIN. **6 Schritte** (Informieren · Planen · Entscheiden · Durchführen · Prüfen · Bewerten) als **komplette Handlungsform**. Antikorrelat zum kleinschrittigen Frontalunterricht. SuS planen + entscheiden selbst (Konstruktivismus-Anker).' },
    { id: 'FA04', frage: 'Realbegegnung = jede Sachaufgabe mit Beruf?', antwort: 'NEIN. **Realbegegnung** verlangt **echten Kontakt** mit Arbeitsplatz / Betrieb / arbeitenden Personen. Eingekleidete Sachaufgaben („Hans ist Friseur und schneidet …") sind KEINE Realbegegnungen.' },
    { id: 'FA05', frage: 'Berufsorientierung = nur Jgst. 8/9?', antwort: 'NEIN. BO ist **Querschnittsthema** durch alle Jgst. (5-9). Schwerpunkte in Jgst. 8 (Regel-Praktikum) und 9 (Vertiefung), aber ab Klasse 5 Berufsbilder in der Lebenswelt + ab Klasse 7 Berufswahlpass.' },
    { id: 'FA06', frage: 'Kompetenzstrukturmodell WiB identisch mit Mathe?', antwort: 'NEIN. WiB: **4 prozessbez.** (Handeln · Analysieren · Kommunizieren · Beurteilen) × **5 Gegenstandsbereiche** (Arbeit · BO · Wirtschaft · Technik · Recht). Mathe: 6 prozessbez. × 4 Gegenstandsbereiche. Sk/GPG: andere Achsen mit Urteilsbildungen.' },
    { id: 'FA07', frage: 'Praktikum = nur Pflicht-Erfahrung ohne Bewertung?', antwort: 'NEIN. Praktikum wird **vor- und nachbereitet** im WiB-Unterricht (Erkundungsfragebogen, Praktikumsbericht, Reflexion). Bewertung des Praktikumsberichts möglich. Pflicht zur **Auswertung** mit Klasse + Eltern + LK.' },
  ],

  faelle: [
    { id: 'F1', titel: 'Betriebserkundung Bäckerei (Jgst. 7, Hauptfall)',
      sachverhalt: 'Sie planen eine Betriebserkundung in einer lokalen Bäckerei für eine Jgst. 7 Regelklasse. Wie strukturieren Sie didaktisch?',
      knackpunkte: [
        '**Vollständige Handlung als Rahmen**: (1) **Informieren** im U. — Bäckerei-Geschäftsmodell, Berufsbilder; (2) **Planen** — Fragebogen, Erkundungsbogen; (3) **Entscheiden** — Beobachtungspunkte, Aufgabenverteilung in Kleingruppen; (4) **Durchführen** — Betriebsbesuch; (5) **Prüfen** — Auswertung im U., Plakat-Erstellung; (6) **Bewerten** — Reflexion + Plakat-Präsentation.',
        '**Realbegegnung** mit 3 Berufsbildern: Bäcker/in · Verkäufer/in · Bäckerei-Fachverkäufer/in.',
        '**Cross-Ref Mathe**: Mischungsverhältnisse Rezept (Roggen/Weizen) — kann mit M7R-LB1 verknüpft werden (Cross-Ref Mathe-Skript A.4 F2).',
        '**Beurteilen-Kompetenz**: Welche Berufsfelder passen zu welchen Stärken/Interessen?',
        '**Sicherheits-/Hygiene-Aspekte**: Cross-Ref JArbSchG (Praktikums-Vorbereitung Jgst. 8).',
        '**LP+-Anker WiB Jgst. 7**: Gegenstandsbereich Berufsorientierung + Arbeit + Wirtschaft.',
      ],
      antwortkette: 'LP+-Bezug nennen → Vollständige Handlung als didaktischen Rahmen → konkretes Vorgehen 6 Schritte (Bäckerei) → Realbegegnungs-Begründung (Dauenhauer) → Cross-Curriculum Mathe/Sk → Auswertung + Berufswahlpass-Eintrag → Reflexion.',
    },
    { id: 'F2', titel: 'Betriebspraktikum Jgst. 8 — Planung, Begleitung, Auswertung',
      sachverhalt: 'Wie strukturieren Sie ein Betriebspraktikum (2 Wochen) in einer Regelklasse Jgst. 8 — vom Vorlauf bis zur Nachbereitung?',
      knackpunkte: [
        '**Vorlauf (8-10 Wochen)**: Berufsbild-Recherche im BIZ · Bewerbungstraining · Praktikumsplatz-Suche · Lehr- + Sicherheits-Belehrung (JArbSchG).',
        '**Begleitung**: Praktikumsbesuche durch LK (mindestens 1×/Schüler:in) · Praktikumstagebuch täglich · Notfallnummern.',
        '**Praktikumsbericht** (Pflicht): Berufsbild · eigene Aufgaben · Tätigkeits-Reflexion · Eignung für sich selbst — bewertet im WiB.',
        '**Nachbereitung**: Klassen-Präsentationen · Berufswahlpass-Eintrag · Reflexion Eignung + Anschluss-Schritte.',
        '**Rechtsrahmen**: JArbSchG (Höchstarbeitszeit, Pausen, gefährliche Arbeiten verboten) · Versicherung über Schulträger · Erziehungsberechtigte schriftlich informiert.',
        '**Cross-Ref Mathe**: bei Lehrberufen mit kaufmännischem Anteil — Prozent/Anteilsrechnung als Werkzeug.',
      ],
      antwortkette: 'Vorlauf 8-10 Wochen explizit benennen → JArbSchG + Versicherung (Rechtssicherheit) → Begleitung mit Praktikumsbesuch → Praktikumsbericht als Bewertungsgrundlage → Nachbereitung + Berufswahlpass → Reflexion Eignung.',
    },
    { id: 'F3', titel: 'Projektprüfung Jgst. 9 — Fächerverbund WiB + Technik',
      sachverhalt: 'Sie betreuen eine Projektprüfung Jgst. 9 Regelklasse im Fächerverbund WiB + Technik. Wie strukturieren Sie?',
      knackpunkte: [
        '**Rechtsrahmen**: {{§ 12/4 MSO}} — Regelklasse Jgst. 9, schriftliche + mündliche + praktische Lerninhalte WiB + WPF. **Technik 240 Min**; SL-Zeitzuschlag bis 20 Min für Gruppen-Kommunikation. Cross-Ref Schulrecht MP_04 A.4.',
        '**Vollständige Handlung als Grundstruktur**: Informieren (Themen-Analyse) · Planen (Materialliste, Skizze) · Entscheiden (Verfahren) · Durchführen (praktische Umsetzung) · Prüfen (Funktionstest) · Bewerten (Reflexion).',
        '**Gesamtnote** aus erbrachten Leistungen (schriftlich + mündlich + praktisch).',
        '**Gruppenarbeit**: SuS in 3-4er-Teams; Rollenverteilung (Projektleitung, Recherche, Bau, Dokumentation).',
        '**Beispiel-Thema**: „Bau einer Werkbank für unsere Klassenwerkstatt" — Materialkalkulation (Wirtschaft), Konstruktion (Technik), Bauausführung (Praxis), Reflexion (Berufsorientierung).',
        '**LP+-Anker**: alle 4 prozessbez. Kompetenzen WiB werden adressiert; mehrere Gegenstandsbereiche (Arbeit + Wirtschaft + Technik) verknüpft.',
      ],
      antwortkette: '{{§ 12/4 MSO}}-Rahmen zitieren → Vollständige Handlung als Struktur → Beispiel-Thema mit Cross-Curriculum → Gruppen-Logik → Bewertungskriterien → Reflexionsphase + Berufsorientierungs-Anschluss.',
    },
    { id: 'F4', titel: 'Schülerfirma in der MS (Wahlangebot)',
      sachverhalt: 'Eine Schülerfirma soll in der MS aufgebaut werden. Wie begründen Sie didaktisch?',
      knackpunkte: [
        '**Realbegegnungs-Anker (Dauenhauer)**: niederschwellige Realbegegnung „im Schul-Umfeld" — SuS gestalten ein echtes Wirtschafts-Mini-Unternehmen.',
        '**Vollständige Handlung**: alle 6 Schritte vollständig durchlaufen — Geschäftsidee, Marktanalyse, Produktentwicklung, Produktion, Verkauf, Bilanzierung.',
        '**Demokratiebezug** (Cross-Ref Sk A.4): demokratische Organisation der Schülerfirma — Vorstand, Mitgliederversammlung — Anker für **Schule als Polis**.',
        '**Kooperation mit IHK/HWK** und Lokalwirtschaft (Sponsor, Mentor:innen).',
        '**Rechtsrahmen**: oft als „Junior-Schülerfirma" über bundesweite Träger; Gewerbe-Status geklärt; Lehrkraft als verantwortliche Person.',
        '**Bewertung**: Reflexion + Praktikumsbericht-Analoge möglich; Optional Schülerfirma als WPF (in einigen Schulen).',
      ],
      antwortkette: 'Realbegegnungs-Begründung → Vollständige-Handlung-Anker → Cross-Ref Demokratielernen (Sk A.4) → Kooperation mit Wirtschaft → Rechts-/Sicherheitsrahmen → didaktischer Mehrwert: integriert mehrere LP+-Kompetenzen.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'Kompetenzstrukturmodell WiB + Selbstverständnis',
      anriss: 'WiB-Fachprofil: Vorbereitung auf von Arbeit geprägte Lebens-Bereiche. 4 prozessbez. × 5 Gegenstandsbereiche. Andere Achsen als Mathe (6×4) und Sk/GPG.',
      norm: 'LP+ Fachprofil WiB', status: 'open', cards: 2,
      subblocks: [{ label: 'Bildungsauftrag + LP+ Selbstverständnis', cards: 1 }, { label: 'Kompetenzstrukturmodell — 4 prozessbez. × 5 Gegenstandsbereiche', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'WiB als Leitfach Berufsorientierung',
      anriss: 'WiB integriert die berufsorient. Wahlpflichtfächer Technik / E+S / W+K. Querschnittsfunktion durch alle Jgst. Anschluss zur Projektprüfung Jgst. 9.',
      norm: 'LP+ MS WPF', status: 'open', cards: 2,
      subblocks: [{ label: 'Leitfach-Logik + WPFs', cards: 1 }, { label: 'Berufsorientierung als Querschnitt', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: 'Realbegegnungen — Erkundung + Praktikum + Schülerfirma',
      anriss: 'Realbegegnungs-Konzept Dauenhauer: drei Anker (Schule · Zuhause · Betrieb). Methodik: Erkundung, Befragung, Interview. JArbSchG-Rahmen für Praktikum.',
      norm: 'Dauenhauer', status: 'open', cards: 3,
      subblocks: [{ label: 'Drei Realbegegnungs-Anker', cards: 1 }, { label: 'Erkundung als zentrale Methode', cards: 1 }, { label: 'Betriebspraktikum Jgst. 8 + Rechtsrahmen', cards: 1 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Vollständige Handlung + Projektorientiertes Arbeiten',
      anriss: 'Hacker/Aebli: 6-Schritte-Modell (Informieren · Planen · Entscheiden · Durchführen · Prüfen · Bewerten). Leittextgesteuert ab Jgst. 7. Anker zur Projektprüfung MS.',
      norm: 'Hacker/Aebli', status: 'open', cards: 3,
      subblocks: [{ label: '6 Schritte verbatim', cards: 1 }, { label: 'Leittext + Selbststeuerung', cards: 1 }, { label: 'Projektprüfung Jgst. 9 (Cross-Ref § 12/4 MSO)', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'Berufswahlkompetenz + Kooperationen',
      anriss: 'Berufswahlpass ab Klasse 7. Kooperation Agentur für Arbeit / BIZ / IHK + HWK. JArbSchG für Praktikum. Aufbau-Logik 5-6 → 7 → 8 → 9 → 10.',
      norm: 'LP+ Jgst. 7-9', status: 'open', cards: 2,
      subblocks: [{ label: 'Berufswahlpass + Aufbau-Logik', cards: 1 }, { label: 'Kooperationspartner + Rechtsrahmen', cards: 1 }],
    },
  ],

  glossar: {
    'BV Art. 131': { titel: 'BV Art. 131 — Bildungsziele', wortlaut: 'Bayerischer Bildungsauftrag: Ehrfurcht / Achtung der Würde des Menschen / Verantwortungsbewusstsein. Werte-Boden auch für Wirtschafts-/Berufs-Bildung.', karten: [] },
    'GG Art. 12': { titel: 'GG Art. 12 — Berufsfreiheit', wortlaut: 'Abs. 1: „Alle Deutschen haben das Recht, Beruf, Arbeitsplatz und Ausbildungsstätte frei zu wählen. Die Berufsausübung kann durch Gesetz oder auf Grund eines Gesetzes geregelt werden." Verfassungsrechtlicher Anker für Berufswahlfreiheit — zentral für BO-Bildungsauftrag.', karten: [] },
    'BBiG': { titel: 'BBiG — Berufsbildungsgesetz (Bund)', wortlaut: 'Rahmenrecht für duale Berufsausbildung. Ausbildungsvertrag, Probezeit, Ausbildungs-/Prüfungsordnungen. Relevanz: SuS, die nach MS in die duale Ausbildung übergehen — BBiG bestimmt deren Status. Cross-Ref Quabi {{§ 34 MSO}} (Schulrecht MP_04).', karten: [] },
    'JArbSchG': { titel: 'JArbSchG — Jugendarbeitsschutzgesetz', wortlaut: 'Bundesgesetz: Schutz Minderjähriger im Arbeitsverhältnis. **Pflicht-Konsultations-Norm für Schul-Praktikum**: Höchstarbeitszeit, Pausen, Nachtarbeit-Verbot, gefährliche Arbeiten verboten. Im WiB-Unterricht vor Praktikum thematisieren (Lehr- + Sicherheits-Belehrung).', karten: [] },
    'LP+ Fachprofil WiB': { titel: 'LP+ Fachprofil Wirtschaft und Beruf', wortlaut: 'WiB als **Leitfach des Lernfelds Berufsorientierung**. Zentrales Bildungsziel: Vorbereitung auf „jene von Arbeit geprägten Bereiche, in denen sie in Zukunft als Erwerbstätige und Produzentinnen und Produzenten von Gütern und Dienstleistungen leben werden." Integriert berufsorient. WPFs (Technik · E+S · W+K) + interdisziplinär in MS-Fächer hinein. Quelle: lehrplanplus.bayern.de.', karten: ['W01', 'W02'] },
    'LP+ MS WPF': { titel: 'Berufsorientierende Wahlpflichtfächer MS', wortlaut: 'SuS wählen ab Jgst. 7 ein WPF verbindlich: **Technik · Ernährung und Soziales (E+S) · Wirtschaft und Kommunikation (W+K)**. WiB liefert theoretische + methodische Grundlagen; WPFs entfalten praktische Anwendung. Cross-Ref Projektprüfung Jgst. 9 ({{§ 12/4 MSO}}): Fächerverbund WiB + WPF.', karten: ['W07'] },
    'LP+ Jgst. 7-9': { titel: 'WiB-Aufbau-Logik Jgst. 5-10', wortlaut: 'Berufswahlkompetenz wird **schrittweise** aufgebaut: **Jgst. 5/6** Berufsbilder in der Lebenswelt + erste Erkundungen. **Jgst. 7** Selbsteinschätzung + Berufswahlpass startet. **Jgst. 8** Regel-Praktikum + Bewerbungstraining. **Jgst. 9** Vertiefungs-Praktikum + Berufswegplanung. **Jgst. 10 (M-Zug)** MSA + erweiterte Aufstiegsperspektiven.', karten: ['W06'] },
    'LP+ Methodik WiB': { titel: 'Methodik WiB (Feldforschung)', wortlaut: 'Zentrale Methoden: **Erkundung** (geplante Wirklichkeitsbegegnung mit Auswertung) · **Beobachten** (systematisch, mit Protokoll) · **Befragen** (Fragebogen mit Auswertung) · **Interviewen** (qualitative Tiefeninterviews). Schrittweise Einführung Klasse 5-9. Cross-Ref Sk-Methodik Erkundung (GPG B4 §2.2.2).', karten: ['W08'] },
    'Dauenhauer': { titel: 'Realbegegnungs-Konzept (Dauenhauer)', wortlaut: 'Erich Dauenhauer — Realbegegnung als didaktisches Prinzip der Arbeitslehre/WiB. **Drei Anker**: (1) Arbeitsplätze im Schul-Umfeld (Schülerfirma, Pausenverkauf, Schul-Garten); (2) Arbeit zu Hause (Familien-Wirtschaft, Hauswirtschaft); (3) Betriebe (Erkundung, Praktikum). Anti-Korrelat zur reinen Buchwissen-Vermittlung.', karten: ['W03'] },
    'Hacker/Aebli': { titel: 'Vollständige Handlung (Hacker / Aebli)', wortlaut: '**Winfried Hacker** (Handlungstheorie) + **Hans Aebli** (Didaktik): **6 Schritte** kompletter Handlungsformen — **(1) Informieren · (2) Planen · (3) Entscheiden · (4) Durchführen · (5) Prüfen · (6) Bewerten/Reflektieren**. Anti-Korrelat zum kleinschrittigen Frontalunterricht — SuS planen + entscheiden + bewerten selbst. Konstruktivistisch begründet. Im LP+ WiB ab Klasse 7 als **leittextgesteuerte vollständige Handlung** verbindlich.', karten: ['W04'] },
    '§ 12/4 MSO': { titel: '§ 12/4 MSO — Projektprüfung Jgst. 9 (Cross-Ref Schulrecht MP_04)', wortlaut: 'Wortlaut-Auszug: „In der Jahrgangsstufe 9 findet für die Schülerinnen und Schüler einer **Regelklasse** eine Projektprüfung mit schriftlichen, mündlichen und praktischen Lerninhalten des Fachs **Wirtschaft und Beruf** sowie des jeweiligen in dieser Jahrgangsstufe besuchten **berufsorientierenden Wahlpflichtfachs** statt." **Arbeitszeiten**: Technik 240 Min · W+K 120 Min · E+S 150 Min. SL-Zeitzuschlag bis 20 Min für Gruppen-Kommunikation. **Gesamtnote** aus erbrachten Leistungen. NUR Regelklasse, NICHT M-Zug.', karten: ['W05'] },
  },
};
