// MP_02 — Hausaufgaben + Beschwerde-Verfahren
window.MODULE = {
  id: 'mp02',
  zalgm: 'ZALGM § 16 Nr. 2',
  schwerpunkt: ['2.1 § 28 Drei-Sätze', '2.2 MS-Spezifik', '2.3 Art. 56/2 Nr. 5', '2.4 Art. 76', '2.5 HA ≠ LNW'],
  titel: 'Hausaufgaben.',
  titel2: 'Beschwerde-Verfahren.',
  abriss:
    '§ 28 BaySchO Drei-Sätze-Logik. MS hat KEINE feste Stundenobergrenze. ' +
    'Beschwerde nacheinander LK → SL → Schulforum. HA ≠ LNW — Drift-Falle ' +
    'der Schulräte.',

  kurz: [
    '§ 28/1 BaySchO Drei-Sätze: (1) Stellpflicht + Maßstab durchschnittlich-bearbeitbar · (2) LK-Konferenz-Grundsätze · (3) Sonntage UND Feiertage UND Ferien frei.',
    'MS hat KEINE 1-Stunde-Obergrenze. „bis zu einer Stunde" gilt NUR GS + GS-Stufe FöS (§ 28/2 S. 1).',
    'HA-Differenzierung steht in § 32/2 Nr. 6 BaySchO — NICHT in § 28. Schranke: „soweit nicht Leistungsfeststellung berührt".',
    'Beschwerde Art. 56/2 Nr. 5: nacheinander LK → SL → Schulforum (NICHT parallel). Eltern-Mitwirkung Art. 76: „achten auf" + „unterstützen".',
    'HA ≠ LNW (Drift-Falle): § 28 sagt zur Benotung NICHTS. Verbot folgt aus LNW-Definition (Art. 52) + Lehrplan. Bei Verstoß: Nacharbeit Art. 86/1, KEINE Note.',
  ],

  deck: { cards: 8, normebenen: 5, hochprior: 8, fallen: 10 },

  kartografie: [
    { ebene: 'I', bez: 'Bayerische Verfassung', kuerzel: 'BV', normen: ['Art. 131 BV'], sub: 'Bildungs-/Erziehungsauftrag' },
    { ebene: 'II', bez: 'BayEUG', kuerzel: 'BayEUG', normen: ['Art. 52', 'Art. 56/2', 'Art. 57', 'Art. 64', 'Art. 65', 'Art. 75', 'Art. 76', 'Art. 86/1', 'Art. 88'], sub: 'SuS-Rechte · Eltern-Mitwirkung · Nacharbeit · Verfahren' },
    { ebene: 'III', bez: 'Schulordnung + LDO', kuerzel: 'VO', normen: ['§ 22 BaySchO', '§ 28 BaySchO', '§ 32 BaySchO', '§ 5 LDO', '§ 6/2 LDO'], sub: 'LK-Konferenz · HA · Differenzierung · Aufsicht · KL-Koordination' },
    { ebene: 'IV', bez: 'Verwaltungsrecht', kuerzel: 'VWR', normen: ['Art. 28 BayVwVfG', 'KMBek HA-GS'], sub: 'Anhörung · 1-Stunde-Konkretisierung' },
    { ebene: 'V', bez: 'Bundesrecht', kuerzel: 'BUND', normen: ['Art. 6 GG', 'Art. 7 GG'], sub: 'Eltern-Erziehungsrecht · Schul-Aufsicht' },
  ],

  pflichtwissen: [
    { id: 'H01', titel: '§ 28/1 Drei-Sätze',
      frage: 'Welche drei Sätze prägen § 28 Abs. 1 BaySchO — und welche Falle steckt in S. 3?',
      antwort: 'S. 1 Stellpflicht + Maßstab „durchschnittliches Leistungsvermögen + angemessene Zeit + Berücksichtigung NM-U./prakt. Ausbildung". S. 2 LK-Konferenz legt Grundsätze vor Schuljahresbeginn fest (Pflicht). S. 3 Sonntage UND Feiertage UND Ferien freihalten — DREI Kategorien, kein Spielraum.',
      norm: '§ 28 BaySchO', status: 'open' },
    { id: 'H02', titel: 'MS-Spezifik Stundenzahl',
      frage: 'Welche HA-Stundenobergrenze gilt in der Mittelschule?',
      antwort: 'KEINE feste Obergrenze. Die „bis zu einer Stunde"-Regel gilt NUR Grundschule + GS-Stufe Förderschulen (§ 28/2 S. 1). Für MS gilt Maßstab S. 1 „angemessen" + LK-Konferenz-Grundsätze.',
      norm: '§ 28 BaySchO', status: 'open' },
    { id: 'H03', titel: 'HA-Differenzierung § 32/2 Nr. 6',
      frage: 'Wo steht die HA-Differenzierung — und welche Schranke begrenzt sie?',
      antwort: '§ 32 Abs. 2 Nr. 6 BaySchO (NICHT § 28!) — als Maßnahme der individuellen Unterstützung. Schranke § 32/1 S. 1: „soweit nicht die Leistungsfeststellung berührt wird". Bei LNW kein Differenzierungs-Spielraum (→ Nachteilsausgleich § 33 BaySchO).',
      norm: '§ 32 BaySchO', status: 'open' },
    { id: 'H04', titel: 'Beschwerde-Kette Art. 56/2 Nr. 5',
      frage: 'Welche Eskalations-Reihenfolge schreibt das Beschwerderecht der SuS vor?',
      antwort: 'Art. 56/2 Nr. 5 BayEUG: „nacheinander" Lehrkraft → Schulleitung → Schulforum. Wortlaut „nacheinander" = sequenziell, NICHT parallel. Maßstab: „entsprechend Alter + Stellung im Schulverhältnis". Lockerung bei Befangenheit.',
      norm: 'Art. 56/2 BayEUG', status: 'open' },
    { id: 'H05', titel: 'Art. 76 Eltern-Mitwirkung',
      frage: 'Welche zwei Pflichten formuliert Art. 76 BayEUG für Eltern?',
      antwort: 'Zwei verschiedene Pflichten: (1) „achten auf" regelmäßige Schul-Teilnahme + Erfüllung der Schulpflicht · (2) „unterstützen" die Erziehungsarbeit der Schule. Bei systematischem Boykott: SL-Mitteilung + Art. 75 EB-Unterrichtung + ggf. Jugendamt.',
      norm: 'Art. 76 BayEUG', status: 'open' },
    { id: 'H06', titel: 'Nacharbeit Art. 86/1',
      frage: 'Welche Erziehungsmaßnahme erlaubt Art. 86/1 BayEUG bei nicht erledigten HA?',
      antwort: 'Verbatim: „Bei nicht hinreichender Beteiligung am Unterricht auch eine Nacharbeit unter Aufsicht einer Lehrkraft." Erziehungsmaßnahme (NICHT Ordnungsmaßnahme). Aufsicht greift § 5 LDO. Subsidiarität: erst Erziehungs-, dann ggf. Ordnungsmaßnahme (Art. 86/2 + 88).',
      norm: 'Art. 86/1 BayEUG', status: 'open' },
    { id: 'H07', titel: 'HA ≠ LNW Drift-Falle',
      frage: 'Warum dürfen Hausaufgaben NICHT benotet werden — und wo steht das?',
      antwort: 'Drift-Falle: § 28 BaySchO sagt zur Benotung NICHTS. Das Verbot folgt aus der LNW-Definition (Art. 52 BayEUG) + Lehrplan-Vorgaben — HA dienen Einübung, nicht Leistungsbewertung. Bei Verstoß: Nacharbeit Art. 86/1 erlaubt, schlechte Note als Sanktion NICHT.',
      norm: 'Art. 52 BayEUG', status: 'open' },
    { id: 'H08', titel: 'KL-Stufenplan',
      frage: 'Welche 5 Stufen durchläuft die KL bei einer Eltern-Beschwerde wegen HA-Überlastung?',
      antwort: '(1) Sondierungsgespräch Eltern (Arbeitsplatz, Ablenkungen, Block-Arbeit, Zeit-pro-Fach). (2) Austausch Fach-LK (Aufgaben? Koordination?) — KL-Koordinationspflicht LDO § 6/2. (3) LK-Konferenz, § 28/1 S. 2 Grundsätze prüfen. (4) Elternbeirat (Art. 64/65). (5) SL (Art. 57).',
      norm: '§ 6/2 LDO', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: '§ 28 BaySchO verbietet HA-Benotung?', antwort: 'NEIN (Drift-Falle). § 28 sagt zur Benotung NICHTS. Verbot folgt aus LNW-Definition Art. 52 BayEUG + Lehrplan.' },
    { id: 'FA02', frage: 'MS hat 1-Stunde-Obergrenze für HA?', antwort: 'NEIN. „bis zu einer Stunde" gilt NUR GS + GS-Stufe FöS (§ 28/2 S. 1). MS hat keine feste Stundenzahl.' },
    { id: 'FA03', frage: 'HA-Differenzierung steht in § 28 BaySchO?', antwort: 'NEIN. Steht in § 32/2 Nr. 6 BaySchO. § 28 selbst regelt nur Zweck + Maßstab + LK-Konferenz + Sonn-/Feiertage/Ferien.' },
    { id: 'FA04', frage: 'Beschwerde gleichzeitig an LK + SL + Schulforum?', antwort: 'NEIN. Art. 56/2 Nr. 5: „nacheinander" — sequenziell, NICHT parallel.' },
    { id: 'FA05', frage: 'Sonntage sind frei, aber Samstage nicht?', antwort: 'VORSICHT. § 28/1 S. 3: drei Kategorien (Sonntag UND Feiertag UND Ferien). Samstag nicht explizit — aber Maßstab „angemessene Zeit" S. 1 als Schranke. Wochenend-Belastung bis Sonntag = Verstoß.' },
    { id: 'FA06', frage: 'LK-Konferenz-Grundsätze sind optional?', antwort: 'NEIN. § 28/1 S. 2: „legt … fest" — verbindliche Pflicht.' },
    { id: 'FA07', frage: 'Schlechte Note in HA als Sanktion zulässig?', antwort: 'NEIN. HA ≠ LNW. Stattdessen Nacharbeit Art. 86/1 BayEUG, ggf. Eskalation nach Verhältnismäßigkeit.' },
    { id: 'FA08', frage: 'KL hat mit Fach-HA nichts zu tun?', antwort: 'NEIN. LDO § 6/2 KL-Koordinationspflicht + § 3/3 LK-Kooperationspflicht. „Mein Fach, mein Königreich" ist dienstrechtlich problematisch.' },
    { id: 'FA09', frage: 'Eltern können HA-Erledigung verweigern?', antwort: 'NEIN. Art. 76 BayEUG Eltern-Mitwirkungspflicht („achten auf" + „unterstützen"). Bei Boykott: SL-Mitteilung + ggf. Jugendamt.' },
    { id: 'FA10', frage: 'Elternbeirat entscheidet die Individual-Beschwerde?', antwort: 'NEIN. Elternbeirat ist Mitwirkungs-/Anhörungsorgan für allgemeine Fragen (Art. 64/65). Individual-Beschwerde-Pfad ist Art. 56/2 Nr. 5.' },
  ],

  faelle: [
    { id: 'F1', titel: 'Hauptfall — 3 Stunden HA in 7. Klasse',
      sachverhalt: 'Mutter beschwert sich bei der Klassenleitung: ihr Kind in der 7. Klasse MS sitze jeden Nachmittag drei Stunden an den HA und werde trotzdem nicht fertig.',
      knackpunkte: [
        '§ 28/1 Drei-Sätze-Logik: Maßstab durchschnittlich-bearbeitbar + LK-Konferenz-Grundsätze + Sonntage/Feiertage/Ferien frei.',
        'MS hat KEINE 1-Stunde-Obergrenze (§ 28/2 S. 1 gilt nur GS/GS-Stufe FöS).',
        '3 Stunden in 7. Kl. MS = grenzwertig → individuelles ODER systemisches Problem.',
        'KL-Stufenplan: Sondierung → Fach-LK → LK-Konferenz → Elternbeirat → SL.',
        '§ 32/2 Nr. 6 Differenzierung möglich, ABER Schranke „soweit nicht Leistungsfeststellung berührt".',
      ],
      antwortkette: '§ 28/1 Drei-Sätze → MS hat keine feste Obergrenze → KL-Stufenplan (5 Stufen) → § 32/2 Nr. 6 Differenzierung → Art. 76 Eltern-Mitwirkung als Partnerschaft.',
    },
    { id: 'F2', titel: 'Variante — Kollegen-LK weigert sich',
      sachverhalt: 'Wie Fall 1, aber der Mathematik-Kollege sagt der KL: „Das ist nicht mein Problem, ich hab ja meine Aufgaben gestellt."',
      knackpunkte: [
        'LDO § 6/2 KL-Koordinationspflicht (Cross-Ref MP_06).',
        'LDO § 3/3 LK-Kooperationspflicht — kein „mein Fach, mein Königreich".',
        '§ 28/1 S. 2 LK-Konferenz-Grundsätze sind verbindlich.',
        'Bei dauerhafter Weigerung: SL-Information + ggf. Disziplinar-Schiene (Cross-Ref MP_07).',
      ],
      antwortkette: 'LDO § 6/2 KL-Koordination → LDO § 3/3 LK-Kooperation → § 28/1 S. 2 Konferenz-Grundsätze → bei Weigerung SL + Disziplinar MP_07.',
    },
    { id: 'F3', titel: 'Variante — LK benotet nicht gemachte HA mit „6"',
      sachverhalt: 'Ein Fach-LK sanktioniert nicht erledigte HA mit der Note „6".',
      knackpunkte: [
        'Drift-Falle: § 28 BaySchO sagt zur Benotung NICHTS.',
        'HA ≠ LNW — Verbot folgt aus Art. 52 BayEUG + Lehrplan-Vorgaben.',
        'Erlaubt stattdessen: Nacharbeit Art. 86/1 unter Aufsicht (§ 5 LDO greift).',
        'Eskalation: Mitteilung EB (Art. 75) → bei Fortsetzung Ordnungsmaßnahme Art. 86/2 + 88 (Cross-Ref MP_01/MP_05).',
      ],
      antwortkette: 'HA ≠ LNW (Art. 52 BayEUG) → § 28 sagt zur Benotung nichts → Nacharbeit Art. 86/1 erlaubte Erziehungsmaßnahme → bei Fortsetzung Ordnungsmaßnahme nach Verhältnismäßigkeit.',
    },
    { id: 'F4', titel: 'Variante — Sonntags-Hausaufgaben',
      sachverhalt: 'Eine LK gibt am Freitag HA, die unweigerlich Sonntags-Arbeit erfordern (umfangreiche Recherche-Aufgabe für Montag).',
      knackpunkte: [
        '§ 28/1 S. 3 verbatim: „Sonntage, Feiertage und Ferien sind von Hausaufgaben freizuhalten." — drei Kategorien, kein Spielraum.',
        'Verstoß bei HA-Umfang, der vor Sonntag nicht bearbeitbar ist.',
        'Beschwerde: Art. 56/2 Nr. 5 (SuS) bzw. Art. 76 (Eltern-Mitwirkung).',
        'KL-Reaktion: Fach-LK informieren + LK-Konferenz-Grundsätze § 28/1 S. 2 prüfen.',
        'Lieblingsfalle der Schulräte — präzise Wortlaut-Wiedergabe.',
      ],
      antwortkette: '§ 28/1 S. 3 verbatim drei Kategorien → Verstoß bei Sonntags-Pflicht-Belastung → Beschwerde-Pfad Art. 56/2 Nr. 5 + Art. 76 → LK-Konferenz-Grundsätze überarbeiten.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'Was sind Hausaufgaben — § 28 BaySchO',
      anriss: 'Stellpflicht + Maßstab durchschnittlich-bearbeitbar + LK-Konferenz-Grundsätze + Sonn-/Feiertage/Ferien frei. HA ist Pflicht, aber kein LNW.',
      norm: '§ 28 BaySchO', status: 'open', cards: 3,
      subblocks: [{ label: 'Drei-Sätze-Logik', cards: 1 }, { label: 'Verbindlichkeitsgrad', cards: 1 }, { label: 'NM-U.-Sonderregel', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'Angemessene Zeit + Differenzierung',
      anriss: 'GS-Limit ≠ MS-Limit. HA-Differenzierung in § 32/2 Nr. 6 (NICHT § 28). Schranke „soweit nicht Leistungsfeststellung berührt".',
      norm: '§ 32 BaySchO', status: 'open', cards: 3,
      subblocks: [{ label: 'Maßstab-Tabelle', cards: 1 }, { label: '§ 32/2 Nr. 6', cards: 1 }, { label: 'Schranke LNW', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: 'Beschwerde-Eskalations-Kette',
      anriss: '5 SuS-Rechte aus Art. 56/2 BayEUG. Nr. 5: nacheinander LK → SL → Schulforum. KL-Stufenplan als Praxis-Choreographie.',
      norm: 'Art. 56/2 BayEUG', status: 'open', cards: 4,
      subblocks: [{ label: '5 SuS-Rechte', cards: 1 }, { label: 'Drei-Stufen-Kette', cards: 1 }, { label: 'KL-Stufenplan', cards: 2 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Erziehungsmaßnahmen — Art. 86/1 (Nacharbeit)',
      anriss: 'Nacharbeit unter Aufsicht als Erziehungsmaßnahme. Subsidiarität. Bei Fortsetzung Eskalation zu Ordnungsmaßnahme nach Verhältnismäßigkeit.',
      norm: 'Art. 86/1 BayEUG', status: 'open', cards: 3,
      subblocks: [{ label: 'Nacharbeit-Schlüsselsatz', cards: 1 }, { label: '§ 5 LDO Aufsicht', cards: 1 }, { label: 'Eskalations-Pfad', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'HA ≠ LNW — Drift-Falle',
      anriss: 'Benotungs-Verbot folgt NICHT aus § 28, sondern aus Art. 52 BayEUG LNW-Definition + Lehrplan. Lieblingsfalle der Schulräte.',
      norm: 'Art. 52 BayEUG', status: 'open', cards: 2,
      subblocks: [{ label: 'Drift-Aufklärung', cards: 1 }, { label: 'Notenauskunfts-Falle', cards: 1 }],
    },
  ],

  glossar: {
    'Art. 52 BayEUG': { titel: 'Art. 52 BayEUG — LNW-Definition (Anker)', wortlaut: 'Leistungsfeststellung/Bewertung in den einzelnen Fächern; HA gehören NICHT zu LNW (folgt mittelbar aus Definition + Lehrplan). Cross-Ref MP_05 Notenauskunft.', karten: ['H07'] },
    'Art. 56/2 BayEUG': { titel: 'Art. 56 Abs. 2 BayEUG — 5 SuS-Rechte', wortlaut: 'Verbatim: SuS haben das Recht, entsprechend Alter + Stellung im Schulverhältnis: (1) sich am Schulleben beteiligen · (2) im Rahmen von Schulordnung + Lehrplan an U.-Gestaltung mitwirken · (3) über wesentliche Angelegenheiten hinreichend unterrichtet werden · (4) Auskunft über Leistungsstand + Hinweise auf Förderung erhalten · (5) bei als ungerecht empfundener Behandlung/Beurteilung sich „nacheinander" an LK, SL und Schulforum wenden.', karten: ['H04'] },
    'Art. 57 BayEUG': { titel: 'Art. 57 BayEUG — SL-Gesamtverantwortung (Anker)', wortlaut: 'SL trägt Gesamtverantwortung für die Schule; bei systemischen Konflikten Adressat der letzten KL-Stufenplan-Eskalation.', karten: [] },
    'Art. 64 BayEUG': { titel: 'Art. 64 BayEUG — Elternbeirat-Aufgaben (Anker)', wortlaut: 'Mitwirkungs-/Anhörungsorgan für allgemeine Fragen — KEIN Individual-Beschwerde-Mandat.', karten: [] },
    'Art. 65 BayEUG': { titel: 'Art. 65 BayEUG — Elternbeirat-Anhörung (Anker)', wortlaut: 'Anhörungsrecht bei wesentlichen Schulangelegenheiten — bei systemischen HA-Konflikten möglicher Konsultations-Anker.', karten: [] },
    'Art. 75 BayEUG': { titel: 'Art. 75 BayEUG — EB-Unterrichtungspflicht (Anker)', wortlaut: 'Eltern sind über wesentliche Vorgänge zu unterrichten. Bei Nacharbeit / Eskalation: schriftliche EB-Mitteilung Pflicht.', karten: [] },
    'Art. 76 BayEUG': { titel: 'Art. 76 BayEUG — Eltern-Mitwirkungspflicht', wortlaut: 'Eltern haben „auf den regelmäßigen Schulbesuch zu achten und die Erziehungsarbeit der Schule zu unterstützen". Zwei Pflichten: „achten auf" + „unterstützen". Bei dauerhaftem Boykott: SL-Mitteilung + ggf. Jugendamt.', karten: ['H05'] },
    'Art. 86/1 BayEUG': { titel: 'Art. 86 Abs. 1 BayEUG — Erziehungsmaßnahmen + Nacharbeit', wortlaut: 'Verbatim: „Zur Sicherung des Bildungs- und Erziehungsauftrags … können Erziehungsmaßnahmen gegenüber SuS getroffen werden. Dazu zählt bei nicht hinreichender Beteiligung am Unterricht auch eine Nacharbeit unter Aufsicht einer Lehrkraft. Soweit andere Erziehungsmaßnahmen nicht ausreichen, können Ordnungs- und Sicherungsmaßnahmen ergriffen werden. Maßnahmen des Hausrechts bleiben stets unberührt. Alle Maßnahmen werden nach dem Grundsatz der Verhältnismäßigkeit ausgewählt."', karten: ['H06'] },
    'Art. 88 BayEUG': { titel: 'Art. 88 BayEUG — Verfahren bei Ordnungsmaßnahmen (Anker)', wortlaut: 'Vor Ordnungsmaßnahme: Anhörung SuS + EB. Schriftliche Mitteilung an EB rechtzeitig vor Vollzug. Cross-Ref MP_01.', karten: [] },
    '§ 22 BaySchO': { titel: '§ 22 BaySchO — Lehrerkonferenz (Anker)', wortlaut: 'Forum für u.a. HA-Grundsätze (Cross-Ref § 28/1 S. 2). LK-Konferenz-Beschluss bindet alle LK.', karten: [] },
    '§ 28 BaySchO': { titel: '§ 28 BaySchO — Hausaufgaben (Abs. 1 + 2)', wortlaut: 'Abs. 1: S. 1 Stellpflicht + Maßstab durchschnittliches Leistungsvermögen + angemessene Zeit + Berücksichtigung NM-U./prakt. Ausbildung. S. 2 LK-Konferenz legt vor Schuljahresbeginn Grundsätze fest. S. 3 Sonntage, Feiertage UND Ferien freihalten. Abs. 2 S. 1: GS + GS-Stufe FöS = bis zu einer Stunde angemessen. S. 2: Förderschulen individuelle Leistungsfähigkeit. S. 3: An Tagen mit verpflichtendem NM-U. (GS+FöS) keine schriftlichen HA für nächsten Tag; Abweichung nur im Einvernehmen mit Elternbeirat.', karten: ['H01', 'H02'] },
    '§ 32 BaySchO': { titel: '§ 32 BaySchO — Individuelle Unterstützung', wortlaut: 'Abs. 1: Pädagogische, didaktisch-methodische und organisatorische Maßnahmen + technische Hilfen — „soweit nicht die Leistungsfeststellung berührt wird". Abs. 2 — 7-Maßnahmen-Katalog: 1. besondere Arbeitsmittel · 2. geeignete Räume · 3. individuelle Pausenregelung · 4. Hand-/Lautzeichen + Symbole · 5. individuelle Arbeitsanweisungen · 6. HA differenzieren (schulartspezifisch!) · 7. Visualisierung + Verbalisierung.', karten: ['H03'] },
    '§ 5 LDO': { titel: '§ 5 LDO — Aufsichtspflicht (Schlüsselsatz)', wortlaut: 'Insbesondere hat die LK spätestens von Beginn des Unterrichts an im Unterrichtsraum anwesend zu sein und während der gesamten Dauer ggf. bis zum Weggang der SuS Aufsicht zu führen. Greift auch bei Nacharbeit Art. 86/1 — Vollzitat siehe MP_06 A.2.', karten: [] },
    '§ 6/2 LDO': { titel: '§ 6 Abs. 2 LDO — KL-Koordinationspflicht (Anker)', wortlaut: 'KL koordiniert mit Fach-LK + EB. Hebel im KL-Stufenplan Stufe 2.', karten: ['H08'] },
    '§ 14 LDO': { titel: '§ 14 LDO — Verschwiegenheit', wortlaut: 'Verschwiegenheit über dienstlich bekannte Angelegenheiten. § 14/4 regelt Drittauskunfts-Schranke — KEIN „Notengeheimnis" ggü. SuS/EB selbst, aber kein vergleichender Bezug auf andere SuS. Cross-Ref MP_06.', karten: [] },
    'KMBek HA-GS': { titel: 'KMBek HA Grundschule (Anker)', wortlaut: 'Verwaltungs-Konkretisierung der 1-Stunde-Regel + qualitative Vorgaben für GS-HA. Gilt nur GS — nicht MS.', karten: [] },
    'Art. 131 BV': { titel: 'Art. 131 BV — Bildungsziele', wortlaut: 'Bayerische Bildungsziele: Ehrfurcht vor Gott, Achtung vor religiöser Überzeugung, Würde des Menschen, Selbstbeherrschung, Verantwortung, Demokratie, Völkerversöhnung.', karten: [] },
  },
};
