// MP_07 — Disziplinarrecht und Haftung im Schuldienst
window.MODULE = {
  id: 'mp07',
  zalgm: 'ZALGM § 16 Nr. 7',
  schwerpunkt: ['7.1 Haftungsdreieck', '7.2 Amtshaftung', '7.3 BayDG-Katalog', '7.4 Strafrecht', '7.5 Verschulden'],
  titel: 'Disziplinarrecht',
  titel2: '+ Haftung im Schuldienst.',
  abriss:
    'Drei-Pfad-Haftung: Zivil (Art. 34 GG → Freistaat) · Disziplinar (BayDG 5+2) · ' +
    'Strafrecht (persönlich). Bund-Land-Trennschärfe. Kumulativ ohne ne-bis-in-idem-' +
    'Verstoß.',

  kurz: [
    'Haftungsdreieck: Zivil/Amtshaftung (§ 839 BGB + Art. 34 GG → Freistaat haftet außen) · Disziplinarrecht (§ 47 BeamtStG + BayDG Art. 6) · Strafrecht (§ 229 / § 203 / § 174 StGB).',
    'Außenhaftung trifft Freistaat. Rückgriff auf LK NUR bei Vorsatz + grober Fahrlässigkeit (Art. 34 S. 2 GG). Bei einfacher Fahrlässigkeit: KEIN Rückgriff.',
    'Bund-Land-Trennschärfe: § 47 BeamtStG (Bund) = Dienstvergehen-TATBESTAND · BayDG Art. 6 (Land) = MAßNAHMEN-Katalog (5 Stufen Lebenszeit + 2 Ruhestand).',
    'Drei Pfade laufen KUMULATIV. Art. 103/3 GG ne bis in idem gilt nur „allgemeine Strafgesetze" — Disziplinar + Strafe NICHT verdrängend.',
    'Verschuldensformen: einfache Fahrlässigkeit („kann vorkommen") · grobe Fahrlässigkeit („darf nicht vorkommen") · Vorsatz (wissentlich + willentlich). Berufsbeamtentum-Anker = GG Art. 33/5 (NICHT BV Art. 130).',
  ],

  deck: { cards: 8, normebenen: 5, hochprior: 8, fallen: 10 },

  kartografie: [
    { ebene: 'I', bez: 'Bayerische Verfassung', kuerzel: 'BV', normen: ['Art. 95 BV'], sub: 'Beamtenverhältnis Bayern' },
    { ebene: 'II', bez: 'BayEUG', kuerzel: 'BayEUG', normen: ['Art. 56/4', 'Art. 57/2'], sub: 'SuS-Pflicht-Spiegel · SL-Verantwortung' },
    { ebene: 'III', bez: 'LDO + BaySchO', kuerzel: 'VO', normen: ['§ 5 LDO', '§ 14 LDO', '§ 22 BaySchO'], sub: 'Aufsicht-/Verschwiegenheits-Substrat (Cross-Ref MP_06)' },
    { ebene: 'IV', bez: 'Bay. Disziplinarrecht', kuerzel: 'BayDG', normen: ['Art. 6 BayDG', 'Art. 7 BayDG', 'Art. 8 BayDG', 'Art. 9 BayDG', 'Art. 10 BayDG', 'Art. 11 BayDG', 'Art. 12 BayDG', 'Art. 13 BayDG'], sub: '5+2-Stufen-Katalog (Verweis → Aberkennung Ruhegehalt)' },
    { ebene: 'V', bez: 'Bundesrecht', kuerzel: 'BUND', normen: ['Art. 33/5 GG', 'Art. 34 GG', 'Art. 103/3 GG', '§ 47 BeamtStG', '§ 839 BGB', '§ 203 StGB', '§ 229 StGB', '§ 174 StGB'], sub: 'Berufsbeamtentum · Staatshaftung · ne bis in idem · Dienstvergehen · StGB-Schiene' },
  ],

  pflichtwissen: [
    { id: 'D01', titel: 'Haftungsdreieck',
      frage: 'Welche drei Schienen treffen die LK bei einer Pflichtverletzung — wer haftet jeweils nach außen?',
      antwort: 'Zivil/Amtshaftung (§ 839 BGB + Art. 34 GG): Freistaat haftet außen, Rückgriff bei Vorsatz/grober Fahrlässigkeit. Disziplinar (§ 47 BeamtStG + BayDG Art. 6): LK persönlich, 5+2-Stufen. Strafrecht (StGB): LK persönlich (Schuld). KUMULATIV.',
      norm: 'Art. 34 GG', status: 'open' },
    { id: 'D02', titel: 'Bund-Land-Trennschärfe',
      frage: 'Wo steht der Tatbestand „Dienstvergehen" — und wo der Maßnahmen-Katalog?',
      antwort: 'Tatbestand: § 47 BeamtStG (BUND). Maßnahmen: BayDG Art. 6 ff. (LAND). 5-Stufen Lebenszeit (Verweis / Geldbuße / Kürzung Dienstbezüge / Zurückstufung / Entfernung) + 2-Stufen Ruhestand (Kürzung / Aberkennung Ruhegehalt). Wer beide Ebenen vermischt, fällt in die Falle.',
      norm: '§ 47 BeamtStG', status: 'open' },
    { id: 'D03', titel: 'BayDG 5+2 Stufen',
      frage: 'Welche fünf Stufen Lebenszeit + zwei Stufen Ruhestand kennt BayDG Art. 6?',
      antwort: 'Lebenszeit (Abs. 1): (1) Verweis (Art. 7) · (2) Geldbuße (Art. 8) · (3) Kürzung Dienstbezüge (Art. 9) · (4) Zurückstufung (Art. 10) · (5) Entfernung aus Beamtenverhältnis (Art. 11). Ruhestand (Abs. 2): (1) Kürzung Ruhegehalt (Art. 12) · (2) Aberkennung Ruhegehalt (Art. 13).',
      norm: 'Art. 6 BayDG', status: 'open' },
    { id: 'D04', titel: 'Rückgriff bei Vorsatz/grober Fahrlässigkeit',
      frage: 'Wann darf der Freistaat auf die LK Regress nehmen — und wer trägt die Beweislast?',
      antwort: 'Art. 34 S. 2 GG: NUR bei Vorsatz ODER grober Fahrlässigkeit. Bei einfacher Fahrlässigkeit: KEIN Rückgriff. Beweislast trägt der Freistaat. Faustregel: einfache F. = „kann vorkommen"; grobe F. = „darf nicht vorkommen"; Vorsatz = wissentlich + willentlich.',
      norm: 'Art. 34 GG', status: 'open' },
    { id: 'D05', titel: 'ne bis in idem',
      frage: 'Warum dürfen Strafverfahren UND Disziplinarverfahren parallel laufen?',
      antwort: 'Art. 103/3 GG Wortlaut: „Niemand darf wegen derselben Tat auf Grund der ALLGEMEINEN STRAFGESETZE mehrmals bestraft werden." Disziplinarrecht ist NICHT „allgemeines Strafrecht" (Sonderrecht für Beamte) — beide laufen kumulativ. Strafe + Disziplinarmaßnahme + Zivilhaftung KUMULATIV zulässig.',
      norm: 'Art. 103/3 GG', status: 'open' },
    { id: 'D06', titel: 'Berufsbeamtentum-Anker',
      frage: 'Wo steht der „Berufsbeamtentum"-Anker (Streikverbot, Treuepflicht) — Bund oder Bayern?',
      antwort: 'GG Art. 33/5 (BUND): „hergebrachte Grundsätze des Berufsbeamtentums". NICHT BV Art. 130 (stale Sekundärquellen-Pfad). Aus Art. 33/5 folgen u.a. Streikverbot + Treuepflicht + Alimentationsprinzip + lebenslange Anstellung.',
      norm: 'Art. 33/5 GG', status: 'open' },
    { id: 'D07', titel: 'StGB-Schiene',
      frage: 'Welche drei StGB-Tatbestände sind in der Schulrechts-Praxis am häufigsten?',
      antwort: '§ 229 StGB fahrl. KV (Aufsichtsversagen mit Verletzung). § 203 StGB Berufsgeheimnis (Schulpsych. zwingend, LK i.d.R. nicht; aber § 14 LDO greift). § 174 StGB sex. Missbrauch Schutzbefohlener (gravierender Tatbestand mit besonderem Vertrauensschutz). Strafrecht trifft Täter persönlich (Schuldprinzip).',
      norm: '§ 229 StGB', status: 'open' },
    { id: 'D08', titel: 'Außerdienstliches Verhalten',
      frage: 'Wann führt außerdienstliches Verhalten zu Disziplinarmaßnahmen?',
      antwort: '§ 47 Abs. 1 S. 2 BeamtStG: außerdienstlich, „wenn nach den Umständen des Einzelfalls in besonderem Maße geeignet, das Vertrauen in einer für das Amt bedeutsamen Weise zu beeinträchtigen". Hohe Schwelle — nicht jeder Privat-Verstoß. Bei LK z.B. Straftaten gegen Kinder/Jugendliche regelmäßig amtsbezogen.',
      norm: '§ 47 BeamtStG', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: 'LK haftet direkt gegenüber den Eltern?', antwort: 'NEIN. Art. 34 GG: Freistaat haftet außen. Eltern verklagen Freistaat, nicht LK. Rückgriff Freistaat → LK NUR bei Vorsatz/grober Fahrlässigkeit.' },
    { id: 'FA02', frage: 'Tatbestand des Dienstvergehens in BayDG Art. 6?', antwort: 'NEIN. Tatbestand in § 47 BeamtStG (Bund). BayDG Art. 6 = nur Maßnahmen-Katalog. Bund-Land-Trennschärfe.' },
    { id: 'FA03', frage: 'Strafverfahren verdrängt Disziplinarverfahren (Art. 103/3 GG)?', antwort: 'NEIN. Wortlaut: „allgemeine Strafgesetze". Disziplinarrecht ist Sonderrecht, kein „allgemeines Strafrecht". Beide laufen kumulativ.' },
    { id: 'FA04', frage: 'Bei einfacher Fahrlässigkeit haftet die LK persönlich?', antwort: 'NEIN. Art. 34 S. 2 GG: Rückgriff NUR bei Vorsatz + grober Fahrlässigkeit. Einfache F. = „kann vorkommen" → kein Rückgriff.' },
    { id: 'FA05', frage: 'Berufsbeamtentum-Anker steht in BV Art. 130?', antwort: 'NEIN. GG Art. 33/5 (BUND). BV Art. 130 ist stale Sekundärquellen-Pfad — präzise Norm-Zuordnung wichtig.' },
    { id: 'FA06', frage: 'BayDG kennt 7 Stufen?', antwort: 'JA — aber strukturiert: 5 Stufen Lebenszeit (Verweis bis Entfernung) + 2 Stufen Ruhestand (Kürzung/Aberkennung Ruhegehalt). Wer 7 ohne Trennung nennt, verkürzt.' },
    { id: 'FA07', frage: 'Aufsichtsversagen ist immer fahrlässige KV nach § 229 StGB?', antwort: 'NEIN. § 229 StGB setzt Kausalität + Vorhersehbarkeit + tatsächliche KV voraus. Aufsichtsversagen ohne KV-Folge → nur Disziplinar + ggf. Zivilhaftung, keine Strafbarkeit.' },
    { id: 'FA08', frage: 'Außerdienstliches Verhalten ist immer Dienstvergehen?', antwort: 'NEIN. § 47 Abs. 1 S. 2 BeamtStG: hohe Schwelle — „in besonderem Maße geeignet, das Vertrauen … in für ihr Amt bedeutsamer Weise zu beeinträchtigen". Einzelfall-Bewertung.' },
    { id: 'FA09', frage: 'Rückgriff der Freistaat → LK ist Pflicht?', antwort: 'NEIN. Art. 34 S. 2 GG: „Rückgriff bleibt vorbehalten" — Ermessen. Bei klar fahrlässiger Einzelpflichtverletzung übt der Freistaat regelmäßig kein Rückgriff aus, um Berufsausübung nicht zu lähmen.' },
    { id: 'FA10', frage: '„§ 203 StGB greift auch für jede LK"?', antwort: 'NEIN. § 203 StGB erfasst Berufsgruppen mit „geschütztem Privatgeheimnis" (Ärzte, Anwälte, Schulpsychologen). LK i.d.R. nicht direkt — aber § 14 LDO Verschwiegenheit greift, Verstoß = Dienstvergehen.' },
  ],

  faelle: [
    { id: 'F1', titel: 'Aufsichtsversagen mit schwerer Verletzung',
      sachverhalt: 'Während des Sportunterrichts verlässt LK den Raum für einen 10-min Telefonanruf. In ihrer Abwesenheit verletzt sich ein Schüler beim Klettern schwer (Schädel-Hirn-Trauma).',
      knackpunkte: [
        'Aufsichtspflichtverletzung § 5/1 LDO (Cross-Ref MP_06): Verlassen während Sportkletter-Phase ohne notwendige Maßnahmen.',
        'Zivilrechtlich: § 839 BGB + Art. 34 GG → Freistaat haftet außen. Eltern verklagen Freistaat.',
        'Rückgriff Freistaat → LK: bei grober Fahrlässigkeit zulässig (Telefonanruf während gefährlicher Sportphase = wahrscheinlich grob fahrlässig).',
        'Disziplinar: § 47 BeamtStG + BayDG Art. 6 — Stufe nach Schwere (Verweis bis Kürzung Dienstbezüge).',
        'Strafrecht: § 229 StGB fahrl. KV. Persönlich. KUMULATIV zum Disziplinar.',
      ],
      antwortkette: 'Aufsichtsverletzung § 5 LDO → Freistaat-Außenhaftung Art. 34 GG → Rückgriff bei grober F. → BayDG-Disziplinar parallel → § 229 StGB fahrl. KV persönlich (Schuldprinzip).',
    },
    { id: 'F2', titel: 'Verschwiegenheitsbruch — Eltern-Klatsch',
      sachverhalt: 'Eine LK erzählt einer befreundeten Mutter auf einem Geburtstag, dass ein bestimmter Schüler die LRS-Diagnose habe und „dauernd vergisst, seine Tabletten zu nehmen".',
      knackpunkte: [
        'Verschwiegenheitsbruch § 14 LDO + § 37 BeamtStG — dienstlich bekannt gewordene Gesundheits-/Förderdaten.',
        'Disziplinar: § 47 BeamtStG-Tatbestand erfüllt → BayDG Art. 6 Maßnahme (Verweis bis schärfer, je nach Schaden).',
        'Strafrecht: § 203 StGB greift NICHT direkt (LK keine geschützte Berufsgruppe iSd § 203), aber DSGVO-Verstoß möglich.',
        'Zivilrecht: Persönlichkeitsrechts-Verletzung → § 839 BGB + Art. 34 GG; Schadensersatz bei nachweisbarem Schaden.',
        'Notenauskunfts-Cross-Ref MP_06/MP_05: Drittauskunfts-Verbot greift verstärkt.',
      ],
      antwortkette: '§ 14 LDO + § 37 BeamtStG Verschwiegenheitsbruch → Disziplinar BayDG-Maßnahme → ggf. zivilrechtl. Persönlichkeitsrechts-Klage → § 203 StGB i.d.R. nicht direkt → DSGVO-Verstoß möglich.',
    },
    { id: 'F3', titel: 'Strafverfahren + Disziplinarverfahren parallel',
      sachverhalt: 'Eine LK wird wegen Volksverhetzung außerdienstlich angezeigt. Sie sagt: „Wenn ich strafrechtlich verurteilt werde, kann das Land mich doch nicht NOCHMAL über das Disziplinarrecht bestrafen — das wäre Doppelbestrafung!"',
      knackpunkte: [
        'Art. 103/3 GG: ne bis in idem GILT NUR für „allgemeine Strafgesetze" (Wortlaut).',
        'Disziplinarrecht = Sonderrecht für Beamte, KEIN „allgemeines Strafrecht". Beide Verfahren laufen kumulativ.',
        '§ 47 Abs. 1 S. 2 BeamtStG: außerdienstliches Verhalten erfasst, wenn „in besonderem Maße geeignet, das Vertrauen … bedeutsam zu beeinträchtigen". Bei LK: Volksverhetzung regelmäßig amtsbezogen wegen Vorbildfunktion.',
        'Disziplinarmaßnahme kann bis Entfernung aus Beamtenverhältnis (BayDG Art. 11) reichen.',
      ],
      antwortkette: 'Art. 103/3 GG „allgemeine Strafgesetze" → Disziplinarrecht ist Sonderrecht → kumulativ zulässig → § 47 BeamtStG außerdienstlich i.S.d. Amts-Vertrauens → BayDG-Maßnahme bis Entfernung.',
    },
    { id: 'F4', titel: 'Privater Verkehrsunfall — Außerdienstliches Verhalten',
      sachverhalt: 'Eine LK verursacht außerhalb der Dienstzeit einen Verkehrsunfall (einfache Fahrlässigkeit). Eltern klagen Schmerzensgeld.',
      knackpunkte: [
        'Privater Bereich — Außerdienst! KEINE Aufsichtspflichtverletzung im Schulkontext.',
        'Art. 34 GG greift NICHT — § 839 BGB direkt persönlich gegen LK.',
        '§ 47 BeamtStG außerdienstlich: nur bei „bedeutsamer" Amts-Beeinträchtigung. Einfacher Verkehrsunfall regelmäßig NICHT amtsbezogen → KEIN Dienstvergehen.',
        'Privat-Haftpflicht greift, Disziplinarrecht typisch nicht.',
      ],
      antwortkette: 'Privatbereich → Art. 34 GG greift nicht → § 839 BGB direkt LK → einfacher Verkehrsunfall = KEIN Dienstvergehen i.S.d. § 47 BeamtStG → Privat-Haftpflicht statt Amtshaftung.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'Haftungsdreieck — drei Pfade kumulativ',
      anriss: 'Zivil/Amtshaftung (Freistaat) · Disziplinar (LK persönlich, BayDG) · Strafrecht (LK persönlich, StGB). KEINE Verdrängung — Art. 103/3 GG nur „allgemeine Strafgesetze".',
      norm: 'Art. 34 GG', status: 'open', cards: 4,
      subblocks: [{ label: 'Drei-Pfad-Tabelle', cards: 1 }, { label: 'ne bis in idem', cards: 1 }, { label: 'Bund-Land-Trennschärfe', cards: 1 }, { label: 'Kumulativität', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'Amtshaftung § 839 BGB + Art. 34 GG',
      anriss: 'Außenhaftung Freistaat. Rückgriff NUR bei Vorsatz + grober Fahrlässigkeit. Beweislast Freistaat. Verschulden-Faustregel.',
      norm: '§ 839 BGB', status: 'open', cards: 3,
      subblocks: [{ label: 'Konstruktion', cards: 1 }, { label: 'Rückgriff-Schwelle', cards: 1 }, { label: 'Antwort-Schema', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: 'BayDG-Katalog 5+2 Stufen',
      anriss: 'Lebenszeit: Verweis · Geldbuße · Kürzung · Zurückstufung · Entfernung. Ruhestand: Kürzung · Aberkennung Ruhegehalt. Tatbestand § 47 BeamtStG (Bund).',
      norm: 'Art. 6 BayDG', status: 'open', cards: 3,
      subblocks: [{ label: '5 Stufen Lebenszeit', cards: 1 }, { label: '2 Stufen Ruhestand', cards: 1 }, { label: '§ 47 BeamtStG Tatbestand', cards: 1 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Strafrechts-Schnittstelle',
      anriss: '§ 229 StGB fahrl. KV · § 203 StGB Berufsgeheimnis (Schulpsych.) · § 174 StGB Schutzbefohlene. LK persönlich (Schuldprinzip). Kumulativ.',
      norm: '§ 229 StGB', status: 'open', cards: 3,
      subblocks: [{ label: 'StGB-Tatbestände', cards: 2 }, { label: '§ 203 vs. § 14 LDO', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'Verschuldensformen',
      anriss: 'Einfache F. („kann vorkommen") · grobe F. („darf nicht vorkommen") · Vorsatz (wissentlich + willentlich). Faustregel für Rückgriff Art. 34 S. 2.',
      norm: 'Art. 34 GG', status: 'open', cards: 2,
      subblocks: [{ label: 'Drei Stufen', cards: 1 }, { label: 'Rückgriff-Wirkung', cards: 1 }],
    },
  ],

  glossar: {
    'Art. 33/5 GG': { titel: 'Art. 33 Abs. 5 GG — Berufsbeamtentum', wortlaut: '„Das Recht des öffentlichen Dienstes ist unter Berücksichtigung der hergebrachten Grundsätze des Berufsbeamtentums zu regeln und fortzuentwickeln." Streikverbot, Treuepflicht, Alimentationsprinzip folgen aus diesem Anker. NICHT BV Art. 130.', karten: ['D06'] },
    'Art. 34 GG': { titel: 'Art. 34 GG — Staatshaftung', wortlaut: '„Verletzt jemand in Ausübung eines ihm anvertrauten öffentlichen Amtes die ihm einem Dritten gegenüber obliegende Amtspflicht, so trifft die Verantwortlichkeit grundsätzlich den Staat … Bei Vorsatz oder grober Fahrlässigkeit bleibt der Rückgriff vorbehalten."', karten: ['D01', 'D04'] },
    'Art. 103/3 GG': { titel: 'Art. 103 Abs. 3 GG — ne bis in idem', wortlaut: '„Niemand darf wegen derselben Tat auf Grund der ALLGEMEINEN STRAFGESETZE mehrmals bestraft werden." Wortlaut „allgemeine Strafgesetze" → Disziplinarrecht ist Sonderrecht, kein „allgemeines Strafrecht". Strafverfahren + Disziplinarverfahren laufen kumulativ.', karten: ['D05'] },
    'Art. 95 BV': { titel: 'Art. 95 BV — Beamtenverhältnis', wortlaut: 'Bayern-spezifischer Verfassungsanker für das Beamtenrecht. Ergänzt {{Art. 33/5 GG}}, das primärer „Berufsbeamtentum"-Anker bleibt.', karten: [] },
    '§ 47 BeamtStG': { titel: '§ 47 BeamtStG — Dienstvergehen (Bund)', wortlaut: 'Abs. 1: „Beamte begehen ein Dienstvergehen, wenn sie schuldhaft die ihnen obliegenden Pflichten verletzen. Verhalten außerhalb des Dienstes ist nur dann ein Dienstvergehen, wenn es nach den Umständen des Einzelfalls in besonderem Maße geeignet ist, das Vertrauen in einer für ihr Amt bedeutsamen Weise zu beeinträchtigen." Tatbestand des Dienstvergehens — NICHT in BayDG Art. 6 (dort nur Maßnahmen).', karten: ['D02', 'D08'] },
    '§ 839 BGB': { titel: '§ 839 BGB — Beamtenhaftung', wortlaut: 'Abs. 1: Verletzt ein Beamter vorsätzlich oder fahrlässig die ihm einem Dritten gegenüber obliegende Amtspflicht, so hat er den Schaden zu ersetzen. I.V.m. {{Art. 34 GG}} → Staatshaftung mit Rückgriff bei Vorsatz/grober Fahrlässigkeit.', karten: ['D01'] },
    '§ 203 StGB': { titel: '§ 203 StGB — Berufsgeheimnis', wortlaut: 'Unbefugte Offenbarung von Privatgeheimnissen durch geschützte Berufsgruppen (Ärzte, Anwälte, Schulpsychologen) strafbar. LK i.d.R. NICHT direkt erfasst — aber {{§ 14 LDO}} Verschwiegenheit greift; Verstoß ist Dienstvergehen.', karten: [] },
    '§ 229 StGB': { titel: '§ 229 StGB — fahrlässige Körperverletzung', wortlaut: 'Wer durch Fahrlässigkeit die Körperverletzung eines anderen verursacht, wird mit Freiheitsstrafe bis 3 Jahren oder Geldstrafe bestraft. Kausalität + Vorhersehbarkeit erforderlich. Typische Aufsichtsfall-Strafnorm.', karten: ['D07'] },
    '§ 174 StGB': { titel: '§ 174 StGB — Sexueller Missbrauch Schutzbefohlener', wortlaut: 'Sexuelle Handlungen an oder mit Personen unter 16/18 J., die der Erziehung/Ausbildung anvertraut sind. Gravierender Tatbestand mit besonderem Vertrauensschutz. Strafe persönlich + Disziplinarmaßnahme bis Entfernung.', karten: [] },
    'Art. 6 BayDG': { titel: 'Art. 6 BayDG — Disziplinarmaßnahmen-Katalog', wortlaut: 'Abs. 1: 5 Stufen Lebenszeit-Beamte: (1) Verweis ({{Art. 7 BayDG}}) · (2) Geldbuße ({{Art. 8 BayDG}}) · (3) Kürzung der Dienstbezüge ({{Art. 9 BayDG}}) · (4) Zurückstufung ({{Art. 10 BayDG}}) · (5) Entfernung aus dem Beamtenverhältnis ({{Art. 11 BayDG}}). Abs. 2: 2 Stufen Ruhestand: (1) Kürzung Ruhegehalt ({{Art. 12 BayDG}}) · (2) Aberkennung Ruhegehalt ({{Art. 13 BayDG}}). Tatbestand „Dienstvergehen" steht in {{§ 47 BeamtStG}}.', karten: ['D03'] },
    'Art. 7 BayDG': { titel: 'Art. 7 BayDG — Verweis', wortlaut: 'Niedrigste Disziplinarmaßnahme — schriftlicher Tadel. Keine finanziellen Auswirkungen, bleibt aber in der Personalakte.', karten: [] },
    'Art. 8 BayDG': { titel: 'Art. 8 BayDG — Geldbuße', wortlaut: 'Geldbuße bis zur Höhe der monatlichen Dienstbezüge.', karten: [] },
    'Art. 9 BayDG': { titel: 'Art. 9 BayDG — Kürzung der Dienstbezüge', wortlaut: 'Kürzung um max. 1/5 für längstens 3 Jahre.', karten: [] },
    'Art. 10 BayDG': { titel: 'Art. 10 BayDG — Zurückstufung', wortlaut: 'Zurückstufung in eine niedrigere Besoldungsgruppe — schwerwiegende Disziplinarmaßnahme.', karten: [] },
    'Art. 11 BayDG': { titel: 'Art. 11 BayDG — Entfernung aus dem Beamtenverhältnis', wortlaut: 'Höchste Disziplinarmaßnahme bei Lebenszeit-Beamten. Beendigung des Beamtenverhältnisses; Verlust der Bezüge + Ruhegehalts-Anwartschaft. Nur bei Lebenszeit-Beamten.', karten: [] },
    'Art. 12 BayDG': { titel: 'Art. 12 BayDG — Kürzung des Ruhegehalts', wortlaut: 'Bei Ruhestandsbeamt:innen Kürzung um max. 1/5 für längstens 3 Jahre.', karten: [] },
    'Art. 13 BayDG': { titel: 'Art. 13 BayDG — Aberkennung des Ruhegehalts', wortlaut: 'Höchste Disziplinarmaßnahme bei Ruhestandsbeamt:innen. Verlust des Ruhegehalt-Anspruchs (ggf. Härtefallregelung).', karten: [] },
    '§ 5 LDO': { titel: '§ 5 LDO — Aufsichtspflicht (Cross-Ref MP_06)', wortlaut: 'Aufsichtspflicht-Substrat (Cross-Ref MP_06 A.2 für Vollzitat + Reichweite + Vier-Leitfragen-Schema).', karten: [] },
    '§ 14 LDO': { titel: '§ 14 LDO — Verschwiegenheit (Cross-Ref MP_06)', wortlaut: 'Verschwiegenheits-Trias mit drei Bereichen — Vollzitat siehe MP_06 A.3. Verstoß = Dienstvergehen iSd § 47 BeamtStG.', karten: [] },
    '§ 22 BaySchO': { titel: '§ 22 BaySchO — Aufsicht-Anker (Cross-Ref MP_06)', wortlaut: '§ 22 BaySchO Beaufsichtigungs-Anker — Vollzitat siehe MP_06 A.2.', karten: [] },
  },
};
