// D Mathematik — Fachdidaktik · 2. Staatsexamen MS Bayern · Mai 2026
window.MODULE = {
  id: 'd-mathematik',
  zalgm: 'Fachdidaktik · D Mathematik',
  schwerpunkt: ['A.1 Grundlagen + Kompetenzmodell', 'A.2 EIS + Konstruktivismus', 'A.3 Operatives Prinzip', 'A.4 Modellieren', 'A.5 Sequenz + Spiral + Diff.', 'A.6 Antwort-Schema'],
  titel: 'Mathematik.',
  titel2: 'Didaktische Prinzipien + Antwortgerüst.',
  abriss:
    'Würzburg-Kanon (Weigand 8 Prinzipien) + Bausteinskripte Engelking + LP+ ' +
    'Bayern Mittelschule. Top-12 Themen für die mündliche Prüfung, mit ' +
    'Realisierungs-Anker auf Pauls M7c-Praxis (Prozent-Sequenz 26 UE).',

  kurz: [
    '**EIS-Prinzip (Bruner)**: enaktiv → ikonisch → symbolisch. Im LP+ wörtlich verlangt („handelnd sichtbar machen"). Praxis-Beispiel: M7R-Prozent UE1-7 (100er-Feld → Prozentstreifen → Dreisatz-Schema).',
    '**Operatives Prinzip (Aebli/Wittmann)**: 5 Operationsmerkmale — Reversibilität · Transitivität · Komposition · Assoziativität · Distributivität. Praxis: umgekehrter Dreisatz p%→1%→100% als Reversibilitäts-Anker.',
    '**Modellieren / Sachrechnen / Beziehungshaltigkeit**: prozessbezogene Kernkompetenz LP+. Modellierungskreislauf realer Situation → math. Modell → Lösung → Validierung. Praxis: Mischungsverhältnisse Bäckerei/Maler/Apotheke.',
    '**Sequenz-Architektur**: Spiralprinzip (LP+ markiert Spirale) + 4-Phasen-Modell (Einführung · Sicherung · Übung · Anwendung) + Differenzierung 3 Niveaustufen (Basis/Regelstandard/Erhöht). Cross-Layer: sprachsensibel + inklusiv.',
    'Antwort-Schema 8 Punkte (Seminar SW V): Zusammenhang · Grobgliederung · Begriffsklärungen · LP+-Wortlaut · Realisierung mit Praxisbeispiel · Probleme/Grenzen · Wertung · Zusammenfassung. **Bewertungsachsen**: Erfassen · Fachkenntnisse · Darlegung.',
  ],

  deck: { cards: 10, normebenen: 5, hochprior: 10, fallen: 9 },

  kartografie: [
    { ebene: 'I', bez: 'Verfassung + KMK', kuerzel: 'VERF', normen: ['BV Art. 131', 'KMK MSA 2003/04', 'KMK Bildungsstandards Mathe'], sub: 'Bildungsauftrag · Bildungsstandards-Anker' },
    { ebene: 'II', bez: 'LehrplanPLUS Bayern', kuerzel: 'LP+', normen: ['Fachprofil Mathematik MS', 'Kompetenzstrukturmodell M', 'Lernbereiche M5–M10'], sub: '6 prozessbez. Kompetenzen + 4 Gegenstandsbereiche · 5 LBs/Jgst.' },
    { ebene: 'III', bez: 'Didaktische Prinzipien', kuerzel: 'DIDA', normen: ['Weigand 8 Prinzipien', 'Bausteinskript Engelking', 'EIS Bruner', 'Operativ Aebli/Wittmann', 'Polya'], sub: 'Würzburg-Kanon · Lehrbuch-Kanon · Klassiker' },
    { ebene: 'IV', bez: 'Schulbücher + KMBek', kuerzel: 'SB', normen: ['FormelPLUS R7', 'AH SINUS Bayern'], sub: 'Lehrwerk-Anker · Aufgabenkultur SINUS' },
    { ebene: 'V', bez: 'Eigene Praxis', kuerzel: 'PRAXIS', normen: ['M7c SJ 25/26 Prozent-Sequenz (26 UE)', 'Seminarübung v2/v3', 'Tafelfußball-Gamification'], sub: 'Real-Beispiele aus eigener UE' },
  ],

  pflichtwissen: [
    { id: 'M01', titel: 'Kompetenzstrukturmodell M',
      frage: 'Wie ist das Kompetenzstrukturmodell für Mathematik im LP+ aufgebaut?',
      antwort: 'Zwei Achsen: **6 prozessbezogene Kompetenzen** (modellieren · Probleme lösen · argumentieren · kommunizieren · mit symbolischen/formalen/techn. Elementen umgehen · Darstellungen verwenden) × **4 Gegenstandsbereiche** (Zahlen und Operationen · Größen und Messen · Raum und Form · Daten und Zufall · Funktionaler Zusammenhang). Jede KE im LP+ ist **doppeltgetaggt** — prozessbez. + gegenstandsbez.',
      norm: 'LP+ Fachprofil M', status: 'open' },
    { id: 'M02', titel: 'EIS-Prinzip (Bruner)',
      frage: 'Was ist das EIS-Prinzip und warum ist es zentral für den MU?',
      antwort: '**Drei Repräsentationsebenen** (Bruner 1966): **E**naktiv (Handlung am Material) → **I**konisch (Bild) → **S**ymbolisch (Notation). Lernende sollen jede Stufe durchlaufen. Im LP+ wörtlich gefordert („handelnd sichtbar machen"). **Praxis** (M7R-Prozent): 100er-Feld enaktiv UE1-2 → Prozentstreifen ikonisch UE3-7 → Dreisatz/Schema symbolisch UE7+. Quelle: Weigand §7 + GB §3.4.',
      norm: 'EIS-Bruner', status: 'open' },
    { id: 'M03', titel: 'Operatives Prinzip + 5 Operationsmerkmale',
      frage: 'Was bedeutet das Operative Prinzip — und welche 5 Operationsmerkmale gehören dazu?',
      antwort: 'Operatives Prinzip (Aebli/Wittmann): Lernende durchdringen mathematische Begriffe durch **Operationen mit ihnen**. **5 Merkmale**: **Reversibilität** (Umkehrbarkeit) · **Transitivität** (a→b, b→c also a→c) · **Komposition** (Verkettung) · **Assoziativität** · **Distributivität**. **Praxis** (Prozent): Reversibilität = umgekehrter Dreisatz p%→1%→100%; Komposition = Doppelrabatt; Transitivität = Entscheidungsbaum GW/PW/PS.',
      norm: 'Aebli/Wittmann', status: 'open' },
    { id: 'M04', titel: 'Modellieren + Modellierungskreislauf',
      frage: 'Was ist Modellieren als prozessbezogene Kompetenz — und wie verläuft der Modellierungskreislauf?',
      antwort: 'Modellieren = Übersetzung **realer Sachsituation ↔ mathematisches Modell**. **5-Schritt-Kreislauf** (Blum/Leiß): (1) Verstehen + Konstruieren des Situationsmodells · (2) Vereinfachen + Strukturieren · (3) Mathematisieren · (4) Mathematisch arbeiten · (5) Interpretieren + Validieren. **Praxis**: Mischungsverhältnisse Bäckerei (10% Roggen + 90% Weizen für 5 kg Brot) — Sachsituation → Anteilsrechnung → Validierung am realen Rezept.',
      norm: 'LP+ prozessbez.', status: 'open' },
    { id: 'M05', titel: 'Polya + Heuristiken',
      frage: 'Welche 4 Phasen des Problemlöseprozesses sieht Polya — und welche Heuristiken sind relevant?',
      antwort: '**Polya 4 Phasen** („How to Solve It" 1945): (1) Verstehen der Aufgabe · (2) Plan ausdenken · (3) Plan ausführen · (4) Rückschau. **12 Heuristiken** (Auswahl): Skizze · Tabelle · Rückwärtsarbeiten · Analogiebildung · systematisches Probieren · Vereinfachen · Spezialisieren · Generalisieren · Symmetrie nutzen · Invariante suchen · Hilfsproblem · Hilfsfigur. Im LP+ Bayern als Auftrag „Probleme lösen" verankert.',
      norm: 'Polya 1945', status: 'open' },
    { id: 'M06', titel: 'Spiralprinzip + Kumulatives Lernen',
      frage: 'Wie zeigt sich das Spiralprinzip im LP+ Mathematik MS?',
      antwort: 'Spiralprinzip (Bruner): jedes Thema kehrt mit **steigender kognitiver Anforderung** wieder. **LP+ markiert die Spirale selbst** durch Lernbereich-Querverweise. **Praxis**: M6-LB1.1 Bruch ↔ Dezimal ↔ Prozent → M7R-LB1 Prozentrechnung → M9R-LB1 Zinsrechnung. **Kumulativ**: jedes Folge-LB greift auf das vorhergehende zurück. Bezug: Fachprofil M §2.3.',
      norm: 'Bruner / LP+', status: 'open' },
    { id: 'M07', titel: 'Konstruktivismus + Primat der Handlung',
      frage: 'Was bedeutet konstruktivistisches Lernen für den MU — und wie unterscheidet es sich vom Behaviorismus?',
      antwort: '**Konstruktivismus**: Wissen wird vom Lernenden aktiv **selbst konstruiert** — nicht „eingegossen" (≠ Behaviorismus). **Primat der Handlung**: Verstehen entsteht im operativen Tun, nicht durch passives Zuhören (Montessori, Piaget). **Konsequenz**: aktive SuS-Phase > Lehrer-Vortrag; offene Aufgaben > geschlossene; produktives Üben > rein imitierendes Üben (Wittmann).',
      norm: 'Piaget / Montessori', status: 'open' },
    { id: 'M08', titel: '4-Phasen-Sequenzaufbau',
      frage: 'Welche vier Phasen kennt der klassische MU-Sequenzaufbau B1/B2?',
      antwort: '**4 Phasen** (Bausteinskript B1/B2): (1) **Einführung** — Problemkontext, Vorwissen aktivieren, kognitiver Konflikt · (2) **Sicherung** — Begriff/Verfahren fixieren, Hefteintrag · (3) **Übung** — automatisieren, Differenzierung Basis/Regel/Erhöht · (4) **Anwendung** — Transfer, Sachkontexte, produktives Üben. **Praxis** (Prozent): UE1-2 Einstieg → UE6 Hefteintrag GW/PW/PS → UE7-16 Üben → UE21+ Mischung/Beruf.',
      norm: 'Bausteinskript B1/B2', status: 'open' },
    { id: 'M09', titel: 'Differenzierung + Sprachsensibler MU',
      frage: 'Wie wird Differenzierung im MU realisiert — und was meint Sprachsensibilität?',
      antwort: '**Differenzierung 3 Niveaustufen** (Basis · Regelstandard · Erhöht) pro Aufgabe/AB. Methoden: Tippkarten, Lösungsbeispiele, Worked Examples, Aufgabenpool. **Sprachsensibler MU** (Leisen): Fachsprache schrittweise aufbauen, Bildsprache → Symbolsprache vermitteln, Operatoren-Wortschatz explizit machen. **DaZ-Anker**: Begriffsklärungen visualisieren + verbalisieren. Bezug: LP+ §1.5 + KMBek BIK.',
      norm: 'Leisen / LP+', status: 'open' },
    { id: 'M10', titel: 'Aufgabenkultur SINUS + Produktives Üben',
      frage: 'Was kennzeichnet die SINUS-Aufgabenkultur — und was ist „produktives Üben"?',
      antwort: '**SINUS-Aufgabenkultur** (BLK-Modellversuch): offene Aufgaben mit mehreren Lösungswegen · Beziehungsreichtum · Selbstdifferenzierung · Reflexion explizit. **Produktives Üben** (Wittmann): Übung mit gleichzeitiger Entdeckung neuer Zusammenhänge — nicht imitierendes Wiederholen. **Praxis**: 1×1-Forschermappe statt 10× Rechnung; Zahlenmauern; Rechendreieck.',
      norm: 'SINUS / Wittmann', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: 'EIS-Stufen = drei verschiedene Klassenstufen?', antwort: 'NEIN. EIS sind **drei Repräsentationsebenen** desselben Begriffs — alle drei sollen pro Begriff durchlaufen werden, idealerweise in **einer** UE oder Sequenz. Nicht: enaktiv nur GS, symbolisch nur MS — jeder Begriff braucht alle drei Stufen.' },
    { id: 'FA02', frage: 'Operatives Prinzip = einfach mit Material arbeiten?', antwort: 'NEIN. **Operatives Prinzip ≠ enaktive Stufe**. Operativ meint die **5 Operationsmerkmale** (Reversibilität, Transitivität, …) — also Beziehungs-Operationen mit dem Begriff. Material-Arbeit ist EIS-enaktiv (separates Prinzip).' },
    { id: 'FA03', frage: 'Modellieren = jede Sachaufgabe?', antwort: 'NEIN. Modellieren verlangt **echte Übersetzung** Realsituation → math. Modell mit **Validierung**. Eine reine eingekleidete Sachaufgabe („Hans hat 5 Äpfel …") ist KEIN Modellieren — sie liefert das Modell vorweg.' },
    { id: 'FA04', frage: 'Spiralprinzip = Wiederholung am Schuljahresanfang?', antwort: 'NEIN. Spirale ≠ Wiederholung. **Spiralig** heißt: Thema kehrt mit **erweiterter kognitiver Anforderung** wieder (M6 Bruch → M7 Prozent → M9 Zins — jeweils neue Operationen, höhere AFB).' },
    { id: 'FA05', frage: 'Konstruktivismus = LK sagt nichts mehr, SuS entdecken alles?', antwort: 'NEIN. Konstruktivismus = **aktive Konstruktion** durch SuS — aber Lehrkraft als **Lernbegleiter, Strukturgeber, Impulsgeber**. „Stiller Mathematikraum" ohne LK-Strukturierung ist nicht konstruktivistisch, sondern unangeleitet.' },
    { id: 'FA06', frage: '4-Phasen-Modell = starre Reihenfolge in jeder UE?', antwort: 'NEIN. **Sequenz-Modell**, nicht Stunden-Modell. Phasen können sich über eine **gesamte Lernsequenz** (z.B. 5–8 UEs) erstrecken. Eine einzelne UE kann komplett in Phase 3 (Übung) liegen.' },
    { id: 'FA07', frage: '„Mitarbeit" im MU als eigene Note?', antwort: 'NEIN (Cross-Ref Schulrecht MP_04 / Art. 52/3 BayEUG): Zeugnisnote = Gesamtleistungen. „Anlagen, Mitarbeit, Verhalten" als **Soll-Bemerkungen** möglich, aber keine eigenständige Mitarbeitsnote.' },
    { id: 'FA08', frage: 'SINUS-Aufgaben = nur für leistungsstarke SuS?', antwort: 'NEIN. SINUS-offene Aufgaben sind gerade **selbst-differenzierend** — schwache SuS arbeiten auf einfacher Ebene, starke auf komplexer; eine Aufgabe deckt mehrere Niveaustufen ab. Beispiel: Zahlenmauer mit Pflicht- und Forscher-Aufgaben.' },
    { id: 'FA09', frage: 'Im MU ist Sprache nicht so wichtig — Mathematik ist eine Symbolsprache?', antwort: 'NEIN. **Sprachsensibler MU** ist zentral (Leisen). Operatoren-Sprache („vergleichen", „beschreiben", „begründen"), Aufgabenverständnis, Fachsprache-Aufbau und Bild-Symbol-Übersetzung sind kritisch — gerade für SuS mit DaZ.' },
  ],

  faelle: [
    { id: 'F1', titel: 'M7R Prozent-Sequenz — EIS + Spirale (Hauptfall, eigene Praxis)',
      sachverhalt: 'M7c-Klasse (heterogen, ⅔ Migrationshintergrund, einige DaZ, 3× LRS-Verdacht): Einführung in die Prozentrechnung. Sie sollen eine 26-UE-Sequenz didaktisch begründen.',
      knackpunkte: [
        '**EIS-Progression**: UE1-2 enaktiv (100er-Feld, Hundertstelquadrat) → UE3-9 ikonisch (Prozentstreifen, Farbcodierung) → UE10-22 symbolisch (Dreisatz, Schema) → UE23-26 anwendend (Mischung, Diagramme, Beruf).',
        '**Spiralanker**: Direkter Anschluss an M6-LB1.1 (Bruch ↔ Dezimal ↔ Prozent — Hundertstel als Vor-Wissen) + Ausblick auf M9R-LB1 (Zinsrechnung).',
        '**Operatives Prinzip**: UE10 Reversibilität (umgekehrter Dreisatz GW), UE15 Transitivität (Entscheidungsbaum GW/PW/PS), UE19 Komposition (Doppelrabatt).',
        '**Modellieren**: UE20 Mischungsverhältnisse Bäckerei/Maler/Apotheke — Realsituation → Anteilsrechnung → Validierung.',
        '**Differenzierung**: Tafelfußball-Gamification 13.10.2025 mit Schwierigkeitsstufen (Basis/Regel/Erhöht); Worked Examples für leistungsschwache SuS.',
        '**Sprachsensibel**: Farbcodierung BLAU/ROT/GRÜN für GW/PW/PS; Begriffsklärungen explizit als Hefteintrag UE6.',
      ],
      antwortkette: '8-Punkte-Schema: (1) Prozent als Anteile im Gesamtzusammenhang LP+ → (2) Grobgliederung 4 Phasen → (3) Begriffe GW/PW/PS → (4) LP+-Wortlaut M7R-LB1 → (5) Realisierung 26 UE (eigene Praxis 13.10. zitieren!) → (6) Probleme: heterogene Vorkenntnisse, DaZ-Sprachhürde → (7) Wertung: Spirale trägt, Operatives Prinzip macht Reversibilität greifbar → (8) Zusammenfassung.',
    },
    { id: 'F2', titel: 'Modellieren mit Mischungsverhältnissen',
      sachverhalt: 'Sie sollen modellbasiertes Mathematiklernen im LP+ am Beispiel Mischungsverhältnisse erläutern.',
      knackpunkte: [
        '**LP+-Wortlaut M7R-LB1**: „bestimmen Prozentwert und Prozentsatz bei Mischungsverhältnissen und bewältigen problemorientierte Aufgaben aus Alltag und Beruf."',
        '**Modellierungskreislauf** Blum/Leiß: (1) Situationsmodell (Brot-Rezept) · (2) Vereinfachen (nur Mehl-Anteil zählt) · (3) Mathematisieren (Anteilsrechnung) · (4) Lösen (Dreisatz) · (5) Validieren (Test am realen Rezept).',
        '**Beziehungshaltigkeit / Lebensweltbezug** (Freudenthal): Bäckerei, Maler-Mischung, Apotheke — alles im LP+ als Berufsbezug verankert.',
        '**Prozessbez. Kompetenz LP+**: modellieren explizit gefordert. Doppeltagging mit Gegenstandsbereich „Zahlen und Operationen".',
      ],
      antwortkette: 'LP+-Wortlaut → Modellierungskreislauf erläutern → Bäckerei-Beispiel mit Validierung am Brot-Rezept → Bezug zum Berufsorientierungs-Anker LP+ → Cross-Ref WiB-Schnittstelle.',
    },
    { id: 'F3', titel: 'Differenzierung in heterogener M7c — Tafelfußball-Praxis',
      sachverhalt: 'Sie haben in einer heterogenen M7c eine Übungsphase Prozent durchgeführt. Wie haben Sie differenziert?',
      knackpunkte: [
        '**Tafelfußball-Gamification** (Miro-Board, 4 Teams) mit drei Schwierigkeitsstufen: Basis (Standardaufgaben mit Tipps) · Regelstandard (Sachaufgaben) · Erhöht (Doppelrabatt, Mischung).',
        '**Self-Differentiation**: SuS wählen ihre Stufe; bei Punkten zählen alle gleich (Motivations-Anker für schwache SuS).',
        '**Tippkarten + Worked Examples** für Basis-Stufe; Aufgabenpool mit Reflexionsfragen für Erhöht-Stufe.',
        '**Sprachsensibel**: Farbcodierung BLAU (GW) / ROT (PW) / GRÜN (PS) durchgehend; Begriffsklärung visualisiert.',
        '**LNW-Vorbereitung UE25**: gemischte Aufgaben mit allen drei Niveaus, Probearbeit UE26 als regulär-bewertende Erhebung.',
      ],
      antwortkette: 'Heterogenität benennen → 3-Stufen-Differenzierung erläutern → Tafelfußball-Praxis konkret zitieren → Bezug LP+-Differenzierungsauftrag + Inklusion → Reflexion: was lief gut/was nicht.',
    },
    { id: 'F4', titel: 'Antwort-Schema 8-Punkte am Beispiel „EIS-Prinzip"',
      sachverhalt: 'Prüfungsfrage: „Erläutern Sie das EIS-Prinzip und seine Realisierung im Mathematikunterricht der Mittelschule." (10 Min Antwortzeit)',
      knackpunkte: [
        '**(1) Zusammenhang**: EIS = Repräsentationsebenen-Prinzip Bruner 1966, zentral für Begriffsbildung im MU.',
        '**(2) Grobgliederung**: Theorie → Realisierung → Wertung → Schluss.',
        '**(3) Begriffe**: enaktiv (Handlung) · ikonisch (Bild) · symbolisch (Zeichen).',
        '**(4) LP+-Wortlaut**: „handelnd sichtbar machen" (M7R-LB1) als wörtlicher Auftrag zur enaktiven Stufe.',
        '**(5) Realisierung**: Prozent-Sequenz 100er-Feld → Prozentstreifen → Dreisatz-Schema. Eigene Praxis 22.09.2025 zitieren.',
        '**(6) Probleme**: Zeit-Aufwand für enaktive Phase; SuS mit Vorwissen springen direkt symbolisch.',
        '**(7) Wertung**: trägt, weil Begriffsverständnis stabilisiert wird — auch für leistungsschwache SuS.',
        '**(8) Zusammenfassung**: EIS als didaktisches Rückgrat jeder MU-Sequenz.',
      ],
      antwortkette: '8-Punkte-Schema strikt durchgehen; **immer Praxis zitieren** (Bewertungsachse Fachkenntnisse + Praxisorientierung); auf Lehrplan- und Sekundärquellen-Bezüge achten.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'Grundlagen — LP+ + Kompetenzstrukturmodell M',
      anriss: 'BV Art. 131 Bildungsauftrag · LP+ Bayern MS Fachprofil M · Kompetenzstrukturmodell mit 6 prozessbez. × 4 Gegenstands-Bereichen. Doppeltagging-Logik im LP+.',
      norm: 'LP+ Fachprofil M', status: 'open', cards: 2,
      subblocks: [{ label: 'Verfassungs-/KMK-Anker', cards: 1 }, { label: 'Kompetenzstrukturmodell M (Doppeltagging)', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'EIS-Prinzip + Konstruktivismus',
      anriss: 'EIS-Stufen enaktiv/ikonisch/symbolisch (Bruner). Konstruktivistisches Lernen + Primat der Handlung (Piaget/Montessori). Realisierung an M7R-Prozent-Sequenz.',
      norm: 'EIS-Bruner', status: 'open', cards: 3,
      subblocks: [{ label: 'EIS-Stufen + LP+-Wortlaut', cards: 1 }, { label: 'Konstruktivismus + Primat der Handlung', cards: 1 }, { label: 'Praxis-Anker M7R-Prozent UE1-7', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: 'Operatives Prinzip + 5 Operationsmerkmale',
      anriss: 'Aebli/Wittmann — Begriffe durch Operationen durchdringen. Reversibilität · Transitivität · Komposition · Assoziativität · Distributivität. Cross-Differenzierung zu EIS.',
      norm: 'Aebli/Wittmann', status: 'open', cards: 3,
      subblocks: [{ label: '5 Operationsmerkmale verbatim', cards: 1 }, { label: 'Abgrenzung zu EIS (häufige Falle)', cards: 1 }, { label: 'Praxis-Anker Reversibilität Prozent', cards: 1 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Modellieren + Sachrechnen + Beziehungshaltigkeit',
      anriss: 'Modellierungskreislauf Blum/Leiß (5 Schritte). Beziehungshaltigkeit (Freudenthal). LP+ als prozessbezogene Kompetenz mit explizitem Berufsbezug.',
      norm: 'LP+ prozessbez.', status: 'open', cards: 3,
      subblocks: [{ label: '5-Schritt-Kreislauf Blum/Leiß', cards: 1 }, { label: 'Modellieren ≠ Sachaufgabe (Falle)', cards: 1 }, { label: 'Praxis Mischungsverhältnisse Beruf', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'Sequenz-Architektur — 4 Phasen + Spirale + Diff.',
      anriss: '4-Phasen-Modell (Einführung/Sicherung/Übung/Anwendung). Spiralprinzip + Kumulatives Lernen. Differenzierung 3 Niveaustufen + Sprachsensibler MU.',
      norm: 'Bausteinskript B1/B2', status: 'open', cards: 4,
      subblocks: [{ label: '4-Phasen-Modell B1/B2', cards: 1 }, { label: 'Spiralprinzip + LP+-Spirale', cards: 1 }, { label: 'Differenzierung 3 Niveaustufen', cards: 1 }, { label: 'Sprachsensibler MU (Leisen)', cards: 1 }],
    },
    { id: 'A6', kuerzel: 'A.6', titel: 'Antwort-Schema 8-Punkte + Polya + Aufgabenkultur',
      anriss: '8-Punkte-Schema Seminar SW V als Antwort-Gerüst. Polya 4-Phasen + 12 Heuristiken. SINUS-Aufgabenkultur + Produktives Üben (Wittmann). Bewertungsachsen Erfassen/Fachkenntnisse/Darlegung.',
      norm: 'Polya / SINUS', status: 'open', cards: 3,
      subblocks: [{ label: '8-Punkte-Antwort-Schema', cards: 1 }, { label: 'Polya 4 Phasen + Heuristiken', cards: 1 }, { label: 'SINUS + Produktives Üben', cards: 1 }],
    },
  ],

  glossar: {
    'BV Art. 131': { titel: 'BV Art. 131 — Bildungsziele', wortlaut: 'Bayerischer Bildungsauftrag: Ehrfurcht vor Gott, Achtung vor religiöser Überzeugung, vor der Würde des Menschen + Selbstbeherrschung, Verantwortungsbewusstsein, Hilfsbereitschaft. Rahmen für jedes Fach.', karten: [] },
    'LP+ Fachprofil M': { titel: 'LP+ Bayern MS — Fachprofil Mathematik', wortlaut: 'Definiert den Bildungs- und Erziehungsauftrag des Faches Mathematik. **6 prozessbez. Kompetenzen** (modellieren · Probleme lösen · argumentieren · kommunizieren · symbolische/formale/techn. Elemente · Darstellungen) × **4–5 Gegenstandsbereiche** (Zahlen und Operationen · Größen und Messen · Raum und Form · Daten und Zufall · Funktionaler Zusammenhang). Jede KE wird **doppeltgetaggt** prozessbez. + gegenstandsbez.', karten: ['M01'] },
    'Kompetenzstrukturmodell M': { titel: 'Kompetenzstrukturmodell Mathematik', wortlaut: 'Zweidimensionale Struktur prozessbez. × gegenstandsbez. Kompetenzen. Cross-Layer-Logik: jede KE zeigt, welche Prozessebenen + Gegenstandsbereiche sie bedient. Unterschied zu GPG / Sk: dort eigenes Kompetenzstrukturmodell mit anderen Achsen.', karten: ['M01'] },
    'EIS-Bruner': { titel: 'EIS-Prinzip (Bruner 1966)', wortlaut: 'Drei Repräsentationsebenen: **E**naktiv (Handlung am Material) → **I**konisch (Bild/Visualisierung) → **S**ymbolisch (Notation/Zeichensystem). Lernende durchlaufen alle drei Stufen pro Begriff. Im LP+ wörtlich gefordert: „handelnd sichtbar machen" (M7R-LB1). Quelle: Bruner, Studies in Cognitive Growth.', karten: ['M02'] },
    'Aebli/Wittmann': { titel: 'Operatives Prinzip (Aebli/Wittmann)', wortlaut: 'Lernende durchdringen mathematische Begriffe durch **Operationen mit ihnen**. **5 Operationsmerkmale**: Reversibilität (Umkehrbarkeit) · Transitivität (a→b→c) · Komposition (Verkettung) · Assoziativität · Distributivität. Praxis-Anker: Umkehraufgaben, Entscheidungsbäume, verkettete Operationen. Quelle: Wittmann, Grundfragen des Mathematikunterrichts; Aebli, Zwölf Grundformen des Lehrens.', karten: ['M03'] },
    'LP+ prozessbez.': { titel: 'Prozessbezogene Kompetenzen LP+ M', wortlaut: '6 prozessbez. Kompetenzen Mathematik: (1) **modellieren** — Realsituation ↔ math. Modell · (2) **Probleme lösen** — Polya · (3) **argumentieren** · (4) **kommunizieren** · (5) **mit symbolischen/formalen/techn. Elementen umgehen** · (6) **Darstellungen verwenden**. Jede KE im LP+ trägt mindestens eine prozessbez. Komp.', karten: ['M04'] },
    'Polya 1945': { titel: 'Polya 4 Phasen + 12 Heuristiken', wortlaut: '**Polya (How to Solve It, 1945) — 4 Phasen**: (1) Verstehen · (2) Plan · (3) Ausführen · (4) Rückschau. **12 Heuristiken**: Skizze · Tabelle · Rückwärtsarbeiten · Analogiebildung · systematisches Probieren · Vereinfachen · Spezialisieren · Generalisieren · Symmetrie · Invariante · Hilfsproblem · Hilfsfigur. Im LP+ unter „Probleme lösen" verankert.', karten: ['M05'] },
    'Bruner / LP+': { titel: 'Spiralprinzip (Bruner / LP+)', wortlaut: 'Jedes Thema kehrt mit **steigender kognitiver Anforderung** wieder. LP+ markiert die Spirale durch LB-Querverweise. **Beispiel**: M6-LB1.1 Bruch↔Dezimal↔Prozent → M7R-LB1 Prozent → M9R-LB1 Zins. Kumulatives Lernen = Folge-LB greift auf Vor-LB zurück. Quelle: Bruner, Prozeß der Erziehung; LP+ Fachprofil §2.3.', karten: ['M06'] },
    'Piaget / Montessori': { titel: 'Konstruktivismus + Primat der Handlung', wortlaut: '**Konstruktivismus** (Piaget): Wissen wird vom Lernenden **aktiv konstruiert** — nicht passiv übernommen. **Primat der Handlung** (Montessori, Piaget): kognitive Entwicklung verläuft über sensomotorische Stufen — Verstehen entsteht im Tun. Konsequenz für MU: aktive SuS-Phasen, offene Aufgaben, Material-Arbeit, Diskursphasen.', karten: ['M07'] },
    'Bausteinskript B1/B2': { titel: '4-Phasen-Sequenzmodell (Bausteinskript B1/B2 Engelking)', wortlaut: '**4 Phasen**: (1) **Einführung** — Problemkontext + Vorwissen + kognitiver Konflikt · (2) **Sicherung** — Begriff/Verfahren fixieren, Hefteintrag · (3) **Übung** — automatisieren, differenzieren · (4) **Anwendung** — Transfer, Sachkontexte, produktives Üben. Modell ist **Sequenz-** nicht Stunden-bezogen. Quelle: Bausteinskripte Mathematik Engelking Unterfranken.', karten: ['M08'] },
    'Leisen / LP+': { titel: 'Sprachsensibler MU (Leisen)', wortlaut: 'Methodik nach Josef Leisen: Bildsprache → Symbolsprache → Fachsprache schrittweise aufbauen. **Operatoren-Wortschatz** explizit machen („vergleichen", „begründen", „erläutern"). **DaZ-Anker**: Begriffsklärungen visualisieren + verbalisieren, Sprachgerüste anbieten. Cross-Ref BIK-KMBek.', karten: ['M09'] },
    'SINUS / Wittmann': { titel: 'Aufgabenkultur SINUS + Produktives Üben', wortlaut: '**SINUS-Aufgabenkultur** (BLK-Modellversuch 1998–2003): offene Aufgaben mit mehreren Lösungswegen · Beziehungsreichtum · Selbstdifferenzierung. **Produktives Üben** (Wittmann): Übung mit gleichzeitiger Entdeckung neuer Zusammenhänge — Zahlenmauern, Rechendreieck, 1×1-Forschermappe. Cross-Ref: kein imitierendes Wiederholen.', karten: ['M10'] },
  },
};
