// N18 Sozialkunde — Fachdidaktik · 2. Staatsexamen MS Bayern · Mai 2026
window.MODULE = {
  id: 'n18-sozialkunde',
  zalgm: 'N18 · Sozialkunde (Unterrichtsfach + Fachdidaktik)',
  schwerpunkt: ['A.1 LP+ + Kompetenzmodell GPG', 'A.2 Beutelsbach', 'A.3 Mündigkeit + Urteilsbildung', 'A.4 Demokratielernen', 'A.5 Handlungsorientierung + Methoden'],
  titel: 'Sozialkunde.',
  titel2: 'Politische Bildung MS Bayern.',
  abriss:
    'Sozialkunde liegt in der MS unter GPG (LB3 + LB4 jeder Jgst.). Beutelsbacher ' +
    'Konsens als Minimal-Konsens politischer Bildung. Mündigkeit (Detjen) als ' +
    'Zielkategorie. Handlungsorientierung in Realhandeln + Simulationshandeln.',

  kurz: [
    '**Beutelsbacher Konsens** (1976, LpB BW): drei Minimalbedingungen — (1) **Überwältigungsverbot** / Indoktrinationsverbot · (2) **Kontroversitätsgebot** (in Politik/Wiss. Kontroverses muss im U. kontrovers erscheinen) · (3) **Schülerorientierungs-Prinzip** (eigene Position analysieren + Konsequenzen ziehen).',
    '**Politische Mündigkeit** (Detjen 2007) als Zielkategorie: selbstständig politisch urteilen + handeln können. NICHT durch Belehrung erreichbar — methodisches Korrelat = **Handlungsorientierung**. Cross-Ref Kant „Sapere aude".',
    '**Politische Urteilsbildung** zentrales Lernziel — drei Urteilsformen (Sachurteil · Werturteil · Entscheidungsurteil). Voraussetzung: **Multiperspektivität** (mehrere Standpunkte/Quellen, GPG GB §3.2).',
    '**Demokratielernen** als Schulleitprinzip: Demokratie als **Lebens-, Gesellschafts-, Herrschaftsform** (Dewey). Operative Anker: Klassenrat · SMV · Schule als Polis (Werterziehungsansatz).',
    '**Handlungsorientierung** (Reinhardt, Massing): didaktisches Leitprinzip, kein Einzelverfahren. **Realhandeln** (Klassenrat, Petition) vs. **Simulationshandeln** (Rollenspiel, Planspiel). Beide sind legitime Realisierungen.',
  ],

  deck: { cards: 10, normebenen: 5, hochprior: 10, fallen: 8 },

  kartografie: [
    { ebene: 'I', bez: 'Verfassung + KMK', kuerzel: 'VERF', normen: ['BV Art. 131', 'KMK Demokratie-Erklärung 2018', 'GG Art. 20 Demokratieprinzip'], sub: 'Bildungsauftrag · Demokratieprinzip' },
    { ebene: 'II', bez: 'LehrplanPLUS Bayern', kuerzel: 'LP+', normen: ['Fachprofil GPG', 'Kompetenzstrukturmodell GPG', 'LB3 Politik und Gesellschaft (jede Jgst.)', 'LB4 Demokratie und Beteiligung'], sub: 'GPG5-9 LB3+LB4 = Sk-Anteil in der MS' },
    { ebene: 'III', bez: 'Konsens + Klassiker', kuerzel: 'KLASSIK', normen: ['Beutelsbacher Konsens 1976', 'Detjen Mündigkeit 2007', 'Sander 2014', 'Dewey Demokratie'], sub: 'Minimal-Konsens politischer Bildung' },
    { ebene: 'IV', bez: 'Methodik-Kanon', kuerzel: 'METH', normen: ['GPG B3 + B4 (Bausteinskript Bayern)', 'Reinhardt Handlungsorientierung 2018', 'Massing Realhandeln 2012', 'Klippert Methodik 1997'], sub: 'Sk-Sekundärliteratur · Mikro-/Makromethoden' },
    { ebene: 'V', bez: 'Eigene Praxis', kuerzel: 'PRAXIS', normen: ['GPG5b SJ 24/25 Ägypten (Rollenspiel)', 'GPG5b Antike Demokratie (Pro-Contra)', 'Just-Community-Konflikte'], sub: 'Real-Beispiele aus GPG5b' },
  ],

  pflichtwissen: [
    { id: 'S01', titel: 'Beutelsbacher Konsens',
      frage: 'Was ist der Beutelsbacher Konsens — und welche drei Prinzipien umfasst er?',
      antwort: '**Tagungsergebnis 1976** (LpB Baden-Württemberg) — drei **Minimalbedingungen politischer Bildung**: (1) **Überwältigungsverbot** (Indoktrinationsverbot): LK darf SuS nicht überwältigen; SuS müssen sich eigene Meinung bilden können. (2) **Kontroversitätsgebot**: Was in Politik/Wissenschaft kontrovers ist, muss kontrovers im Unterricht erscheinen. (3) **Schülerorientierung**: SuS sollen befähigt werden, ihre politische Lage zu analysieren und Konsequenzen zu ziehen. Quelle: bpb · GPG B3 §1.1.',
      norm: 'Beutelsbach 1976', status: 'open' },
    { id: 'S02', titel: 'Politische Mündigkeit (Detjen)',
      frage: 'Was bedeutet politische Mündigkeit als Zielkategorie?',
      antwort: 'Selbstständig **politisch urteilen + handeln** können (Detjen 2007). NICHT durch Belehrung erreichbar — methodisches Korrelat = **Handlungsorientierung**. Kant-Bezug: „Sapere aude — habe Mut, dich deines eigenen Verstandes zu bedienen." Zentrale Zielkategorie aller politischen Bildung; ohne Mündigkeit verfehlt Sk-U. seinen Auftrag.',
      norm: 'Detjen 2007', status: 'open' },
    { id: 'S03', titel: 'Politische Urteilsbildung — 3 Urteilsformen',
      frage: 'Welche drei Urteilsformen unterscheidet die politische Urteilsbildung?',
      antwort: '(1) **Sachurteil**: deskriptives, faktenbasiertes Urteil („So ist es"). (2) **Werturteil**: normatives Urteil unter Bezug auf Werte/Normen („So soll es sein"). (3) **Entscheidungsurteil**: praktisches Handlungs-Urteil unter Bedingungen („Das tue ich"). Voraussetzung für rationale Urteilsbildung: **Multiperspektivität** (mehrere Standpunkte/Quellen).',
      norm: 'Sander 2014', status: 'open' },
    { id: 'S04', titel: 'Demokratielernen — drei Demokratie-Aspekte',
      frage: 'Demokratielernen umfasst Demokratie in welchen drei Aspekten?',
      antwort: '**Drei Aspekte** (Dewey, übernommen Sander 2014): (1) **Lebensform** (Demokratie als Alltagspraxis · gegenseitige Anerkennung) · (2) **Gesellschaftsform** (Pluralismus, Vielfalt der Lebensentwürfe) · (3) **Herrschaftsform** (Institutionen, Wahlen, Gewaltenteilung). Operative Anker im Schulalltag: **Klassenrat · SMV · Schule als Polis**. Schulleitprinzip LP+ ÜBZ.',
      norm: 'Dewey / Sander', status: 'open' },
    { id: 'S05', titel: 'Handlungsorientierung — Real vs. Simulation',
      frage: 'Was unterscheidet Realhandeln von Simulationshandeln (Massing)?',
      antwort: '**Realhandeln**: **echte politische Partizipation** — Klassenrat, SMV, Petition, Brief an die Stadtverwaltung. Wirkung in der realen Welt. **Simulationshandeln**: simulierte politische Situation — Planspiel, Rollenspiel, Gerichtssimulation, Pro-Contra-Debatte. Wirkung nur im Bildungsraum. **Beide sind legitime Realisierungen** handlungsorientierter Sk; Wahl je nach Lernziel + Thema.',
      norm: 'Massing 2012', status: 'open' },
    { id: 'S06', titel: 'Multiperspektivität',
      frage: 'Was ist Multiperspektivität als didaktisches Prinzip?',
      antwort: '**Gleichzeitige Berücksichtigung verschiedener Standpunkte/Quellen** zu einem Sachverhalt. Voraussetzung für **rationale Urteilsbildung** und Erfüllung des Kontroversitätsgebots. Für GPG verbatim im LP+ Kompetenzstrukturmodell verankert. Quelle: GPG GB §3.2 · Sander 2014. Cross-Ref Schulrecht MP_05 (SuS-Anhörungsrecht — auch dort Multiperspektivität verfahrenslogisch).',
      norm: 'Sander 2014', status: 'open' },
    { id: 'S07', titel: 'Werterziehung — drei Konzept-Stufen',
      frage: 'Welche drei Konzepte der Werterziehung kennt die Sk-Didaktik?',
      antwort: '(1) **Dilemmadiskussion** (Kohlberg): kognitiv urteilsbildend, ABER moralisch folgenarm — als Propädeutik politischen Handelns ungeeignet. (2) **Just-Community** (Kohlberg/Power): SuS für Schul-/Klassenkonflikte selbst verantwortlich (Fairness-Komitees); reaktiv-konfliktorientiert, Wirkungsbereich zu schmal. (3) **Schule als Polis**: erweitert Just-Community um die **gestalterische Komponente** — SuS gestalten Schule mit; „Es ist für mich bedeutsam" + praktisches Handeln. Anker für Demokratielernen.',
      norm: 'GPG B3 §1.2', status: 'open' },
    { id: 'S08', titel: 'Mikro- vs. Makromethoden (Klippert)',
      frage: 'Wie unterscheiden sich Mikro- und Makromethoden in der Sk-Methodik?',
      antwort: '**Mikromethoden**: einzelne Lern-/Arbeitstechniken — Textarbeit, Karikatur-Analyse, Brainstorming, Diskussion, **Pro-Contra-Debatte**, Mind-Mapping. **Makromethoden**: komplexe Vollzugsformen aus mehreren Mikromethoden — **Fallanalyse, Erkundung, Projekt, Sozialstudie, Rollenspiel, Planspiel, Entscheidungsspiel**. Quelle: Klippert 1997 · GPG B4 §2.',
      norm: 'Klippert 1997', status: 'open' },
    { id: 'S09', titel: 'Kasuistik / Fallanalyse',
      frage: 'Was ist das kasuistische Prinzip in der Sk?',
      antwort: '**„Ausschnitt aus der Wirklichkeit"** als didaktischer Zugang: ein **konkreter Fall** steht im Mittelpunkt, nicht systematische Inhaltsentfaltung. Trägt **Fallanalyse, Aktualstunde, Lebensweltbezug**. Cross-Ref: Aktualitätsprinzip GPG GB §5.4 — Sk-U. knüpft an gegenwärtige polit./gesellschaftl. Ereignisse an.',
      norm: 'GPG B3 §2.1.1', status: 'open' },
    { id: 'S10', titel: 'Rollenspiel — vier Stufen (Giesecke)',
      frage: 'Welche vier Stufen unterscheidet das Rollenspiel als Sk-Methode?',
      antwort: '**Vier Stufen** (Giesecke 1973): **frei · offen · halboffen · gebunden** — vom freien Hineinversetzen in eine soziale Situation bis zur stark strukturierten Rolle mit vorgegebenem Text. **Schult**: Ambiguitätstoleranz, Rollendistanz, Empathie, kommunikative Kompetenz. Cross-Ref Planspiel (GPG B4 §2.2.8): höhere Komplexität, SuS vertreten Institutionen/Interessengruppen statt Individuen.',
      norm: 'Giesecke 1973', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: 'Überwältigungsverbot = LK darf keine Meinung haben?', antwort: 'NEIN. LK darf eine **eigene begründete Position** haben und nennen — aber NICHT die SuS in diese Position überwältigen/indoktrinieren. Position muss als **eine** Position kenntlich sein; SuS müssen sich eigene Meinung bilden können. Cross-Ref Kontroversitätsgebot.' },
    { id: 'FA02', frage: 'Kontroversitätsgebot = im Unterricht muss alles gleich gewichtet sein?', antwort: 'NEIN. **„Was in Politik/Wissenschaft kontrovers ist"** — wo kein gesellschaftlicher Konsens besteht. Antidemokratische Positionen sind NICHT „kontrovers" zu behandeln (Werte-Boden GG/BV). Kontroversität bezieht sich auf den Stand der Debatte, nicht auf jedes Thema.' },
    { id: 'FA03', frage: 'Beutelsbach-Schülerorientierung = SuS bestimmen die Themen?', antwort: 'NEIN. Drittes Prinzip: SuS sollen **befähigt werden, ihre eigene politische Lage zu analysieren und Konsequenzen zu ziehen** — Lernziel-Kategorie, nicht Themen-Auswahl. Lehrplan bleibt Rahmen.' },
    { id: 'FA04', frage: 'Mündigkeit (Detjen) entsteht durch politisches Wissen?', antwort: 'NEIN. Mündigkeit ist NICHT durch Belehrung erreichbar — verlangt **Handlungsorientierung** als methodisches Korrelat. Sk-U. nur als „politische Faktenkunde" verfehlt Mündigkeitsauftrag.' },
    { id: 'FA05', frage: 'Dilemmadiskussion (Kohlberg) = empfohlene Sk-Methode?', antwort: 'NEIN — kritisch beurteilt. Dilemmadiskussion ist zwar **kognitiv urteilsbildend**, aber **moralisch folgenarm** — als Propädeutik politischen Handelns ungeeignet (GPG B3 §1.2). Stattdessen: **Schule als Polis** mit gestalterischer Komponente.' },
    { id: 'FA06', frage: 'Realhandeln = besser als Simulationshandeln?', antwort: 'NEIN. **Beide sind legitime Realisierungen** handlungsorientierter Sk. Realhandeln (Klassenrat, Petition) wirkt in der Welt; Simulationshandeln (Rollenspiel, Planspiel) ermöglicht riskante Experimente ohne reale Konsequenzen. Wahl je nach Lernziel + Thema.' },
    { id: 'FA07', frage: 'Multiperspektivität = alle Meinungen sind gleich gut?', antwort: 'NEIN. Multiperspektivität ist **Voraussetzung für rationale Urteilsbildung** — verschiedene Standpunkte werden geprüft, aber **Argument-Qualität entscheidet**. Werte-Boden GG/BV bleibt unhintergehbar.' },
    { id: 'FA08', frage: 'Beutelsbacher Konsens steht im LP+?', antwort: 'NICHT direkt — Beutelsbach ist ein **Fach-Konsens der politischen Bildung** (1976, LpB BW), kein Gesetz/Lehrplan. ABER: Der LP+ Bayern setzt Beutelsbach implizit voraus (GPG B3 §1.1). Im Examen Beutelsbach NAMENTLICH nennen + Quelle (bpb / 1976).' },
  ],

  faelle: [
    { id: 'F1', titel: 'Antike Demokratie + Volksversammlung (Hauptfall, eigene Praxis GPG5b)',
      sachverhalt: 'GPG5b, Klasse 5 (SJ 24/25, 20 SuS, ⅔ arab. Migrationshintergrund, 2 DaZ, 3× LRS-Verdacht). LP+ GPG5 LB3: „beschreiben Zusammensetzung und Befugnisse der Volksversammlung im antiken Griechenland und beurteilen diese Form der Mitsprache für die Bürgerinnen und Bürger als ersten Ansatz von Demokratie."',
      knackpunkte: [
        '**LP+-Wortlaut**: Operator „beurteilen" verlangt **Urteilsbildung** — Werturteil (war griechische Demokratie demokratisch?) + Entscheidungsurteil (welche Elemente sind heute übertragbar?).',
        '**Methode**: **Rollenspiel** (Giesecke-Stufe halboffen) — Volksversammlung mit Zusammensetzung/Befugnissen; SuS vertreten Bevölkerungsgruppen nach Rechten/Pflichten.',
        '**Pro-Contra-Debatte**: „Demokratie damals/heute" — Multiperspektivität + Kontroversitätsgebot.',
        '**Demokratielernen-Anker** (Sander 2014): Polis als Vorform der Demokratie als Lebens-/Gesellschafts-/Herrschaftsform.',
        '**Mündigkeit (Detjen)**: SuS sollen eigenes Urteil über demokratische Mitsprache bilden — nicht nur historisch reproduzieren.',
        '**Sprachsensibel**: Kartenarbeit Griechenland (UE1) + Modellanalyse Polis (UE2) zur Visualisierung; Begriffe „Bürger", „Mitsprache" explizit erarbeitet (BIK-Anker für DaZ).',
      ],
      antwortkette: 'LP+-Wortlaut zitieren → Beutelsbach-Konsens als Rahmen → Rollenspiel + Pro-Contra als Methoden-Wahl begründen (Mikro-/Makromethoden Klippert) → Praxis GPG5b Juni 2025 zitieren → Mündigkeit + Urteilsbildung als Lernziele explizit machen → Probleme: DaZ-Sprachbarriere, Vergleich antik/modern für 5.-Klässler abstrakt → Wertung: tragfähig, vor allem mit visueller Unterstützung.',
    },
    { id: 'F2', titel: 'Beutelsbacher Konsens als Examensfrage',
      sachverhalt: 'Erläutern Sie den Beutelsbacher Konsens und seine Bedeutung für die Sk-Unterrichtspraxis (10 Min).',
      knackpunkte: [
        '**(1) Zusammenhang**: Beutelsbach = **Minimal-Konsens politischer Bildung** in Deutschland seit 1976. Verbindlich für alle Lehrkräfte; quasi-normativer Standard.',
        '**(2) Grobgliederung**: Drei Prinzipien → Bezug zum LP+ → Realisierung → Grenzen → Wertung.',
        '**(3) Begriffsklärung**: Indoktrinations- vs. Überwältigungsverbot; Kontroversität in Wissenschaft/Politik (NICHT Werte-Boden GG); Schülerorientierung als Befähigungs-Ziel.',
        '**(4) LP+-Anker**: Beutelsbach nicht verbatim im LP+, aber implizit vorausgesetzt — GPG Fachprofil §1 Prinzipien politischer Bildung.',
        '**(5) Realisierung**: Pro-Contra-Debatte als Kontroversitäts-Anker; eigene Lehrer-Position als „eine" Position nennen; Multiperspektivität in Quellen.',
        '**(6) Probleme**: Werte-Boden bei AfD-/Extremismus-Themen; was ist „kontrovers genug"?',
        '**(7) Wertung**: trägt, weil er **professionelle Standards** sichert ohne lehrplanmäßige Verengung.',
        '**(8) Zusammenfassung**: Beutelsbach = ethischer Standard, nicht Methodenrezept.',
      ],
      antwortkette: 'Strikt nach 8-Punkte-Schema. **Quelle 1976 + bpb** namentlich nennen. Konkretes Beispiel aus eigener Praxis: Pro-Contra Demokratie (GPG5b Juni 2025).',
    },
    { id: 'F3', titel: 'Ägypten-Gesellschaftspyramide — Rollenspiel + Multiperspektivität',
      sachverhalt: 'GPG5b SJ 24/25 KW 2-5 (Januar–Februar 2025, 8 UEs). LP+ GPG5 LB3: „stellen die unterschiedlichen Lebens- und Arbeitsbedingungen der Menschen im alten Ägypten dar und erklären anhand der hierarchisch aufgebauten Gesellschaftspyramide deren unterschiedliche Stellung und Macht in der Hochkultur."',
      knackpunkte: [
        '**Methode**: Rollenspiel zur Gesellschaftspyramide (Pharao, Beamte, Bauern, Sklaven) — Giesecke halboffene Stufe.',
        '**Multiperspektivität** (Sander 2014, GPG GB §3.2): jede Schicht aus eigener Perspektive sprechen lassen; verschiedene „Stimmen" der Hochkultur.',
        '**Stationenlernen** (Mikromethoden-Kombination): Götter, Pyramiden, Hieroglyphen.',
        '**KLN 2 Abfrage** + **GLN 2 Stationen-Test** als LNW-Verfahren.',
        '**Kompetenzstrukturmodell GPG**: prozessbez. **Methodenkompetenz** (Bildanalyse Nil) + **historische Urteilsbildung** + gegenstandsbez. „Politik und Gesellschaft" LB3.',
        '**Wiederholung**: Mind-Mapping als Sicherungs-Anker.',
      ],
      antwortkette: 'LP+-Wortlaut zitieren → Methoden-Wahl (Rollenspiel, Stationenlernen) begründen → Multiperspektivität + Kompetenzstrukturmodell explizit → Eigene Praxis-Daten (8 UEs Jan-Feb 2025) → Bildungsziel: historische Urteilsbildung als Vorform politischer Urteilsbildung.',
    },
    { id: 'F4', titel: 'Demokratielernen — Klassenrat in der GPG5b einführen',
      sachverhalt: 'Sie wollen in der GPG5b einen Klassenrat als demokratiebildende Maßnahme einführen. Wie begründen Sie das didaktisch?',
      knackpunkte: [
        '**Demokratielernen** (Dewey/Sander 2014): Demokratie als Lebens-/Gesellschafts-/Herrschaftsform — Klassenrat ist **operativer Anker für Lebensform**.',
        '**Realhandeln (Massing 2012)**: echte Partizipation, nicht Simulation.',
        '**Schule als Polis** (Werterziehung): SuS gestalten Schule/Klasse mit; „Es ist für mich bedeutsam" + praktisches Handeln.',
        '**Beutelsbach-Konformität**: Klassenrat ermöglicht Kontroversität (verschiedene Meinungen werden gehört) + Schülerorientierung (SuS analysieren ihre Lage).',
        '**Mündigkeit (Detjen)**: Klassenrat als Übungsfeld für politische Urteilsbildung + Handeln.',
        '**LP+-Anker**: Schulleitprinzip ÜBZ Demokratielernen; nicht in einzelnen LBs verankert.',
      ],
      antwortkette: 'Demokratie-3-Aspekte erläutern → Klassenrat als Lebensform-Anker positionieren → Massing-Realhandeln zitieren → Schule-als-Polis als überlegene Werterziehungsform (vs. Just-Community / Dilemma) → Beutelsbach-Konformität demonstrieren → Wertung: praktikabel ab GS, in MS standardmäßig.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'LP+ + Kompetenzstrukturmodell GPG (Sk-Anker)',
      anriss: 'In der MS ist Sozialkunde **kein eigenständiges Fach** — sozialwissenschaftliche Inhalte stehen unter GPG (Geschichte/Politik/Geographie), LB3 + LB4 jeder Jahrgangsstufe. Sonderfall N18: 2 Schulrecht-Fragen statt SR + SB.',
      norm: 'LP+ Fachprofil GPG', status: 'open', cards: 3,
      subblocks: [{ label: 'Sozialkunde in der MS = GPG LB3+4', cards: 1 }, { label: 'Kompetenzstrukturmodell GPG', cards: 1 }, { label: 'BV Art. 131 + Demokratie GG Art. 20', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'Beutelsbacher Konsens — 3 Prinzipien',
      anriss: '1976, LpB BW — Minimal-Konsens politischer Bildung: Überwältigungsverbot · Kontroversitätsgebot · Schülerorientierung. Quasi-normativer Standard für alle LK.',
      norm: 'Beutelsbach 1976', status: 'open', cards: 3,
      subblocks: [{ label: 'Überwältigungsverbot (1)', cards: 1 }, { label: 'Kontroversitätsgebot (2)', cards: 1 }, { label: 'Schülerorientierung (3)', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: 'Mündigkeit (Detjen) + Politische Urteilsbildung',
      anriss: 'Mündigkeit als Zielkategorie politischer Bildung — selbstständig urteilen + handeln. Drei Urteilsformen (Sachurteil / Werturteil / Entscheidungsurteil) mit Multiperspektivität als Voraussetzung.',
      norm: 'Detjen 2007', status: 'open', cards: 3,
      subblocks: [{ label: 'Mündigkeit + Kant-Bezug', cards: 1 }, { label: '3 Urteilsformen (Sach/Wert/Entscheidung)', cards: 1 }, { label: 'Multiperspektivität als Voraussetzung', cards: 1 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Demokratielernen + Werterziehungs-Konzepte',
      anriss: 'Demokratie als Lebens-/Gesellschafts-/Herrschaftsform (Dewey). Werterziehungs-Konzepte: Dilemma (Kohlberg) → Just-Community → Schule als Polis. Operative Anker Klassenrat + SMV.',
      norm: 'Dewey / Sander', status: 'open', cards: 3,
      subblocks: [{ label: '3 Demokratie-Aspekte (Dewey)', cards: 1 }, { label: 'Werterziehung 3 Stufen', cards: 1 }, { label: 'Klassenrat + SMV als Anker', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'Handlungsorientierung + Methodik',
      anriss: 'Reinhardt/Massing: didaktisches Leitprinzip. Realhandeln vs. Simulationshandeln. Mikro-/Makromethoden (Klippert): Rollenspiel · Planspiel · Pro-Contra · Erkundung · Fallanalyse.',
      norm: 'Reinhardt / Massing', status: 'open', cards: 4,
      subblocks: [{ label: 'Handlungsorientierung als Leitprinzip', cards: 1 }, { label: 'Real- vs. Simulationshandeln (Massing)', cards: 1 }, { label: 'Mikro/Makro (Klippert) — Methoden-Katalog', cards: 1 }, { label: 'Rollenspiel (Giesecke 4 Stufen)', cards: 1 }],
    },
  ],

  glossar: {
    'BV Art. 131': { titel: 'BV Art. 131 — Bildungsziele', wortlaut: 'Bayerischer Bildungsauftrag: Ehrfurcht vor Gott, Achtung vor religiöser Überzeugung, vor der Würde des Menschen + Selbstbeherrschung, Verantwortungsbewusstsein, Hilfsbereitschaft. Werte-Boden auch für politische Bildung.', karten: [] },
    'GG Art. 20': { titel: 'GG Art. 20 — Demokratieprinzip', wortlaut: 'Abs. 1: „Die Bundesrepublik Deutschland ist ein demokratischer und sozialer Bundesstaat." Abs. 2: Alle Staatsgewalt geht vom Volke aus. Verfassungsrechtlicher Anker für **Demokratielernen** als Schulleitprinzip.', karten: [] },
    'LP+ Fachprofil GPG': { titel: 'LP+ Bayern MS — Fachprofil GPG', wortlaut: 'Geschichte / Politik / Geographie als integriertes Fach in der MS. **LB3 Politik und Gesellschaft** + **LB4 Demokratie und Beteiligung** je Jgst. 5-9 = Sozialkunde-Anteil. Sonderfall N18: 2 Schulrecht-Fragen statt SR+SB.', karten: [] },
    'Kompetenzstrukturmodell GPG': { titel: 'Kompetenzstrukturmodell GPG', wortlaut: 'Eigene Achsen: **Methodenkompetenz** + **Sach-/Orientierungskompetenz** + **historische Urteilsbildung** + **politische Urteilsbildung** + **Handlungskompetenz** × Inhaltsbereiche. NICHT identisch mit Kompetenzmodell M (Cross-Ref Falle: nicht verwechseln).', karten: [] },
    'Beutelsbach 1976': { titel: 'Beutelsbacher Konsens (1976)', wortlaut: 'Tagungsergebnis 1976 LpB Baden-Württemberg. **Drei Minimalbedingungen politischer Bildung**: (1) **Überwältigungsverbot** = Indoktrinationsverbot: LK darf SuS nicht überwältigen; SuS müssen eigene Meinung bilden können. (2) **Kontroversitätsgebot**: was in Politik/Wissenschaft kontrovers ist, muss kontrovers im Unterricht erscheinen. (3) **Schülerorientierung**: SuS sollen befähigt werden, ihre politische Lage zu analysieren und Konsequenzen zu ziehen. Quelle: bpb · GPG B3 §1.1. Quasi-normativer Standard ohne Gesetzes-Status.', karten: ['S01'] },
    'Detjen 2007': { titel: 'Politische Mündigkeit (Detjen)', wortlaut: 'Joachim Detjen, „Politische Bildung" 2007. **Mündigkeit** = selbstständig politisch urteilen + handeln können. NICHT durch Belehrung erreichbar — methodisches Korrelat = **Handlungsorientierung**. Kant-Bezug: „Sapere aude — habe Mut, dich deines eigenen Verstandes zu bedienen." Zentrale Zielkategorie aller politischen Bildung.', karten: ['S02'] },
    'Sander 2014': { titel: 'Wolfgang Sander — Politische Urteilsbildung', wortlaut: '„Politik in der Schule" 2014 — drei Urteilsformen: **Sachurteil** (deskriptiv) · **Werturteil** (normativ) · **Entscheidungsurteil** (Handlungs-Urteil). Voraussetzung: **Multiperspektivität**. Sander auch zentrale Quelle für Demokratielernen-Konzeption (Lebensform-Gesellschaftsform-Herrschaftsform Trias).', karten: ['S03', 'S06'] },
    'Dewey / Sander': { titel: 'Demokratielernen (Dewey / Sander)', wortlaut: '**John Dewey** „Demokratie und Erziehung" (1916/1930): Demokratie nicht nur als Herrschaftsform, sondern als **Lebensform**. **Wolfgang Sander 2014** systematisiert drei Aspekte: (1) **Lebensform** (Alltagspraxis, gegenseitige Anerkennung) · (2) **Gesellschaftsform** (Pluralismus, Vielfalt) · (3) **Herrschaftsform** (Institutionen, Wahlen, Gewaltenteilung). Operative Anker: Klassenrat · SMV · Schule als Polis.', karten: ['S04'] },
    'Massing 2012': { titel: 'Handlungsorientierung — Real vs. Simulation (Massing)', wortlaut: '**Peter Massing 2012**: zwei Realisierungen handlungsorientierter Sk: **Realhandeln** = echte Partizipation (Klassenrat, SMV, Petition, Brief an Stadtverwaltung) mit realer Wirkung. **Simulationshandeln** = Planspiel, Rollenspiel, Gerichtssimulation mit Wirkung nur im Bildungsraum. Beide legitim; Wahl je nach Lernziel + Thema.', karten: ['S05'] },
    'GPG B3 §1.2': { titel: 'Werterziehungs-Konzepte (GPG B3 §1.2)', wortlaut: 'Drei Stufen der Werterziehungs-Konzeption: (1) **Dilemmadiskussion** (Kohlberg) — kognitiv urteilsbildend, aber **moralisch folgenarm**; als Propädeutik politischen Handelns ungeeignet. (2) **Just-Community** (Kohlberg/Power) — SuS für Schul-/Klassenkonflikte selbst verantwortlich (Fairness-Komitees); reaktiv-konfliktorientiert, Wirkungsbereich zu schmal. (3) **Schule als Polis** — erweitert Just-Community um die **gestalterische Komponente**; SuS gestalten Schule mit, „Es ist für mich bedeutsam" + praktisches Handeln. Anker für Demokratielernen.', karten: ['S07'] },
    'Klippert 1997': { titel: 'Mikro-/Makromethoden (Klippert)', wortlaut: '**Heinz Klippert 1997** „Methodenlernen". **Mikromethoden** = einzelne Lern-/Arbeitstechniken (Textarbeit, Karikatur, Brainstorming, Diskussion, Pro-Contra-Debatte, Mind-Mapping). **Makromethoden** = komplexe Vollzugsformen aus mehreren Mikromethoden (Fallanalyse, Erkundung, Projekt, Sozialstudie, Rollenspiel, Planspiel, Entscheidungsspiel). Cross-Ref GPG B4 §2 — bayerische Sk-Methodik.', karten: ['S08'] },
    'GPG B3 §2.1.1': { titel: 'Kasuistik / Fallanalyse', wortlaut: '**„Ausschnitt aus der Wirklichkeit"** als didaktischer Zugang. Konkreter Fall steht im Mittelpunkt, nicht systematische Inhaltsentfaltung. Trägt Fallanalyse, Aktualstunde, Lebensweltbezug. Cross-Ref Aktualitätsprinzip GPG GB §5.4.', karten: ['S09'] },
    'Giesecke 1973': { titel: 'Rollenspiel — 4 Stufen (Giesecke)', wortlaut: '**Hermann Giesecke 1973** — Rollenspiel als Spielform mit Sich-Hineinversetzen in soziale Situation. **Vier Stufen**: **frei** (improvisierend) · **offen** (Rahmen, freie Gestaltung) · **halboffen** (Rolle + Eckdaten) · **gebunden** (Rolle + Text). Schult **Ambiguitätstoleranz, Rollendistanz, Empathie, kommunikative Kompetenz**. Cross-Ref Planspiel (GPG B4 §2.2.8): höhere Komplexität, Institutionen/Interessengruppen statt Individuen.', karten: ['S10'] },
  },
};
