// MP_08 — Kooperation mit Bildungs- und Betreuungseinrichtungen
window.MODULE = {
  id: 'mp08',
  zalgm: 'ZALGM § 16 Nr. 8',
  schwerpunkt: ['8.1 MSD', '8.2 Förderzentrum', '8.3 Schulberatung', '8.4 Betreuung 4 Säulen', '8.5 GTS + Förderlehrkraft'],
  titel: 'Kooperation Bildung',
  titel2: '+ Betreuung.',
  abriss:
    'Schulinterne Dienste (MSD/BL/SPych) subsidiär; außerschul. Stellen (Hort/Jugendamt) ' +
    'mit eigener Trägerschaft. Lernort entscheiden Eltern (Art. 41 BayEUG). ' +
    'Diagnostik in allgem. Schule = Schulermessen.',

  kurz: [
    'MSD ≠ FöS — Dienst (Art. 21 BayEUG) vs. Schulart (Art. 19). Träger: nächstgelegene FöS mit entspr. Förderschwerpunkt. Aufgaben: diagnostizieren, fördern, beraten, koordinieren, Fortbildung.',
    '7 Förderschwerpunkte (Art. 20/1): Sehen · Hören · k./m. Entwicklung · gE · Sprache · Lernen · em./soz. Entwicklung. Praxis-Erweiterung: + Autismus + ELECOK.',
    'Lernort = Eltern-Entscheidung (Art. 41/1 BayEUG). Hertha-Falle: FS gE → Regelschule rechtlich möglich (Art. 41/1 + 30a/3); Sachaufwandsträger-Zustimmung NUR bei Sehen/Hören/k.-m. (Art. 30a/4) — bei gE NICHT erforderlich.',
    'Beratungsweg 5 Stufen: KL → BL/SPych/MSD → Beratungsrektor:in → Staatl. Schulberatungsstelle → Außerschulisch (Erziehungsberatung, Jugendamt). BL ≠ SPych — Lehrkraft + Zusatzqual. vs. Psychologe. LK darf NICHT selbst therapieren.',
    'Vier Säulen Betreuung: Mittagsbetreuung (Art. 31/3, Gemeinde) · Halbtags-GS (KMBek, staatl.) · GTS oGTS/gGTS (Art. 6/4 + KMBek, staatl.) · Hort (§ 22 SGB VIII, JuHi-Träger). Drei Rechtsregime. gGTS-Anmeldung freiwillig, Teilnahme verpflichtend.',
  ],

  deck: { cards: 9, normebenen: 4, hochprior: 9, fallen: 11 },

  kartografie: [
    { ebene: 'I', bez: 'Bundesrecht', kuerzel: 'BUND', normen: ['§ 22 SGB VIII'], sub: 'Hort als Tageseinrichtung für Kinder' },
    { ebene: 'II', bez: 'BayEUG', kuerzel: 'BayEUG', normen: ['Art. 6/4', 'Art. 19', 'Art. 20', 'Art. 21', 'Art. 30a', 'Art. 31/3', 'Art. 41', 'Art. 60', 'Art. 78'], sub: 'FöS · MSD · Inklusion · Lernort · Schulberatung · GTS · FL' },
    { ebene: 'III', bez: 'Schulordnungen', kuerzel: 'VO', normen: ['MSO § 14', 'GrSO § 5', 'BaySchO §§ 31/36', 'VSO-F § 25'], sub: 'Förderplan · Überweisungsverfahren · FL-Arbeitszeit (Anker)' },
    { ebene: 'IV', bez: 'KMBek', kuerzel: 'KMBek', normen: ['08.07.2013 (oGTS)', '10.02.2020 (gGTS)', '12.06.1991 (Hort↔Schule)', '29.10.2001 (Schulberatung)'], sub: 'GTS · Hort · Schulberatung · MSD · Inklusion' },
  ],

  pflichtwissen: [
    { id: 'K01', titel: 'MSD-Ziel',
      frage: 'Was ist das zentrale Ziel des MSD — und in welcher Norm steht es?',
      antwort: '**Verbleib an allgemeiner Schule** sichern, FöS-Überweisung **vermeiden**. Präventiv-integrativ. {{Art. 21 BayEUG}}. Träger: nächstgelegene FöS mit entsprechendem Förderschwerpunkt.',
      norm: 'Art. 21 BayEUG', status: 'open' },
    { id: 'K02', titel: 'MSD ≠ FöS',
      frage: 'Wo liegt der Unterschied MSD ↔ FöS?',
      antwort: 'MSD = **Dienst** an der allgem. Schule ({{Art. 21 BayEUG}}). FöS = **Schulart** ({{Art. 19 BayEUG}}). MSD wird VON der FöS GELEISTET, ist aber selbst keine Schulart. Wer beides vermischt, fällt in die Falle.',
      norm: 'Art. 21 BayEUG', status: 'open' },
    { id: 'K03', titel: 'Förderdiagn. Bericht',
      frage: 'Wer verantwortet den Förderdiagnostischen Bericht — und was ist Pflicht?',
      antwort: 'MSD verantwortet den Förderdiagn. Bericht. **Eltern-Info-Pflicht** vor standardisierten Tests — Eltern müssen vorab informiert werden. Cross-Ref MP_05 (BaySchO § 39 Schülerunterlagen-Weitergabe nur mit Einwilligung).',
      norm: 'Art. 21 BayEUG', status: 'open' },
    { id: 'K04', titel: '7 Förderschwerpunkte',
      frage: 'Welche 7 Förderschwerpunkte kennt {{Art. 20/1 BayEUG}}?',
      antwort: 'Sehen · Hören · körperliche/motor. Entwicklung · geistige Entwicklung (gE) · Sprache · Lernen · emotionale/soziale Entwicklung. Praxis-Erweiterung in MSD: + Autismus + ELECOK → 9 Bereiche.',
      norm: 'Art. 20 BayEUG', status: 'open' },
    { id: 'K05', titel: 'Lernort-Entscheidung Art. 41',
      frage: 'Wer entscheidet über den schulischen Lernort eines Kindes mit Förderbedarf?',
      antwort: '**Eltern** ({{Art. 41/1 BayEUG}}): „Die Erziehungsberechtigten entscheiden, an welchem der … schulischen Lernorte ihr Kind unterrichtet werden soll." Bei Nicht-Einvernehmen entscheidet die **Schulaufsichtsbehörde** (Abs. 6). FöS-Aufnahme setzt sonderpäd. Gutachten voraus (Abs. 4).',
      norm: 'Art. 41 BayEUG', status: 'open' },
    { id: 'K06', titel: 'Förderplanpflicht MSO § 14',
      frage: 'Wann besteht Förderplanpflicht — und was ist Pflicht-Inhalt?',
      antwort: 'Pflicht bei voraussichtlich **nicht erreichten Lernzielen**. Inhalt: Ziele + Maßnahmen + Leistungserhebungen. **Jährlich fortschreiben**. **MSD-Einbeziehung Pflicht**, mit Eltern erörtern. {{MSO § 14}}. Sonderpäd. Bedarf ≠ Schulartzugehörigkeit ({{Art. 30a/5 BayEUG}}).',
      norm: 'MSO § 14', status: 'open' },
    { id: 'K07', titel: 'BL ≠ SPych',
      frage: 'Wie unterscheiden sich Beratungslehrkraft (BL) und Schulpsycholog:in (SPych) — Qualifikation + Aufgaben?',
      antwort: '**BL** = Lehrkraft + Erweiterungsstudium Univ. ODER 2-J-Weiterbildung; im Schul-Kollegium. **SPych** = Psychologie-Studium mit schulpsych. Schwerpunkt; meist für mehrere Schulen zuständig. Unterschiedlicher Aufgabenkatalog — SPych verantwortet Tests/Diagnose (LRS, Rechenschwäche), Krisenintervention, KIBBS.',
      norm: 'Art. 78 BayEUG', status: 'open' },
    { id: 'K08', titel: 'LK ≠ Therapie',
      frage: 'Darf eine LK Schüler:innen selbst therapieren?',
      antwort: 'NEIN. **Weiterleitung Pflicht** (BL/SPych/Erziehungsberatung). **Verschwiegenheit** + **Eltern-Einverständnis** Voraussetzung für Erziehungsberatung. **Freiwilligkeitsgrundsatz** Schulberatung — Eltern können ablehnen.',
      norm: 'Art. 78 BayEUG', status: 'open' },
    { id: 'K09', titel: 'oGTS vs. gGTS · GTS-Antragsprinzip',
      frage: 'Worin liegt der Unterschied oGTS ↔ gGTS — und wer beantragt eine GTS?',
      antwort: '**oGTS** (offen, KMBek 08.07.2013): Vormittag im Klassenverband, Nachmittag **freiwillig** mit Anmeldung. **gGTS** (gebunden, KMBek 10.02.2020): Ganztagszug, **verpflichtend** ab Anmeldung; mind. 4 Tage à 7 Std., rhythmisierter U. **Anmeldung freiwillig — Teilnahme verpflichtend**. **Antrag** durch **Schulaufwandsträger**, im Benehmen mit JuHi-Trägern. **Kein Rechtsanspruch** auf GTS-Platz.',
      norm: 'Art. 6/4 BayEUG', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: 'MSD = Förderzentrum?', antwort: 'NEIN. MSD = **Dienst** an allgem. Schule ({{Art. 21 BayEUG}}). FöS = **Schulart** ({{Art. 19 BayEUG}}). MSD wird von der FöS geleistet, ist aber keine eigene Schulart.' },
    { id: 'FA02', frage: 'MSD = MSH?', antwort: 'NEIN. MSD = **schulisch** (Art. 21). MSH (Mobile Sonderpädagogische Hilfe) = **vorschulisch** ({{Art. 19/2 BayEUG}}).' },
    { id: 'FA03', frage: 'Eltern-Info vor MSD-Tests ist optional?', antwort: 'NEIN — **Pflicht**. Eltern müssen vor standardisierten Tests vorab informiert werden. Schülerunterlagen-Weitergabe nur mit Einwilligung (BaySchO § 39 — Cross-Ref MP_05).' },
    { id: 'FA04', frage: 'Hertha (FS gE) → Regelschule braucht Sachaufwandsträger-Zustimmung?', antwort: 'NEIN. {{Art. 30a/4 BayEUG}} sieht Sachaufwandsträger-Zustimmung **NUR** für **Sehen / Hören / körperl.-motor.** vor. FS gE fällt NICHT darunter. Rechtsgrundlage Lernort: {{Art. 41/1 BayEUG}} + {{Art. 30a/3 BayEUG}}.' },
    { id: 'FA05', frage: 'BL = SPych?', antwort: 'NEIN. **BL** = Lehrkraft + Erweiterungsstudium / 2-J-Weiterbildung. **SPych** = Psychologe mit schulpsych. Schwerpunkt. Unterschiedliche Qualifikation + Aufgabenkatalog.' },
    { id: 'FA06', frage: 'LK darf selbst therapieren?', antwort: 'NEIN. **Weiterleitung Pflicht** (BL / SPych / Erziehungsberatung). **Verschwiegenheit + Eltern-Einverständnis** Voraussetzung.' },
    { id: 'FA07', frage: 'gGTS-Anmeldung verpflichtend?', antwort: 'NEIN — **Anmeldung freiwillig**. ABER: **Teilnahme ab Anmeldung verpflichtend** (Ganztagszug, kein Tages-Rückzug). Wechsel nur zum SJ-Ende.' },
    { id: 'FA08', frage: 'Mittagsbetreuung = Hort = GTS?', antwort: 'NEIN. **Drei verschiedene Rechtsträger**: Gemeinde (Mittagsbetreuung, {{Art. 31/3 BayEUG}}) · freier/kirchl./kommunaler JuHi-Träger (Hort, {{§ 22 SGB VIII}}) · staatl. Schule (GTS, {{Art. 6/4 BayEUG}}).' },
    { id: 'FA09', frage: 'Aufsichtspflicht Mittagspause Halbtags-GS = Schule?', antwort: 'NEIN — **Schulverband / Gemeinde**, NICHT Schule. Aufsichtspflicht-Sphären getrennt (Cross-Ref MP_06 A.2 + MP_07 Haftungsachsen).' },
    { id: 'FA10', frage: 'Rechtsanspruch auf GTS-Platz?', antwort: 'NEIN. **Kein Anspruch**; Wahlfreiheit Halbtag↔Ganztag. **Antrag** läuft über **Schulaufwandsträger** an der jeweiligen Schulart; Ausbau hängt von Träger-Entscheidung.' },
    { id: 'FA11', frage: 'FL permanent als Vertretung einsetzbar?', antwort: 'NEIN. FL-Vertretungsunterricht NUR **kurzfristig** in unabweisbaren Fällen, **max. 5 WStd**, NICHT permanent. Schutz der 8 eigenverantwortlichen AG-Stunden.' },
  ],

  faelle: [
    { id: 'F1', titel: 'Tom — em./soz. + Eltern-Veto + Hort-Frage (Hauptfall)',
      sachverhalt: '7. Kl. MS. Aggressives Verhalten, Schulverweigerung, Konzentrationsprobleme. Sie vermuten Förderbedarf em./soz. Eltern lehnen MSD-Diagnostik ab, fordern SPych-Termin und fragen nach Hortwechsel.',
      knackpunkte: [
        '**MSD-Anfrage trotz Eltern-Veto möglich**: MSD = Dienst an allgem. Schule ({{Art. 21 BayEUG}}), kein Schulartwechsel. Eltern haben **Lernort-Primat** ({{Art. 41 BayEUG}}), kein Diagnostik-Veto. Pflicht: Eltern vorab über standardisierte Tests informieren.',
        '**BL ≠ SPych** — beide möglich, unterschiedliche Qualifikation/Aufgaben. Bei em./soz.-Verdacht ist MSD primär; SPych ergänzend für psychol. Diagnostik/Krisenintervention.',
        '**Hort = außerschulisch** ({{§ 22 SGB VIII}}), Träger ≠ Schule. Anmeldung über Jugendhilfe; Schule kooperiert (KMBek 12.06.1991), bietet aber nicht selbst an.',
        '**Therapie-Verbot**: falls Tom psychotherapeutisch auffällig → Weiterleitung an BL/SPych/Erziehungsberatung, nicht Selbst-Therapie.',
      ],
      antwortkette: 'Anfrage-Indikatoren em./soz. erkennen (Maßstab Ausprägung+Dauer+Intensität+Häufigkeit+Kombination) → Elterngespräch (MSD ≠ Stigma) → Beratungsweg KL→BL/SPych/MSD parallel → Förderplanpflicht {{MSO § 14}} ankündigen falls Bedarf bestätigt → Hort-Anregung in JuHi-Kanal verweisen → bei Eltern-Verhärtung SL + Beratungsrektor:in einschalten; Schulaufsichtsbehörde nur bei FöS-Überweisungs-Konflikt ({{Art. 41/6 BayEUG}}).',
    },
    { id: 'F2', titel: 'Hertha — FS gE → Regelschule',
      sachverhalt: '7-jährige Hertha (FS gE) soll an die Sprengelschule wechseln.',
      knackpunkte: [
        'Rechtlich möglich über {{Art. 41/1 BayEUG}} (Eltern-Lernort-Entscheidung) + {{Art. 30a/3 BayEUG}} (gemeinsamer Unterricht möglich).',
        '**Sachaufwandsträger-Zustimmung NICHT erforderlich** — {{Art. 30a/4 BayEUG}} betrifft NUR Sehen/Hören/k.-m., nicht gE.',
        '**Förderplan {{MSO § 14}} verbindlich**; Schulprofil Inklusion oder Kooperations-/Partnerklasse prüfen; MSD em./soz. + gE zur Begleitung anfragen.',
      ],
      antwortkette: 'Eltern-Anmeldung an Sprengelschule → Schulprofil Inklusion verfügbar? → MSD-Anbindung an FS gE → Förderplan + Nachteilsausgleich → pädagogische Wertigkeit FöS verdeutlichen, Rückkehr-Option offen halten.',
    },
    { id: 'F3', titel: 'Hanna — therapeutisch auffällig',
      sachverhalt: 'Schülerin zeigt Symptome, die therapeutische Behandlung nahelegen.',
      knackpunkte: [
        '**LK darf NICHT selbst therapieren** — Pflicht zur Weiterleitung (BL/SPych/Erziehungsberatung).',
        '**Verschwiegenheit + Eltern-Einverständnis** Voraussetzung für Erziehungsberatung.',
        '**Freiwilligkeitsgrundsatz Schulberatung** — Eltern können ablehnen.',
      ],
      antwortkette: 'Beobachtungen dokumentieren → Elterngespräch (Sorge, kein Diagnose-Verdikt) → SPych/BL als nächste Stufe vorschlagen → bei Bestätigung Weiterleitung Erziehungsberatung → kein Selbsttherapie-Versuch.',
    },
    { id: 'F4', titel: 'Lina — gGTS-Anmeldung',
      sachverhalt: '9-jährige Lina will keine gebundene Ganztagsschule mehr besuchen.',
      knackpunkte: [
        '**Anmeldung freiwillig** — Eltern-Entscheidung.',
        '**Teilnahme ab Anmeldung verpflichtend** — gGTS = Ganztagszug, kein Tages-Rückzug.',
        '**Wechsel nur zum SJ-Ende** möglich; alternativ oGTS prüfen (freiwillige Nachmittagsanmeldung).',
      ],
      antwortkette: 'Eltern-Beratung {{Art. 78 BayEUG}} → Wechsel-Antrag zum SJ-Ende, oder Wechsel in oGTS falls angeboten → bei Halbtags-Bedarf akut: Mittagsbetreuung (Gemeinde) oder Hort (außerschulisch) als Alternative.',
    },
    { id: 'F5', titel: 'Niklas — Aufsichtspflicht Schule ↔ Hort (Cross-Ref MP_06/MP_07)',
      sachverhalt: 'Niklas (7) verletzt sich auf dem Weg von der Halbtags-GS zum Hort um 13:15 Uhr. Mutter macht die Schule haftbar.',
      knackpunkte: [
        '**Aufsichtspflicht-Sphären getrennt**: Schule (Unterricht) ↔ Schulverband/Gemeinde (Mittagspause Halbtags-GS) ↔ Hort-Träger (außerschulisch, {{§ 22 SGB VIII}}).',
        '**Mittagsbetreuung ≠ Hort ≠ GTS** — drei verschiedene Träger, drei verschiedene Haftungsachsen.',
        '**Schule haftet nur** für die Zeit unter SL-Aufsicht (bei GTS Nachmittag inkl., bei Halbtags-GS NICHT).',
      ],
      antwortkette: 'Sphären-Zuordnung klären → Niklas-Unfall um 13:15 außerhalb Schulpräsenz → Schulverband/Gemeinde bzw. Hort-Träger verantwortlich → KL informiert SL + Eltern, dokumentiert Vorfall, verweist Mutter an Hort-Träger / Gemeindeverwaltung. Cross-Ref MP_06 A.2 + MP_07 Haftungsdreieck.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'MSD — Mobile Sonderpädagogische Dienste',
      anriss: 'Präventiv-integrativer Dienst an allgem. Schule. Träger: nächstgelegene FöS. 5 Aufgaben + 7 (+2) Bereiche. Ziel: Verbleib allgem. Schule, FöS-Überweisung vermeiden.',
      norm: 'Art. 21 BayEUG', status: 'open', cards: 3,
      subblocks: [{ label: 'Träger + 5 Aufgaben (Wortlaut)', cards: 1 }, { label: '7+2 Förderbereiche', cards: 1 }, { label: 'Anfrage-Indikatoren + Maßstab', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'Förderzentrum (FöS) + Lernort Art. 41',
      anriss: 'Aufgaben Art. 19 · 7 Schwerpunkte Art. 20 · Lernort Art. 41 (Eltern!) · Inklusion Art. 30a · Überweisungsverfahren § 5 GrSO · Förderplan MSO § 14. Hertha-Falle.',
      norm: 'Art. 41 BayEUG', status: 'open', cards: 4,
      subblocks: [{ label: 'Aufgaben + 7 Schwerpunkte', cards: 1 }, { label: 'Lernort-Tabelle Art. 41', cards: 1 }, { label: 'Überweisungsverfahren § 5 GrSO', cards: 1 }, { label: 'Inklusion + Hertha-Falle', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: 'Schulberatung — 5 Eskalationsstufen',
      anriss: 'KL → BL/SPych/MSD → Beratungsrektor:in → Staatl. Schulberatungsstelle → Außerschulisch. BL ≠ SPych — Qualifikation und Aufgaben unterscheiden.',
      norm: 'Art. 78 BayEUG', status: 'open', cards: 3,
      subblocks: [{ label: '5 Stufen Beratungsweg', cards: 1 }, { label: 'BL vs. SPych — Qual./Aufgaben', cards: 1 }, { label: 'LK ≠ Therapie + Freiwilligkeit', cards: 1 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Betreuung — vier Säulen, drei Rechtsregime',
      anriss: 'Mittagsbetreuung (Gemeinde) · Halbtags-GS (staatl.) · GTS oGTS/gGTS (staatl.) · Hort (JuHi-Träger). Drei Rechtsregime, drei Haftungsachsen.',
      norm: 'Art. 6/4 BayEUG', status: 'open', cards: 3,
      subblocks: [{ label: 'Übersicht 4 Säulen', cards: 1 }, { label: 'oGTS vs. gGTS', cards: 1 }, { label: 'Aufsichtspflicht-Übergänge', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'GTS-Antragsprinzip · Förderlehrkraft',
      anriss: 'Antrag durch Schulaufwandsträger; kein Rechtsanspruch; Teilnahmepflicht ab Anmeldung. FL Art. 60: 28 UE = 8 + 20 + 5; Vertretung max. 5 WStd.',
      norm: 'Art. 60 BayEUG', status: 'open', cards: 2,
      subblocks: [{ label: 'GTS-Antragsprinzip + Kein Anspruch', cards: 1 }, { label: 'FL-Arbeitszeit + Vertretungs-Cap', cards: 1 }],
    },
  ],

  glossar: {
    'Art. 6/4 BayEUG': { titel: 'Art. 6/4 BayEUG — Ganztagsschule', wortlaut: 'Rahmen-Norm für oGTS und gGTS in Bayern. Ausgestaltung über KMBek 08.07.2013 (oGTS) und 10.02.2020 (gGTS). Antrag läuft über Schulaufwandsträger; kein Rechtsanspruch auf GTS-Platz.', karten: ['K09'] },
    'Art. 19 BayEUG': { titel: 'Art. 19 BayEUG — Förderzentrum (Schulart)', wortlaut: 'Abs. 1–3: Aufgaben FöS — diagnostizieren · erziehen · unterrichten · beraten · fördern. Adressaten: K/J mit Bedarf, an allgem. Schule nicht ausreichend förderbar. Leistungsspektrum: Klassen-U. + SVE + MSH + MSD. Schulart-Norm, abzugrenzen von {{Art. 21 BayEUG}}.', karten: ['K02'] },
    'Art. 19/2 BayEUG': { titel: 'Art. 19 Abs. 2 BayEUG — MSH (vorschulisch)', wortlaut: 'Mobile Sonderpädagogische Hilfe vorschulisch (in Kindergarten / Heim / Familie). Abgrenzung zum schulischen MSD ({{Art. 21 BayEUG}}).', karten: [] },
    'Art. 20 BayEUG': { titel: 'Art. 20 BayEUG — Förderschwerpunkte + Aufbau', wortlaut: 'Abs. 1: **7 Förderschwerpunkte** — Sehen · Hören · k./m. Entwicklung · gE · Sprache · Lernen · em./soz. Entwicklung. Abs. 2: Aufbau — GS-Stufe 1–4, MS-Stufe 5–9 (ggf. 10 MR), **Berufsschulstufe** 10–12 bei FS gE (ersetzt BS).', karten: ['K04'] },
    'Art. 20/1 BayEUG': { titel: 'Art. 20/1 BayEUG — 7 Förderschwerpunkte', wortlaut: 'Wortlaut-Anker für die 7 Schwerpunkte. Praxis-Erweiterung MSD: + Autismus + ELECOK → 9 Bereiche.', karten: ['K04'] },
    'Art. 21 BayEUG': { titel: 'Art. 21 BayEUG — MSD', wortlaut: 'Abs. 1 S. 2: „Sie diagnostizieren und fördern die Schülerinnen und Schüler, sie beraten Lehrkräfte, Erziehungsberechtigte und Schülerinnen und Schüler, koordinieren sonderpädagogische Förderung und führen Fortbildungen für Lehrkräfte durch." S. 3: „Mobile Sonderpädagogische Dienste werden von den nächstgelegenen Förderschulen mit entsprechendem Förderschwerpunkt geleistet." MSD ist **Dienst**, nicht Schulart ({{Art. 19 BayEUG}}).', karten: ['K01', 'K02', 'K03'] },
    'Art. 30a BayEUG': { titel: 'Art. 30a BayEUG — Inklusion', wortlaut: 'Abs. 1: Pflicht aller Schularten zur Zusammenarbeit. Abs. 3: SuS mit/ohne Bedarf gemeinsam möglich; FöS unterstützt. **Abs. 4**: FS Sehen/Hören/k.-m. an allgem. Schule **nur mit Sachaufwandsträger-Zustimmung**. Abs. 5: sonderpäd. Bedarf begründet keine Schulart-Zugehörigkeit.', karten: [] },
    'Art. 30a/3 BayEUG': { titel: 'Art. 30a/3 BayEUG — gemeinsamer Unterricht', wortlaut: 'Gemeinsamer Unterricht von SuS mit/ohne sonderpäd. Bedarf möglich; FöS unterstützt. Rechtsgrundlage für Inklusion in Regelschule.', karten: [] },
    'Art. 30a/4 BayEUG': { titel: 'Art. 30a/4 BayEUG — Sachaufwandsträger-Zustimmung', wortlaut: 'Sachaufwandsträger-Zustimmung **NUR** bei FS **Sehen / Hören / k.-m. Entwicklung** an allgem. Schule. Bei anderen Schwerpunkten (gE, Sprache, Lernen, em./soz.) NICHT erforderlich — **Hertha-Falle**.', karten: [] },
    'Art. 30a/5 BayEUG': { titel: 'Art. 30a/5 BayEUG — Bedarf ≠ Schulart', wortlaut: 'Sonderpädagogischer Bedarf begründet keine Schulart-Zugehörigkeit — Lernort offen.', karten: [] },
    'Art. 31/3 BayEUG': { titel: 'Art. 31/3 BayEUG — Mittagsbetreuung', wortlaut: 'Rahmen-Norm für Mittagsbetreuung. Träger: Gemeinde / gemeinnützig. Sozialpäd. Fachpersonal. SL-Benehmen bei Organisation. Standard bis ca. 14 Uhr; verlängert bis 15:30/16:00 mit HA-Betreuung möglich. **Aufsichtspflicht ≠ Schule** (Cross-Ref MP_06).', karten: [] },
    'Art. 41 BayEUG': { titel: 'Art. 41 BayEUG — Schulischer Lernort', wortlaut: 'Abs. 1: „Die **Erziehungsberechtigten entscheiden**, an welchem der … schulischen Lernorte ihr Kind unterrichtet werden soll." Abs. 2: Längerfristig Kranke → Schule für Kranke. Abs. 3: Eltern sollen Beratungsstelle aufsuchen. Abs. 4: „melden ihr Kind … an der Sprengelschule, einer Schule mit dem Schulprofil »Inklusion« oder an der Förderschule an. Die Aufnahme an der Förderschule setzt die Erstellung eines sonderpädagogischen Gutachtens voraus." Abs. 5: Bedarf nicht deckbar → geeignete FöS. Abs. 6: „Kommt keine einvernehmliche Aufnahme zustande, entscheidet die zuständige **Schulaufsichtsbehörde** nach Anhörung … über den schulischen Lernort."', karten: ['K05'] },
    'Art. 41/1 BayEUG': { titel: 'Art. 41/1 BayEUG — Eltern entscheiden Lernort', wortlaut: 'Wortlaut-Anker für Eltern-Lernort-Primat.', karten: ['K05'] },
    'Art. 41/6 BayEUG': { titel: 'Art. 41/6 BayEUG — Schulaufsicht bei Dissens', wortlaut: 'Bei Nicht-Einvernehmen entscheidet die Schulaufsichtsbehörde nach Anhörung der Beteiligten.', karten: [] },
    'Art. 60 BayEUG': { titel: 'Art. 60 BayEUG — Förderlehrkraft', wortlaut: 'Abs. 1 S. 2 (Wortlaut): „selbstständig und eigenverantwortlich". Begleit-Normen: VSO-F § 25, MSO §§ 9/10. Arbeitszeit GS/MS: 28 UE (45 Min) = 8 eigenverantwortlich (AGs) + 20 Kooperations-U. + 5 Verwaltungsstunden (60 Min). FöS/Kranke: 27 UE. FL-Vertretungs-Cap: max. 5 WStd, kurzfristig, unabweisbar.', karten: [] },
    'Art. 78 BayEUG': { titel: 'Art. 78 BayEUG — Schulberatung', wortlaut: 'Abs. 1 (Wortlaut): „Jede Schule und jede Lehrkraft hat die Aufgabe, die Erziehungsberechtigten und die Schülerinnen und Schüler in Fragen der Schullaufbahn zu beraten." Abs. 2: überregionale Aufgaben durch staatliche Schulberatungsstellen. **Freiwilligkeitsgrundsatz**. KMBek 29.10.2001 (geänd. 24.06.2011) ergänzt.', karten: ['K07', 'K08'] },
    '§ 22 SGB VIII': { titel: '§ 22 SGB VIII — Tageseinrichtungen für Kinder', wortlaut: 'Bundes-Norm — Tageseinrichtungen für Kinder. Hort-Begriff wird unter „Tageseinrichtungen" subsumiert (nicht explizit im Wortlaut). Träger: kirchlich / kommunal / freie Jugendhilfe. Außerschulische Einrichtung — Aufsichtspflicht ≠ Schule.', karten: [] },
    'MSO § 14': { titel: 'MSO § 14 — Individueller Förderplan', wortlaut: 'SuS mit voraussichtlich nicht erreichten Lernzielen erhalten **individuellen Förderplan + Nachteilsausgleich**. Inhalt: Ziele + Maßnahmen + Leistungserhebungen. **Jährlich fortschreiben**. **MSD-Einbeziehung Pflicht**, mit Eltern erörtern. Sonderpäd. Bedarf ≠ Schulart-Zugehörigkeit.', karten: ['K06'] },
    'GrSO § 5': { titel: 'GrSO § 5 — Überweisungsverfahren', wortlaut: '6-Schritte-Überweisungsverfahren: (1) KL erörtert mit Eltern → (2) schriftl. Meldung an SL → (3) SL benachrichtigt Eltern → (4) Hinweis auf BL/SPych → (5) sonderpäd. Gutachten → (6) Eltern-Stellungnahme, Förderort. Cross-Ref {{Art. 41 BayEUG}}.', karten: [] },
    'BaySchO § 31': { titel: 'BaySchO § 31 — Individuelle Unterstützung', wortlaut: 'Individuelle Unterstützung / Nachteilsausgleich. Begleit-Norm zum Förderplan {{MSO § 14}}.', karten: [] },
    'BaySchO § 36': { titel: 'BaySchO § 36 — Nachteilsausgleich', wortlaut: 'Nachteilsausgleich-Regelung. Cross-Ref MP_05 (BVerwG 29.07.2015 BaySchO § 33 NA / § 34 NS).', karten: [] },
    'VSO-F § 25': { titel: 'VSO-F § 25 — Förderlehrkraft an Förderschulen', wortlaut: 'Begleit-Norm zur Förderlehrkraft an Förderschulen.', karten: [] },
  },
};
