// MP_03 — Gliederung Bildungssystem · Bildungswege
window.MODULE = {
  id: 'mp03',
  zalgm: 'ZALGM § 16 Nr. 2',
  schwerpunkt: ['3.1 Schulwesen', '3.2 KiGa→GS', '3.3 Einschulung + Schulpflicht', '3.4 Übertritt', '3.5 MS-Abschlüsse'],
  titel: 'Gliederung Bildungs-',
  titel2: 'system + Bildungswege.',
  abriss:
    'Gegliedert UND durchlässig zugleich. BV Art. 132 Anlagen-/Leistungs-Prinzip. ' +
    'Schulpflicht 12 J. (Art. 35). Übertritts-Schwellen GS→Sek I 2,33 / 2,66. ' +
    'Drei Aufstiegswege MS → Fachabi.',

  kurz: [
    'Verfassungsanker BV Art. 128 (Bildungsanspruch), Art. 132 (Anlagen-/Leistungs-Prinzip), Art. 133 (Bildungsträger), Art. 134 (Privatschulen).',
    'Schulpflicht Art. 35 BayEUG: Beginn Vollendung 6. Lj., Stichtag 30.09., Dauer 12 J. (9 Vollzeit + 3 BS). Einschulungskorridor 01.07.–30.09.',
    'Übertritts-Schwellen GS→Sek I (D/M/HSU): Gym ≤ 2,33 · RS ≤ 2,66 · MS alle übrigen. Probeunterricht-Bestehen mind. 1×3 + 1×4.',
    'Gelenkklasse Jgst. 5 MS (Jahreszeugnis): D+M ≤ 2,0 Gym · D+M ≤ 2,5 RS. M-Zug: M7 ≤ 2,66 / M8-10 ≤ 2,33 D+M+E.',
    'Drei Aufstiegswege MS → Fachabi: (A) M-Zug → M10+MSA → FOS. (B) ESA+Quali → Berufsausbildung+BS → Quabi → FOS. (C) WS 4-stufig → mittlerer Abschluss → FOS.',
  ],

  deck: { cards: 8, normebenen: 5, hochprior: 8, fallen: 12 },

  kartografie: [
    { ebene: 'I', bez: 'Bayerische Verfassung', kuerzel: 'BV', normen: ['Art. 128 BV', 'Art. 129 BV', 'Art. 132 BV', 'Art. 133 BV', 'Art. 134 BV'], sub: 'Bildungsanspruch · Schulpflicht · Anlagen/Leistung · Träger · Privatschulen' },
    { ebene: 'II', bez: 'BayEUG', kuerzel: 'BayEUG', normen: ['Art. 3', 'Art. 6', 'Art. 7-9', 'Art. 35', 'Art. 37', 'Art. 39', 'Art. 41', 'Art. 43', 'Art. 44', 'Art. 76', 'Art. 78', 'Art. 118', 'Art. 119'], sub: 'Schularten · Schulpflicht · Übertritt · Elternwahl · Schulzwang' },
    { ebene: 'III', bez: 'Schulordnungen', kuerzel: 'VO', normen: ['§ 6 GrSO', '§ 10 GrSO', '§ 6 MSO', '§ 7 MSO', '§ 8 MSO', '§ 22 MSO', '§ 34 MSO', '§ 19/4 BaySchO', '§ 20 BaySchO'], sub: 'ÜZ · Probearbeiten · M-Zug · MS-Abschlüsse · Distanzunterricht' },
    { ebene: 'IV', bez: 'KMBek', kuerzel: 'KMBek', normen: ['Vorkurs Deutsch 240'], sub: 'Sprachförder-Programm 240 h × 1,5 J.' },
    { ebene: 'V', bez: 'Bundesrecht', kuerzel: 'BUND', normen: ['§ 1 JuSchG'], sub: 'Kind / Jugendlicher / sittliche Reife' },
  ],

  pflichtwissen: [
    { id: 'G01', titel: 'Schwellen GS→Sek I',
      frage: 'Welche Übertritts-Schwellen gelten Ende Jgst. 4 — und welche Fächer zählen?',
      antwort: 'Mai-Übertrittszeugnis: NUR D/M/HSU. Gym ≤ 2,33 · RS ≤ 2,66 · MS alle übrigen. Bei knapper Verfehlung: Probeunterricht 3 Tage D/M (bestanden = mind. 1×3 + 1×4). Bei 2× Note 4: Elternwille entscheidet.',
      norm: '§ 6 GrSO', status: 'open' },
    { id: 'G02', titel: 'Schulpflicht Dauer + Beginn',
      frage: 'Wann beginnt die Schulpflicht, wie lange dauert sie — und was ist der Einschulungskorridor?',
      antwort: 'Beginn: Vollendung 6. Lj. zum Stichtag 30.09. (Art. 35/37 BayEUG). Dauer: 12 J. = 9 Vollzeit + 3 Berufsschule. Einschulungskorridor 01.07.–30.09. seit SJ 2019/2020 — Eltern entscheiden. Nach 31.12. nur mit schulpsychologischem Gutachten.',
      norm: 'Art. 35 BayEUG', status: 'open' },
    { id: 'G03', titel: 'Schulpflicht ≠ Schulzwang',
      frage: 'Wie unterscheiden sich Schulpflicht und Schulzwang — und welche Norm-Kette verbindet sie?',
      antwort: 'Schulpflicht = Grundpflicht (Art. 35 + Art. 76 + § 20 BaySchO). Schulzwang = Sanktion (Art. 118 → Antrag der Schule bei Kreisverwaltungsbehörde / Art. 119 OWi / Art. 120 Grundrechtseinschränkung). KEIN Synonym!',
      norm: 'Art. 118 BayEUG', status: 'open' },
    { id: 'G04', titel: 'Migration Tiefer-Einweisung',
      frage: 'Wann darf bei zugewanderten Schüler:innen eine Jgst. tiefer eingewiesen werden?',
      antwort: 'NUR bei allgemeinem Bildungsstand-Defizit (Art. 36/3 S. 4 BayEUG) — max. 2 Jgst. tiefer. Sprachliche Defizite allein reichen NICHT (Falle!). Schulpflicht beginnt 3 Monate nach Zuzug. Altersgleichheits-Prinzip. Cross-Ref MP_05.',
      norm: 'Art. 36/3 BayEUG', status: 'open' },
    { id: 'G05', titel: 'Vorkurs Deutsch 240',
      frage: 'Welche Dauer + welcher Träger-Verbund kennzeichnen den Vorkurs Deutsch 240?',
      antwort: '240 h über 1,5 Schuljahre (NICHT 1 J., NICHT 2 J.) — vorletztes + letztes KiTa-Jahr. Träger gemeinsam Kindergarten + Grundschule (je Hälfte). KMBek KWMBl 2011 S. 240. „Lieblings-Falle" der Schulräte.',
      norm: 'Vorkurs Deutsch 240', status: 'open' },
    { id: 'G06', titel: 'Gelenkklasse Jgst. 5 MS',
      frage: 'Welche Schwellen gelten für den Wechsel MS Jgst. 5 → Gym/RS?',
      antwort: 'Jahreszeugnis Gelenkklasse: D+M ≤ 2,0 → Gymnasium uneingeschränkt. D+M ≤ 2,5 → Realschule uneingeschränkt. Sonst Härtefall-Antrag oder Probeunterricht. Wichtig: ÜZ-Logik gilt NICHT nur Jgst. 4, auch Jgst. 5 MS.',
      norm: '§ 6 MSO', status: 'open' },
    { id: 'G07', titel: 'M-Zug-Aufnahme',
      frage: 'Welche Schwellen gelten für die Aufnahme in M7 / M8-10?',
      antwort: 'D+M+E ≤ 2,66 → M7 (aus 6. Klasse Jahreszeugnis). ≤ 2,33 → M8/M9/M10. M10 zusätzlich Quali-Zeugnis. Sonst Antrag + Aufnahmeprüfung. Rückkehr MS↔M-Zug jederzeit (MSO § 8/3).',
      norm: '§ 7 MSO', status: 'open' },
    { id: 'G08', titel: 'Drei Aufstiegswege MS → Fachabi',
      frage: 'Welche drei Wege führen vom MS-Start zur Fachhochschulreife?',
      antwort: '(A) M-Zug: MS 5 → M7 → M10+MSA → FOS 11/12. (B) ESA+Quali: ESA Ende 9. → Quali (50/50 + Projekt) → Berufsausbildung+BS → Quabi (MSO § 34) → FOS. (C) Wirtschaftsschule: MS 6./7. → 4-stufige WS → mittlerer Abschluss → FOS.',
      norm: 'Art. 78 BayEUG', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: '„Die GS ist die erste und gemeinsame Schule" — absolut?', antwort: 'NEIN. Ausnahmen: Förderschule ab Jgst. 1 (Art. 41 BayEUG) + SVE (Schulvorbereitende Einrichtung).' },
    { id: 'FA02', frage: 'Schwellen GS→Sek I auswendig?', antwort: 'Gym ≤ 2,33 · RS ≤ 2,66 — NUR D/M/HSU. NICHT 2,5/3,0. NICHT alle Fächer.' },
    { id: 'FA03', frage: 'Probearbeiten Jgst. 4 — Verteilung?', antwort: 'LK-Konferenz legt Grundsätze fest (GrSO § 10/1 S. 1). Gesamtzahl bis ÜZ: 18 Probearbeiten in D/M/HSU (Wortlaut Abs. 3 S. 2). Verteilung 10/4/4 nur Sekundärliteratur. Mind. 4 U.-Wochen probearbeitenfrei „jeweils" pro Fach (Auslegung uneinheitlich).' },
    { id: 'FA04', frage: 'Elternwahlrecht absolut?', antwort: 'NEIN. Art. 44 BayEUG + BV Art. 132: gebunden an Eignung + Leistung.' },
    { id: 'FA05', frage: 'Übertritts-Dokument nur Jgst. 4?', antwort: 'NEIN. Auch Gelenkklasse Jgst. 5 MS (Jahreszeugnis). D+M ≤ 2,0 Gym · D+M ≤ 2,5 RS.' },
    { id: 'FA06', frage: 'Elternwillen bei Note 4 — wann?', antwort: 'NACH Probeunterricht bei 2× Note 4 in D/M. NICHT vorab, NICHT bei nur 1× Note 4.' },
    { id: 'FA07', frage: 'Vorkurs Deutsch 240 — Dauer?', antwort: '240 h über 1,5 Schuljahre. NICHT 1 J., NICHT 2 J. Vorletztes + letztes KiTa-Jahr.' },
    { id: 'FA08', frage: 'Schulpflicht = Schulzwang?', antwort: 'NEIN. Pflicht (Art. 35 + 76) ≠ Sanktion (Art. 118 → Kreisverwaltung / Art. 119 OWi).' },
    { id: 'FA09', frage: 'BS-Pflicht-Ende?', antwort: 'Ende des SJ, in dem das 21. Lj. vollendet wird. 3 BS-Jahre. NICHT „bis 18. Lj." oder „4 Jahre".' },
    { id: 'FA10', frage: 'Migration tiefer-einweisen — Begründung?', antwort: 'NUR bei allgemeinem Bildungsstand-Defizit (Art. 36/3 S. 4). NICHT bei sprachlichen Defiziten allein. Max. 2 Jgst. tiefer.' },
    { id: 'FA11', frage: 'Quali = MSA?', antwort: 'NEIN. Quali = freiwillige externe Prüfung Ende 9. (50/50 + Projekt). MSA = M10-Abschluss mit eigenen Prüfungsformaten.' },
    { id: 'FA12', frage: 'JuSchG § 1 — Kind / Jugendlicher / sittliche Reife?', antwort: 'Wortlaut: Kind = „noch nicht 14 Jahre alt". Jugendliche = „14, aber noch nicht 18 Jahre alt". Sittliche Reife = altersangemessene Einschätzungsfähigkeit, Maßstab für JuSchG-Anwendung (Kinozugang, Klassenfahrt-Themen).' },
  ],

  faelle: [
    { id: 'F1', titel: 'Lara — Schnitt 2,67, Nachbenotung gefordert',
      sachverhalt: '4. Klasse GS. Lara hat im Übertrittszeugnis einen Schnitt von 2,67 in D/M/HSU. Die Mutter fordert Nachbenotung der letzten Probearbeiten (damit der Schnitt auf 2,66 fällt) und besteht zusätzlich auf Probeunterricht am Gymnasium.',
      knackpunkte: [
        'Realschul-PU steht zu — Schnitt 2,67 verfehlt 2,66 knapp; PU 3 Tage D/M.',
        'Gym-PU auf Eltern-Antrag möglich, unabhängig vom Schnitt; aber Erfolgsaussicht gering (bestanden = mind. 1×3 + 1×4 in D/M).',
        'Nachbenotung NICHT möglich — Beurteilungsentscheidung der LK (Art. 52 BayEUG). Änderung nur bei Verfahrensfehler / offensichtlichem Beurteilungsirrtum.',
        'Beratungspflicht Art. 78: KL muss objektive Optionen aufzeigen (Durchlässigkeits-Perspektive: M-Zug → M10+MSA → FOS).',
      ],
      antwortkette: 'Gespräch + Einsicht ins Probearbeiten-Portfolio → Rechtslage darlegen (Schnitt 2,67 → RS-PU steht zu, Gym-PU auf Antrag) → Durchlässigkeit aufzeigen (M-Zug / WS / Quali als Alternativen) → bei Eskalation SL einbeziehen, formaler Widerspruchsweg gegen ÜZ.',
    },
    { id: 'F2', titel: 'Jonas — Eltern verweigern Schulanmeldung',
      sachverhalt: 'Eltern weigern sich, ihren 7-jährigen Sohn Jonas zur Schule anzumelden, mit der Begründung „häuslicher Unterricht reicht".',
      knackpunkte: [
        'Schulpflicht in Bayern ABSOLUT (Art. 35 BayEUG + BV Art. 129). Homeschooling NICHT zulässig.',
        'Eskalations-Kette: Art. 76 (Eltern-Mitwirkung) → § 20 BaySchO (Meldepflicht) → Art. 119 (OWi + Geldbuße) → Art. 118 Schulzwang (Antrag der Schule bei Kreisverwaltung) → Art. 120 (Grundrechtseinschränkung Freiheit/Wohnung).',
        'Schulpflicht ≠ Schulzwang: Pflicht kraft Gesetz, Schulzwang Sanktionsmechanismus.',
      ],
      antwortkette: 'Elterngespräch + Beratung → SL informieren → Ordnungswidrigkeit-Anzeige → bei fortgesetzter Verweigerung: Schulzwang-Antrag SL bei Kreisverwaltungsbehörde → ggf. Grundrechts-Einschränkung Art. 120.',
    },
    { id: 'F3', titel: 'Familie Demir — Schulpflicht nach Zuzug',
      sachverhalt: 'Familie Demir zog vor 2 Wochen aus Syrien zu (Aufenthaltsgestattung). Tochter Aylin (10) soll in 5. Klasse MS eingewiesen werden, hat aber kein Deutsch.',
      knackpunkte: [
        'Schulpflicht beginnt 3 Monate nach Zuzug (bei Aufenthaltsgestattung/-erlaubnis/Duldung/Ausreisepflicht).',
        'Altersgleichheits-Prinzip: Aylin (10) → Jgst. 5 analog zu Dauer-in-Bayern-SuS.',
        'Tiefer-Einweisung NUR bei allg. Bildungsstand-Defizit (Art. 36/3 S. 4). Sprachlich allein NICHT — Falle!',
        'Vorkurs Deutsch / DaZ-Förderung parallel. Keine Verlängerung der Schulpflicht durch tiefere Einweisung.',
      ],
      antwortkette: 'Ankunfts-Datum prüfen → 3-Monats-Frist → Bildungsstand-Diagnostik (allgem. Wissen, NICHT Deutsch-Test allein) → Einweisung Jgst. 5 + DaZ-Begleitprogramm.',
    },
    { id: 'F4', titel: 'Yusuf — PU mit 2× Note 4 (Elternwille)',
      sachverhalt: 'Yusuf (4. Klasse) hat ÜZ-Schnitt 2,80 D/M/HSU. Eltern beantragen Probeunterricht am Gymnasium. Yusuf erreicht im PU 2× Note 4 in D und M.',
      knackpunkte: [
        'Eltern-Antragsrecht PU: unabhängig vom Schnitt zulässig.',
        'Bestanden = mind. 1×3 + 1×4. Yusuf hat 2× Note 4, also nicht regulär bestanden.',
        'Elternwillen-Regel: bei 2× Note 4 KANN Elternwille die Aufnahme bewirken — gilt NACH PU, NICHT vorab.',
        'Beratungspflicht Art. 78: Erfolgsprognose bei 2,80 + 2×4 schwierig; RS/M-Zug als Alternativen aufzeigen.',
      ],
      antwortkette: 'PU-Ergebnis dokumentieren → Eltern über Elternwillen-Option klar informieren (ohne Druck) → Hinweis auf Durchlässigkeit (RS, M-Zug) → Eltern-Entscheidung respektieren.',
    },
    { id: 'F5', titel: 'Lina — Distanzunterrichts-Verweigerung',
      sachverhalt: 'Lina (8. Kl. MS) loggt sich seit 3 Wochen nicht mehr in den Distanzunterricht ein. Mutter sagt: „Sie ist halt müde."',
      knackpunkte: [
        'Distanzunterricht-Pflicht seit SJ 2020/2021 (BaySchO § 19/4) + Art. 56/4 S. 3 BayEUG: aktive Teilnahmepflicht mit Bild + Ton.',
        'Eltern-Meldepflicht § 20/1 BaySchO bei Verhinderung.',
        'Sanktionsplan: Beratung-Unterstützung-Sanktion (SL, Schulpsych, Beratungs-LK, KL-Kontrollanrufe). Bei Fortsetzung: Erziehungs-/Ordnungsmaßnahmen (Cross-Ref MP_01/MP_05).',
        'Schulpflicht-Eskalation: Art. 119 (OWi) → Art. 118 (Schulzwang) bei Beharrlichkeit.',
      ],
      antwortkette: 'Eltern-Mutter-Gespräch + Beratung → KL-Kontrollanrufe + Meldepflicht einfordern → Beratungs-LK / Schulpsych einbinden → SL informieren → bei Fortsetzung ordnungsbehördliche Schritte.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'Schulwesen + Schularten',
      anriss: 'Dreigliedriges System (Art. 6 BayEUG) — durchlässig zugleich. Verfassungsrahmen BV Art. 128/132/133/134. Elternwahlrecht gebunden an Eignung/Leistung.',
      norm: 'Art. 6 BayEUG', status: 'open', cards: 3,
      subblocks: [{ label: 'Verfassungsrahmen', cards: 1 }, { label: 'Schularten-Katalog', cards: 1 }, { label: 'Privatschulen', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'KiGa → Grundschule',
      anriss: 'Kooperations-Maßnahmen + Vorkurs Deutsch 240 (240 h × 1,5 J.). SVE als sonderpäd. Anbahnung.',
      norm: 'Vorkurs Deutsch 240', status: 'open', cards: 2,
      subblocks: [{ label: 'Kooperation', cards: 1 }, { label: 'Vorkurs + SVE', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: 'Einschulung + Schulpflicht',
      anriss: 'Schulpflicht 12 J. Stichtag 30.09. + Einschulungskorridor. Migration: 3 Monate nach Zuzug. Schulpflicht ≠ Schulzwang.',
      norm: 'Art. 35 BayEUG', status: 'open', cards: 5,
      subblocks: [{ label: 'Schulpflicht-Norm-Kette', cards: 1 }, { label: 'Stichtag + Korridor', cards: 1 }, { label: 'Migration', cards: 1 }, { label: 'BS-Pflicht', cards: 1 }, { label: 'Schulzwang-Eskalation', cards: 1 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Übertritt + Durchlässigkeit',
      anriss: 'Mai-ÜZ Jgst. 4: Gym ≤ 2,33 · RS ≤ 2,66 (D/M/HSU). Gelenkklasse Jgst. 5. M-Zug-Schwellen.',
      norm: '§ 6 GrSO', status: 'open', cards: 4,
      subblocks: [{ label: 'GS 4 → Sek I', cards: 1 }, { label: 'MS 5 Gelenkklasse', cards: 1 }, { label: 'M-Zug-Aufnahme', cards: 1 }, { label: 'Wirtschaftsschule', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'MS-Abschlüsse + 3 Aufstiegswege',
      anriss: 'ESA (Vorrückung ≥ 4,00) · Quali (50/50 + Projekt) · MSA (M10) · Praxisklasse · Quabi. Drei Wege MS → Fachabi.',
      norm: 'MSO § 34', status: 'open', cards: 3,
      subblocks: [{ label: 'Vier Abschlüsse', cards: 1 }, { label: 'Drei Aufstiegswege', cards: 1 }, { label: 'Beratungspflicht Art. 78', cards: 1 }],
    },
  ],

  glossar: {
    'Art. 128 BV': { titel: 'Art. 128 BV — Bildungsanspruch', wortlaut: 'Abs. 1: „Jeder Bewohner Bayerns hat Anspruch darauf, eine seinen erkennbaren Fähigkeiten und seiner inneren Berufung entsprechende Ausbildung zu erhalten."', karten: [] },
    'Art. 129 BV': { titel: 'Art. 129 BV — Schulpflicht + Unentgeltlichkeit', wortlaut: 'Abs. 1: „Alle Kinder sind zum Besuch der Volksschule und der Berufsschule verpflichtet." Abs. 2: „Der Unterricht an diesen Schulen ist unentgeltlich."', karten: ['G02'] },
    'Art. 132 BV': { titel: 'Art. 132 BV — Anlagen/Leistungs-Prinzip', wortlaut: '„Für die Aufnahme eines Kindes in eine bestimmte Schule sind seine Anlagen, seine Neigung, seine Leistung und seine innere Berufung maßgebend, nicht aber die wirtschaftliche und gesellschaftliche Stellung der Eltern."', karten: [] },
    'Art. 133 BV': { titel: 'Art. 133 BV — Bildungsträger', wortlaut: 'Bildung durch öffentliche Anstalten; Staat + Gemeinde wirken zusammen; anerkannte Religions-/Weltanschauungsgemeinschaften sind Bildungsträger.', karten: [] },
    'Art. 134 BV': { titel: 'Art. 134 BV — Privatschulen', wortlaut: 'Privatschulen bedürfen staatlicher Genehmigung; müssen den Anforderungen an öffentliche Schulen entsprechen.', karten: [] },
    'Art. 3 BayEUG': { titel: 'Art. 3 BayEUG — Träger-Differenzierung', wortlaut: 'Öffentliche Schulen (staatlich/kommunal) und private Schulen. Dienstherr LK = Freistaat (staatlich) bzw. Gemeinde/Landkreis (kommunal).', karten: [] },
    'Art. 6 BayEUG': { titel: 'Art. 6 BayEUG — Schularten', wortlaut: 'Allgemein bildend (GS, MS, RS, Gym, …), beruflich (BS, BFS, WS, FOS, BOS, …), Förderschulen, Schulen für Kranke.', karten: [] },
    'Art. 35 BayEUG': { titel: 'Art. 35 BayEUG — Schulpflicht', wortlaut: '„Wer die altersmäßigen Voraussetzungen erfüllt und in Bayern seinen gewöhnlichen Aufenthalt hat oder in einem Berufsausbildungsverhältnis oder einem Beschäftigungsverhältnis steht, unterliegt der Schulpflicht." 12 Jahre = 9 Vollzeit + 3 Berufsschule.', karten: ['G02'] },
    'Art. 36/3 BayEUG': { titel: 'Art. 36 Abs. 3 BayEUG — Jgst.-Einweisung', wortlaut: 'S. 1: Schule stellt für jeden aus Ausland zugezogenen Schulpflichtigen fest, in welche Jgst. einzuweisen ist. S. 4: Tiefer-Einstufung bis 2 Jgst. zulässig NUR bei mangelndem Bildungsstand (NICHT sprachlich!).', karten: ['G04'] },
    'Art. 37 BayEUG': { titel: 'Art. 37 BayEUG — Stichtag + Einschulungskorridor', wortlaut: 'Stichtag 30.09. Einschulungskorridor 01.07.–30.09. seit SJ 2019/2020: Eltern entscheiden Einschulung oder Zurückstellung. Nach 31.12. nur mit schulpsychologischem Gutachten.', karten: ['G02'] },
    'Art. 39 BayEUG': { titel: 'Art. 39 BayEUG — Berufsschulpflicht', wortlaut: 'Nach Vollzeitschulpflicht: 3 BS-Jahre (Spanne 2–3½), spätestens Ende des SJ, in dem das 21. Lj. vollendet wird. Ausnahmen u.a. mittlerer Abschluss + kein Ausbildungsverhältnis, Hochschulzugang, BVJ/BGJ, Beamten-Vorbereitung, FSJ/FÖJ, Bundeswehr.', karten: [] },
    'Art. 41 BayEUG': { titel: 'Art. 41 BayEUG — FöS-Lernort', wortlaut: 'Schulpflichtige mit sonderpäd. Förderbedarf erfüllen Schulpflicht durch allgemeine Schule ODER Förderschule. Eltern entscheiden Lernort (Abs. 1). Bei Streit: Schulaufsichtsbehörde entscheidet (Abs. 6).', karten: [] },
    'Art. 43 BayEUG': { titel: 'Art. 43 BayEUG — Schulartwechsel', wortlaut: 'Wechsel der Schulart bei Erfüllung der Aufnahmevoraussetzungen.', karten: [] },
    'Art. 44 BayEUG': { titel: 'Art. 44 BayEUG — Elternwahlrecht', wortlaut: 'Eltern wählen Schulart / Ausbildungs-/Fachrichtung — gebunden an Eignung + Leistung. NICHT absolut!', karten: [] },
    'Art. 76 BayEUG': { titel: 'Art. 76 BayEUG — Eltern-Mitwirkung', wortlaut: 'Eltern haben „auf den regelmäßigen Schulbesuch zu achten und die Erziehungsarbeit der Schule zu unterstützen". Zwei Pflichten: achten + unterstützen.', karten: [] },
    'Art. 78 BayEUG': { titel: 'Art. 78 BayEUG — Schulberatung', wortlaut: 'Schule + jede LK beraten Eltern + SuS in Schullaufbahn-Fragen + Hilfe bei Bildungsmöglichkeitswahl entsprechend Anlagen/Fähigkeiten.', karten: ['G08'] },
    'Art. 118 BayEUG': { titel: 'Art. 118 BayEUG — Schulzwang', wortlaut: 'Auf Antrag der Schule kann die Kreisverwaltungsbehörde durch Beauftragte den/die Schulpflichtige(n) zwangsweise der Schule zuführen. Akteur „die Schule" — Antragsweg über SL.', karten: ['G03'] },
    'Art. 119 BayEUG': { titel: 'Art. 119 BayEUG — Ordnungswidrigkeit', wortlaut: 'Ordnungswidrigkeit + Geldbuße bei Unterlassung Schul-Anmeldung oder Vereitelung der Schulpflicht.', karten: [] },
    '§ 6 GrSO': { titel: '§ 6 GrSO — Übertrittszeugnis', wortlaut: 'ÜZ Anfang Mai Jgst. 4. Schwellen D/M/HSU: Gym ≤ 2,33 · RS ≤ 2,66 · MS alle übrigen.', karten: ['G01'] },
    '§ 10 GrSO': { titel: '§ 10 GrSO — Probearbeiten Jgst. 4', wortlaut: 'Abs. 1 S. 1: LK-Konferenz legt vor Schuljahresbeginn die Grundsätze fest. Abs. 1 S. 3: in Jgst. 4 „jeweils" in D/M/HSU mindestens 4 U.-Wochen probearbeitenfrei. Abs. 3 S. 2: 18 Probearbeiten bis zum ÜZ in D/M/HSU. Verteilung 10/4/4 nur Sekundärliteratur.', karten: [] },
    '§ 6 MSO': { titel: '§ 6 MSO — Gelenkklasse Jgst. 5', wortlaut: 'Jahreszeugnis: D+M ≤ 2,0 → Gym uneingeschränkt. D+M ≤ 2,5 → RS uneingeschränkt. Sonst Härtefall oder Probeunterricht.', karten: ['G06'] },
    '§ 7 MSO': { titel: '§ 7 MSO — M-Zug-Aufnahme', wortlaut: 'M7 (aus 6. Kl. Jahreszeugnis): D+M+E ≤ 2,66 uneingeschränkt. M8/M9/M10: ≤ 2,33. M10 zusätzlich Quali-Zeugnis. Sonst Antrag + Aufnahmeprüfung.', karten: ['G07'] },
    '§ 8 MSO': { titel: '§ 8 MSO — Durchlässigkeit MS ↔ M-Zug', wortlaut: 'Rückkehr MS ↔ M-Zug grundsätzlich jederzeit möglich. Abs. 3 normiert die Wechselbedingungen.', karten: [] },
    '§ 22 MSO': { titel: '§ 22 MSO — Praxisklasse-Abschluss', wortlaut: 'Theorie-entlastete Prüfung: D/DaZ 90 Min (75 schriftl. + 15 mdl.) + M 60 Min + Fächerverbund 45 Min + Projekt AWT (Projektnote zählt doppelt). Bestehen ≤ 4,0.', karten: [] },
    '§ 34 MSO': { titel: '§ 34 MSO — Quabi', wortlaut: 'Qualifizierter beruflicher Bildungsabschluss = Quali + abgeschlossene Berufsausbildung. Gleichwertig zum mittleren Schulabschluss.', karten: ['G08'] },
    '§ 19/4 BaySchO': { titel: '§ 19 Abs. 4 BaySchO — Distanzunterricht', wortlaut: 'Distanzunterricht verpflichtend seit SJ 2020/2021. Aktive Teilnahmepflicht mit Bild + Ton (i.V.m. Art. 56/4 S. 3 BayEUG).', karten: [] },
    '§ 20 BaySchO': { titel: '§ 20 BaySchO — Eltern-Meldepflicht', wortlaut: 'Eltern müssen Schule bei Verhinderung des Kindes unverzüglich melden.', karten: [] },
    'Vorkurs Deutsch 240': { titel: 'KMBek Vorkurs Deutsch 240', wortlaut: '240 h über 1,5 Schuljahre — vorletztes + letztes KiTa-Jahr. Träger gemeinsam KiTa + GS (je Hälfte). KMBek KWMBl 2011 S. 240.', karten: ['G05'] },
    '§ 1 JuSchG': { titel: '§ 1 JuSchG — Begriffsbestimmungen', wortlaut: 'Kind = Person, „die noch nicht 14 Jahre alt" ist. Jugendliche = Person, „die 14, aber noch nicht 18 Jahre alt" ist. „Sittliche Reife" als zusätzliches Tatbestandsmerkmal für altersangemessene Einschätzung. „Lieblingsbegriff" Schulräte.', karten: [] },
  },
};
