// D Sport — Fachdidaktik · 2. Staatsexamen MS Bayern · Mai 2026
window.MODULE = {
  id: 'd-sport',
  zalgm: 'Fachdidaktik · D Sport',
  schwerpunkt: ['A.1 Doppelauftrag + Kompetenzmodell', 'A.2 Pädagogische Perspektiven (Kurz)', 'A.3 Lernbereiche + Sportfelder', 'A.4 Sicherheit + Aufsicht', 'A.5 Heterogenität + Inklusion'],
  titel: 'Sport.',
  titel2: 'Erziehung im und durch Sport.',
  abriss:
    'Doppelauftrag „Erziehung im Sport" + „Erziehung durch Sport". ' +
    'Sechs pädagogische Perspektiven (Kurz). LP+ Kompetenzstrukturmodell ' +
    'mit 4 prozessbez. × 4 Gegenstandsbereiche. Sicherheits-Anker zentral.',

  kurz: [
    '**Doppelauftrag** des Schulsports (LP+ Bayern): **(a) Erziehung IM Sport** — Freude an Bewegungsvielfalt + körperliche Leistungsfähigkeit erleben. **(b) Erziehung DURCH Sport** — soziale Kompetenzen, Fairness, Teamgeist, Umgang mit Sieg/Niederlage.',
    'Kompetenzstrukturmodell Sport: **4 prozessbez. Kompetenzen** (Leisten/Gestalten/Spielen · Wahrnehmen-analysieren-bewerten · Entscheiden-handeln-verantworten · Kooperieren-kommunizieren-präsentieren) × **4 Gegenstandsbereiche** (Sportliche Handlungsfelder · Gesundheit und Fitness · Fairness/Kooperation/Selbst · Freizeit und Umwelt).',
    '**Pädagogische Perspektiven (Kurz)** — sechs Sinnrichtungen sportlichen Handelns: **Eindruck** (Wahrnehmung) · **Ausdruck** (Bewegungsgestaltung) · **Wagnis** · **Leistung** · **Miteinander** · **Gesundheit**. **Mehrperspektivität** als didaktisches Leitprinzip.',
    '**Sicherheitserziehung** ist zentraler Anker: amtliche Sicherheitsbestimmungen + KMBek + besondere Qualifikationen bei Schwimmen/Sportklettern. **Aufsichtspflicht** während gesamter Sport-Stunde + Wege Umkleide-Halle. Cross-Ref Schulrecht MP_06 § 5 LDO + MP_07 Haftung.',
    '**Heterogenität als Chance** (LP+): methodische Differenzierung in Kleingruppen + individuelle Aufgabenstellung. **Inklusion** durch angepasste Bewegungs-Anforderungen, Material-Vielfalt, ggf. Para-Sportarten. Sport-Förderunterricht (SFU) als Wahloption.',
  ],

  deck: { cards: 8, normebenen: 5, hochprior: 8, fallen: 8 },

  kartografie: [
    { ebene: 'I', bez: 'Verfassung + Bildungsstandards', kuerzel: 'VERF', normen: ['BV Art. 131', 'KMK Bildungsstandards Sport', 'GG Art. 2/2 körperl. Unversehrtheit'], sub: 'Bildungsauftrag · Körperliche Bildung' },
    { ebene: 'II', bez: 'LehrplanPLUS Bayern', kuerzel: 'LP+', normen: ['Fachprofil Sport MS', 'Kompetenzstrukturmodell Sport', 'Lernbereiche LB1–LB7'], sub: 'Doppelauftrag · 4 prozessbez. × 4 Gegenstandsbereiche' },
    { ebene: 'III', bez: 'Sportdidaktik-Klassiker', kuerzel: 'DIDA', normen: ['Kurz 6 Pädagogische Perspektiven', 'Mehrperspektivität', 'Erziehender Sportunterricht', 'Bewegungslernen Meinel/Schnabel'], sub: 'Theoretische Anker' },
    { ebene: 'IV', bez: 'Sicherheit + KMBek', kuerzel: 'SICH', normen: ['KMBek Sicherheits-Bestimmungen Schulsport', 'KUVB Bayern', 'Schwimm-Befähigung', 'Sportklettern-Qualifikation', '§ 5 LDO Aufsichtspflicht'], sub: 'Verbindliche Sicherheitsanker · Cross-Ref MP_06' },
    { ebene: 'V', bez: 'Förderung + DSU', kuerzel: 'FÖRD', normen: ['Differenzierter Sportunterricht (DSU)', 'Sportförderunterricht (SFU)', 'KMBek Inklusion Sport'], sub: 'Optionale Förderformate · Inklusion' },
  ],

  pflichtwissen: [
    { id: 'P01', titel: 'Doppelauftrag des Schulsports',
      frage: 'Welche zwei Erziehungs-Aufträge umfasst der Schulsport?',
      antwort: '**(a) Erziehung IM Sport** — fachintern. SuS entwickeln **Freude an Bewegungsvielfalt** + **erleben körperliche Leistungsfähigkeit**. Ziel: Bedürfnis nach regelmäßiger sportlicher Aktivität. **(b) Erziehung DURCH Sport** — fächerübergreifend. SuS lernen **Kooperationsfähigkeit, Fairness, Teamgeist, Rücksichtnahme, Umgang mit Sieg und Niederlage** durch gemeinsame Bewegungs-Erlebnisse. Beide Aufträge gleichgewichtig.',
      norm: 'LP+ Fachprofil Sport', status: 'open' },
    { id: 'P02', titel: 'Kompetenzstrukturmodell Sport',
      frage: 'Wie ist das Kompetenzstrukturmodell Sport aufgebaut?',
      antwort: 'Zwei Achsen: **4 prozessbez. Kompetenzen** (Leisten/Gestalten/Spielen · Wahrnehmen-analysieren-bewerten · Entscheiden-handeln-verantworten · Kooperieren-kommunizieren-präsentieren) × **4 Gegenstandsbereiche** (Sportliche Handlungsfelder · Gesundheit und Fitness · Fairness/Kooperation/Selbst · Freizeit und Umwelt). Doppeltagging je KE. Andere Achsen als Mathe (6×4), Sk/GPG, WiB (4×5).',
      norm: 'LP+ Fachprofil Sport', status: 'open' },
    { id: 'P03', titel: '6 Pädagogische Perspektiven (Kurz)',
      frage: 'Welche sechs pädagogischen Perspektiven nach Dietrich Kurz strukturieren den Sportunterricht?',
      antwort: '**(A) Eindruck** — Wahrnehmungsfähigkeit verbessern, Bewegungserfahrungen erweitern. **(B) Ausdruck** — sich körperlich ausdrücken, Bewegungen gestalten. **(C) Gesundheit** — Fitness verbessern, Gesundheitsbewusstsein entwickeln. **(D) Wagnis** — etwas wagen und verantworten. **(E) Leistung** — Leistung erfahren und reflektieren. **(F) Miteinander** — gemeinsam handeln, sich messen, sich verstehen. **Mehrperspektivität** = Pflicht-Prinzip: pro Sequenz mehrere Perspektiven adressieren.',
      norm: 'Kurz', status: 'open' },
    { id: 'P04', titel: 'Mehrperspektivität als didaktisches Leitprinzip',
      frage: 'Was bedeutet Mehrperspektivität im Sportunterricht — und welche Funktion erfüllt sie?',
      antwort: '**Mehrperspektivität** = Anwendung **mehrerer** der 6 pädagogischen Perspektiven Kurz pro Sequenz/Inhalt. Verhindert Verengung des SU auf eine einzige Sinnrichtung (z.B. nur Leistungssport). **Beispiel**: Volleyball-Sequenz kann gleichzeitig Leistung (Spielfähigkeit), Miteinander (Teamspiel), Wagnis (Sprung-Schmetterschlag), Ausdruck (Bewegungsgestaltung) adressieren. **LP+-Pflicht**: Mehrperspektivität als integriertes Bildungsziel.',
      norm: 'Kurz', status: 'open' },
    { id: 'P05', titel: 'Lernbereiche LB1–LB7',
      frage: 'Welche Lernbereiche kennt der LP+ Sport MS und wie sind sie strukturiert?',
      antwort: 'Die LP+-Lernbereiche entsprechen weitgehend den Gegenstandsbereichen: **LB1 Sportliche Handlungsfelder** (zentral) mit den klassischen Sportarten-Feldern Leichtathletik · Schwimmen · Spiele (Mannschaft + Rückschlag) · Turnen · Tanz/Gymnastik · Wintersport. **LB2-LB4** Gesundheit/Fitness · Fairness/Kooperation · Freizeit/Umwelt (integriert in LB1). Zusatz: **DSU** (Differenzierter Sportunterricht) + **SFU** (Sportförderunterricht) als Wahloptionen.',
      norm: 'LP+ Sport LB', status: 'open' },
    { id: 'P06', titel: 'Sicherheitserziehung — Kern-Anker',
      frage: 'Welche Sicherheits-Anker gelten für den Sportunterricht — und wer haftet?',
      antwort: '**Verbindlich**: amtliche **KMBek Sicherheits-Bestimmungen Schulsport** + Veröffentlichungen **KUVB** (Kommunale Unfallversicherung Bayern). **Besondere Qualifikationen**: **Schwimmen** = Rettungsschwimmer-Schein (DLRG/DRK Bronze); **Sportklettern** = Trainerschein C oder gleichwertige Qual. **Aufsichtspflicht**: gesamte Sportstunde + Wege Umkleide-Halle ({{§ 5 LDO}}). Bei Aufsichtspflichtverletzung mit Verletzungsfolge: § 229 StGB fahrl. KV + Disziplinar + Amtshaftung Freistaat (Cross-Ref Schulrecht MP_06 + MP_07).',
      norm: 'KMBek Sicherheit', status: 'open' },
    { id: 'P07', titel: 'Heterogenität + Differenzierung im Sport',
      frage: 'Wie wird Heterogenität im Sportunterricht didaktisch produktiv genutzt?',
      antwort: '**LP+-Grundsatz**: Heterogenität als **Chance**, nicht als Defizit. **Methodische Differenzierung**: (1) **Kleingruppen** (3-6 SuS) mit niveau-passenden Aufgaben. (2) **Individuelle Aufgabenstellungen** — SuS wählen Schwierigkeitsstufe. (3) **Material-Vielfalt** — verschiedene Bälle, Geräte, Höhen. (4) **Para-Sportarten** als Inklusions-Anker (Sitzvolleyball, Boccia). **Cross-Ref Mathe-Skript A.5**: 3-Niveaustufen-Logik gilt auch im Sport.',
      norm: 'LP+ Heterogenität', status: 'open' },
    { id: 'P08', titel: 'Bewegungslernen — drei Phasen (Meinel/Schnabel)',
      frage: 'Wie verläuft Bewegungslernen nach Meinel/Schnabel — und welche didaktische Konsequenz hat das?',
      antwort: '**Drei Phasen** (Meinel/Schnabel, Bewegungslehre): **(1) Grobkoordination** — Grundstruktur der Bewegung erlernen; viele Fehler, hoher Energieverbrauch. **(2) Feinkoordination** — Bewegung präziser, ökonomischer; weniger Fehler. **(3) Feinste Koordination + Anpassung** — automatisiert, situationsadaptiv. **Didaktische Konsequenz**: Reihenfolge in der UE-Sequenz von Grob zu Fein; visuelles Vorbild + Demonstration in Grobphase wichtig; Korrekturen erst in Feinphase. Cross-Ref Mathe EIS-Prinzip (parallele Stufenlogik).',
      norm: 'Meinel/Schnabel', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: 'Doppelauftrag = Sport-Stunde halb Theorie, halb Praxis?', antwort: 'NEIN. Doppelauftrag ist eine **Bildungs-Doppelausrichtung** (Erziehung IM + DURCH Sport), keine Stundenstruktur. Beide Aufträge realisieren sich gleichzeitig in jeder Sportstunde — z.B. Volleyball gibt sportliche Bewegungserfahrung (IM) + Teamfähigkeit (DURCH).' },
    { id: 'FA02', frage: 'Pädagogische Perspektiven (Kurz) = 5 Stück?', antwort: 'NEIN — **6** Perspektiven: Eindruck · Ausdruck · Gesundheit · Wagnis · Leistung · Miteinander. Wer fünf nennt, hat eine vergessen. Mehrperspektivität = mehrere davon pro Sequenz adressieren.' },
    { id: 'FA03', frage: 'Mehrperspektivität = alle 6 Perspektiven pro Stunde?', antwort: 'NEIN. Mehrperspektivität bedeutet **mehrere** Perspektiven pro Sequenz/Inhalt — nicht zwingend alle 6 in einer Stunde. Verhindert Verengung auf eine einzige Sinnrichtung (z.B. nur Leistung).' },
    { id: 'FA04', frage: 'Sportlehrer braucht keine Zusatzqualifikation für Schwimmen?', antwort: 'NEIN — **Rettungsschwimmer-Schein Pflicht** (DLRG/DRK Bronze als Mindeststandard, regelmäßige Auffrischung). Bei Sportklettern: Trainerschein C oder gleichwertige Qualifikation. KMBek Sicherheits-Bestimmungen verbindlich.' },
    { id: 'FA05', frage: 'Wenn ein SuS sich verletzt, haftet die LK persönlich?', antwort: 'NEIN (Cross-Ref Schulrecht MP_07 Haftungsdreieck). Bei Aufsichtspflichtverletzung greift {{Art. 34 GG}} — **Freistaat haftet außen**. **Rückgriff** auf LK NUR bei Vorsatz oder grober Fahrlässigkeit. Bei verletzungs-relevanter Aufsichtspflichtverletzung zusätzlich § 229 StGB fahrl. KV persönlich.' },
    { id: 'FA06', frage: 'Kompetenzstrukturmodell Sport identisch mit Mathe?', antwort: 'NEIN. Sport: **4 prozessbez. × 4 Gegenstandsbereiche**. Mathe: **6 × 4**. WiB: **4 × 5**. Sk/GPG: andere Achsen. Sport-Achsen: Leisten/Gestalten/Spielen · Wahrnehmen-analysieren-bewerten · Entscheiden-handeln-verantworten · Kooperieren-kommunizieren-präsentieren × Sportliche Handlungsfelder/Gesundheit/Fairness/Freizeit-Umwelt.' },
    { id: 'FA07', frage: 'Heterogenität im Sport = Problem?', antwort: 'NEIN. LP+ sieht Heterogenität als **Chance** — Vielfalt fördert. Methodische Differenzierung (Kleingruppen, individuelle Aufgaben, Material-Vielfalt) als reguläre Methodik. Inklusion durch Para-Sportarten möglich.' },
    { id: 'FA08', frage: 'Bewegungslernen verläuft in zwei Phasen?', antwort: 'NEIN — **drei Phasen** (Meinel/Schnabel): Grobkoordination → Feinkoordination → feinste Koordination + Anpassung. Korrekturen erst in Feinphase ansetzen, nicht in Grobphase überfordern.' },
  ],

  faelle: [
    { id: 'F1', titel: 'Volleyball Jgst. 8 — Mehrperspektivität (Hauptfall)',
      sachverhalt: 'Sie planen eine 8-UE-Volleyball-Sequenz in der M8 Regelklasse. Wie realisieren Sie Mehrperspektivität nach Kurz?',
      knackpunkte: [
        '**Pädagogische Perspektiven aktivieren**: (E) Eindruck — Ball-Wahrnehmung, Antizipation des Flugverhaltens; (B) Ausdruck — Bewegungsgestaltung beim Pritschen, Baggern, Sprung-Schmetterschlag; (C) Gesundheit — Konditionsanteil, Sprungkraft, Ausdauer; (D) Wagnis — Hechtbagger, Sprung-Schmetterschlag in Höhe; (E) Leistung — individuelle und Team-Leistung messen, sich verbessern; (F) Miteinander — Kooperatives Mannschaftsspiel, faire Punktwertung, Sieg/Niederlage.',
        '**Kompetenzstrukturmodell**: Leisten/Gestalten/Spielen × Sportliche Handlungsfelder LB1 als Haupt-Tagging; Kooperieren-kommunizieren-präsentieren × Fairness/Kooperation als zweiter Schwerpunkt.',
        '**Differenzierung**: Kleingruppen 4-6 SuS mit niveau-passenden Aufgaben; Material-Vielfalt (weiche Bälle für Anfänger, Standard-Volleyball für Fortgeschrittene).',
        '**Bewegungslernen-Stufung** (Meinel/Schnabel): UE1-3 Grobkoordination Pritschen/Baggern → UE4-6 Feinkoordination + erste Spielsituationen → UE7-8 spielfähigkeits-orientiert.',
        '**Sicherheits-Anker**: Aufwärm-Phase strukturiert; Sicherheitsregeln am Netz (Verletzungs-Prophylaxe); KUVB-Konformität.',
        '**Reflexion**: SuS bewerten am Ende eigene Lernfortschritte + Team-Erfahrungen (Verschmelzung der Perspektiven Leistung + Miteinander).',
      ],
      antwortkette: 'LP+-Bezug Sport LB1 nennen → Doppelauftrag verbatim erläutern → 6 Perspektiven Kurz verbatim → konkret zeigen, welche Perspektiven die Sequenz adressiert → Bewegungslernen-Stufung Meinel/Schnabel → Differenzierungs-Strategie → Sicherheits-Anker → Reflexion.',
    },
    { id: 'F2', titel: 'Inklusion im Sport — SuS mit Förderbedarf körperl.-motor.',
      sachverhalt: 'In Ihrer M7-Klasse ist ein:e SuS mit Förderbedarf k.-m. Entwicklung (Rollstuhl). Wie inkludieren Sie im Sportunterricht?',
      knackpunkte: [
        '**Methodische Differenzierung** (LP+ Heterogenität): Aufgaben so anpassen, dass jede:r teilnehmen kann — z.B. Sitz-Volleyball, Boccia, Rollstuhl-Basketball.',
        '**Para-Sportarten als Vollwert-Angebot** (nicht „abgespeckte" Variante): SuS mit Rolli IS Vollwertspieler:in, Mitspielende lernen Spielregeln + Bewegungs-Anpassung.',
        '**Cross-Ref Schulrecht**: {{Art. 41 BayEUG}} Eltern entscheiden Lernort. {{Art. 30a/4 BayEUG}} — bei FS k.-m. Entwicklung **Sachaufwandsträger-Zustimmung erforderlich** (Cross-Ref MP_08 Hertha-Falle: bei FS gE NICHT, bei k.-m. JA).',
        '**Sicherheit**: bei körperlichen Einschränkungen besondere Gefährdungs-Beurteilung; ggf. zusätzliche Aufsichtsperson (Schulbegleiter:in).',
        '**Soziale Dimension**: Inklusion stärkt die **Miteinander-Perspektive** (Kurz F) — alle SuS profitieren.',
        '**Förderplan** {{MSO § 14}}: bei voraussichtl. Nicht-Erreichen der MS-Lernziele Pflicht (Cross-Ref Schulrecht MP_04 A.5).',
      ],
      antwortkette: 'LP+-Bezug Heterogenität als Chance → konkrete Methoden (Para-Sportarten, Sitz-Volleyball, Boccia) → Cross-Ref Schulrecht Art. 30a/4 + Art. 41 → Sicherheits-Aspekt → soziale Dimension Miteinander → Förderplan-Anker MSO § 14.',
    },
    { id: 'F3', titel: 'Sicherheits-Vorfall — Aufsichtspflicht beim Sportklettern',
      sachverhalt: 'Während Sie eine Sportklettern-AG in Jgst. 7 leiten, verletzt sich ein:e SuS beim Abseilen. Sie sind wegen eines Telefonats kurz aus der Halle gegangen. Eltern klagen.',
      knackpunkte: [
        '**Aufsichtspflichtverletzung** {{§ 5 LDO}} (Cross-Ref Schulrecht MP_06 A.2): Verlassen während gefährlicher Sportphase ohne notwendige Maßnahmen.',
        '**Sportklettern-Qualifikation**: KMBek Sicherheits-Bestimmungen verlangen **Trainerschein C** o.ä. — bei fehlender Qualifikation bereits SL-Verantwortung berührt.',
        '**Zivilrechtlich** (Cross-Ref MP_07 A.2): {{§ 839 BGB}} + {{Art. 34 GG}} → **Freistaat haftet außen**. Rückgriff auf LK NUR bei Vorsatz/grober Fahrlässigkeit.',
        '**Strafrechtlich**: § 229 StGB fahrl. KV — wenn Kausalität + Vorhersehbarkeit gegeben. **Persönlich** (Schuldprinzip).',
        '**Disziplinarrechtlich**: {{§ 47 BeamtStG}} + Art. 6 BayDG — Maßnahme nach Schwere (Verweis bis Kürzung Dienstbezüge).',
        '**Kumulativ**: alle drei Pfade laufen parallel (keine Doppelbestrafung wegen Art. 103/3 GG — Disziplinar ist Sonderrecht).',
      ],
      antwortkette: 'Aufsichtspflicht § 5 LDO verbatim → Sportklettern-Qualifikations-Anforderung → Haftungsdreieck Zivil/Disziplinar/Straf erläutern → Freistaat-Außenhaftung Art. 34 GG → § 229 StGB persönlich (wahrscheinl. grobe F. → Rückgriff) → BayDG-Maßnahme parallel.',
    },
    { id: 'F4', titel: 'Schwimm-Unterricht Jgst. 5 — Eingangsbedingungen + Sicherheit',
      sachverhalt: 'Sie übernehmen eine M5 Schwimm-Stunde im Hallenbad. Wie strukturieren Sie sicherheitstechnisch + didaktisch?',
      knackpunkte: [
        '**Eingangs-Voraussetzung LK**: **Rettungsschwimmer-Schein** Pflicht (DLRG/DRK Bronze; aktuell). KMBek Sicherheits-Bestimmungen verbindlich.',
        '**SuS-Eingangs-Status erheben**: Schwimm-Können (Seepferdchen, Bronze, Silber, Gold) — Differenzierung in Schwimmer/Nichtschwimmer-Gruppen.',
        '**Aufsichts-Verteilung**: Sichtkontakt zu allen SuS jederzeit; Auf-Becken-Rand-Aufstellung statt Schwimm-Lehre vom Wasser aus. Cross-Ref MP_06 § 5 LDO.',
        '**Pädagogische Perspektiven Kurz**: (A) Eindruck — Wasser-Wahrnehmung; (D) Wagnis — Sprung vom Beckenrand; (C) Gesundheit — Ausdauer; (F) Miteinander — Schwimmpartner-Aufgaben.',
        '**Bewegungslernen Meinel/Schnabel**: bei Nichtschwimmern Grobkoordination Wasser-Gewöhnung → Auftrieb → einfache Schwimm-Antriebe; Korrekturen erst in Feinkoordinations-Phase.',
        '**Erste-Hilfe-Bereitschaft**: Standort Rettungsring, Notfall-Telefon, Bademeister:in (falls vor Ort).',
      ],
      antwortkette: 'Rettungsschwimmer-Schein als Pflicht-Voraussetzung → SuS-Status-Differenzierung → Aufsichts-Logik § 5 LDO → Pädagogische Perspektiven (Kurz) für die Stunde aktivieren → Bewegungslernen-Stufung → Erste-Hilfe-Anker.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'Doppelauftrag + Kompetenzstrukturmodell Sport',
      anriss: 'LP+ Bayern: Erziehung IM Sport (Bewegungsvielfalt, Leistungsfähigkeit) + Erziehung DURCH Sport (Fairness, Teamgeist). 4 prozessbez. × 4 Gegenstandsbereiche.',
      norm: 'LP+ Fachprofil Sport', status: 'open', cards: 2,
      subblocks: [{ label: 'Doppelauftrag IM + DURCH Sport', cards: 1 }, { label: 'Kompetenzstrukturmodell Sport — 4 × 4', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'Pädagogische Perspektiven (Kurz) + Mehrperspektivität',
      anriss: 'Sechs Sinnrichtungen sportlichen Handelns (Eindruck · Ausdruck · Gesundheit · Wagnis · Leistung · Miteinander). Mehrperspektivität als didaktisches Leitprinzip.',
      norm: 'Kurz', status: 'open', cards: 3,
      subblocks: [{ label: '6 Perspektiven verbatim (Kurz)', cards: 1 }, { label: 'Mehrperspektivität als Leitprinzip', cards: 1 }, { label: 'Praxis-Beispiel Mehrperspektivität (Volleyball)', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: 'Lernbereiche + Sportarten-Felder + Bewegungslernen',
      anriss: 'LP+ LB1 Sportliche Handlungsfelder (Leichtathletik · Schwimmen · Spiele · Turnen · Tanz · Wintersport). Meinel/Schnabel 3-Phasen-Bewegungslernen. DSU + SFU.',
      norm: 'LP+ Sport LB', status: 'open', cards: 3,
      subblocks: [{ label: 'LB1-LB4 Übersicht', cards: 1 }, { label: 'Bewegungslernen 3 Phasen (Meinel/Schnabel)', cards: 1 }, { label: 'DSU + SFU als Wahloptionen', cards: 1 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Sicherheitserziehung + Aufsichtspflicht (Cross-Ref Schulrecht)',
      anriss: 'KMBek Sicherheits-Bestimmungen + KUVB. Schwimm-/Sportklettern-Qualifikationen. § 5 LDO Aufsichtspflicht. Bei Verletzung: Haftungsdreieck MP_07.',
      norm: 'KMBek Sicherheit', status: 'open', cards: 3,
      subblocks: [{ label: 'Sicherheits-Bestimmungen + Qualifikationen', cards: 1 }, { label: 'Aufsichtspflicht § 5 LDO + Wege Umkleide-Halle', cards: 1 }, { label: 'Haftungsachsen bei Verletzung (Cross-Ref MP_07)', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'Heterogenität + Inklusion + Differenzierung',
      anriss: 'LP+ sieht Heterogenität als Chance. Methodische Differenzierung in Kleingruppen + individuelle Aufgaben. Inklusion durch Para-Sportarten. Cross-Ref MP_08 Lernort.',
      norm: 'LP+ Heterogenität', status: 'open', cards: 3,
      subblocks: [{ label: 'Heterogenität als Chance', cards: 1 }, { label: 'Methodische Differenzierung 4 Wege', cards: 1 }, { label: 'Inklusion + Para-Sportarten + MP_08-Anker', cards: 1 }],
    },
  ],

  glossar: {
    'BV Art. 131': { titel: 'BV Art. 131 — Bildungsziele', wortlaut: 'Bayerischer Bildungsauftrag mit Werte-Boden auch für Sport: Achtung der Würde des Menschen, Verantwortungsbewusstsein, Hilfsbereitschaft. Cross-Ref Erziehung durch Sport (Fairness, Teamgeist).', karten: [] },
    'GG Art. 2/2': { titel: 'GG Art. 2 Abs. 2 — körperliche Unversehrtheit', wortlaut: '„Jeder hat das Recht auf Leben und körperliche Unversehrtheit." Verfassungsrechtlicher Anker für **Sicherheitserziehung** im Schulsport: die Schule darf SuS keiner unverhältnismäßigen Verletzungsgefahr aussetzen. Cross-Ref Schulrecht MP_06 § 5 LDO + MP_07 § 229 StGB.', karten: [] },
    'LP+ Fachprofil Sport': { titel: 'LP+ Fachprofil Sport MS Bayern', wortlaut: '**Doppelauftrag**: (a) Erziehung **IM** Sport — SuS entwickeln „Freude und Interesse an der Vielfalt sportlicher Bewegungsformen sowie das Bedürfnis nach regelmäßiger sportlicher Aktivität" + erleben körperliche Leistungsfähigkeit. (b) Erziehung **DURCH** Sport — „Kooperationsfähigkeit, Fairness, Teamgeist, Rücksichtnahme, der Umgang mit Sieg und Niederlage". Quelle: lehrplanplus.bayern.de.', karten: ['P01', 'P02'] },
    'LP+ Sport LB': { titel: 'LP+ Lernbereiche Sport MS', wortlaut: 'Lernbereich-Struktur: **LB1 Sportliche Handlungsfelder** (zentral) — Leichtathletik · Schwimmen · Spiele (Mannschaft + Rückschlag) · Turnen · Tanz/Gymnastik · Wintersport. **LB2-LB4** Gesundheit und Fitness · Fairness/Kooperation/Selbstkompetenz · Freizeit und Umwelt (integriert in LB1). Zusatz: **DSU** (Differenzierter Sportunterricht) + **SFU** (Sportförderunterricht) als Wahloptionen.', karten: ['P05'] },
    'LP+ Heterogenität': { titel: 'LP+ Sport — Heterogenität als Chance', wortlaut: '„Heterogenität wird als förderlich für Vielfalt genutzt." **Methodische Differenzierung** in Kleingruppen oder individuelle Aufgabenstellung. **Inklusion**: Para-Sportarten als Vollwert-Angebot (Sitzvolleyball, Boccia, Rollstuhl-Basketball). Material-Vielfalt + Schwierigkeits-Stufen.', karten: ['P07'] },
    'Kurz': { titel: '6 Pädagogische Perspektiven (Dietrich Kurz)', wortlaut: '**Sechs Sinnrichtungen** sportlichen Handelns (Kurz 1990 ff.): **(A) Eindruck** — Wahrnehmungsfähigkeit verbessern, Bewegungserfahrungen erweitern. **(B) Ausdruck** — sich körperlich ausdrücken, Bewegungen gestalten. **(C) Gesundheit** — Fitness verbessern, Gesundheitsbewusstsein entwickeln. **(D) Wagnis** — etwas wagen und verantworten. **(E) Leistung** — Leistung erfahren und reflektieren. **(F) Miteinander** — gemeinsam handeln, sich messen, sich verstehen. **Mehrperspektivität** = mehrere Perspektiven pro Sequenz adressieren; verhindert Verengung auf eine einzige Sinnrichtung (z.B. nur Leistung). Übernommen in alle modernen Schul-Sport-Curricula (NRW, BW, Bayern u.a.).', karten: ['P03', 'P04'] },
    'Meinel/Schnabel': { titel: 'Bewegungslernen — 3 Phasen (Meinel/Schnabel)', wortlaut: '**Kurt Meinel + Günter Schnabel**, „Bewegungslehre — Sportmotorik" (Klassiker, seit 1962). **Drei Phasen**: (1) **Grobkoordination** — Grundstruktur erlernen; viele Fehler, hoher Energieverbrauch, visuelles Vorbild zentral. (2) **Feinkoordination** — präziser, ökonomischer; Korrekturen ansetzen. (3) **Feinste Koordination + Anpassung** — automatisiert, situationsadaptiv. **Didaktische Konsequenz**: in der UE-Sequenz von Grob zu Fein; Korrekturen erst in Feinphase, nicht in Grobphase überfordern.', karten: ['P08'] },
    'KMBek Sicherheit': { titel: 'KMBek Sicherheits-Bestimmungen Schulsport Bayern', wortlaut: 'Verbindlicher Sicherheits-Rahmen für den Schulsport in Bayern + Veröffentlichungen der **KUVB** (Kommunale Unfallversicherung Bayern). **Besondere Qualifikationen**: Schwimmen = **Rettungsschwimmer-Schein** (DLRG/DRK Bronze) Pflicht; Sportklettern = Trainerschein C o.ä. Pflicht. **Aufsichtspflicht** während gesamter Sport-Stunde + Wege Umkleide-Halle nach {{§ 5 LDO}}. Bei Aufsichtspflichtverletzung mit Verletzungsfolge: § 229 StGB fahrl. KV + Disziplinar + Amtshaftung (Cross-Ref Schulrecht MP_06 + MP_07).', karten: ['P06'] },
    '§ 5 LDO': { titel: '§ 5 LDO — Aufsichtspflicht (Cross-Ref Schulrecht MP_06)', wortlaut: 'Vollzitat in Schulrecht-V3 MP_06 A.2. Im Sportunterricht relevant: Aufsichtspflicht **gesamte Sport-Stunde + Wege Umkleide-Halle** + bei besonders gefährlichen Sportphasen (Klettern, Schwimmen, Turnen Großgeräte) erhöhte Aufmerksamkeit. Bei Verletzungsfolge: § 229 StGB fahrl. KV möglich.', karten: ['P06'] },
    'Art. 41 BayEUG': { titel: 'Art. 41 BayEUG — Lernort (Cross-Ref Schulrecht MP_08)', wortlaut: 'Cross-Ref Schulrecht-V3 MP_08 A.2. Im Sport relevant: **Eltern entscheiden Lernort**. Bei SuS mit FS k.-m. Entwicklung + Inklusion in Regelschule = **Sachaufwandsträger-Zustimmung erforderlich** ({{Art. 30a/4 BayEUG}}). Bei FS gE: Sachaufwandsträger-Zustimmung NICHT erforderlich (Hertha-Falle).', karten: [] },
    'Art. 30a/4 BayEUG': { titel: 'Art. 30a/4 BayEUG — Sachaufwandsträger-Zustimmung', wortlaut: 'Cross-Ref Schulrecht-V3 MP_08 A.2. Sachaufwandsträger-Zustimmung erforderlich für Inklusion in Regelschule **NUR** bei Förderschwerpunkten **Sehen / Hören / körperlich-motorische Entwicklung**. Bei anderen Schwerpunkten NICHT.', karten: [] },
    'Art. 34 GG': { titel: 'Art. 34 GG — Staatshaftung (Cross-Ref Schulrecht MP_07)', wortlaut: 'Cross-Ref Schulrecht-V3 MP_07 A.2. Bei Aufsichtspflichtverletzung im Sport: **Freistaat haftet außen** (Art. 34 GG S. 1). Rückgriff Freistaat → LK NUR bei **Vorsatz oder grober Fahrlässigkeit** (Art. 34 GG S. 2). Bei Sportkletter-Aufsichtsversagen: typisch grobe Fahrlässigkeit → Rückgriff möglich.', karten: [] },
    '§ 839 BGB': { titel: '§ 839 BGB — Beamtenhaftung (Cross-Ref Schulrecht MP_07)', wortlaut: 'Cross-Ref Schulrecht-V3 MP_07 A.2. Anspruchsgrundlage für Schadensersatz bei Amtspflichtverletzung. I.V.m. {{Art. 34 GG}} → Staatshaftung mit Rückgriff bei Vorsatz/grober Fahrlässigkeit.', karten: [] },
    '§ 47 BeamtStG': { titel: '§ 47 BeamtStG — Dienstvergehen (Cross-Ref Schulrecht MP_07)', wortlaut: 'Cross-Ref Schulrecht-V3 MP_07 A.3. Bei Aufsichtspflichtverletzung im Sport: schuldhafte Pflichtverletzung → Dienstvergehen-Tatbestand → Maßnahmen-Katalog Art. 6 BayDG.', karten: [] },
    'MSO § 14': { titel: 'MSO § 14 — Individueller Förderplan (Cross-Ref Schulrecht MP_04)', wortlaut: 'Cross-Ref Schulrecht-V3 MP_04 A.5. Bei voraussichtl. Nicht-Erreichen der MS-Lernziele wegen sonderpäd. Förderbedarfs: Förderplan-Pflicht. MSD-Einbeziehung Pflicht, jährlich fortzuschreiben. Gilt auch im Sport-Kontext bei Inklusion.', karten: [] },
  },
};
