// D Sport — Fachdidaktik · 2. Staatsexamen MS Bayern · Mai 2026
window.MODULE = {
  id: 'd-sport',
  zalgm: 'Fachdidaktik · D Sport',
  schwerpunkt: ['A.1 Doppelauftrag + Kompetenzmodell', 'A.2 3-Phasen-Hofmann + Methoden', 'A.3 Lernbereiche + Sportfelder + Pädagogische Perspektiven', 'A.4 Sicherheit + Aufsicht (B6)', 'A.5 Leistungsbeurteilung (B7) + MSO § 15', 'A.6 Heterogenität + Inklusion'],
  titel: 'Sport.',
  titel2: 'Erziehung im und durch Sport.',
  abriss:
    'Doppelauftrag „Erziehung im Sport" + „Erziehung durch Sport". ' +
    '3-Phasen-Modell nach Hofmann (Bausteinskript Bayern-Unterfranken VERBINDLICH) ' +
    'mit operativer 7-Sub-Phasen-Feingliederung. LP+ Kompetenzstrukturmodell ' +
    '4 prozessbez. × 4 Gegenstandsbereiche. Sport NICHT Vorrückungsfach (MSO § 15).',

  kurz: [
    '**Doppelauftrag** des Schulsports (LP+ Bayern + Bausteinskript GB Kap. 1): **(a) Erziehung IM Sport** — Freude an Bewegungsvielfalt + körperliche Leistungsfähigkeit erleben. **(b) Erziehung DURCH Sport** — Kooperationsfähigkeit, Fairness, Teamgeist, Umgang mit Sieg/Niederlage. Beide simultan, KEINE Stunden-Aufteilung.',
    'Kompetenzstrukturmodell Sport: **4 prozessbez. Kompetenzen** (Leisten/Gestalten/Spielen · Wahrnehmen-analysieren-bewerten · Entscheiden-handeln-verantworten · Kooperieren-kommunizieren-präsentieren) × **4 Gegenstandsbereiche** (Sportliche Handlungsfelder · Gesundheit und Fitness · Fairness/Kooperation/Selbst · Freizeit und Umwelt).',
    '**3-Phasen-Modell nach HOFMANN** (Bausteinskript SP GB Kap. 8, AG MS-Sem.-Unterfranken · **VERBINDLICH**): (1) Aufwärmphase mit Sub-Stufung 1.1 allg + 1.2 spez. Erwärmung · (2) Hauptphase/Erarbeitungsphase · (3) Schlussteil/Ausklang. NICHT 7-Phasen-Söll! Söll 2019 wird im Bausteinskript NICHT zitiert.',
    '**Sport ist KEIN Vorrückungsfach** (MSO § 15 Abs. 2 S. 2 verbatim: „Vorrückungsfächer sind alle Pflicht- und Wahlpflichtfächer mit Ausnahme des Fachs Sport"). Trotzdem Notengebungs-Pflicht. **3-Achsen-Beurteilung** (Können · Lernverhalten · Lernfortschritt) + **LASPO**: pro HJ 2 praktische + 1 nicht-praktischer LNW. DSU-Note (BSU×2+DSU):3.',
    '**Sicherheitserziehung** zentraler Anker (Bausteinskript B6): **Großtrampoline NICHT zulässig** · Schmuck ablegen · schulsportgerechte Brille · Sicht-/Funktionsprüfung Geräte · LK als Erste:r/Letzte:r. KMBek 08.04.2003 + 11.12.2002 + KUVB. Cross-Ref Schulrecht MP_06 § 5 LDO + MP_07 Haftung.',
    '**Pädagogische Perspektiven (Kurz · ergänzend!)** — sechs Sinnrichtungen: Eindruck · Ausdruck · Gesundheit · Wagnis · Leistung · Miteinander. **Wichtig**: Kurz ist NRW-/Bundes-Tradition, im Bayern-Unterfranken-Bausteinskript NICHT zentral. Mehrperspektivität = mehrere Perspektiven pro Sequenz.',
    '**Heterogenität als Chance** (LP+): methodische Differenzierung in Kleingruppen + individuelle Aufgabenstellung + Material-Vielfalt + Para-Sportarten. **BSU** geschlechtsgetrennt, **DSU** koedukativ möglich. M-/R-Niveau nicht extra ausgewiesen — LK differenziert selbst.',
  ],

  deck: { cards: 11, normebenen: 5, hochprior: 11, fallen: 12 },

  kartografie: [
    { ebene: 'I', bez: 'Verfassung + Bundesrecht', kuerzel: 'VERF', normen: ['BV Art. 131', 'GG Art. 2/2 körperl. Unversehrtheit', 'MSO § 15 Sport nicht Vorrückungsfach', 'KMK Bildungsstandards Sport'], sub: 'Bildungsauftrag · Körperliche Bildung · Sport-Sonderstatus' },
    { ebene: 'II', bez: 'LehrplanPLUS Bayern', kuerzel: 'LP+', normen: ['Fachprofil Sport MS', 'Kompetenzstrukturmodell Sport (4×4)', 'Lernbereiche LB1–LB7'], sub: 'Doppelauftrag · 4 prozessbez. × 4 Gegenstandsbereiche' },
    { ebene: 'III', bez: 'Bausteinskripte Bayern-Unterfranken (Hofmann SR · VERBINDLICH)', kuerzel: 'BAUSTEIN', normen: ['SP GB Grundsätze (3-Phasen-Modell · 4 Methoden · 7 Intensivierung · 6 Merkmale)', 'SP B1-B5 Handlungsfelder', 'SP B6 Sicherheit', 'SP B7 Leistungsmessung'], sub: 'AG MS-Seminarleiter:innen Unterfranken · primäre Quelle' },
    { ebene: 'IV', bez: 'Sportdidaktik-Klassiker (sekundär)', kuerzel: 'DIDA', normen: ['Kurz 6 Pädagogische Perspektiven (NRW-Tradition)', 'Meinel/Schnabel Bewegungslernen 3 Phasen', 'Fetz 1996 / Größing / Erdmann (Leistung)', 'Söll 2019 (NICHT im Bausteinskript zitiert)'], sub: 'Ergänzende Theorie-Anker' },
    { ebene: 'V', bez: 'Sicherheit + KMBek + Leistung', kuerzel: 'SICH', normen: ['KMBek Sicherheits-Bestimmungen Schulsport 08.04.2003', 'KMBek Sicherheit Schule + Schülerunfallversicherung 11.12.2002', 'KUVB Bayern', 'Schwimm-Befähigung DLRG Bronze', 'Sportklettern-Qualifikation C', '§ 5 LDO Aufsichtspflicht', 'LASPO Bewertungstabellen'], sub: 'Verbindliche Sicherheits- + Leistungs-Anker · Cross-Ref MP_06+07' },
    { ebene: 'VI', bez: 'Förderung + DSU + SFU', kuerzel: 'FÖRD', normen: ['BSU geschlechtsgetrennt', 'DSU koedukativ möglich', 'Sportförderunterricht (SFU)', 'KMBek Inklusion Sport'], sub: 'Optionale Förderformate · Inklusion' },
  ],

  pflichtwissen: [
    { id: 'P01', titel: 'Doppelauftrag des Schulsports',
      frage: 'Welche zwei Erziehungs-Aufträge umfasst der Schulsport?',
      antwort: '**(a) Erziehung IM Sport** — fachintern. SuS entwickeln **Freude an Bewegungsvielfalt** + **erleben körperliche Leistungsfähigkeit**. Ziel: Bedürfnis nach regelmäßiger sportlicher Aktivität. **(b) Erziehung DURCH Sport** — fächerübergreifend. SuS lernen **Kooperationsfähigkeit, Fairness, Teamgeist, Rücksichtnahme, Umgang mit Sieg und Niederlage** durch gemeinsame Bewegungs-Erlebnisse. Beide Aufträge gleichgewichtig.',
      norm: 'LP+ Fachprofil Sport', status: 'open' },
    { id: 'P02', titel: 'Kompetenzstrukturmodell Sport',
      frage: 'Wie ist das Kompetenzstrukturmodell Sport aufgebaut?',
      antwort: 'Zwei Achsen: **4 prozessbez. Kompetenzen** (Leisten/Gestalten/Spielen · Wahrnehmen-analysieren-bewerten · Entscheiden-handeln-verantworten · Kooperieren-kommunizieren-präsentieren) × **4 Gegenstandsbereiche** (Sportliche Handlungsfelder · Gesundheit und Fitness · Fairness/Kooperation/Selbst · Freizeit und Umwelt). Doppeltagging je KE. Andere Achsen als Mathe (6×4), Sk/GPG, WiB (4×5).',
      norm: 'LP+ Fachprofil Sport', status: 'open' },
    { id: 'P03', titel: '6 Pädagogische Perspektiven (Kurz)',
      frage: 'Welche sechs pädagogischen Perspektiven nach Dietrich Kurz strukturieren den Sportunterricht?',
      antwort: '**(A) Eindruck** — Wahrnehmungsfähigkeit verbessern, Bewegungserfahrungen erweitern. **(B) Ausdruck** — sich körperlich ausdrücken, Bewegungen gestalten. **(C) Gesundheit** — Fitness verbessern, Gesundheitsbewusstsein entwickeln. **(D) Wagnis** — etwas wagen und verantworten. **(E) Leistung** — Leistung erfahren und reflektieren. **(F) Miteinander** — gemeinsam handeln, sich messen, sich verstehen. **Mehrperspektivität** = Pflicht-Prinzip: pro Sequenz mehrere Perspektiven adressieren.',
      norm: 'Kurz', status: 'open' },
    { id: 'P04', titel: 'Mehrperspektivität als didaktisches Leitprinzip',
      frage: 'Was bedeutet Mehrperspektivität im Sportunterricht — und welche Funktion erfüllt sie?',
      antwort: '**Mehrperspektivität** = Anwendung **mehrerer** der 6 pädagogischen Perspektiven Kurz pro Sequenz/Inhalt. Verhindert Verengung des SU auf eine einzige Sinnrichtung (z.B. nur Leistungssport). **Beispiel**: Volleyball-Sequenz kann gleichzeitig Leistung (Spielfähigkeit), Miteinander (Teamspiel), Wagnis (Sprung-Schmetterschlag), Ausdruck (Bewegungsgestaltung) adressieren. **LP+-Pflicht**: Mehrperspektivität als integriertes Bildungsziel.',
      norm: 'Kurz', status: 'open' },
    { id: 'P05', titel: 'Lernbereiche LB1–LB7',
      frage: 'Welche Lernbereiche kennt der LP+ Sport MS und wie sind sie strukturiert?',
      antwort: 'Die LP+-Lernbereiche entsprechen weitgehend den Gegenstandsbereichen: **LB1 Sportliche Handlungsfelder** (zentral) mit den klassischen Sportarten-Feldern Leichtathletik · Schwimmen · Spiele (Mannschaft + Rückschlag) · Turnen · Tanz/Gymnastik · Wintersport. **LB2-LB4** Gesundheit/Fitness · Fairness/Kooperation · Freizeit/Umwelt (integriert in LB1). Zusatz: **DSU** (Differenzierter Sportunterricht) + **SFU** (Sportförderunterricht) als Wahloptionen.',
      norm: 'LP+ Sport LB', status: 'open' },
    { id: 'P06', titel: 'Sicherheitserziehung — Kern-Anker',
      frage: 'Welche Sicherheits-Anker gelten für den Sportunterricht — und wer haftet?',
      antwort: '**Verbindlich**: amtliche **KMBek Sicherheits-Bestimmungen Schulsport** + Veröffentlichungen **KUVB** (Kommunale Unfallversicherung Bayern). **Besondere Qualifikationen**: **Schwimmen** = Rettungsschwimmer-Schein (DLRG/DRK Bronze); **Sportklettern** = Trainerschein C oder gleichwertige Qual. **Aufsichtspflicht**: gesamte Sportstunde + Wege Umkleide-Halle ({{§ 5 LDO}}). Bei Aufsichtspflichtverletzung mit Verletzungsfolge: § 229 StGB fahrl. KV + Disziplinar + Amtshaftung Freistaat (Cross-Ref Schulrecht MP_06 + MP_07).',
      norm: 'KMBek Sicherheit', status: 'open' },
    { id: 'P07', titel: 'Heterogenität + Differenzierung im Sport',
      frage: 'Wie wird Heterogenität im Sportunterricht didaktisch produktiv genutzt?',
      antwort: '**LP+-Grundsatz**: Heterogenität als **Chance**, nicht als Defizit. **Methodische Differenzierung**: (1) **Kleingruppen** (3-6 SuS) mit niveau-passenden Aufgaben. (2) **Individuelle Aufgabenstellungen** — SuS wählen Schwierigkeitsstufe. (3) **Material-Vielfalt** — verschiedene Bälle, Geräte, Höhen. (4) **Para-Sportarten** als Inklusions-Anker (Sitzvolleyball, Boccia). **Cross-Ref Mathe-Skript A.5**: 3-Niveaustufen-Logik gilt auch im Sport.',
      norm: 'LP+ Heterogenität', status: 'open' },
    { id: 'P08', titel: 'Bewegungslernen — drei Phasen (Meinel/Schnabel)',
      frage: 'Wie verläuft Bewegungslernen nach Meinel/Schnabel — und welche didaktische Konsequenz hat das?',
      antwort: '**Drei Phasen** (Meinel/Schnabel, Bewegungslehre): **(1) Grobkoordination** — Grundstruktur der Bewegung erlernen; viele Fehler, hoher Energieverbrauch. **(2) Feinkoordination** — Bewegung präziser, ökonomischer; weniger Fehler. **(3) Feinste Koordination + Anpassung** — automatisiert, situationsadaptiv. **Didaktische Konsequenz**: Reihenfolge in der UE-Sequenz von Grob zu Fein; visuelles Vorbild + Demonstration in Grobphase wichtig; Korrekturen erst in Feinphase. Cross-Ref Mathe EIS-Prinzip (parallele Stufenlogik).',
      norm: 'Meinel/Schnabel', status: 'open' },
    { id: 'P09', titel: '3-Phasen-Modell nach Hofmann (VERBINDLICH Bayern-Unterfranken)',
      frage: 'Welches Phasen-Modell ist verbindlich für eine Sport-UE in Bayern-Unterfranken?',
      antwort: '**3-Phasen-Modell nach HOFMANN, SR** (Bausteinskript SP GB Kap. 8, AG MS-Sem.-Unterfranken): **(1) Aufwärmphase** (8-10 min) mit Sub-Stufung **1.1 allgemeine Erwärmung** (HK-Aktivierung, mobilisierend) + **1.2 spezielle Erwärmung** (sportartspezifisch). **(2) Hauptphase/Erarbeitungsphase** (ca. 25 min) — Stundentypen Hofmann: Sammeln Bewegungserfahrung · Konditionsschulung · Neuerwerb · Üben+Festigen · Gestalten+Anwenden. **(3) Schlussteil/Ausklang** (5 min) mit Lernzielkontrolle. **WICHTIG**: NICHT als „7-Phasen-Söll" formulieren — Söll 2019 wird im Bausteinskript NICHT zitiert! Operative 7-Sub-Phasen-Feingliederung möglich als Verfeinerung (aus Aufwärm-Sub-Stufung + Meinel/Schnabel + UV-Empirie).',
      norm: 'Bausteinskript GB Hofmann', status: 'open' },
    { id: 'P10', titel: 'B7 · Leistungsbeurteilung + MSO § 15',
      frage: 'Wie wird im Sportunterricht der MS Bayern Leistung beurteilt — und was ist der Sport-Sonderstatus?',
      antwort: '**Sport ist KEIN Vorrückungsfach** ({{MSO § 15}} Abs. 2 S. 2 verbatim: „Vorrückungsfächer sind alle Pflicht- und Wahlpflichtfächer mit Ausnahme des Fachs Sport"). Trotzdem **Notengebungs-Pflicht**. **3-Achsen-Beurteilungsmodell** (Bausteinskript B7): **(a) Können** (körperliche Fähigkeiten · sportliche Fertigkeiten · Wissen) · **(b) Lernverhalten** (Lernbereitschaft · Leistungswille · soziale Verhaltensweisen) · **(c) Lernfortschritt** (Lern-/Leistungsfortschritt · relative Leistung). **LASPO-Empfehlung**: pro Schulhalbjahr **mind. 2 praktische LNW aus 2 sportlichen Handlungsfeldern + mind. 1 nicht-praktischer LNW**. **DSU-Note-Formel**: (BSU × 2 + DSU) : 3. Fetz 1996: Mitarbeit kann ±1 Grad verändern.',
      norm: 'MSO § 15 + Bausteinskript B7', status: 'open' },
    { id: 'P11', titel: '4 Methoden-Grundkonzeptionen (Hofmann GB Kap. 5)',
      frage: 'Welche vier Methoden-Grundkonzeptionen kennt die bayerische Sport-Didaktik nach Hofmann?',
      antwort: 'Zwei Achsen, die kombiniert werden. **Achse 1 induktiv ↔ deduktiv**: **Deduktiv** (normgeleitet) = direkte Bewegungsvorschrift, Demonstration, Vereinfachung, Schlüsselsequenzen, geschlossene Lehrwege vom Leichten zum Schweren. **Induktiv** (normsuchend) = SuS-Selbsttätigkeit, offene Bewegungsaufgaben (Funke „Differenzierte Erfahrungssituationen"), Erproben, brauchbare Lösungen demonstrieren. **Achse 2 analytisch-synthetisch ↔ ganzheitlich**: **Analytisch-synthetisch** = Teile isoliert üben, dann zur Gesamtbewegung zusammensetzen (unverzichtbar bei schwierigen Bewegungen, Risiko Zusatzbewegungen). **Ganzheitlich** = von Beginn an ganzheitlich, direkt ans Lernziel bei einfachen Bewegungen.',
      norm: 'Bausteinskript GB Hofmann', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: 'Doppelauftrag = Sport-Stunde halb Theorie, halb Praxis?', antwort: 'NEIN. Doppelauftrag ist eine **Bildungs-Doppelausrichtung** (Erziehung IM + DURCH Sport), keine Stundenstruktur. Beide Aufträge realisieren sich gleichzeitig in jeder Sportstunde — z.B. Volleyball gibt sportliche Bewegungserfahrung (IM) + Teamfähigkeit (DURCH).' },
    { id: 'FA02', frage: 'Pädagogische Perspektiven (Kurz) = 5 Stück?', antwort: 'NEIN — **6** Perspektiven: Eindruck · Ausdruck · Gesundheit · Wagnis · Leistung · Miteinander. Wer fünf nennt, hat eine vergessen. Mehrperspektivität = mehrere davon pro Sequenz adressieren.' },
    { id: 'FA03', frage: 'Mehrperspektivität = alle 6 Perspektiven pro Stunde?', antwort: 'NEIN. Mehrperspektivität bedeutet **mehrere** Perspektiven pro Sequenz/Inhalt — nicht zwingend alle 6 in einer Stunde. Verhindert Verengung auf eine einzige Sinnrichtung (z.B. nur Leistung).' },
    { id: 'FA04', frage: 'Sportlehrer braucht keine Zusatzqualifikation für Schwimmen?', antwort: 'NEIN — **Rettungsschwimmer-Schein Pflicht** (DLRG/DRK Bronze als Mindeststandard, regelmäßige Auffrischung). Bei Sportklettern: Trainerschein C oder gleichwertige Qualifikation. KMBek Sicherheits-Bestimmungen verbindlich.' },
    { id: 'FA05', frage: 'Wenn ein SuS sich verletzt, haftet die LK persönlich?', antwort: 'NEIN (Cross-Ref Schulrecht MP_07 Haftungsdreieck). Bei Aufsichtspflichtverletzung greift {{Art. 34 GG}} — **Freistaat haftet außen**. **Rückgriff** auf LK NUR bei Vorsatz oder grober Fahrlässigkeit. Bei verletzungs-relevanter Aufsichtspflichtverletzung zusätzlich § 229 StGB fahrl. KV persönlich.' },
    { id: 'FA06', frage: 'Kompetenzstrukturmodell Sport identisch mit Mathe?', antwort: 'NEIN. Sport: **4 prozessbez. × 4 Gegenstandsbereiche**. Mathe: **6 × 4**. WiB: **4 × 5**. Sk/GPG: andere Achsen. Sport-Achsen: Leisten/Gestalten/Spielen · Wahrnehmen-analysieren-bewerten · Entscheiden-handeln-verantworten · Kooperieren-kommunizieren-präsentieren × Sportliche Handlungsfelder/Gesundheit/Fairness/Freizeit-Umwelt.' },
    { id: 'FA07', frage: 'Heterogenität im Sport = Problem?', antwort: 'NEIN. LP+ sieht Heterogenität als **Chance** — Vielfalt fördert. Methodische Differenzierung (Kleingruppen, individuelle Aufgaben, Material-Vielfalt) als reguläre Methodik. Inklusion durch Para-Sportarten möglich.' },
    { id: 'FA08', frage: 'Bewegungslernen verläuft in zwei Phasen?', antwort: 'NEIN — **drei Phasen** (Meinel/Schnabel): Grobkoordination → Feinkoordination → feinste Koordination + Anpassung. Korrekturen erst in Feinphase ansetzen, nicht in Grobphase überfordern.' },
    { id: 'FA09', frage: '7-Phasen-Söll-Modell ist verbindlich für Bayern-Unterfranken?', antwort: 'NEIN. **Verbindlich ist 3-Phasen-Hofmann** (Bausteinskript SP GB Kap. 8). Söll 2019 wird im Bausteinskript NICHT zitiert. Die 7-Phasen-Detaillierung ist eine **operative Sub-Differenzierung** aus Aufwärm-Sub-Stufung + Meinel/Schnabel + UV-Empirie — als Verfeinerung verträglich, aber Rahmen-Begriff bleibt 3-Phasen-Hofmann.' },
    { id: 'FA10', frage: 'Sport ist ein Vorrückungsfach?', antwort: 'NEIN. **{{MSO § 15}}** Abs. 2 S. 2 verbatim: „Vorrückungsfächer sind alle Pflichtfächer und Wahlpflichtfächer mit Ausnahme des Fachs Sport." Trotzdem Notengebungs-Pflicht. Klassische Examens-Falle.' },
    { id: 'FA11', frage: 'Großtrampoline sind im Schulsport zulässig?', antwort: 'NEIN. **Bausteinskript B6 verbatim**: „Die Verwendung von Groß-Trampolinen ist nicht zulässig." Absolutes Verbot. Hintergrund: hohe Unfallwahrscheinlichkeit.' },
    { id: 'FA12', frage: 'BSU und DSU sind beide geschlechtsgetrennt?', antwort: 'NEIN. **BSU** (Basissportunterricht) wird in **geschlechtsgetrennten Sportklassen** unterrichtet. **DSU** (Differenzierter Sportunterricht) kann **koedukativ** erteilt werden (Schulleitungs-Entscheidung). M-/R-Anforderungsniveau wird NICHT extra ausgewiesen — LK differenziert selbst.' },
  ],

  faelle: [
    { id: 'F1', titel: 'Volleyball Jgst. 8 — Mehrperspektivität (Hauptfall)',
      sachverhalt: 'Sie planen eine 8-UE-Volleyball-Sequenz in der M8 Regelklasse. Wie realisieren Sie Mehrperspektivität nach Kurz?',
      knackpunkte: [
        '**Pädagogische Perspektiven aktivieren**: (E) Eindruck — Ball-Wahrnehmung, Antizipation des Flugverhaltens; (B) Ausdruck — Bewegungsgestaltung beim Pritschen, Baggern, Sprung-Schmetterschlag; (C) Gesundheit — Konditionsanteil, Sprungkraft, Ausdauer; (D) Wagnis — Hechtbagger, Sprung-Schmetterschlag in Höhe; (E) Leistung — individuelle und Team-Leistung messen, sich verbessern; (F) Miteinander — Kooperatives Mannschaftsspiel, faire Punktwertung, Sieg/Niederlage.',
        '**Kompetenzstrukturmodell**: Leisten/Gestalten/Spielen × Sportliche Handlungsfelder LB1 als Haupt-Tagging; Kooperieren-kommunizieren-präsentieren × Fairness/Kooperation als zweiter Schwerpunkt.',
        '**Differenzierung**: Kleingruppen 4-6 SuS mit niveau-passenden Aufgaben; Material-Vielfalt (weiche Bälle für Anfänger, Standard-Volleyball für Fortgeschrittene).',
        '**Bewegungslernen-Stufung** (Meinel/Schnabel): UE1-3 Grobkoordination Pritschen/Baggern → UE4-6 Feinkoordination + erste Spielsituationen → UE7-8 spielfähigkeits-orientiert.',
        '**Sicherheits-Anker**: Aufwärm-Phase strukturiert; Sicherheitsregeln am Netz (Verletzungs-Prophylaxe); KUVB-Konformität.',
        '**Reflexion**: SuS bewerten am Ende eigene Lernfortschritte + Team-Erfahrungen (Verschmelzung der Perspektiven Leistung + Miteinander).',
      ],
      antwortkette: 'LP+-Bezug Sport LB1 nennen → Doppelauftrag verbatim erläutern → 6 Perspektiven Kurz verbatim → konkret zeigen, welche Perspektiven die Sequenz adressiert → Bewegungslernen-Stufung Meinel/Schnabel → Differenzierungs-Strategie → Sicherheits-Anker → Reflexion.',
    },
    { id: 'F2', titel: 'Inklusion im Sport — SuS mit Förderbedarf körperl.-motor.',
      sachverhalt: 'In Ihrer M7-Klasse ist ein:e SuS mit Förderbedarf k.-m. Entwicklung (Rollstuhl). Wie inkludieren Sie im Sportunterricht?',
      knackpunkte: [
        '**Methodische Differenzierung** (LP+ Heterogenität): Aufgaben so anpassen, dass jede:r teilnehmen kann — z.B. Sitz-Volleyball, Boccia, Rollstuhl-Basketball.',
        '**Para-Sportarten als Vollwert-Angebot** (nicht „abgespeckte" Variante): SuS mit Rolli IS Vollwertspieler:in, Mitspielende lernen Spielregeln + Bewegungs-Anpassung.',
        '**Cross-Ref Schulrecht**: {{Art. 41 BayEUG}} Eltern entscheiden Lernort. {{Art. 30a/4 BayEUG}} — bei FS k.-m. Entwicklung **Sachaufwandsträger-Zustimmung erforderlich** (Cross-Ref MP_08 Hertha-Falle: bei FS gE NICHT, bei k.-m. JA).',
        '**Sicherheit**: bei körperlichen Einschränkungen besondere Gefährdungs-Beurteilung; ggf. zusätzliche Aufsichtsperson (Schulbegleiter:in).',
        '**Soziale Dimension**: Inklusion stärkt die **Miteinander-Perspektive** (Kurz F) — alle SuS profitieren.',
        '**Förderplan** {{MSO § 14}}: bei voraussichtl. Nicht-Erreichen der MS-Lernziele Pflicht (Cross-Ref Schulrecht MP_04 A.5).',
      ],
      antwortkette: 'LP+-Bezug Heterogenität als Chance → konkrete Methoden (Para-Sportarten, Sitz-Volleyball, Boccia) → Cross-Ref Schulrecht Art. 30a/4 + Art. 41 → Sicherheits-Aspekt → soziale Dimension Miteinander → Förderplan-Anker MSO § 14.',
    },
    { id: 'F3', titel: 'Sicherheits-Vorfall — Aufsichtspflicht beim Sportklettern',
      sachverhalt: 'Während Sie eine Sportklettern-AG in Jgst. 7 leiten, verletzt sich ein:e SuS beim Abseilen. Sie sind wegen eines Telefonats kurz aus der Halle gegangen. Eltern klagen.',
      knackpunkte: [
        '**Aufsichtspflichtverletzung** {{§ 5 LDO}} (Cross-Ref Schulrecht MP_06 A.2): Verlassen während gefährlicher Sportphase ohne notwendige Maßnahmen.',
        '**Sportklettern-Qualifikation**: KMBek Sicherheits-Bestimmungen verlangen **Trainerschein C** o.ä. — bei fehlender Qualifikation bereits SL-Verantwortung berührt.',
        '**Zivilrechtlich** (Cross-Ref MP_07 A.2): {{§ 839 BGB}} + {{Art. 34 GG}} → **Freistaat haftet außen**. Rückgriff auf LK NUR bei Vorsatz/grober Fahrlässigkeit.',
        '**Strafrechtlich**: § 229 StGB fahrl. KV — wenn Kausalität + Vorhersehbarkeit gegeben. **Persönlich** (Schuldprinzip).',
        '**Disziplinarrechtlich**: {{§ 47 BeamtStG}} + Art. 6 BayDG — Maßnahme nach Schwere (Verweis bis Kürzung Dienstbezüge).',
        '**Kumulativ**: alle drei Pfade laufen parallel (keine Doppelbestrafung wegen Art. 103/3 GG — Disziplinar ist Sonderrecht).',
      ],
      antwortkette: 'Aufsichtspflicht § 5 LDO verbatim → Sportklettern-Qualifikations-Anforderung → Haftungsdreieck Zivil/Disziplinar/Straf erläutern → Freistaat-Außenhaftung Art. 34 GG → § 229 StGB persönlich (wahrscheinl. grobe F. → Rückgriff) → BayDG-Maßnahme parallel.',
    },
    { id: 'F4', titel: 'Schwimm-Unterricht Jgst. 5 — Eingangsbedingungen + Sicherheit',
      sachverhalt: 'Sie übernehmen eine M5 Schwimm-Stunde im Hallenbad. Wie strukturieren Sie sicherheitstechnisch + didaktisch?',
      knackpunkte: [
        '**Eingangs-Voraussetzung LK**: **Rettungsschwimmer-Schein** Pflicht (DLRG/DRK Bronze; aktuell). KMBek Sicherheits-Bestimmungen verbindlich.',
        '**SuS-Eingangs-Status erheben**: Schwimm-Können (Seepferdchen, Bronze, Silber, Gold) — Differenzierung in Schwimmer/Nichtschwimmer-Gruppen.',
        '**Aufsichts-Verteilung**: Sichtkontakt zu allen SuS jederzeit; Auf-Becken-Rand-Aufstellung statt Schwimm-Lehre vom Wasser aus. Cross-Ref MP_06 § 5 LDO.',
        '**Pädagogische Perspektiven Kurz**: (A) Eindruck — Wasser-Wahrnehmung; (D) Wagnis — Sprung vom Beckenrand; (C) Gesundheit — Ausdauer; (F) Miteinander — Schwimmpartner-Aufgaben.',
        '**Bewegungslernen Meinel/Schnabel**: bei Nichtschwimmern Grobkoordination Wasser-Gewöhnung → Auftrieb → einfache Schwimm-Antriebe; Korrekturen erst in Feinkoordinations-Phase.',
        '**Erste-Hilfe-Bereitschaft**: Standort Rettungsring, Notfall-Telefon, Bademeister:in (falls vor Ort).',
      ],
      antwortkette: 'Rettungsschwimmer-Schein als Pflicht-Voraussetzung → SuS-Status-Differenzierung → Aufsichts-Logik § 5 LDO → Pädagogische Perspektiven (Kurz) für die Stunde aktivieren → Bewegungslernen-Stufung → Erste-Hilfe-Anker.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'Doppelauftrag + Kompetenzstrukturmodell Sport',
      anriss: 'LP+ Bayern: Erziehung IM Sport (Bewegungsvielfalt, Leistungsfähigkeit) + Erziehung DURCH Sport (Fairness, Teamgeist). 4 prozessbez. × 4 Gegenstandsbereiche.',
      norm: 'LP+ Fachprofil Sport', status: 'open', cards: 2,
      subblocks: [{ label: 'Doppelauftrag IM + DURCH Sport', cards: 1 }, { label: 'Kompetenzstrukturmodell Sport — 4 × 4', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'Pädagogische Perspektiven (Kurz) + Mehrperspektivität',
      anriss: 'Sechs Sinnrichtungen sportlichen Handelns (Eindruck · Ausdruck · Gesundheit · Wagnis · Leistung · Miteinander). Mehrperspektivität als didaktisches Leitprinzip.',
      norm: 'Kurz', status: 'open', cards: 3,
      subblocks: [{ label: '6 Perspektiven verbatim (Kurz)', cards: 1 }, { label: 'Mehrperspektivität als Leitprinzip', cards: 1 }, { label: 'Praxis-Beispiel Mehrperspektivität (Volleyball)', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: 'Lernbereiche + Sportarten-Felder + Bewegungslernen',
      anriss: 'LP+ LB1 Sportliche Handlungsfelder (Leichtathletik · Schwimmen · Spiele · Turnen · Tanz · Wintersport). Meinel/Schnabel 3-Phasen-Bewegungslernen. DSU + SFU.',
      norm: 'LP+ Sport LB', status: 'open', cards: 3,
      subblocks: [{ label: 'LB1-LB4 Übersicht', cards: 1 }, { label: 'Bewegungslernen 3 Phasen (Meinel/Schnabel)', cards: 1 }, { label: 'DSU + SFU als Wahloptionen', cards: 1 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Sicherheitserziehung + Aufsichtspflicht (Cross-Ref Schulrecht)',
      anriss: 'KMBek Sicherheits-Bestimmungen + KUVB. Schwimm-/Sportklettern-Qualifikationen. § 5 LDO Aufsichtspflicht. Bei Verletzung: Haftungsdreieck MP_07.',
      norm: 'KMBek Sicherheit', status: 'open', cards: 3,
      subblocks: [{ label: 'Sicherheits-Bestimmungen + Qualifikationen', cards: 1 }, { label: 'Aufsichtspflicht § 5 LDO + Wege Umkleide-Halle', cards: 1 }, { label: 'Haftungsachsen bei Verletzung (Cross-Ref MP_07)', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'Heterogenität + Inklusion + Differenzierung',
      anriss: 'LP+ sieht Heterogenität als Chance. Methodische Differenzierung in Kleingruppen + individuelle Aufgaben. Inklusion durch Para-Sportarten. Cross-Ref MP_08 Lernort.',
      norm: 'LP+ Heterogenität', status: 'open', cards: 3,
      subblocks: [{ label: 'Heterogenität als Chance', cards: 1 }, { label: 'Methodische Differenzierung 4 Wege', cards: 1 }, { label: 'Inklusion + Para-Sportarten + MP_08-Anker', cards: 1 }],
    },
    { id: 'A6', kuerzel: 'A.6', titel: 'Bayern-Unterfranken-Bausteinskript (Hofmann SR) — verbindliche Diktion',
      anriss: '3-Phasen-Modell GB Kap. 8 (Aufwärm/Haupt/Ausklang mit Sub-Stufung) + 4 Methoden-Grundkonzeptionen (deduktiv/induktiv × analytisch-synthetisch/ganzheitlich) + 7 Intensivierungs-Wege + 6 Merkmale guten SU + B7-Leistungsbeurteilung (3-Achsen + LASPO + MSO § 15 Sport-Nicht-Vorrückungsfach) + B6-Sicherheit (Großtrampoline verboten).',
      norm: 'Bausteinskript GB Hofmann', status: 'open', cards: 4,
      subblocks: [{ label: '3-Phasen-Hofmann mit Sub-Stufung', cards: 1 }, { label: '4 Methoden-Grundkonzeptionen + 7 Intensivierung + 6 Merkmale', cards: 1 }, { label: 'B7 Leistung + MSO § 15 + LASPO + DSU-Formel', cards: 1 }, { label: 'B6 Sicherheit konkret (Großtrampoline · Schmuck · Brille · Sicht-/Funktionsprüfung)', cards: 1 }],
    },
  ],

  glossar: {
    'BV Art. 131': { titel: 'BV Art. 131 — Bildungsziele', wortlaut: 'Bayerischer Bildungsauftrag mit Werte-Boden auch für Sport: Achtung der Würde des Menschen, Verantwortungsbewusstsein, Hilfsbereitschaft. Cross-Ref Erziehung durch Sport (Fairness, Teamgeist).', karten: [] },
    'GG Art. 2/2': { titel: 'GG Art. 2 Abs. 2 — körperliche Unversehrtheit', wortlaut: '„Jeder hat das Recht auf Leben und körperliche Unversehrtheit." Verfassungsrechtlicher Anker für **Sicherheitserziehung** im Schulsport: die Schule darf SuS keiner unverhältnismäßigen Verletzungsgefahr aussetzen. Cross-Ref Schulrecht MP_06 § 5 LDO + MP_07 § 229 StGB.', karten: [] },
    'LP+ Fachprofil Sport': { titel: 'LP+ Fachprofil Sport MS Bayern', wortlaut: '**Doppelauftrag**: (a) Erziehung **IM** Sport — SuS entwickeln „Freude und Interesse an der Vielfalt sportlicher Bewegungsformen sowie das Bedürfnis nach regelmäßiger sportlicher Aktivität" + erleben körperliche Leistungsfähigkeit. (b) Erziehung **DURCH** Sport — „Kooperationsfähigkeit, Fairness, Teamgeist, Rücksichtnahme, der Umgang mit Sieg und Niederlage". Quelle: lehrplanplus.bayern.de.', karten: ['P01', 'P02'] },
    'LP+ Sport LB': { titel: 'LP+ Lernbereiche Sport MS', wortlaut: 'Lernbereich-Struktur: **LB1 Sportliche Handlungsfelder** (zentral) — Leichtathletik · Schwimmen · Spiele (Mannschaft + Rückschlag) · Turnen · Tanz/Gymnastik · Wintersport. **LB2-LB4** Gesundheit und Fitness · Fairness/Kooperation/Selbstkompetenz · Freizeit und Umwelt (integriert in LB1). Zusatz: **DSU** (Differenzierter Sportunterricht) + **SFU** (Sportförderunterricht) als Wahloptionen.', karten: ['P05'] },
    'LP+ Heterogenität': { titel: 'LP+ Sport — Heterogenität als Chance', wortlaut: '„Heterogenität wird als förderlich für Vielfalt genutzt." **Methodische Differenzierung** in Kleingruppen oder individuelle Aufgabenstellung. **Inklusion**: Para-Sportarten als Vollwert-Angebot (Sitzvolleyball, Boccia, Rollstuhl-Basketball). Material-Vielfalt + Schwierigkeits-Stufen.', karten: ['P07'] },
    'Kurz': { titel: '6 Pädagogische Perspektiven (Dietrich Kurz · ergänzend)', wortlaut: '**Sechs Sinnrichtungen** sportlichen Handelns (Kurz 1990 ff.): **(A) Eindruck** — Wahrnehmungsfähigkeit verbessern, Bewegungserfahrungen erweitern. **(B) Ausdruck** — sich körperlich ausdrücken, Bewegungen gestalten. **(C) Gesundheit** — Fitness verbessern, Gesundheitsbewusstsein entwickeln. **(D) Wagnis** — etwas wagen und verantworten. **(E) Leistung** — Leistung erfahren und reflektieren. **(F) Miteinander** — gemeinsam handeln, sich messen, sich verstehen. **Mehrperspektivität** = mehrere Perspektiven pro Sequenz adressieren. **WICHTIG**: Kurz ist NRW-/Bundes-Tradition. Im **Bayern-Unterfranken-Bausteinskript Hofmann SR ist Kurz NICHT zentral zitiert** — Bayern arbeitet mit Kompetenzstrukturmodell (4 prozessbez. × 4 Gegenstandsbereiche) + sportlichen Handlungsfeldern. Im Examen Kurz als ergänzender Theorie-Anker, NICHT als „Bayern-Verbindlichkeit".', karten: ['P03', 'P04'] },
    'Meinel/Schnabel': { titel: 'Bewegungslernen — 3 Phasen (Meinel/Schnabel)', wortlaut: '**Kurt Meinel + Günter Schnabel**, „Bewegungslehre — Sportmotorik" (Klassiker, seit 1962). **Drei Phasen**: (1) **Grobkoordination** — Grundstruktur erlernen; viele Fehler, hoher Energieverbrauch, visuelles Vorbild zentral. (2) **Feinkoordination** — präziser, ökonomischer; Korrekturen ansetzen. (3) **Feinste Koordination + Anpassung** — automatisiert, situationsadaptiv. **Didaktische Konsequenz**: in der UE-Sequenz von Grob zu Fein; Korrekturen erst in Feinphase, nicht in Grobphase überfordern.', karten: ['P08'] },
    'KMBek Sicherheit': { titel: 'KMBek Sicherheits-Bestimmungen Schulsport Bayern', wortlaut: 'Verbindlicher Sicherheits-Rahmen für den Schulsport in Bayern + Veröffentlichungen der **KUVB** (Kommunale Unfallversicherung Bayern). **Besondere Qualifikationen**: Schwimmen = **Rettungsschwimmer-Schein** (DLRG/DRK Bronze) Pflicht; Sportklettern = Trainerschein C o.ä. Pflicht. **Aufsichtspflicht** während gesamter Sport-Stunde + Wege Umkleide-Halle nach {{§ 5 LDO}}. Bei Aufsichtspflichtverletzung mit Verletzungsfolge: § 229 StGB fahrl. KV + Disziplinar + Amtshaftung (Cross-Ref Schulrecht MP_06 + MP_07).', karten: ['P06'] },
    '§ 5 LDO': { titel: '§ 5 LDO — Aufsichtspflicht (Cross-Ref Schulrecht MP_06)', wortlaut: 'Vollzitat in Schulrecht-V3 MP_06 A.2. Im Sportunterricht relevant: Aufsichtspflicht **gesamte Sport-Stunde + Wege Umkleide-Halle** + bei besonders gefährlichen Sportphasen (Klettern, Schwimmen, Turnen Großgeräte) erhöhte Aufmerksamkeit. Bei Verletzungsfolge: § 229 StGB fahrl. KV möglich.', karten: ['P06'] },
    'Art. 41 BayEUG': { titel: 'Art. 41 BayEUG — Lernort (Cross-Ref Schulrecht MP_08)', wortlaut: 'Cross-Ref Schulrecht-V3 MP_08 A.2. Im Sport relevant: **Eltern entscheiden Lernort**. Bei SuS mit FS k.-m. Entwicklung + Inklusion in Regelschule = **Sachaufwandsträger-Zustimmung erforderlich** ({{Art. 30a/4 BayEUG}}). Bei FS gE: Sachaufwandsträger-Zustimmung NICHT erforderlich (Hertha-Falle).', karten: [] },
    'Art. 30a/4 BayEUG': { titel: 'Art. 30a/4 BayEUG — Sachaufwandsträger-Zustimmung', wortlaut: 'Cross-Ref Schulrecht-V3 MP_08 A.2. Sachaufwandsträger-Zustimmung erforderlich für Inklusion in Regelschule **NUR** bei Förderschwerpunkten **Sehen / Hören / körperlich-motorische Entwicklung**. Bei anderen Schwerpunkten NICHT.', karten: [] },
    'Art. 34 GG': { titel: 'Art. 34 GG — Staatshaftung (Cross-Ref Schulrecht MP_07)', wortlaut: 'Cross-Ref Schulrecht-V3 MP_07 A.2. Bei Aufsichtspflichtverletzung im Sport: **Freistaat haftet außen** (Art. 34 GG S. 1). Rückgriff Freistaat → LK NUR bei **Vorsatz oder grober Fahrlässigkeit** (Art. 34 GG S. 2). Bei Sportkletter-Aufsichtsversagen: typisch grobe Fahrlässigkeit → Rückgriff möglich.', karten: [] },
    '§ 839 BGB': { titel: '§ 839 BGB — Beamtenhaftung (Cross-Ref Schulrecht MP_07)', wortlaut: 'Cross-Ref Schulrecht-V3 MP_07 A.2. Anspruchsgrundlage für Schadensersatz bei Amtspflichtverletzung. I.V.m. {{Art. 34 GG}} → Staatshaftung mit Rückgriff bei Vorsatz/grober Fahrlässigkeit.', karten: [] },
    '§ 47 BeamtStG': { titel: '§ 47 BeamtStG — Dienstvergehen (Cross-Ref Schulrecht MP_07)', wortlaut: 'Cross-Ref Schulrecht-V3 MP_07 A.3. Bei Aufsichtspflichtverletzung im Sport: schuldhafte Pflichtverletzung → Dienstvergehen-Tatbestand → Maßnahmen-Katalog Art. 6 BayDG.', karten: [] },
    'MSO § 14': { titel: 'MSO § 14 — Individueller Förderplan (Cross-Ref Schulrecht MP_04)', wortlaut: 'Cross-Ref Schulrecht-V3 MP_04 A.5. Bei voraussichtl. Nicht-Erreichen der MS-Lernziele wegen sonderpäd. Förderbedarfs: Förderplan-Pflicht. MSD-Einbeziehung Pflicht, jährlich fortzuschreiben. Gilt auch im Sport-Kontext bei Inklusion.', karten: [] },
    'MSO § 15': { titel: 'MSO § 15 Abs. 2 S. 2 — Sport ist KEIN Vorrückungsfach', wortlaut: 'Verbatim: „Vorrückungsfächer sind alle Pflichtfächer und Wahlpflichtfächer **mit Ausnahme des Fachs Sport**." Die Sportnote wird zwar erteilt (Notengebungs-Pflicht), kann aber NICHT zur Nicht-Vorrückung führen. Klassische Examens-Falle. Cross-Ref Schulrecht MP_04.', karten: ['P10'] },
    'Bausteinskript GB Hofmann': { titel: 'SP GB Grundsätze — Bausteinskript Bayern-Unterfranken (Hofmann SR)', wortlaut: '**Verbindliche Diktion** für Bayern-Unterfranken-MS-LAA (AG MS-Seminarleiter:innen Unterfranken · Dieter Hofmann, SR). 8 Kapitel: (1) Ziele/Aufgaben — Bedürfnis nach regelmäßiger sportl. Aktivität wecken · (2) Hinweise zum Unterricht — BSU geschlechtsgetrennt/DSU koedukativ möglich · (3) Kompetenzstrukturmodell · (4) Fachlehrplan-Aufbau · (5) **4 Methoden-Grundkonzeptionen** (deduktiv/induktiv × analytisch-synth/ganzheitlich) · (6) Differenzierung + **7 Intensivierungs-Wege** · (7) **6 Merkmale für „guten" Sportunterricht** (AK Sport 2011) · (8) **3-Phasen-Strukturmodell** (Aufwärm/Haupt/Ausklang). Söll 2019 wird NICHT zitiert. Lokal: Unterrichtseinwicklung/Repsitory Unterrichtsmaterial/Sport Ressourcen/Sport_Bausteinskripte/.', karten: ['P09', 'P11'] },
    'Bausteinskript B7 Hofmann': { titel: 'SP B7 Leistungsmessung — Bausteinskript Bayern-Unterfranken', wortlaut: '**3-Achsen-Beurteilungsmodell**: (a) Können (körperliche Fähigkeiten · sportliche Fertigkeiten · Wissen) · (b) Lernverhalten (Lernbereitschaft · Leistungswille · soziale Verhaltensweisen) · (c) Lernfortschritt (Lern-/Leistungsfortschritt · relative Leistung auf anthropogene Voraussetzungen). **LASPO-Empfehlung** (Bayer. Landesstelle Schulsport): pro Schulhalbjahr mind. 2 praktische LNW aus 2 sportlichen Handlungsfeldern + mind. 1 nicht-praktischer LNW. Gesamtnote = gerundeter Mittelwert aller praktischen + nicht-praktischen LNW. **DSU-Note-Formel**: (BSU × 2 + DSU) : 3. Theoretiker: Fetz 1996 (Mitarbeit ±1 Grad) · Größing · Erdmann · Miethling.', karten: ['P10'] },
    'Bausteinskript B6 Hofmann': { titel: 'SP B6 Sicherheit — Bausteinskript Bayern-Unterfranken', wortlaut: '5 Kap.: (1) Vorbemerkung · (2) Sportstätten + Geräte · (3) Kleidung + Ausrüstung · (4) Organisation + Aufsicht · (5) Inhalte. **Verbote/Pflichten verbatim**: „Die Verwendung von Groß-Trampolinen ist nicht zulässig." · Schmuck/Piercings/Uhren grundsätzlich vor Beginn ablegen · schulsportgerechte Brille oder Kontaktlinsen · LK betritt als Erste:r/verlässt als Letzte:r · Sicht- + Funktionsprüfung Geräte vor Verwendung · jährliche Wartung durch Sachkundige · während Geräte-Auf-/Abbau absolutes Übungsverbot · optische + akustische Verständigungszeichen · Sicherheitsabstand zu Wänden/Geräten/Mitschülern · Hallenboden frei von Nässe.', karten: ['P06'] },
  },
};
