// MP_06 — Rechte und Pflichten der Lehrkräfte
window.MODULE = {
  id: 'mp06',
  zalgm: 'ZALGM § 16 Nr. 6',
  schwerpunkt: ['6.1 Doppelstruktur', '6.2 Aufsicht (HF)', '6.3 Schriftwesen', '6.4 Fortbildung', '6.5 Personalvertretung'],
  titel: 'Rechte + Pflichten',
  titel2: 'der Lehrkräfte.',
  abriss:
    'Doppelstruktur Beamten- + Schul-Säule. Aufsichtspflicht als Hochfrequenz-Thema. ' +
    'Haftungsdreieck zivil/disziplinar/strafrecht. Auskunfts-Trias § 14 LDO. ' +
    'Fortbildung 12 Tage/4 J. Streikverbot.',

  kurz: [
    'Doppelstruktur: Beamten-Säule (BayBG/BeamtStG: Treue, Verschwiegenheit, Weisungsbindung) + Schul-Säule (LDO/BayEUG: Unterricht, Erziehung, Aufsicht, Beratung, KL, Fortbildung).',
    'Aufsichtspflicht § 5 LDO + § 22 BaySchO + Art. 57/2 BayEUG: vor U. (GS+FöS 15 Min) · während · nach (bis Weggang) · Pausen · Mittagspause · Wandertage.',
    'Haftungsdreieck: Zivil/Amtshaftung Art. 34 GG → Freistaat haftet, Rückgriff auf LK NUR bei Vorsatz + grober Fahrlässigkeit · Disziplinar BayDG 5+2 Stufen · Strafrecht persönlich.',
    'Auskunfts-/Verschwiegenheits-Trias § 14 LDO: Verschwiegenheit (post-dienstlich) · Presse-Hoheit SL · Drittauskunfts-Verbot — KEIN „Notengeheimnis" ggü. SuS/EB.',
    'Fortbildung § 9a/2 LDO + Art. 20 BayLBG: 12 Tage / 4 Jahre, mind. 1/3 SchiLF. Personalvertretung BayPVG: Mitbestimmung ≠ Mitwirkung. Beamte: KEIN Streikrecht (GG Art. 33/5).',
  ],

  deck: { cards: 8, normebenen: 5, hochprior: 8, fallen: 10 },

  kartografie: [
    { ebene: 'I', bez: 'Bayerische Verfassung', kuerzel: 'BV', normen: ['Art. 95 BV', 'Art. 136 BV'], sub: 'Beamtenverhältnis · ReliU' },
    { ebene: 'II', bez: 'BayEUG', kuerzel: 'BayEUG', normen: ['Art. 56/4', 'Art. 57/2', 'Art. 58', 'Art. 59', 'Art. 60a', 'Art. 75', 'Art. 84'], sub: 'SL-Verantwortung · Lehrkräfte · LK-Konferenz · EB-Auskunft · Werbeverbot' },
    { ebene: 'III', bez: 'LDO + BaySchO', kuerzel: 'VO', normen: ['§ 2 LDO', '§ 4 LDO', '§ 5 LDO', '§ 6 LDO', '§ 9a LDO', '§ 9b LDO', '§ 14 LDO', '§ 22 BaySchO'], sub: 'U.+Erz. · Wandertage · Aufsicht · KL · Dienstpflichten · Verschwiegenheit' },
    { ebene: 'IV', bez: 'Beamten-/Personalvertretungsrecht', kuerzel: 'BB', normen: ['Art. 6 BayDG', 'Art. 20 BayLBG', 'Art. 75 BayPVG', 'Art. 76 BayPVG'], sub: 'Disziplinar · Fortbildung · Personalvertretung · Mitbestimmung' },
    { ebene: 'V', bez: 'Bundesrecht', kuerzel: 'BUND', normen: ['Art. 33/5 GG', 'Art. 34 GG', '§ 47 BeamtStG', '§ 839 BGB', '§ 203 StGB'], sub: 'Berufsbeamtentum · Amtshaftung · Dienstvergehen · Berufsgeheimnis' },
  ],

  pflichtwissen: [
    { id: 'L01', titel: 'Doppelstruktur LK-Pflichten',
      frage: 'Welche zwei Säulen tragen die LK-Pflichten — und welche Pflicht steht in BEIDEN?',
      antwort: 'Beamten-Säule (BayBG/BeamtStG: Dienstleistung, Treue, Verschwiegenheit, Weisung, Annahmeverbot). Schul-Säule (LDO/BayEUG: Unterricht, Erziehung, Aufsicht, Beratung, KL, Konferenz, Wandertage, Fortbildung). Quer in beiden Säulen: Verschwiegenheit / Vertraulichkeit (§ 37 BeamtStG ↔ § 14 LDO).',
      norm: '§ 9a LDO', status: 'open' },
    { id: 'L02', titel: '§ 5 LDO Aufsichts-Schlüsselsatz',
      frage: 'Welche Reichweite hat die LK-Aufsicht laut § 5 LDO Wortlaut?',
      antwort: 'Verbatim S. 2: „Insbesondere hat die LK spätestens von Beginn des Unterrichts an im Unterrichtsraum anwesend zu sein und von diesem Zeitpunkt an während der gesamten Dauer des von ihr erteilten Unterrichts, erforderlichenfalls bis zum Weggang der SuS, die Aufsicht zu führen." Erforderlichenfalls = ggf. über Stundenende hinaus.',
      norm: '§ 5 LDO', status: 'open' },
    { id: 'L03', titel: '§ 22 BaySchO Vor-/Nach-U.',
      frage: 'Welche Zeit vor + nach Unterricht ist von der Aufsicht erfasst?',
      antwort: '§ 22/1 BaySchO: U.-Zeit + sonstige Schulveranstaltungen + „angemessene Zeit vor Beginn und nach Beendigung". An GS + GS-Stufe FöS: 15 Min vor + bis zum Verlassen des Schulgeländes nach. Bei Bedarf: halbe Stunde vor U.-Beginn. § 22/2 — Umfang nach geistiger/charakterlicher Reife.',
      norm: '§ 22 BaySchO', status: 'open' },
    { id: 'L04', titel: 'Haftungsdreieck',
      frage: 'Welche drei Haftungsschienen treffen die LK — und wer haftet wann?',
      antwort: 'Zivil/Amtshaftung (§ 839 BGB i.V.m. Art. 34 GG): Freistaat haftet nach AUßEN, Rückgriff auf LK NUR bei Vorsatz + grober Fahrlässigkeit. Disziplinar (BayDG Art. 6 ff.): 5 Stufen Lebenszeitbeamte + 2 Ruhestand. Strafrecht (StGB): persönlich (KV/fahrl. Tötung/§ 203 Berufsgeheimnis).',
      norm: 'Art. 34 GG', status: 'open' },
    { id: 'L05', titel: '§ 14 LDO Drei Bereiche',
      frage: 'Welche drei Auskunfts-/Verschwiegenheitsbereiche unterscheidet § 14 LDO?',
      antwort: '(1) Verschwiegenheit über dienstlich bekannte Angelegenheiten (post-dienstlich fortwirkend). (2) Presse-/Öffentlichkeitsauskunft NUR durch SL. (3) Drittauskunfts-Verbot ggü. Personen, die nicht zum SuS-Verhältnis gehören. → KEIN „Notengeheimnis" ggü. eigenen SuS/EB; aber kein VERGLEICHENDER Bezug auf andere SuS namentlich.',
      norm: '§ 14 LDO', status: 'open' },
    { id: 'L06', titel: 'Fortbildungspflicht',
      frage: 'Welcher Umfang gilt für die LK-Fortbildung — und welcher Anteil ist SchiLF?',
      antwort: 'Art. 20 BayLBG + § 9a/2 LDO + KMBek 09.08.2002 (Anpassung 08.2025): 12 Fortbildungstage / 4 Jahre (≈ 60 h), davon mind. 1/3 Schulinterne Lehrerfortbildung (SchiLF). Selbst-Fortbildung + dienstliche Fortbildung.',
      norm: '§ 9a LDO', status: 'open' },
    { id: 'L07', titel: 'Mitbestimmung ↔ Mitwirkung',
      frage: 'Wo verläuft die Grenze zwischen Mitbestimmung und Mitwirkung im BayPVG?',
      antwort: 'Mitbestimmung (Art. 75 BayPVG) = ZUSTIMMUNGSPFLICHT der Personalvertretung; ohne Zustimmung Maßnahme unwirksam. Mitwirkung (Art. 76 BayPVG) = geringere Beteiligungsstufe — Stellungnahme, aber Dienststelle entscheidet. Wichtig für Versetzungen, Einstellungen, Beförderungen.',
      norm: 'Art. 75 BayPVG', status: 'open' },
    { id: 'L08', titel: 'Streikverbot Beamte',
      frage: 'Warum dürfen verbeamtete LK nicht streiken — und welche Rechte haben sie?',
      antwort: 'Streikverbot folgt aus „hergebrachten Grundsätzen des Berufsbeamtentums" (GG Art. 33/5) — Treuepflicht + Alimentationsprinzip kompensieren. Beamte haben Vereinigungs-/Gewerkschafts-Recht (Art. 9/3 GG), aber kein Streikrecht. BVerfG-Rechtsprechung bestätigt. Tarifbeschäftigte LK dürfen streiken.',
      norm: 'Art. 33/5 GG', status: 'open' },
  ],

  fallen: [
    { id: 'FA01', frage: 'Beamtenrecht und Schulrecht sind getrennte Pflichtensysteme?', antwort: 'NEIN. Doppelstruktur — beide gelten kumulativ. Verschwiegenheit (§ 37 BeamtStG ↔ § 14 LDO) liegt in beiden Säulen.' },
    { id: 'FA02', frage: 'LK haftet immer persönlich bei Aufsichtsversagen?', antwort: 'NEIN. Art. 34 GG: Freistaat haftet nach außen. Rückgriff auf LK NUR bei Vorsatz + GROBER Fahrlässigkeit. Bei einfacher Fahrlässigkeit kein Rückgriff.' },
    { id: 'FA03', frage: 'Aufsicht endet mit der letzten U.-Stunde?', antwort: 'NEIN. § 5/1 LDO: „erforderlichenfalls bis zum Weggang der SuS" — geht ggf. über Stundenende hinaus. Plus § 22/1 BaySchO „angemessene Zeit nach Beendigung".' },
    { id: 'FA04', frage: 'Aufsicht gilt auch für den Schulweg?', antwort: 'NEIN. Schulweg = Eltern-Verantwortung. ABER Schulbus + Wartezeiten = Gemeinde/Schulverband (Aufwandsträger), NICHT Schule.' },
    { id: 'FA05', frage: '„Notengeheimnis" verbietet Auskunft an Eltern?', antwort: 'NEIN. § 14 LDO normiert Verschwiegenheit ggü. Dritten, KEIN Notengeheimnis ggü. eigenen SuS/EB. Aber kein VERGLEICHENDER Bezug auf andere SuS namentlich (Lara-Note geht andere Eltern nichts an).' },
    { id: 'FA06', frage: 'Pressekontakt durch jede LK möglich?', antwort: 'NEIN. § 14 LDO: Presse-/Öffentlichkeits-Auskunft NUR durch Schulleitung. LK darf nicht selbständig zu Schulthemen öffentlich Stellung nehmen.' },
    { id: 'FA07', frage: 'Fortbildungspflicht erfüllt mit beliebigen Veranstaltungen?', antwort: 'TEILWEISE. Mindestens 1/3 muss SchiLF (Schulinterne Lehrerfortbildung) sein — kollektive Schulentwicklung wird priorisiert. 12 Tage / 4 Jahre Gesamt.' },
    { id: 'FA08', frage: 'Symbol-Verbot Art. 59/2 ist absolut?', antwort: 'NEIN. Art. 59/2 S. 4: konditional — verboten, „sofern Symbole bei SuS/Eltern auch als Ausdruck einer Haltung verstanden werden können, die mit verfassungsrechtlichen Grundwerten + christlich-abendländischen Bildungs-/Kulturwerten nicht vereinbar ist". Einzelfall-Bewertung.' },
    { id: 'FA09', frage: 'Mitbestimmung = Mitwirkung?', antwort: 'NEIN. Mitbestimmung (BayPVG Art. 75) = Zustimmungspflicht. Mitwirkung (Art. 76) = Stellungnahme ohne Vetorecht. Zwei verschiedene Beteiligungsstufen.' },
    { id: 'FA10', frage: 'Beamte dürfen streiken, wenn die Gewerkschaft aufruft?', antwort: 'NEIN. GG Art. 33/5 hergebrachte Grundsätze — Treuepflicht schließt Streik aus. Vereinigungs-/Gewerkschafts-Recht (Art. 9/3 GG) bleibt, aber Streik ist Dienstvergehen.' },
  ],

  faelle: [
    { id: 'F1', titel: 'Aufsichtsversagen mit Verletzung — Haftungsdreieck',
      sachverhalt: 'Während des Sportunterrichts verlässt LK den Raum für einen Telefonanruf. In ihrer Abwesenheit verletzt sich ein Schüler beim Klettern schwer. Eltern fordern Schadensersatz.',
      knackpunkte: [
        '§ 5/1 LDO: LK darf U.-Raum nur in Ausnahmefällen verlassen, dann notwendige + mögliche Maßnahmen (z.B. SL/Kollege übernimmt). Hier verletzt.',
        'Zivil/Amtshaftung: Art. 34 GG → Freistaat haftet nach AUßEN. Eltern verklagen Freistaat.',
        'Rückgriff auf LK NUR bei Vorsatz + grober Fahrlässigkeit. Hier: Telefonanruf während Sportkletter-Phase = wahrscheinlich grobe Fahrlässigkeit → Rückgriff möglich.',
        'Disziplinar BayDG: separater Pfad, Verweis bis Entlassung je nach Schwere.',
        'Strafrecht: fahrl. KV (§ 229 StGB) persönlich, wenn Kausalität + Vorhersehbarkeit.',
      ],
      antwortkette: 'Aufsichtspflicht-Verletzung § 5/1 LDO → Freistaat-Außenhaftung Art. 34 GG → Rückgriff bei grober Fahrlässigkeit → Disziplinar BayDG parallel → ggf. fahrl. KV strafrechtlich persönlich.',
    },
    { id: 'F2', titel: 'Notenauskunft an EB mit Vergleich',
      sachverhalt: 'EB von Tim fragt im Elterngespräch: „Wie hat denn Lara abgeschnitten? Mein Tim hat doch genauso lange gelernt!"',
      knackpunkte: [
        '§ 14 LDO Drittauskunfts-Verbot: Auskunft über DRITTE SuS unzulässig.',
        'Eigene Tim-Note: Auskunft regulär (Art. 56/2 BayEUG Nr. 4 i.V.m. Art. 52/1 — Cross-Ref MP_05 A.3).',
        'Lara-Note geht andere Eltern nichts an — auch nicht „nur kurz vergleichend".',
        'KEIN „Notengeheimnis" ggü. eigenen EB — aber kein VERGLEICHENDER Bezug auf Dritte. Cross-Ref MP_05 Hannah-Fall.',
      ],
      antwortkette: 'Tim-Notenauskunft regulär gewähren → Lara-Frage höflich-bestimmt zurückweisen mit Verweis auf Daten Dritter → Drittauskunfts-Schranke § 14 LDO begründen.',
    },
    { id: 'F3', titel: 'Symbol im Unterricht (Kopftuch/Kreuz)',
      sachverhalt: 'Eine LK trägt im Unterricht ein Symbol (z.B. großes Kreuz). Eltern beschweren sich, das Symbol vermittle eine bestimmte Haltung.',
      knackpunkte: [
        'Art. 59/2 S. 4 BayEUG: Symbol-Verbot KONDITIONAL — „sofern bei SuS/Eltern auch als Ausdruck einer Haltung verstanden werden können, die mit verfassungsrechtlichen Grundwerten + christlich-abendländischen Bildungs-/Kulturwerten nicht vereinbar ist".',
        'Einzelfall-Bewertung erforderlich. Kein automatisches Verbot.',
        'Art. 84 Abs. 2: politische Werbung untersagt — Symbol-Verbot bleibt davon unberührt.',
        'Beschwerde-Weg Art. 56/2 Nr. 5 BayEUG (SuS) / Art. 76 (Eltern).',
      ],
      antwortkette: 'Art. 59/2 S. 4 BayEUG konditionales Symbol-Verbot prüfen → Einzelfall-Bewertung (verstehen SuS/Eltern als Haltung?) → SL-Gespräch → Beschwerdeweg formal.',
    },
    { id: 'F4', titel: 'Streik-Aufruf der Gewerkschaft',
      sachverhalt: 'Die GEW ruft alle LK zum Warnstreik auf. Eine verbeamtete LK fragt: „Kann ich mitstreiken?"',
      knackpunkte: [
        'GG Art. 33/5 hergebrachte Grundsätze des Berufsbeamtentums — Streikverbot folgt aus Treuepflicht + Alimentationsprinzip.',
        'BVerfG-Rechtsprechung bestätigt: Streikverbot greift bei jeder verbeamteten LK, auch bei Warnstreik.',
        'Vereinigungs-/Gewerkschaftsrecht Art. 9/3 GG bleibt — Mitgliedschaft + Demos in Freizeit erlaubt.',
        'Tarifbeschäftigte LK (TVöD/TV-L) dürfen streiken.',
        'Verstoß = Dienstvergehen § 47 BeamtStG → Disziplinarmaßnahme BayDG Art. 6 ff.',
      ],
      antwortkette: 'Streikverbot Art. 33/5 GG → Treuepflicht + Alimentation → kein Streikrecht für Beamte → Mitgliedschaft + Demos in Freizeit OK → bei Streik Dienstvergehen + Disziplinar.',
    },
  ],

  vertiefung: [
    { id: 'A1', kuerzel: 'A.1', titel: 'Pflichten-Doppelstruktur',
      anriss: 'Beamten-Säule (BayBG/BeamtStG) + Schul-Säule (LDO/BayEUG). Beide kumulativ. § 9a LDO Allgemeine Dienstpflichten + § 9b außerunterrichtlich.',
      norm: '§ 9a LDO', status: 'open', cards: 3,
      subblocks: [{ label: 'Zwei-Säulen-Tabelle', cards: 1 }, { label: '§ 9a/9b LDO', cards: 1 }, { label: 'Art. 59 BayEUG', cards: 1 }],
    },
    { id: 'A2', kuerzel: 'A.2', titel: 'Aufsichtspflicht (Hochfrequenz)',
      anriss: '§ 5 LDO + § 22 BaySchO + Art. 57/2 BayEUG. Zeitliche + räumliche Reichweite. 4 Leitfragen gerichtliche Nachprüfung. Haftungsdreieck.',
      norm: '§ 5 LDO', status: 'open', cards: 4,
      subblocks: [{ label: 'Norm-Verbund', cards: 1 }, { label: 'Reichweite Zeit + Raum', cards: 1 }, { label: 'Vier Leitfragen', cards: 1 }, { label: 'Haftungsdreieck', cards: 1 }],
    },
    { id: 'A3', kuerzel: 'A.3', titel: 'Auskunfts- + Verschwiegenheits-Trias',
      anriss: '§ 14 LDO mit drei Bereichen: Verschwiegenheit · Presse-Hoheit SL · Drittauskunfts-Verbot. KEIN „Notengeheimnis" ggü. eigenen SuS/EB.',
      norm: '§ 14 LDO', status: 'open', cards: 3,
      subblocks: [{ label: 'Drei Bereiche', cards: 1 }, { label: 'Drittauskunfts-Logik', cards: 1 }, { label: 'Notenauskunfts-Falle', cards: 1 }],
    },
    { id: 'A4', kuerzel: 'A.4', titel: 'Fortbildung + KL-Aufgaben',
      anriss: '§ 9a/2 LDO + Art. 20 BayLBG: 12 Tage / 4 J. + mind. 1/3 SchiLF. § 6 LDO KL-Aufgaben + Koordinations-Pflicht.',
      norm: 'Art. 20 BayLBG', status: 'open', cards: 2,
      subblocks: [{ label: 'Fortbildung-Umfang', cards: 1 }, { label: 'KL-Aufgaben § 6 LDO', cards: 1 }],
    },
    { id: 'A5', kuerzel: 'A.5', titel: 'Personalvertretung + Streikverbot',
      anriss: 'BayPVG Art. 75 Mitbestimmung (Zustimmung) ≠ Art. 76 Mitwirkung (Stellungnahme). GG Art. 33/5: Streikverbot Beamte; Tarifbeschäftigte dürfen.',
      norm: 'Art. 75 BayPVG', status: 'open', cards: 2,
      subblocks: [{ label: 'Mitbestimmung ↔ Mitwirkung', cards: 1 }, { label: 'Streikverbot + Gewerkschaft', cards: 1 }],
    },
  ],

  glossar: {
    'Art. 33/5 GG': { titel: 'Art. 33 Abs. 5 GG — Berufsbeamtentum', wortlaut: '„Das Recht des öffentlichen Dienstes ist unter Berücksichtigung der hergebrachten Grundsätze des Berufsbeamtentums zu regeln und fortzuentwickeln." Streikverbot folgt mittelbar — Treuepflicht + Alimentationsprinzip kompensieren.', karten: ['L08'] },
    'Art. 34 GG': { titel: 'Art. 34 GG — Amtshaftung', wortlaut: '„Verletzt jemand in Ausübung eines ihm anvertrauten öffentlichen Amtes die ihm einem Dritten gegenüber obliegende Amtspflicht, so trifft die Verantwortlichkeit grundsätzlich den Staat. Bei Vorsatz oder grober Fahrlässigkeit bleibt der Rückgriff vorbehalten."', karten: ['L04'] },
    '§ 47 BeamtStG': { titel: '§ 47 BeamtStG — Dienstvergehen', wortlaut: 'Abs. 1: „Beamte begehen ein Dienstvergehen, wenn sie schuldhaft die ihnen obliegenden Pflichten verletzen." Außerdienstlich erfasst, wenn das Vertrauen in besonderem Maße beeinträchtigt wird.', karten: [] },
    '§ 839 BGB': { titel: '§ 839 BGB — Beamtenhaftung', wortlaut: 'Schadensersatz für vorsätzliche/fahrlässige Amtspflichtverletzung. I.V.m. Art. 34 GG: Staat haftet nach außen, Rückgriff bei Vorsatz + grober Fahrlässigkeit.', karten: ['L04'] },
    '§ 203 StGB': { titel: '§ 203 StGB — Berufsgeheimnis', wortlaut: 'Strafbarkeit bei unbefugter Offenbarung von Privatgeheimnissen durch Berufsgruppen. Schulpsycholog:innen sind erfasst; LK i.d.R. nicht — aber Verschwiegenheits-Pflicht § 14 LDO.', karten: [] },
    'Art. 57/2 BayEUG': { titel: 'Art. 57 Abs. 2 BayEUG — SL-Gesamtverantwortung', wortlaut: 'SL trägt Gesamtverantwortung für ordnungsgemäßen Ablauf des Unterrichts und der Erziehungsarbeit. Aufsichts-Einteilung der LK durch SL (§ 5/2 LDO).', karten: [] },
    'Art. 58 BayEUG': { titel: 'Art. 58 BayEUG — Lehrerkonferenz', wortlaut: 'Kollegiales Beschluss-Organ der Schule. Zuständig u.a. für Grundsätze HA, EOM-Eskalation, Probearbeiten.', karten: [] },
    'Art. 59 BayEUG': { titel: 'Art. 59 BayEUG — Lehrkräfte', wortlaut: 'Abs. 1: LK tragen unmittelbare pädagogische Verantwortung für U. + Erziehung. Abs. 2: Distanz-U. — Bild + Ton bei techn. Voraussetzungen. Symbol-Verbot S. 4 konditional: „sofern auch als Haltung verstanden werden können", die verfassungsrechtlichen Grundwerten + christlich-abendländischen Bildungs-/Kulturwerten widerspricht.', karten: [] },
    'Art. 75 BayEUG': { titel: 'Art. 75 BayEUG — EB-Auskunft', wortlaut: 'Eltern werden über wesentliche Vorgänge unterrichtet, die ihr Kind betreffen. Bei Ordnungsmaßnahmen: schriftlich, rechtzeitig vor Vollzug.', karten: [] },
    'Art. 84 BayEUG': { titel: 'Art. 84 BayEUG — Werbeverbot', wortlaut: 'Abs. 2: Politische Werbung auf Schulgelände/Veranstaltungen unzulässig. Abs. 3: Politische Abzeichen zulässig nur, wenn 5 Schutzgüter (Schulfrieden · Schulbetrieb · Bildungs-/Erziehungsauftrag · pers. Ehre · Erziehung zur Toleranz) NICHT gefährdet.', karten: [] },
    '§ 2 LDO': { titel: '§ 2 LDO — Aufgaben der Lehrkraft', wortlaut: 'Erziehung + Unterricht + Verwaltung. Vorbild-Funktion. Pädagogische Verantwortung primär — i.V.m. Art. 59 BayEUG.', karten: [] },
    '§ 4 LDO': { titel: '§ 4 LDO — Schulische Veranstaltungen', wortlaut: 'Pflicht zur Teilnahme an Wandertagen, Schullandheimaufenthalten, Skikursen u.a. außerunterrichtlichen Schulveranstaltungen.', karten: [] },
    '§ 5 LDO': { titel: '§ 5 LDO — Aufsichtspflicht', wortlaut: 'Abs. 1: LK wirkt bei Aufsicht mit; auch außerhalb eigenen U. Insbesondere: ab U.-Beginn im Raum + gesamte Dauer + erforderlichenfalls bis Weggang SuS. Verlassen nur in Ausnahmefällen + notwendige Maßnahmen. Abs. 2: SL-Einteilung. Abs. 3: außerschul. Veranstaltungen — Treff-/Endpunkt = Aufsichtsbeginn/-ende; Jgst. 1–4 im Schulsprengel. Abs. 4: bei Mitwirkung Dritter LK anwesend.', karten: ['L02'] },
    '§ 6 LDO': { titel: '§ 6 LDO — Klassenleitung', wortlaut: 'KL-Aufgaben: pädagogische + organisatorische Koordination der Klasse + Kontakt zu EB. § 6/2: Koordinationspflicht mit Fach-LK. Hebel im KL-Stufenplan bei Eltern-Beschwerden.', karten: [] },
    '§ 9a LDO': { titel: '§ 9a LDO — Allgemeine Dienstpflichten', wortlaut: 'Abs. 1: Arbeitskraft dem Dienst widmen + erzieherischer Einsatz auch außerhalb U. Abs. 2: Selbst-Fortbildung + dienstliche Fortbildung (i.V.m. Art. 66/2 LlbG + Art. 20 BayLBG + KMBek 09.08.2002). Abs. 3: U.-Zeiten einhalten + Vertretung in zumutbarem Umfang. Abs. 4: fachfremder U. NICHT zum Nachteil bei Beurteilung. Abs. 8: Rauchverbot Schulgelände absolut; außerhalb „sollen verzichten".', karten: ['L01', 'L06'] },
    '§ 9b LDO': { titel: '§ 9b LDO — Außerunterrichtliche Dienstpflichten', wortlaut: '10-Punkte-Katalog „insbesondere": Vorbereitung SJ · Verwaltung · Besprechungen · Mitwirkung Aus-/Fortbildung · Qualitätssicherung · Schulentwicklung · Zusammenarbeit andere Schulen · Kontakt EB/Ausbildung · außerschul. Partner · Schulleben. SL achtet auf gleichmäßige Verteilung unter Berücksichtigung individueller Belastung.', karten: [] },
    '§ 14 LDO': { titel: '§ 14 LDO — Verschwiegenheit + Auskunft', wortlaut: 'Drei Bereiche: (1) Verschwiegenheit über dienstlich bekannte Angelegenheiten — post-dienstlich fortwirkend. (2) Presse-/Öffentlichkeits-Auskunft NUR durch SL. (3) Drittauskunfts-Verbot — KEIN „Notengeheimnis" ggü. eigenen SuS/EB, aber kein VERGLEICHENDER Bezug auf andere SuS namentlich. § 14/4 regelt, WEM die Schule Auskunft geben darf (primär Erziehungsberechtigte).', karten: ['L05'] },
    '§ 22 BaySchO': { titel: '§ 22 BaySchO — Beaufsichtigung', wortlaut: 'Abs. 1: Aufsichtspflicht erstreckt sich auf U.-Zeit + sonstige Schulveranstaltungen + angemessene Zeit vor + nach. GS + GS-Stufe FöS: 15 Min vor + bis Verlassen des Schulgeländes; bei Bedarf 30 Min vor. Abs. 2: Umfang nach geistiger + charakterlicher Reife; unterrichtsfreie Zeit Schulanlage verlassen (außer GS+FöS); Grundsätze mit Schulforum abstimmen. Abs. 3: Praktische Ausbildung — Aufsicht bei Praxisanleiter; Distanz-U. außerhalb der Schule — Aufsicht bei EB.', karten: ['L03'] },
    'Art. 6 BayDG': { titel: 'Art. 6 BayDG — Disziplinarmaßnahmen-Katalog', wortlaut: '5 Stufen Lebenszeitbeamte: Verweis · Geldbuße · Kürzung Dienstbezüge · Zurückstufung · Entfernung aus Beamtenverhältnis. 2 Stufen Ruhestand: Kürzung Ruhegehalt · Aberkennung Ruhegehalt. Tatbestand „Dienstvergehen" steht in § 47 BeamtStG (Bund).', karten: ['L04'] },
    'Art. 20 BayLBG': { titel: 'Art. 20 BayLBG — Fortbildung', wortlaut: 'Pflicht zur Fortbildung. Konkretisierung KMBek 09.08.2002 (Anpassung 08.2025): 12 Fortbildungstage / 4 Jahre, mind. 1/3 SchiLF.', karten: ['L06'] },
    'Art. 75 BayPVG': { titel: 'Art. 75 BayPVG — Mitbestimmung', wortlaut: 'Personalrat hat Mitbestimmungsrecht u.a. bei Einstellung, Versetzung, Beförderung. Zustimmung erforderlich — ohne Zustimmung Maßnahme unwirksam. Höchste Beteiligungsstufe.', karten: ['L07'] },
    'Art. 76 BayPVG': { titel: 'Art. 76 BayPVG — Mitwirkung', wortlaut: 'Geringere Beteiligungsstufe als Mitbestimmung. Personalrat gibt Stellungnahme ab; Dienststelle entscheidet trotzdem. Bei Auflösung/Verkleinerung Organisationseinheiten.', karten: ['L07'] },
    'Art. 95 BV': { titel: 'Art. 95 BV — Beamtenverhältnis Bayern', wortlaut: 'Bayern-spezifischer Verfassungsanker für das Beamtenrecht. Ergänzt GG Art. 33.', karten: [] },
    'Art. 136 BV': { titel: 'Art. 136 BV — Religionsunterricht', wortlaut: 'ReliU als ordentliches Lehrfach. Lehrkräfte bedürfen religionspädagogischer Bevollmächtigung (Vocatio/Missio canonica).', karten: [] },
  },
};
