// LB-Matrix Mathematik MS Bayern — LP+ Stoff-Verteilung 5–10 × 6 LBs
// Pro Zelle: KE-Ankerung + optional ausgearbeitete Sequenzplanung mit
// fachdidaktischer Begründung (Slideover-Content).

window.MATRIX = {
  fach: 'D Mathematik',
  fachKuerzel: 'Mathematik',
  schulart: 'Mittelschule Bayern',
  jgst: [
    { id: 'M5', label: 'Jgst. 5' },
    { id: 'M6', label: 'Jgst. 6' },
    { id: 'M7', label: 'Jgst. 7' },
    { id: 'M8', label: 'Jgst. 8' },
    { id: 'M9', label: 'Jgst. 9' },
    { id: 'M10', label: 'M10' },
  ],
  lernbereiche: [
    { id: 'LB1', titel: 'Zahlen + Operationen', kurz: 'Z+O' },
    { id: 'LB2', titel: 'Größen + Messen', kurz: 'G+M' },
    { id: 'LB3', titel: 'Raum + Form', kurz: 'R+F' },
    { id: 'LB4', titel: 'Daten + Zufall', kurz: 'D+Z' },
    { id: 'LB5', titel: 'Funktionaler Zusammenhang', kurz: 'FZ' },
    { id: 'LB6', titel: 'Muster + Strukturen', kurz: 'MS' },
  ],
  // Zellen-Schlüssel: '<jgst-id>_<lb-id>'.
  // status: 'stub' | 'gerüst' | 'ausgearbeitet'.
  // sequenz: optional — wenn vorhanden, vollständige Sequenzplanung mit Begründung.
  cells: {

    // ─── M5 ─────────────────────────────────────────────────────────────
    'M5_LB1': { ke: 'M5 1.1', titel: 'Natürliche Zahlen', kurz: 'Stellenwertsystem · Bündeln zur Million', status: 'stub' },
    'M5_LB2': { ke: 'M5 2.1', titel: 'Größen', kurz: 'Länge · Geld · Zeit · Masse · Umwandeln', status: 'stub' },
    'M5_LB3': {
      ke: 'M5 3.1', titel: 'Geometrische Körper', kurz: 'Würfel · Quader · Kugel handelnd',
      status: 'ausgearbeitet',
      sequenz: {
        ueberblick: '6-UE-Sequenz · enaktiver Erstkontakt mit geometrischen Körpern. Bruner-EIS-Progression von realer Manipulation (Material-Sammlung, Bauklötze) über Skizzen-Ikonik zur symbolischen Notation (Eckpunkte/Kanten/Flächen zählen). Klassische Einstiegs-Sequenz für M5, didaktisch anchored im Primat der Handlung (Piaget/Montessori).',
        ke_wortlaut: '„Die Schülerinnen und Schüler unterscheiden geometrische Körper (Würfel, Quader, Pyramide, Kegel, Zylinder, Kugel) an Modellen und Bildern. Sie benennen Eckpunkte, Kanten und Flächen und beschreiben deren Eigenschaften."',
        ues: [
          { nr: 1, titel: 'Sammlung Alltagsobjekte', ebene: 'enaktiv', kompetenz: 'Erfahren',
            inhalt: 'Lernende bringen Verpackungen, Bauklötze, Spielwürfel mit. Klassengemeinschaft sortiert nach „wie der Körper aussieht" — ohne Vorgabe. Ergebnis: spontane Gruppen entstehen.',
            begruendung: 'Enaktive Stufe (Bruner): Lernende handeln am konkreten Material. Konstruktivistisches Wissens-Konstruieren (Piaget) — die Lernenden bilden die Begriffe SELBST, bevor Begriffe vorgegeben werden. Operatives Prinzip (Wittmann/Aebli): Vorerfahrungen mit Körpern aktivieren.' },
          { nr: 2, titel: 'Begriffsklärung Eckpunkte · Kanten · Flächen', ebene: 'enaktiv→ikonisch', kompetenz: 'Begreifen',
            inhalt: 'Mit den Materialien werden Eckpunkte (Spitzen), Kanten (Verbindungslinien) und Flächen (Außenseiten) benannt und am Körper gezeigt. Jede:r markiert auf einem eigenen Würfel mit Klebepunkten.',
            begruendung: 'Übergang enaktiv → ikonisch: durch Beschriften wird der reale Körper auf eine Skizze hin geöffnet. Lehrwortschatz präzise einführen (sprachsensibel — Eckpunkt ≠ Spitze, Kante ≠ Linie).' },
          { nr: 3, titel: 'Schrägbilder + Netze (ikonisch)', ebene: 'ikonisch', kompetenz: 'Darstellen',
            inhalt: 'Skizzen-Übungen: Schrägbild Würfel + Quader. Bastel-Netze ausschneiden + falten. Aha-Effekt: das Netz „wird" zum Körper.',
            begruendung: 'Ikonische Stufe (EIS): Repräsentation auf Papier. Spatial-Reasoning-Übung — wichtig für späteren Übergang zu Volumenberechnung. Netz-Falten verbindet handelnd + visuell.' },
          { nr: 4, titel: 'Eulerformel (Anbahnung)', ebene: 'ikonisch→symbolisch', kompetenz: 'Argumentieren',
            inhalt: 'Tabelle: Würfel hat E=8, K=12, F=6. Quader auch. Pyramide: E=5, K=8, F=5. Lernende sollen Muster entdecken. Lehrer*innen lenken zu E − K + F = 2.',
            begruendung: 'Entdeckendes Lernen (Wittmann): die Lernenden ENTDECKEN die Formel, statt sie zu erhalten. Mustererkennen als prozessbezogene Kompetenz. Spirale: vorbereitet auf systematisches Argumentieren in höheren Jgst.' },
          { nr: 5, titel: 'Anwendungs-Übung — Real-Bezug', ebene: 'symbolisch', kompetenz: 'Modellieren',
            inhalt: 'Beispiele aus dem Alltag: Wie viel Karton braucht Lina für ihre Geschenkbox? (Quader-Oberfläche aus Flächenanzahl × Maße).',
            begruendung: 'Anwendungs-Phase im 4-Phasen-Modell (Einführung/Erarbeitung/Übung/Anwendung). Verbindung zur Größen-Welt (LB2) — Spiralprinzip Bruner.' },
          { nr: 6, titel: 'Sicherung + Lernzielkontrolle', ebene: 'symbolisch', kompetenz: 'Reflektieren',
            inhalt: 'Hefteintrag: Tabelle der 6 Körper-Typen mit Eckpunkten/Kanten/Flächen. Kurz-LNW mit 5 Aufgaben (Identifizieren, Skizzieren, Zählen, Anwenden).',
            begruendung: 'Sicherung als 4. Phase. LNW kompetenzorientiert (alle drei AFB I-III abdecken). Hefteintrag systematisiert das Konstruierte.' },
        ],
        bezuege: [
          { didaktik: 'EIS-Prinzip (Bruner)', verweis: 'Vertikale Sequenz-Logik: enaktiv (UE1-2) → ikonisch (UE3) → symbolisch (UE4-6).' },
          { didaktik: 'Operatives Prinzip (Wittmann/Aebli)', verweis: 'UE 2-3: Eckpunkte zählen, Netze falten — Begriffe durch Operationen erschließen.' },
          { didaktik: 'Spiralprinzip (Bruner)', verweis: 'Anbahnung Eulerformel UE4 → systematisches Argumentieren in M7/M8. Volumen-Brücke zu LB2.' },
          { didaktik: 'Entdeckendes Lernen', verweis: 'UE 4: Lernende entdecken die Eulerformel selbst.' },
          { didaktik: 'Sprachsensibler MU', verweis: 'UE 2: Begriffs-Präzision Eckpunkt/Kante/Fläche — Wortschatz-Aufbau.' },
        ],
      },
    },
    'M5_LB4': { ke: 'M5 4.1', titel: 'Daten erheben', kurz: 'Strichliste · einfache Diagramme', status: 'stub' },
    'M5_LB5': { ke: '—', titel: '(nicht in M5)', kurz: 'erste Anbahnung in M6', status: 'stub' },
    'M5_LB6': { ke: 'M5 6.1', titel: 'Muster + Strukturen', kurz: 'Zahlenmuster · Folgen entdecken', status: 'stub' },

    // ─── M6 ─────────────────────────────────────────────────────────────
    'M6_LB1': { ke: 'M6 1.1', titel: 'Brüche', kurz: 'Anteilsvorstellung · Bruch-Brücke', status: 'gerüst' },
    'M6_LB2': { ke: 'M6 2.1', titel: 'Größen', kurz: 'Flächen · Volumen · Zeit-Berechnung', status: 'stub' },
    'M6_LB3': { ke: 'M6 3.1', titel: 'Vielecke + Kreis', kurz: 'Konstruieren · Symmetrie', status: 'stub' },
    'M6_LB4': { ke: 'M6 4.1', titel: 'Säulendiagramm', kurz: 'Daten darstellen + lesen', status: 'stub' },
    'M6_LB5': { ke: 'M6 5.1', titel: 'Proportionalität', kurz: 'Anbahnung Dreisatz', status: 'stub' },
    'M6_LB6': { ke: 'M6 6.1', titel: 'Muster', kurz: 'Geometrische Folgen', status: 'stub' },

    // ─── M7R ────────────────────────────────────────────────────────────
    'M7_LB1': {
      ke: 'M7R 1.4', titel: 'Prozent + Anteile', kurz: '*** Prozentwert · Grundwert · Prozentsatz',
      status: 'ausgearbeitet',
      sequenz: {
        ueberblick: '8-UE-Sequenz Prozentrechnung — meine eigene M7c-Praxis SJ 25/26 + Seminarübung Würzburg Nov 2025 (Beispiel-Sequenz Prozent v2/v3, Goldcluster). EIS-Progression von enaktiver 100er-Feld-Manipulation zu symbolischer Prozentformel. Aktivierung der Bruch-Vorerfahrung aus M6 als Spiral-Anker.',
        ke_wortlaut: '„Die Schülerinnen und Schüler lösen Aufgaben zur Prozentrechnung mit Hilfe ihrer Vorstellung von Anteilen. Sie bestimmen Prozentwert, Grundwert und Prozentsatz in alltagsnahen Kontexten und nutzen die Prozentschreibweise."',
        ues: [
          { nr: 1, titel: 'Einstieg 100er-Feld — Anteile sichtbar machen', ebene: 'enaktiv', kompetenz: 'Erfahren',
            inhalt: '100er-Feld auf Folie. SuS legen Anteile mit Plättchen: „Lege 25 Anteile von 100." Klare visuelle 1/4-Verbindung. Real-Manipulation am Hundertstelquadrat.',
            begruendung: 'Enaktive Stufe Bruner. Aufbauend auf M6 Bruch-Vorstellung (Spiralprinzip). 100er-Feld ist Anker-Bild, das den abstrakten Prozent-Begriff GREIFBAR macht. Konstruktivistisch: Lernende konstruieren die Anteils-Vorstellung über Handlung, BEVOR Notation eingeführt wird.' },
          { nr: 2, titel: 'Hundertstelbrüche — Spiral-Brücke zu M6', ebene: 'enaktiv→ikonisch', kompetenz: 'Begreifen',
            inhalt: 'Übersetzung: 25/100 = 25 von 100 = 25 %. Notation parallel: 25/100, 25 %, „ein Viertel". Drei-Darstellungen-Vergleich.',
            begruendung: 'Spiralprinzip Bruner: Bruch-Wissen aus M6 reaktiviert und auf Prozent erweitert. Operatives Prinzip — durch Umformung wird die Äquivalenz erfahren. Sprach-sensibler MU: Brücken-Vokabular „von Hundert" aufbauen.' },
          { nr: 3, titel: 'Prozentstreifen — neue ikonische Repräsentation', ebene: 'ikonisch', kompetenz: 'Darstellen',
            inhalt: 'Prozentstreifen 0%–100% mit Zwischenmarkierungen. Aufgaben: „Markiere 30%, 75%, 12,5%". Streifen als Werkzeug für Schätzaufgaben.',
            begruendung: 'Ikonische Repräsentation (EIS). Prozentstreifen ist DAS Modell-Werkzeug für Prozentrechnung. Bezug zum Zahlenstrahl aus M5/M6 — Mathematische Vernetzung als Bildungsziel.' },
          { nr: 4, titel: 'Prozentwert berechnen — Modellieren', ebene: 'ikonisch→symbolisch', kompetenz: 'Modellieren',
            inhalt: 'Aufgabe: „Im Schulshop 20% Rabatt auf 50 €. Wie viel ist der Rabatt?" Lösung über Prozentstreifen + Notation P = G · p%/100.',
            begruendung: 'Modellierungskreislauf (Blum/Leiß): Realsituation → math. Modell → Rechnung → Interpretation. SINUS-Aufgabenkultur: alltagsnah + kompetenz-orientiert. Beziehungshaltigkeit (Freudenthal) — math. Strukturen in der echten Welt erfahren.' },
          { nr: 5, titel: 'Grundwert + Prozentsatz — die andere Richtung', ebene: 'symbolisch', kompetenz: 'Argumentieren',
            inhalt: 'Umkehr-Aufgaben: „Rabatt 10 € entspricht 20%. Was war der Grundpreis?" Reversibilität als Operationsmerkmal trainieren.',
            begruendung: 'Operatives Prinzip Wittmann/Aebli — REVERSIBILITÄT ist das zentrale Operationsmerkmal. SuS müssen erkennen: G = P · 100 / p% ist die UMKEHRUNG. Argumentieren als prozessbezogene Kompetenz.' },
          { nr: 6, titel: 'Reale Anwendungen — Praktikum M7c', ebene: 'symbolisch', kompetenz: 'Modellieren',
            inhalt: 'Aufgaben aus dem Alltag der SuS: Rabatt-Aktionen, Steuersätze, MwSt., Trinkgeld. SuS sammeln eigene Real-Beispiele.',
            begruendung: 'Berufsorientierung als Querbezug (Realbezug-Pflicht LP+ Mittelschule). Aufgabenkultur SINUS — produktives Üben. Alltagsbezug erhöht Motivation + Behaltensleistung.' },
          { nr: 7, titel: 'Übung + Differenzierung', ebene: 'symbolisch', kompetenz: 'Üben',
            inhalt: 'AB mit 3 Niveaus (basic / mittel / herausfordernd). Differenzierung nach Schwierigkeitsgrad. Hilfekarten verfügbar.',
            begruendung: 'Differenzierung (LP+ Pflicht-Prinzip). Drei Niveaustufen reduzieren Über- + Unterforderung. Hilfekarten-System als Scaffolding (Wood/Bruner/Ross) — vom Lehrer-Support zur Selbst-Hilfe.' },
          { nr: 8, titel: 'Lernzielkontrolle + Reflexion', ebene: 'symbolisch', kompetenz: 'Reflektieren',
            inhalt: 'Schul-Arbeit Prozentrechnung. Reflexionsrunde: „Wo nutzt ihr Prozent außerhalb der Schule?"',
            begruendung: 'Veränderte Leistungsmessung (LP+) — Fehler-Kultur etablieren. Reflexionsphase macht Bildungsziel-Bezug sichtbar (Bürger:in werden — Prozent kann jede:r brauchen).' },
        ],
        bezuege: [
          { didaktik: 'EIS-Prinzip', verweis: 'Komplette Sequenz folgt der EIS-Treppe — vom 100er-Feld (enaktiv) bis zur Formel (symbolisch).' },
          { didaktik: 'Spiralprinzip', verweis: 'M6 Bruch → M7 Prozent → M8 Zins. Drei Stufen derselben Anteils-Logik in zunehmender Abstraktion.' },
          { didaktik: 'Operatives Prinzip', verweis: 'UE 5 Reversibilität (Grundwert-Bestimmung). UE 2 Darstellungs-Wechsel als Operation.' },
          { didaktik: 'Modellieren (Blum/Leiß)', verweis: 'UE 4 + 6: alltagsnahe Real-Situationen → math. Modell → Lösung → Interpretation.' },
          { didaktik: 'Differenzierung 3-Niveau', verweis: 'UE 7: AB-Differenzierung als verbindliches LP+-Prinzip.' },
          { didaktik: 'Eigene Praxis', verweis: 'M7c SJ 25/26 — diese Sequenz wurde 3 UEs real getestet (Goldcluster). Seminarübung Würzburg Nov 2025 Beispiel-Sequenz v2/v3.' },
        ],
      },
    },
    'M7_LB2': { ke: 'M7R 2.1', titel: 'Flächeninhalt + Umfang', kurz: 'Dreieck · Parallelogramm · Trapez', status: 'gerüst' },
    'M7_LB3': { ke: 'M7R 3.1', titel: 'Geometrie ebener Figuren', kurz: 'Kongruenz · Symmetrie · Konstruktion', status: 'stub' },
    'M7_LB4': { ke: 'M7R 4.1', titel: 'Wahrscheinlichkeit', kurz: 'Laplace-Versuche · empirisch + theoretisch', status: 'stub' },
    'M7_LB5': { ke: 'M7R 5.1', titel: 'Proportionalität', kurz: 'Dreisatz direkt + indirekt', status: 'gerüst' },
    'M7_LB6': { ke: 'M7R 6.1', titel: 'Terme + Variable', kurz: 'Anbahnung Algebra', status: 'stub' },

    // ─── M8 ─────────────────────────────────────────────────────────────
    'M8_LB1': { ke: 'M8 1.1', titel: 'Zinsrechnung', kurz: 'Spiral-Anschluss Prozent · Sparen + Kredit', status: 'gerüst' },
    'M8_LB2': { ke: 'M8 2.1', titel: 'Körper-Volumen', kurz: 'Prisma · Zylinder', status: 'stub' },
    'M8_LB3': { ke: 'M8 3.1', titel: 'Ähnlichkeit + Strahlensätze', kurz: 'Maßstab · Kartografie', status: 'stub' },
    'M8_LB4': { ke: 'M8 4.1', titel: 'Statistik', kurz: 'Mittelwert · Median · Boxplot', status: 'stub' },
    'M8_LB5': {
      ke: 'M8 5.1', titel: 'Lineare Funktionen', kurz: '*** y = m·x + b · Steigung + y-Achsen-Abschnitt',
      status: 'ausgearbeitet',
      sequenz: {
        ueberblick: '8-UE-Sequenz Lineare Funktionen — funktionales Denken als zentrale algebraische Kompetenz der MS-Oberstufe. EIS-Progression von Wertetabellen (enaktiv-listenhaft) über grafische Darstellung (ikonisch) zur Funktionsgleichung (symbolisch). Anknüpfung an M7 Proportionalität als Spiral-Anker.',
        ke_wortlaut: '„Die Schülerinnen und Schüler stellen lineare Zusammenhänge in Wertetabellen, Diagrammen und Termen dar. Sie bestimmen Steigung und y-Achsen-Abschnitt einer linearen Funktion und nutzen sie zur Beschreibung von Realsituationen."',
        ues: [
          { nr: 1, titel: 'Einstieg Sachsituationen', ebene: 'enaktiv', kompetenz: 'Erfahren',
            inhalt: 'Kerze-Brennt-Down-Experiment. Höhe in cm zu Zeit in min messen. Wertetabelle anlegen.',
            begruendung: 'Beziehungshaltigkeit (Freudenthal): math. Begriff entsteht aus realer Erfahrung. Enaktive Stufe — SuS handeln am Material. Modellierungskreislauf-Anfang.' },
          { nr: 2, titel: 'Wertetabelle → Diagramm', ebene: 'enaktiv→ikonisch', kompetenz: 'Darstellen',
            inhalt: 'Werte aus Tabelle in Koordinatensystem übertragen. Auffallend: liegen auf einer Linie.',
            begruendung: 'Darstellungs-Wechsel (Mathe-Standard). Bruner ikonisch: das Diagramm IST das Bild der Funktion. Ent-Algebraisierung — auch nicht-formal-orientierte SuS verstehen die Linie.' },
          { nr: 3, titel: 'Steigung als Verhältnis', ebene: 'ikonisch', kompetenz: 'Begreifen',
            inhalt: 'Steigungsdreieck: m = Δy/Δx. Mehrere Funktionen vergleichen — welche steigt stärker?',
            begruendung: 'Operatives Prinzip: Steigung als OPERATION (Δy pro Δx). Reversibilität: aus m und einem Punkt die Funktion rekonstruieren. Spiralanschluss zu M7-Proportionalität (m als Proportionalitätsfaktor).' },
          { nr: 4, titel: 'y-Achsen-Abschnitt', ebene: 'ikonisch→symbolisch', kompetenz: 'Argumentieren',
            inhalt: 'Was bedeutet b? Was passiert, wenn die Linie nicht im Ursprung startet? Real-Bezug: Anfangsstand der Kerze.',
            begruendung: 'Argumentieren als prozessbezogene Kompetenz. Mehrperspektivität: b als algebraischer Parameter + als realer Anfangswert.' },
          { nr: 5, titel: 'Funktionsgleichung y = mx + b', ebene: 'symbolisch', kompetenz: 'Modellieren',
            inhalt: 'Formal: y = m·x + b. Aus 2 Punkten Funktion bestimmen.',
            begruendung: 'Symbolische Stufe — Notation als Verdichtung der grafischen Erkenntnis. KOMPRIMIERUNG des Verständnisses in einen Term.' },
          { nr: 6, titel: 'Real-Modellierung', ebene: 'symbolisch', kompetenz: 'Modellieren',
            inhalt: 'Aufgaben: Tarif-Vergleich (Grundgebühr + Verbrauchspreis), Tankfüllung, Sparplan. Modellierungs-Kreislauf vollständig durchlaufen.',
            begruendung: 'Modellierungskreislauf Blum/Leiß: 5 Schritte. SINUS-Aufgabenkultur. Bezug zu WiB (Tarif-Vergleich → Berufsorientierung).' },
          { nr: 7, titel: 'Übung + Differenzierung', ebene: 'symbolisch', kompetenz: 'Üben',
            inhalt: '3-Niveau-AB: bestimmen / darstellen / modellieren.',
            begruendung: 'Produktives Üben (Wittmann). Differenzierung nach kognitiver Anforderungsstufe (AFB I-III).' },
          { nr: 8, titel: 'Schul-Arbeit + Reflexion', ebene: 'symbolisch', kompetenz: 'Reflektieren',
            inhalt: 'LNW: alle 3 Darstellungen abprüfen (Tabelle, Graph, Term).',
            begruendung: 'Veränderte Leistungsmessung — alle Repräsentations-Ebenen prüfen, nicht nur Term. Kompetenz-orientierte LNW.' },
        ],
        bezuege: [
          { didaktik: 'EIS-Prinzip', verweis: 'Sequenz folgt der EIS-Treppe: Experiment (UE1) → Diagramm (UE2-4) → Formel (UE5-6).' },
          { didaktik: 'Spiralprinzip', verweis: 'M7 Proportionalität → M8 Lineare Funktion (= proportionale Funktion mit b). M9 quadratische Funktionen.' },
          { didaktik: 'Operatives Prinzip', verweis: 'UE 3 Steigung als Operation, UE 5 Reversibilität (Funktion → Punkt → Funktion).' },
          { didaktik: 'Modellieren (Blum/Leiß)', verweis: 'UE 1+6: vollständiger Modellierungskreislauf 5 Schritte.' },
          { didaktik: 'Beziehungshaltigkeit (Freudenthal)', verweis: 'Sachsituationen als Ausgangspunkt — kein algebraischer Selbstzweck.' },
        ],
      },
    },
    'M8_LB6': { ke: 'M8 6.1', titel: 'Gleichungen lösen', kurz: 'Äquivalenz-Umformung', status: 'stub' },

    // ─── M9 ─────────────────────────────────────────────────────────────
    'M9_LB1': { ke: 'M9R 1.1', titel: 'Zinseszins + Geld', kurz: 'Exponentielles Wachstum (Anbahnung)', status: 'stub' },
    'M9_LB2': { ke: 'M9R 2.1', titel: 'Trigonometrie', kurz: 'Sinus · Cosinus · Tangens', status: 'stub' },
    'M9_LB3': { ke: 'M9R 3.1', titel: 'Pythagoras', kurz: 'a² + b² = c² · Anwendung', status: 'stub' },
    'M9_LB4': { ke: 'M9R 4.1', titel: 'Datenanalyse', kurz: 'Streuung · Quartile', status: 'stub' },
    'M9_LB5': { ke: 'M9R 5.1', titel: 'Quadratische Funktion', kurz: 'Parabel · Scheitelpunkt', status: 'gerüst' },
    'M9_LB6': { ke: 'M9R 6.1', titel: 'Gleichungssysteme', kurz: '2 Variablen · grafisch + rechnerisch', status: 'stub' },

    // ─── M10 ────────────────────────────────────────────────────────────
    'M10_LB1': { ke: 'M10 1.1', titel: 'Geldmathematik', kurz: 'Kredit · Sparen · Zinseszins', status: 'stub' },
    'M10_LB2': { ke: 'M10 2.1', titel: 'Volumen Kegel/Pyramide', kurz: 'Räumliches Vorstellungsvermögen', status: 'stub' },
    'M10_LB3': { ke: 'M10 3.1', titel: 'Geometrische Beweise', kurz: 'Argumentieren · Beweisführung', status: 'stub' },
    'M10_LB4': { ke: 'M10 4.1', titel: 'Mehrstufige Zufallsversuche', kurz: 'Pfadregel · Baum-Diagramm', status: 'stub' },
    'M10_LB5': { ke: 'M10 5.1', titel: 'Funktionen-Vertiefung', kurz: 'lin · quad · exp im Vergleich', status: 'stub' },
    'M10_LB6': { ke: 'M10 6.1', titel: 'Bruchgleichungen', kurz: 'Definitionsbereich · Lösungsverfahren', status: 'stub' },
  },
};
