// LB-Matrix Sport MS Bayern · LP+-konform · zitierfähig · v1
//
// ARCHITEKTUR
// ────────────────────────────────────────────────────────────────────────
// Sport folgt einer SPIRALCURRICULAREN Logik (NICHT GPG-Lernbereich-Matrix):
// die sportlichen Handlungsfelder wiederholen sich mit wachsender Komplexität
// (Technik → Taktik → Anwendung) über Jgst. 5-10.
//
// SPALTEN: Sportliche Handlungsfelder + Querschnitts-LB
//   LB4.1 Laufen · Springen · Werfen (Leichtathletik)
//   LB4.2 Sich im Wasser bewegen (Schwimmen)
//   LB4.3 Spielen + Wetteifern (Sportspiele · Handball/Fußball/Rückschlag/Alternative)
//   LB4.4 Sich an + mit Geräten bewegen (Turnen)
//   LB4.5 Sich körperlich ausdrücken (Gymnastik + Tanz)
//   LB2   Fairness/Kooperation/Selbstkompetenz (durchgängig)
//   LB3   Gesundheit + Fitness (durchgängig)
//
// ZEILEN: Jgst 5, 6, 7, 8, 9, 10 (M-Zug)
//
// PHASEN-STANDARD (Sport-spezifische 5-Phasen-UE, 45 min)
//   1. Begrüßung + Stundeneinstieg  (3-5 min · Anwesenheit, Sportkleidung, Überblick)
//   2. Aufwärmphase                  (5-10 min · Laufschule + Mobilisation)
//   3. Hauptteil (Technik/Taktik)    (25-30 min · Demo + Übungsreihen + Vertiefung)
//   4. Anwendungsphase               (8-10 min · Spielform/Wettkampfform)
//   5. Ausklang + Reflexion          (3-5 min · Feedback, Sicherung, Geräteabbau)
//
// LERNZIELE 3-DIMENSIONAL (Mager-konform, Sport-spezifisch)
//   - motorisch  (konkrete Bewegungshandlung + Erfolgs-Kriterium)
//   - kognitiv   (Bewegungsverständnis: Phasenmerkmale, Biomechanik)
//   - sozial     (Kooperation, Fairplay, Helfen + Sichern)
//
// PILOT-SEQUENZ: LB 4.3 Sportspiele · Jgst. 7 · »Handball-Schlagwurf«
//   · 9-UE-Sequenz Realbezug GPG7c SJ 25/26 + idealtypische Erweiterung
//   · Schwerpunktstunde: UE 5 BUV »Jahrmarkt« Schlagwurf-Präzision (Stationsbetrieb)
//   · Hallenplan + Helfer-/Sicherungskonzept dokumentiert
//
// QUELLEN
//   · LP+ Bayern Fachprofil Sport · /Sport Ressourcen/Sport_Anleitungen/LehrplanPLUS/Fachprofil Sport/
//   · Jahresplanung_Sport7_2025-26.md (eigene Praxis Sm7abc)
//   · Sequenzplan_Handball_7abc_2025-26.md (Pilot-Material verbatim)
//   · Sport_Anleitungen/Anleitung zur TUV-Erstellung Sport (Sm8ab).md
//   · Sport_BUV_Entwicklung/ROLE_Sport_BUV_Unterrichtsentwicklung_Berater.md
//   · KMBek Sicherheit im Sportunterricht + KUVB

window.MATRIX = {
  fach: 'D Sport',
  fachKuerzel: 'Sport',
  schulart: 'Mittelschule Bayern · Erziehung im + durch Sport',

  meta: {
    version: 'v1 · 2026-05-18 · Sport-Spiral · 5-Phasen-Standard',
    spaltenLogik: 'Sportliche Handlungsfelder LB4.1-4.5 (Leichtathletik · Schwimmen · Sportspiele · Turnen · Gymnastik+Tanz) + Querschnitts-LB2 Fairness + LB3 Gesundheit. NICHT GPG-Lernbereich-Logik.',
    quellenLogik: 'verbatim für LP+ Jgst. 7 (Jahresplanung_Sport7_2025-26 · eigene Quelle) + Pilot Handball (Sequenzplan-MD verbatim). sekundaer für andere Jgst (Anleitungen + KMK-Anker).',
    pilotSequenz: 'LB 4.3 Sportspiele · Jgst. 7 · Handball-Sequenz · 9 UEs · Schwerpunktstunde UE 5 Schlagwurf-Präzision (BUV »Jahrmarkt«) mit Hallenplan + Helferkonzept.',
    fachdidaktikStandard: 'LP+ Bayern Fachprofil Sport + Anleitung TUV Sm8ab + ROLE_Sport_BUV (Qualitätskriterien: Sachanalyse + Did. Reduktion + Method. Analyse + Stundenskizze + Hallenplan + Sicherheit).',
  },

  jgst: [
    { id: 'J5',  label: 'Jgst. 5' },
    { id: 'J6',  label: 'Jgst. 6' },
    { id: 'J7',  label: 'Jgst. 7' },
    { id: 'J8',  label: 'Jgst. 8' },
    { id: 'J9',  label: 'Jgst. 9' },
    { id: 'J10', label: 'Jgst. 10 (M)' },
  ],

  // Sportliche Handlungsfelder + Querschnitts-LB
  lernbereiche: [
    { id: 'LA',  titel: 'LA · Leichtathletik',  kurz: 'Laufen · Springen · Werfen' },
    { id: 'SC',  titel: 'SC · Schwimmen',        kurz: 'Sich im Wasser bewegen' },
    { id: 'SP',  titel: 'SP · Sportspiele',      kurz: 'Spielen + Wetteifern' },
    { id: 'TU',  titel: 'TU · Turnen',           kurz: 'An + mit Geräten bewegen' },
    { id: 'GT',  titel: 'GT · Gymnastik + Tanz', kurz: 'Körperlich ausdrücken' },
    { id: 'FAIR',titel: 'FAIR · Fairness',       kurz: 'Querschnitt: Kooperation · Selbst' },
    { id: 'GES', titel: 'GES · Gesundheit',      kurz: 'Querschnitt: Fitness · Wohlbefinden' },
  ],

  // Pädagogische Perspektiven (Kurz · LP+ Bayern Sport)
  perspektiven: [
    { id: 'P1', label: 'Leistung',     kurz: 'Wettkampf · Messung · Vergleich' },
    { id: 'P2', label: 'Miteinander',  kurz: 'Fairplay · Teamfähigkeit · Unterstützung' },
    { id: 'P3', label: 'Wagnis',       kurz: 'Angst überwinden · Vertrauen' },
    { id: 'P4', label: 'Ausdruck',     kurz: 'Kreativität · Bewegungsgestaltung' },
    { id: 'P5', label: 'Gesundheit',   kurz: 'Körperbewusstsein · Lebensweise · Ausdauer' },
    { id: 'P6', label: 'Spielen',      kurz: 'Mit Ungewissheit umgehen · taktisches Denken' },
  ],

  // Prozessbezogene Kompetenzen (LP+ Sport · 6er-Modell)
  prozesskompetenzen: [
    { id: 'PK1', label: 'Leisten',     kurz: 'Sportliches Handeln zu Gütekriterien setzen · Erfolg/Misserfolg verarbeiten' },
    { id: 'PK2', label: 'Gestalten',   kurz: 'Bewegungen variantenreich · kreativ · individuell einsetzen' },
    { id: 'PK3', label: 'Spielen',     kurz: 'Mit Ungewissheit umgehen · Spielregeln anpassen' },
    { id: 'PK4', label: 'Wahrnehmen-analysieren-bewerten',  kurz: 'Körper · Bewegung · Umgebung differenziert wahrnehmen' },
    { id: 'PK5', label: 'Entscheiden-handeln-verantworten', kurz: 'Sach- + situationsgerechte Entscheidungen treffen' },
    { id: 'PK6', label: 'Kooperieren-kommunizieren-präsentieren', kurz: 'Fair verhalten · kommunizieren · präsentieren' },
  ],

  cells: {
    // ─── J5 ─────────────────────────────────────────────────────────────
    'J5_LA': { ke_anzahl: 1, jgst: 'J5', lb: 'LA', lb_titel: 'Leichtathletik', quelle_status: 'sekundaer',
      kes: [
        { ke_id: 'J5-LA-01', thema: 'Grundbewegungen Laufen + Springen + Werfen',
          ke_wortlaut: 'erfahren Grundbewegungen Laufen, Springen und Werfen spielerisch und in vereinfachten Wettkampfformen.',
          ke_wortlaut_quelle: 'LP+ Bayern MS Sport · Jgst. 5 · sekundaer (Sport-Anleitungen)',
          inhalte_lp: ['Sprintspiele · Schlagball-Weitwurf · Weitsprung Zonenmessung · einfache Staffeln'],
          fundort: 'Sport-Anleitungen Jgst. 5' },
      ],
    },
    'J5_SC': { ke_anzahl: 1, jgst: 'J5', lb: 'SC', lb_titel: 'Schwimmen', quelle_status: 'sekundaer',
      kes: [
        { ke_id: 'J5-SC-01', thema: 'Wassersicherheit + erste Schwimmart',
          ke_wortlaut: 'bewegen sich sicher im Wasser und erlernen eine erste Schwimmart in der Grobform.',
          ke_wortlaut_quelle: 'LP+ Bayern MS Sport · Jgst. 5 · sekundaer',
          inhalte_lp: ['Baderegeln · Wassergewöhnung · Auftrieb · 1. Schwimmart Grobform · Schwimmabzeichen-Anbahnung'],
          fundort: 'Sport-Anleitungen Jgst. 5' },
      ],
    },
    'J5_SP': { ke_anzahl: 1, jgst: 'J5', lb: 'SP', lb_titel: 'Sportspiele', quelle_status: 'sekundaer',
      kes: [
        { ke_id: 'J5-SP-01', thema: 'Kleine Spiele · Fang- und Wurfspiele',
          ke_wortlaut: 'spielen Kleine Spiele mit einfachen Regeln und entwickeln Grundtechniken Fangen + Werfen.',
          ke_wortlaut_quelle: 'LP+ Sport · Jgst. 5 · sekundaer',
          inhalte_lp: ['Kleine Spiele · Fangspiele · Ballspiele mit reduzierten Regeln · Goalchaball-Anbahnung'],
          fundort: 'Sport-Anleitungen Jgst. 5' },
      ],
    },
    'J5_TU': { ke_anzahl: 1, jgst: 'J5', lb: 'TU', lb_titel: 'Turnen', quelle_status: 'sekundaer',
      kes: [
        { ke_id: 'J5-TU-01', thema: 'Bewegungslandschaften + Grundfertigkeiten',
          ke_wortlaut: 'bewegen sich vielfältig in Bewegungslandschaften und entwickeln Grundfertigkeiten an Geräten.',
          ke_wortlaut_quelle: 'LP+ Sport · Jgst. 5 · sekundaer',
          inhalte_lp: ['Bewegungslandschaften (Kletterstangen · Matten · Reck) · Rolle vorwärts · Sprung in den Stütz · Helfen + Sichern (Anbahnung)'],
          fundort: 'Sport-Anleitungen Jgst. 5' },
      ],
    },
    'J5_GT': { ke_anzahl: 1, jgst: 'J5', lb: 'GT', lb_titel: 'Gymnastik + Tanz', quelle_status: 'sekundaer',
      kes: [
        { ke_id: 'J5-GT-01', thema: 'Rhythmische Bewegungsformen',
          ke_wortlaut: 'bewegen sich rhythmisch zu Musik und gestalten kurze Bewegungsfolgen.',
          ke_wortlaut_quelle: 'LP+ Sport · Jgst. 5 · sekundaer',
          inhalte_lp: ['Grundrhythmen · einfache Bewegungsfolgen · Kreistänze · Rope Skipping (Anbahnung)'],
          fundort: 'Sport-Anleitungen Jgst. 5' },
      ],
    },
    'J5_FAIR': { ke_anzahl: 1, jgst: 'J5', lb: 'FAIR', lb_titel: 'Fairness', quelle_status: 'sekundaer',
      kes: [
        { ke_id: 'J5-FAIR-01', thema: 'Spielregeln einhalten + erste Selbstreflexion',
          ke_wortlaut: 'akzeptieren Spielregeln und reflektieren Sieg + Niederlage in einfachen Spielformen.',
          ke_wortlaut_quelle: 'LP+ Sport · Querschnitts-LB',
          inhalte_lp: ['Regelverständnis · Konfliktlösung erste Schritte · Sieg/Niederlage'],
          fundort: 'Sport-Anleitungen Jgst. 5' },
      ],
    },
    'J5_GES': { ke_anzahl: 1, jgst: 'J5', lb: 'GES', lb_titel: 'Gesundheit', quelle_status: 'sekundaer',
      kes: [
        { ke_id: 'J5-GES-01', thema: 'Sportkleidung + Aufwärmen',
          ke_wortlaut: 'kennen die Bedeutung von Sportkleidung und Aufwärmen für Sicherheit und Leistung.',
          ke_wortlaut_quelle: 'LP+ Sport · Querschnitts-LB',
          inhalte_lp: ['Sportkleidung · Hygiene · Aufwärmen · einfache Dehnübungen'],
          fundort: 'Sport-Anleitungen Jgst. 5' },
      ],
    },

    // ─── J6 ─────────────────────────────────────────────────────────────
    'J6_LA': { ke_anzahl: 1, jgst: 'J6', lb: 'LA', lb_titel: 'Leichtathletik', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J6-LA-01', thema: 'Technikgrundlagen LA', ke_wortlaut: 'entwickeln Techniken im Sprint (50 m), Weitwurf und Weitsprung weiter.', ke_wortlaut_quelle: 'LP+ Sport · sekundaer', inhalte_lp: ['Sprint mit Tiefstart-Anbahnung · Weitwurf · Weitsprung Zonenmessung'], fundort: 'Sport-Anleitungen Jgst. 6' }],
    },
    'J6_SC': { ke_anzahl: 1, jgst: 'J6', lb: 'SC', lb_titel: 'Schwimmen', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J6-SC-01', thema: 'Schwimmart vertiefen', ke_wortlaut: 'schwimmen die erste Schwimmart sicher und bewältigen Distanzen bis 25 m.', ke_wortlaut_quelle: 'LP+ Sport · sekundaer', inhalte_lp: ['Brust- oder Kraulschwimmen sicher · 25 m am Stück · Schwimmabzeichen Bronze'], fundort: 'Sport-Anleitungen Jgst. 6' }],
    },
    'J6_SP': { ke_anzahl: 1, jgst: 'J6', lb: 'SP', lb_titel: 'Sportspiele', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J6-SP-01', thema: 'Mannschaftsspiele Hinführung', ke_wortlaut: 'spielen Mannschaftsspiele mit grundlegenden taktischen Elementen.', ke_wortlaut_quelle: 'LP+ Sport · sekundaer', inhalte_lp: ['Goalchaball · Brennball · einfache Ballhandlungs-Techniken · Abwehr/Angriff (Anbahnung)'], fundort: 'Sport-Anleitungen Jgst. 6' }],
    },
    'J6_TU': { ke_anzahl: 1, jgst: 'J6', lb: 'TU', lb_titel: 'Turnen', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J6-TU-01', thema: 'Erste Geräte-Elemente', ke_wortlaut: 'turnen an Geräten erste Elemente und wenden Hilfestellung selbstständig an.', ke_wortlaut_quelle: 'LP+ Sport · sekundaer', inhalte_lp: ['Rolle rückwärts · Sprung (Bock/Kasten) · Hüftaufschwung Reck (Anbahnung) · Helfen + Sichern fest'], fundort: 'Sport-Anleitungen Jgst. 6' }],
    },
    'J6_GT': { ke_anzahl: 1, jgst: 'J6', lb: 'GT', lb_titel: 'Gymnastik + Tanz', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J6-GT-01', thema: 'Bewegungsgestaltung mit Handgerät', ke_wortlaut: 'gestalten Bewegungen mit einem Handgerät zu Musik.', ke_wortlaut_quelle: 'LP+ Sport · sekundaer', inhalte_lp: ['Reifen · Ball · Seil · einfache Choreografien'], fundort: 'Sport-Anleitungen Jgst. 6' }],
    },
    'J6_FAIR': { ke_anzahl: 1, jgst: 'J6', lb: 'FAIR', lb_titel: 'Fairness', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J6-FAIR-01', thema: 'Konfliktlösung im Spiel', ke_wortlaut: 'lösen Konflikte im Spiel konstruktiv und übernehmen Verantwortung im Team.', ke_wortlaut_quelle: 'LP+ Sport · Querschnitts-LB', inhalte_lp: ['Konfliktmoderation · Teamrollen · Verantwortung für Mitspielende'], fundort: 'Sport-Anleitungen Jgst. 6' }],
    },
    'J6_GES': { ke_anzahl: 1, jgst: 'J6', lb: 'GES', lb_titel: 'Gesundheit', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J6-GES-01', thema: 'Ausdauer-Anbahnung', ke_wortlaut: 'führen ausdauernde Belastungen über mindestens 8 min durch.', ke_wortlaut_quelle: 'LP+ Sport · Querschnitts-LB', inhalte_lp: ['Laufen 8 min · Ausdauer-Erfahrung · Pulsmessen (Anbahnung)'], fundort: 'Sport-Anleitungen Jgst. 6' }],
    },

    // ─── J7 (Realbezug Sm7abc · verbatim aus Jahresplanung) ─────────────
    'J7_LA': { ke_anzahl: 1, jgst: 'J7', lb: 'LA', lb_titel: 'Leichtathletik', quelle_status: 'verbatim',
      kes: [{ ke_id: 'J7-LA-01', thema: 'LA-Techniken erweitern + Wettkampf',
        ke_wortlaut: 'erweitern Erfahrungen im Sprint, Weitwurf, Hoch- und Weitsprung mit Anlauf und wenden Grundregeln der LA-Wettkämpfe an.',
        ke_wortlaut_quelle: 'Jahresplanung_Sport7_2025-26 · verbatim LP+',
        inhalte_lp: ['Sprint 50/75 m · Schlagballwurf · Hochsprung (Flop) · Weitsprung · Staffel'],
        fundort: 'Jahresplanung_Sport7_2025-26.md' }],
    },
    'J7_SC': { ke_anzahl: 1, jgst: 'J7', lb: 'SC', lb_titel: 'Schwimmen', quelle_status: 'verbatim',
      kes: [{ ke_id: 'J7-SC-01', thema: 'Zweite Schwimmart + Gesundheit',
        ke_wortlaut: 'schwimmen unter gesundheitlichen Aspekten, bewältigen Strecken bis 50 m in hohem Tempo, bewältigen die Gesamtkoordination einer zweiten Schwimmart in der Grobform und erfüllen Bedingungen für ein Schwimmabzeichen.',
        ke_wortlaut_quelle: 'Jahresplanung_Sport7_2025-26 · verbatim LP+',
        ke_wortlaut_anker: ['gesundheitlichen Aspekten', '50 m in hohem Tempo', 'zweiten Schwimmart', 'Grobform', 'Schwimmabzeichen'],
        inhalte_lp: ['Gesundheitsaspekte (Auftrieb · Rückenlage · Aqua-Jogging) · Schnelligkeit · 2. Schwimmart · Synchronschwimmen · Abzeichen'],
        fundort: 'Jahresplanung_Sport7_2025-26.md · KW 43-11' }],
    },
    'J7_SP': { ke_anzahl: 2, jgst: 'J7', lb: 'SP', lb_titel: 'Sportspiele', quelle_status: 'verbatim',
      kes: [
        { ke_id: 'J7-SP-01', thema: '★ Sportspiel-Techniken Handball/Fußball + Individualtaktik',
          ke_wortlaut: 'verwenden sportartspezifische Techniken im Handball und Fußball zur Lösung spielnaher Situationsaufgaben, wenden individualtaktische Verhaltensweisen gezielt an und fügen diese zu gruppentaktischen Grundstrukturen zusammen.',
          ke_wortlaut_quelle: 'Sequenzplan_Handball_7abc_2025-26 · verbatim LP+',
          ke_wortlaut_anker: ['sportartspezifische Techniken', 'Handball', 'spielnaher Situationsaufgaben', 'individualtaktische Verhaltensweisen', 'gruppentaktischen Grundstrukturen'],
          inhalte_lp: ['Handball: Stoppen (Sternschritt) · Prellen · Passen · Schlagwurf · Sprungwurf · Anbieten · Freilaufen · Decken · Goalchaball', 'Fußball: Dribbling · An-/Mitnahme · Kurzpass · Torschuss', 'Badminton · Tchoukball (Querverweis)'],
          fundort: 'Sequenzplan_Handball_7abc_2025-26.md',
          umsetzung_typ: 'real',
          umsetzung_titel: 'Sequenz Handball Sm7abc (KW 39/2025 - KW 10/2026 · 8 UEs + BUV + LP)',
          umsetzung_klasse: 'GPG7c Sm7abc',
          umsetzung_datum: 'KW 39/2025 - KW 10/2026',
          pilot_sequenz: {
            titel: '9-UE-Sequenz Handball · Schwerpunkt Schlagwurf-Präzision',
            praxis: 'Eigene Praxis Sm7abc SJ 25/26 verbatim + BUV-Standard',
            gesamtzeit: '9 UEs à 45 min = 6,75 Zeitstunden',
            phasenStandard: 'Sport-Bayern · 5-Phasen-UE (Begrüßung · Aufwärmen · Hauptteil · Anwendung · Ausklang)',
            qualitaetsstandards_quelle: 'Sport Ressourcen · LP+ Fachprofil Sport + Anleitung TUV-Erstellung Sm8ab + ROLE_Sport_BUV_Berater + KMBek Sicherheit',
            sequenz_meta: {
              lehrplanbezug: 'Sport Jgst. 7 · LB 4.3 Spielen + Wetteifern (Sportspiele) · Querverweise LB 2 Fairness + LB 3 Wetteifern',
              kompetenzerwartungen_verbatim: [
                'Die Schülerinnen und Schüler verwenden sportartspezifische Techniken im Handball zur Lösung spielnaher Situationsaufgaben.',
                'Die Schülerinnen und Schüler wenden individualtaktische Verhaltensweisen im Handball gezielt an und fügen diese zu gruppentaktischen Grundstrukturen zusammen.',
                'Die Schülerinnen und Schüler beschreiben einfache sportartspezifische Bewegungsmerkmale fachgerecht und setzen diese bei ihrer sportlichen Betätigung um.',
                'Die Schülerinnen und Schüler würdigen den Fairplay-Gedanken als übergeordnetes Ziel.',
              ],
              inhalte_lp_verbatim: [
                'Passen · Fangen · Prellen · Stoppen (Sternschritt) · Schlagwurf · Sprungwurf',
                'Anbieten · Freilaufen · Decken · Positionswechsel',
                'Goalchaball als Hinführungs-Spielform',
                'Handball 7v7 als Anwendungs-Spielform',
              ],
              zielsetzung_uebergeordnet: 'Die Sequenz baut Handball-Grundtechniken systematisch von der Hinführung über Goalchaball (UE 1-4) zur Technikvertiefung Schlagwurf (UE 5 BUV-Schwerpunktstunde) und Sprungwurf (UE 7 LP) bis zum Anwendungsturnier (UE 8) auf. Schwerpunkt-Stunde UE 5 demonstriert Stationsbetrieb-Methode + Differenzierung in 4 Spuren + dokumentierten Hallenplan mit Helferkonzept.',
              methodische_schwerpunkte: [
                'Stationsbetrieb (UE 5) als zentrale Methode der Schwerpunktstunde · 3 parallele Stationen + Rotation',
                'Spielform-Progression: Goalchaball (vereinfacht) → Handball 7v7 (Regelform) gemäß didaktischer Reduktion',
                'Differenzierung in 4 Spuren (DaZ · LRS · leistungsschwach · leistungsstark) operationalisiert pro Station',
                'Helfen + Sichern als Pflicht (LB 2 Fairness integriert · Sicherheits-KMBek)',
                '5-Phasen-UE (Begrüßung · Aufwärmen · Hauptteil · Anwendung · Ausklang) konsequent',
              ],
              kompetenzerwerb_progression: 'Pädagogische Perspektiven-Mix: UE 1-3 vorrangig P6 Spielen + P2 Miteinander (Goalchaball-Hinführung). UE 4 P3 Wagnis (erste Handball-Spielsituationen). UE 5 BUV Schlagwurf: P1 Leistung + P4 Wahrnehmen-bewerten (AFB II-III). UE 6 LNW Drehwurf P1 (AFB III-Bewertung). UE 7 LP Sprungwurf P1+P4 (komplexere Technik). UE 8 Miniturnier P6+P2+P5 (alle Perspektiven integriert · Fairplay als Querschnitt).',
              personifikation_durchgaengig: 'Anders als bei GPG/WiB nutzt Sport KEINE Identifikationsfigur, sondern operiert über die SuS selbst als Akteure. Stattdessen: konsequente Verwendung von "ich kann X" (Selbstwirksamkeits-Sprache LP+ Sport) und individuelle Trefferquoten-Ziele.',
              schwerpunktstunde_kandidat: 'UE 5 · BUV-Schlagwurf-Präzision (Stationsbetrieb · Hallenplan · Helferkonzept · 4-Spuren-Differenzierung · AFB I-III)',
            },
            sequenz_tabelle: [
              { uze: 1, datum: 'KW 39', stundenthema_frage: 'Wie spielen wir gemeinsam — auch wenn wir uns noch nicht kennen?',
                prozesskompetenz: 'PK6 Kooperieren', gegenstand: 'Sportspiele', perspektive: 'P2 Miteinander',
                stundenziel_kurz: 'Kleine Spiele · Goalchaball-Einführung · Bedürfnisse Mitschüler:innen',
                kommentar: 'Sequenz-Einstieg · Kennenlernen · Partnerübungen Passen/Fangen', schwerpunkt: false },
              { uze: 2, datum: 'KW 40', stundenthema_frage: 'Was sind die Spielideen von Goalchaball?',
                prozesskompetenz: 'PK3 Spielen', gegenstand: 'Sportspiele', perspektive: 'P6 Spielen',
                stundenziel_kurz: 'Goalchaball-Spielidee + erste Spielformen',
                kommentar: 'Wiederholung Passen/Fangen · Vertiefung', schwerpunkt: false },
              { uze: 3, datum: 'KW 41', stundenthema_frage: 'Wie wenden wir Passen + Fangen in Spielformen an?',
                prozesskompetenz: 'PK3 Spielen · PK1 Leisten', gegenstand: 'Sportspiele', perspektive: 'P6 + P1',
                stundenziel_kurz: 'Passen/Fangen in Spielform · Stationsbetrieb · Spielformen 3v3',
                kommentar: 'Stationsbetrieb · Spielformen 3v3', schwerpunkt: false },
              { uze: 4, datum: 'KW 44', stundenthema_frage: 'Wie führen Überzahl-Spiele zu Handball?',
                prozesskompetenz: 'PK3 Spielen · PK5 Entscheiden', gegenstand: 'Sportspiele', perspektive: 'P6 + P3',
                stundenziel_kurz: 'Individualtaktik · Überzahlspiele 3v2 + 4v3',
                kommentar: 'Handball-Hinführung über Überzahlspiele', schwerpunkt: false },
              { uze: 5, datum: 'KW 49', stundenthema_frage: 'Wie werfe ich gezielt mit Schlagwurf zum Tor?',
                prozesskompetenz: 'PK1 Leisten · PK4 Wahrnehmen-analysieren', gegenstand: 'Sportspiele',
                perspektive: 'P1 + P4', stundenziel_kurz: 'Schlagwurf-Präzision spielnah · Stationsbetrieb',
                kommentar: '**BUV-SCHWERPUNKTSTUNDE** · Stationsbetrieb · Hallenplan · 4-Spuren-Diff', schwerpunkt: true },
              { uze: 6, datum: 'KW 03', stundenthema_frage: 'Beherrsche ich den Drehwurf — und passt mein Spielverständnis Goalchaball?',
                prozesskompetenz: 'PK1 Leisten', gegenstand: 'Sportspiele', perspektive: 'P1',
                stundenziel_kurz: 'LNW Drehwurf + Spielnote Goalchaball',
                kommentar: 'Prüfungsformat · Leistungserhebung', schwerpunkt: false },
              { uze: 7, datum: 'Mo 02.03., KW 10', stundenthema_frage: 'Wie schließe ich spielnah mit Sprungwurf ab?',
                prozesskompetenz: 'PK1 Leisten · PK4 Wahrnehmen', gegenstand: 'Sportspiele',
                perspektive: 'P1 + P4', stundenziel_kurz: 'Sprungwurf-Technik · spielnah anwenden',
                kommentar: 'LP-Stunde (Lehrprobe) · Sondertermin · Erweiterung Wurfkompetenz', schwerpunkt: false },
              { uze: 8, datum: 'Mi 04.03., KW 10', stundenthema_frage: 'Wie integrieren wir Technik + Taktik + Fairplay im Turnier?',
                prozesskompetenz: 'PK3 Spielen · PK6 Kooperieren · PK5 Entscheiden', gegenstand: 'Sportspiele + Fairness',
                perspektive: 'P6 + P2 + P1', stundenziel_kurz: 'Miniturnier Handball 7v7 · Fairplay-Reflexion',
                kommentar: 'Sequenzabschluss · Turnierform · Anwendung', schwerpunkt: false },
              { uze: 9, datum: 'KW 11', stundenthema_frage: 'Was nehme ich mit aus der Handball-Sequenz?',
                prozesskompetenz: 'PK4 Wahrnehmen-bewerten · PK6 Kommunizieren', gegenstand: 'Sportspiele',
                perspektive: 'P4 + P5', stundenziel_kurz: 'Reflexion · Selbsteinschätzung · Transfer',
                kommentar: 'Sequenz-Reflexion · Heft + Selbsteinschätzungsbogen', schwerpunkt: false },
            ],
            phasenSchema: [
              { id: 's1_begruessung', label: '1 Begrüßung',       kurz: 'Anwesenheit · Sportkleidung · Stundenüberblick (3-5 min)' },
              { id: 's2_aufwaermen',  label: '2 Aufwärmen',        kurz: 'Laufschule + Mobilisation (5-10 min)' },
              { id: 's3_hauptteil',   label: '3 Hauptteil',        kurz: 'Technik-Demo + Übungsreihe + Vertiefung (25-30 min)' },
              { id: 's4_anwendung',   label: '4 Anwendung',        kurz: 'Spielform / Wettkampfform (8-10 min)' },
              { id: 's5_ausklang',    label: '5 Ausklang',         kurz: 'Reflexion · Sicherung · Abbau (3-5 min)' },
            ],
            ues_detail: [
              // UE 5 (BUV-Schwerpunktstunde — voll ausgearbeitet)
              {
                nr: 5,
                titel: 'BUV »Jahrmarkt« · Schlagwurf-Präzision Stationsbetrieb',
                stundenthema_frage: 'Wie werfe ich gezielt mit Schlagwurf zum Tor?',
                minuten: 45,
                lernziel: 'SuS wenden den Schlagwurf zielgenau in Stationsformen an und reflektieren ihre Treffquote.',
                lernziel_stundenziel: {
                  verhalten: 'Die Schuelerinnen und Schueler fuehren den Schlagwurf mit korrekter Schrittfolge, Armfuehrung und Koerperspannung aus und treffen mit ihm gezielt,',
                  bedingung: 'indem sie an drei rotierenden Stationen (Zielwurf · Wurfschule · Wandwurf) den Schlagwurf isoliert und im Anschluss in einer Goalchaball-Spielform anwenden,',
                  maszstab: 'was daran erkennbar wird, dass jede:r SuS bei Station 1 (Zielwurf 5 m) mindestens drei von fuenf Wuerfen das Huetchen-Tor trifft und im Spiel mindestens zweimal einen Schlagwurf einsetzt.'
                },
                lernziel_teilziele: [
                  { tz: 'MOTORISCH · SuS fuehren den Schlagwurf phasengerecht aus,',
                    indem: 'indem sie die drei Phasen (Aushol · Beschleunigung · Release) am Leitbild beobachten und an der Station Wurfschule isoliert üben,',
                    erkennbar: 'was daran erkennbar wird, dass sie mindestens drei Bewegungsmerkmale (Schrittfolge · Schulterdrehung · Handgelenk-Schnipp) in ihrer Ausfuehrung zeigen.', afb: 'II', differenziert: false },
                  { tz: 'KOGNITIV · SuS benennen die drei Phasen des Schlagwurfs fachgerecht,',
                    indem: 'indem sie nach der Lehrkraft-Demo die Bewegungsmerkmale am Plakat zuordnen,',
                    erkennbar: 'was daran erkennbar wird, dass sie im Ausklang die Begriffe Aushol/Beschleunigung/Release den richtigen Bewegungsbildern zuordnen.', afb: 'I', differenziert: false },
                  { tz: 'SOZIAL · SuS korrigieren Partner respektvoll und konstruktiv,',
                    indem: 'indem sie an den Stationen mindestens einen Hinweis pro Partner geben (z.B. "Dreh deine Schulter mit"),',
                    erkennbar: 'was daran erkennbar wird, dass die Beobachter-Karten von jeder Person mindestens einen konstruktiven Hinweis enthalten.', afb: 'II', differenziert: false },
                  { tz: '[Differenziert / leistungsstark] SuS bewerten ihre Wurftechnik selbstkritisch,',
                    indem: 'indem sie aus den drei Bewegungsmerkmalen das eigene Verbesserungs-Schwerpunkt-Merkmal benennen,',
                    erkennbar: 'was daran erkennbar wird, dass sie im Ausklang ihren konkreten Trainingsfokus formulieren (z.B. "Naechste Stunde achte ich auf die Schulterdrehung").', afb: 'III', differenziert: true },
                ],
                s1_begruessung: '3\' · Anwesenheit am Halleneingang · Sportkleidung kontrollieren · Stundenuebersicht an Tafel: "Heute Schlagwurf in 3 Stationen + Spielform Goalchaball."',
                s2_aufwaermen: '7\' · Laufschule mit Hütchen-Parcours (Anfersen · Knie-Heben · Skipping) + dynamische Mobilisation Schultergürtel (Armkreisen vor/zurück · Halten 5 sek).',
                s3_hauptteil: '20\' · Lehrkraft-Demo Schlagwurf am Halbkreis (3\') · Stationsbetrieb 3 Stationen (15\' · 3-4\' pro Station + Rotation): St.1 Zielwurf 5m auf Huetchen (3 Wuerfe · Partner zaehlt) · St.2 Wurfschule Schrittfolge auf Becken-Seite (ohne dann mit Ball) · St.3 Wandwurf gegen Wand + Reaktion-Fangen. Beobachter-Karten in Hand. Letzte 2\' Tafel-Sammlung Beobachtungen.',
                s4_anwendung: '10\' · Spielform Goalchaball 3v3 auf 2 parallelen Feldern (Hütchen-Tore) · Fokus: Schlagwurf-Einsatz in Spielsituation · 2 mal 4\' mit Wechsel.',
                s5_ausklang: '5\' · Sitzkreis · Reflexion: "Welches Bewegungsmerkmal gelang? Welches nicht?" · Begriffs-Zuordnung Aushol/Beschleunigung/Release · Selbstwirksamkeits-Aussage: "Naechste Stunde achte ich auf ___" · Geräteabbau koordiniert.',
                phasen_minuten: { s1_begruessung: 3, s2_aufwaermen: 7, s3_hauptteil: 20, s4_anwendung: 10, s5_ausklang: 5 },
                sozialform_phasen: {
                  s1_begruessung: 'Halbkreis (Halleneingang)',
                  s2_aufwaermen: 'Plenum · Laufwege markiert',
                  s3_hauptteil: 'GA (3er-Gruppen Stationen-Rotation)',
                  s4_anwendung: '2 parallele Spielfelder · GA 3v3',
                  s5_ausklang: 'Sitzkreis Plenum',
                },
                differenzierung_block: {
                  daz: 'Bewegungsmerkmale als Bilder (Stationen-Karten mit Foto-Schritten). Wortspeicher Aushol · Beschleunigung · Release · Schlagwurf. Demonstrieren statt erklaeren. Partner-Tandem mit Deutsch-Buddy.',
                  lrs: 'Stationen-Karten in 18pt+ Schrift · Foto-Sequenzen statt Lesetexten · Beobachterkarte mit Symbolen (Daumen hoch / seitlich / runter).',
                  leistungsschwach: 'Station 1 Distanz 3 m statt 5 m · weicherer Ball · Wurfschule ohne Ball (nur Schrittfolge) · vorgegebene Beobachtungs-Punkte ankreuzen.',
                  leistungsstark: 'Station 1 Distanz 7 m + Sprungwurf-Vorbereitung · Beobachter-Rolle uebernehmen + Partner kompetent korrigieren · AFB III Selbst-Verbesserungsfokus benennen (Zusatz-Lernziel TZ4).',
                },
                personifikation_anteil: 'Sport nutzt KEINE Identifikationsfigur sondern SELBSTWIRKSAMKEITSSPRACHE: "Ich kann den Schlagwurf gezielt einsetzen — heute werfe ich 3 von 5 ins Tor."',
                tafelbild_skizze: 'Tafel: 3 Phasen Schlagwurf mit Foto-Sequenz (Aushol · Beschleunigung · Release) + Stations-Karte (3 Stationen + Rotation-Reihenfolge) · Selbstwirksamkeits-Slogan.',
                hallenplan: 'Halle 20 x 12 m. St.1 Zielwurf (5m Wurflinie · Huetchen-Tor an Wand) NORDseite. St.2 Wurfschule (Becken-Seite SUEDOST · Matten unter Beckenrand). St.3 Wandwurf (WESTwand · 1 m Sicherheitsabstand). Spielfelder fuer Anwendung: 2 parallele 8x6 m im Hallenzentrum (Hütchen-Tore). Eingang OSTseite (Sicherheitszone).',
                helferkonzept: 'St.2 Wurfschule: Matten unter Beckenrand (Absturzsicherung). St.3 Wandwurf: 1 m Mindestabstand zur Wand markiert. Stationen-Rotation: zuegig · keine Warteschlangen · Lehrkraft positioniert sich rotierend zwischen Stationen.',
                sicherheit: 'Aufwaermen Pflicht (Verletzungsprophylaxe Schulterguertel) · Sportkleidung kontrolliert · Ball-Groesse altersgerecht · St.3 Wandwurf-Mindestabstand · St.2 Matten · Kollisionszone Spielfelder durch Huetchen markiert.',
                hausaufgabe: '—',
                material: '20 Handbälle (Größe 1) · 8 Hütchen · 4 Markierungshemden · Beobachter-Karten (1 pro SuS) · Stations-Karten A4 (3 Stationen, laminiert) · Audio-Aufnahmegerät optional fuer Reflexion · Hallenplan-Skizze A3 sichtbar',
                lp_bezug: 'KE J7-SP-01 (Schlagwurf · Individualtaktik) · KE J7-FAIR-01 (Helfen + Sichern) · KE J7-GES-01 (Aufwaermen + Verletzungsprophylaxe)',
                prinzipien_b3: ['Mehrperspektivitaet', 'Differenzierung', 'Sicherheit', 'Fairplay-Erziehung', 'Selbstwirksamkeit'],
                kompetenzstruktur: {
                  gegenstand: 'Sportspiele (LB 4.3) · Fairness (LB 2)',
                  perspektive: 'P1 Leistung · P4 Wahrnehmen · P2 Miteinander',
                  prozesskompetenz: 'PK1 Leisten · PK4 Wahrnehmen-analysieren-bewerten · PK6 Kooperieren-kommunizieren',
                },
                sachanalyse: {
                  bewegungsphasen: 'Schlagwurf 3 Phasen: (1) AUSHOL (Arm auf Schulterhoehe, Ellbogen >= 90 Grad Flexion, Oberarm 45 Grad Abduktion) · (2) BESCHLEUNIGUNG (schnelle Armextension, Schulter-Hueft-Rotation, Schrittfolge stabilisiert Rumpfspannung) · (3) RELEASE (Handgelenk-Schnipp fuer Drall, Zeige-/Mittelfinger letzte Kontaktpunkte).',
                  biomechanik: 'Kettenbildung Beine -> Rumpf -> Arm -> Hand. Energie-Uebertragung von gross zu klein. Beschleunigungsprinzip (schnelle Kurzbewegungen Arm > Wurfgeschwindigkeit).',
                  fehlerbilder: 'Fehler 1: Nur Arm arbeitet (keine Koerperdrehung) -> schwache Wurfkraft + Ellbogen-Belastung. Korrektur: "Drehe Schultern mit". Fehler 2: Schrittfolge unzureichend -> instabile Basis. Korrektur: "Schritt-Wurf gleichzeitig".',
                  lernvoraussetzungen: 'Grundwurfkoordination aus Grundschule vorhanden. Schlagwurf neuer Bewegungsablauf. Koerperliche Voraussetzung: Schulterguertelkraft nach pubertaerer Entwicklung Jgst. 7 ausreichend. Vorerfahrung: Goalchaball-Spiel in UE 1-4 trainiert Wurfsituationen.',
                },
                didaktische_reduktion: 'Schlagwurf-Grobform vor Feinform: Schrittfolge zunaechst ohne Ball geuebt (St.2). Goalchaball 3v3 statt Handball 7v7 reduziert Komplexitaet (kleineres Feld · weniger Gegner · vereinfachte Regeln). Sprungwurf wird absichtlich erst in UE 7 LP eingefuehrt um Schlagwurf zu festigen.',
                didaktik: 'Stationsbetrieb (TUV-Anleitung Sm8ab) · 3-Phasen-Modell der Bewegungsanalyse (Meinel/Schnabel) · Differenzierung in 4 Spuren · Selbstwirksamkeits-Sprache LP+ · Hallenplan + Helferkonzept als BUV-Pflicht (ROLE_Sport_BUV)'
              },
              // Restliche UEs als Geruest
              { nr: 1, titel: 'Kleine Spiele/Goalchaball-Hinfuehrung', stundenthema_frage: 'Wie spielen wir gemeinsam — auch wenn wir uns noch nicht kennen?', minuten: 45,
                lernziel: 'SuS spielen Goalchaball als kooperative Hinfuehrung zum Sportspiel und entwickeln Passen+Fangen.',
                stage: 'geruest', material: 'Goalchaball-Bälle · Hütchen · Markierungshemden',
                prinzipien_b3: ['Fairplay-Erziehung', 'Kennenlernen'], lp_bezug: 'KE J7-SP-01 · KE J7-FAIR-01',
                kompetenzstruktur: { gegenstand: 'Sportspiele', perspektive: 'P2 Miteinander · P6 Spielen', prozesskompetenz: 'PK6 Kooperieren · PK3 Spielen' },
                hinweis: 'In Folge-Iteration alle 5 Phasen voll ausarbeiten.' },
              { nr: 2, titel: 'Goalchaball Vertiefung', stundenthema_frage: 'Was sind die Spielideen von Goalchaball?', minuten: 45,
                lernziel: 'SuS verstehen die Spielidee Goalchaball und wenden Passen+Fangen in Spielformen an.',
                stage: 'geruest', material: 'Goalchaball-Bälle · Tore · Hütchen',
                prinzipien_b3: ['Mehrperspektivitaet (P3+P6)'], lp_bezug: 'KE J7-SP-01',
                kompetenzstruktur: { gegenstand: 'Sportspiele', perspektive: 'P6 Spielen', prozesskompetenz: 'PK3 Spielen' },
                hinweis: 'In Folge-Iteration alle 5 Phasen voll ausarbeiten.' },
              { nr: 3, titel: 'Goalchaball Festigung · Stationsbetrieb', stundenthema_frage: 'Wie wenden wir Passen + Fangen in Spielformen an?', minuten: 45,
                lernziel: 'SuS wenden Passen+Fangen in Stationsformen an und spielen 3v3 selbststaendig.',
                stage: 'geruest', material: 'Stations-Karten · Bälle · Hütchen',
                prinzipien_b3: ['Differenzierung', 'Selbsttaetigkeit'], lp_bezug: 'KE J7-SP-01',
                kompetenzstruktur: { gegenstand: 'Sportspiele', perspektive: 'P6 + P1', prozesskompetenz: 'PK3 Spielen · PK1 Leisten' },
                hinweis: 'Probe-UE fuer Stationsbetrieb der BUV (UE 5).' },
              { nr: 4, titel: 'Handball Hinfuehrung · Ueberzahlspiele', stundenthema_frage: 'Wie führen Überzahl-Spiele zu Handball?', minuten: 45,
                lernziel: 'SuS wenden Individualtaktik in Überzahlsituationen 3v2 und 4v3 an.',
                stage: 'geruest', material: 'Handbälle · Hütchen · Markierungshemden',
                prinzipien_b3: ['Mehrperspektivitaet', 'Spiel-Progression'], lp_bezug: 'KE J7-SP-01',
                kompetenzstruktur: { gegenstand: 'Sportspiele', perspektive: 'P6 + P3 + P5', prozesskompetenz: 'PK3 Spielen · PK5 Entscheiden' },
                hinweis: 'In Folge-Iteration alle 5 Phasen voll ausarbeiten.' },
              { nr: 6, titel: 'LNW Drehwurf + Spielnote Goalchaball', stundenthema_frage: 'Beherrsche ich den Drehwurf — und passt mein Spielverständnis Goalchaball?', minuten: 45,
                lernziel: 'SuS weisen Drehwurf-Technik in LNW nach und zeigen Spielverstaendnis Goalchaball.',
                stage: 'geruest', material: 'LNW-Bogen · Bälle · Bewertungsraster',
                prinzipien_b3: ['Veraenderte Leistungsmessung', 'AFB-Stufung'], lp_bezug: 'KE J7-SP-01',
                kompetenzstruktur: { gegenstand: 'Sportspiele', perspektive: 'P1 Leistung', prozesskompetenz: 'PK1 Leisten · PK4 Wahrnehmen' },
                hinweis: 'Pruefungsformat · LNW-Stunde.' },
              { nr: 7, titel: 'LP Sprungwurf · spielnahe Anwendung', stundenthema_frage: 'Wie schließe ich spielnah mit Sprungwurf ab?', minuten: 45,
                lernziel: 'SuS erweitern Wurfkompetenz auf Sprungwurf und wenden ihn spielnah in Goalchaball an.',
                stage: 'geruest', material: 'Handbälle · Tore · Hallenplan',
                prinzipien_b3: ['Mehrperspektivitaet (P1+P4)', 'Spiral-Anschluss (Schlagwurf -> Sprungwurf)'], lp_bezug: 'KE J7-SP-01',
                kompetenzstruktur: { gegenstand: 'Sportspiele', perspektive: 'P1 + P4', prozesskompetenz: 'PK1 Leisten · PK4 Wahrnehmen' },
                hinweis: 'Lehrprobe-Stunde · Sondertermin · 2. Stunde Sonderschiene.' },
              { nr: 8, titel: 'Miniturnier Handball 7v7 · Fairplay-Anwendung', stundenthema_frage: 'Wie integrieren wir Technik + Taktik + Fairplay im Turnier?', minuten: 45,
                lernziel: 'SuS wenden Technik+Taktik im Handball-Miniturnier an und reflektieren Fairplay als Querschnitt.',
                stage: 'geruest', material: 'Handbälle · Tore · Spielplan · Schiedsrichter-Karten',
                prinzipien_b3: ['Fairplay-Erziehung', 'Mehrperspektivitaet (P1+P2+P5+P6)'], lp_bezug: 'KE J7-SP-01 · KE J7-FAIR-01',
                kompetenzstruktur: { gegenstand: 'Sportspiele + Fairness', perspektive: 'P6 + P2 + P1', prozesskompetenz: 'PK3 Spielen · PK6 Kooperieren · PK5 Entscheiden' },
                hinweis: 'Sequenz-Abschluss · Turnierform.' },
              { nr: 9, titel: 'Sequenz-Reflexion · Heft + Selbsteinschätzung', stundenthema_frage: 'Was nehme ich mit aus der Handball-Sequenz?', minuten: 45,
                lernziel: 'SuS reflektieren ihre Lernertraege schriftlich und benennen einen Transferbereich (Freizeit/Verein).',
                stage: 'geruest', material: 'Heft · Selbsteinschätzungsbogen · Reflexions-Karten',
                prinzipien_b3: ['Selbst-Regulation', 'Veraenderte Leistungsmessung'], lp_bezug: 'KE J7-SP-01 + Querschnitt',
                kompetenzstruktur: { gegenstand: 'Sportspiele', perspektive: 'P4 + P5', prozesskompetenz: 'PK4 Wahrnehmen-bewerten · PK6 Kommunizieren' },
                hinweis: 'Sequenz-Reflexion · Heft-LZK.' },
            ],
            bezuege_global: [
              { didaktik: 'Sport-5-Phasen-UE (Anleitung TUV-Erstellung Sm8ab)', verweis: 'Verbindlich Sport-Seminar Bayern: Begrüßung · Aufwärmen · Hauptteil · Anwendung · Ausklang. Konsequent in jeder UE durchgehalten.' },
              { didaktik: 'BUV-Qualitätskriterien (ROLE_Sport_BUV)', verweis: 'UE 5 BUV-Schwerpunktstunde: Mager-3D-Lernziele (motorisch + kognitiv + sozial) · Sachanalyse mit Phasenmodell + Biomechanik + Fehlerbilder · Didaktische Reduktion · Methodische Analyse · Stundenskizze · Hallenplan + Helferkonzept · Sicherheitsmaßnahmen explizit.' },
              { didaktik: 'Mehrperspektivität (LP+ Bayern Sport Fachprofil)', verweis: 'Sequenz aktiviert 5 pädagogische Perspektiven: P1 Leisten (Schlagwurf-Trefferquote) · P2 Miteinander (Partnerkorrektur) · P3 Wagnis (erste Spielsituation) · P4 Wahrnehmen (Bewegungsmerkmale) · P5 Gesundheit (Aufwärmen) · P6 Spielen (Goalchaball). Mehrperspektivität als didaktisches Pflichtprinzip.' },
              { didaktik: 'Sicherheitserziehung (KMBek + KUVB)', verweis: 'Pro UE Sicherheitsmaßnahmen dokumentiert. UE 5 BUV: Hallenplan mit Gefahrenstellen (Wand · Beckenrand) markiert · Helferkonzept (Matten unter Beckenrand · Sicherheitsabstand Wand) · Aufwärmen als Verletzungsprophylaxe · altersgerechte Bälle.' },
              { didaktik: 'Differenzierung in 4 Spuren', verweis: 'DaZ (Bewegungsmerkmale als Bilder · Wortspeicher) · LRS (Stations-Karten 18pt+) · leistungsschwach (Distanz 3m statt 5m · weicherer Ball) · leistungsstark (Distanz 7m · Beobachter-Rolle · AFB III Selbst-Verbesserungsfokus).' },
              { didaktik: 'Bewegungsanalyse 3-Phasen-Modell (Meinel/Schnabel)', verweis: 'Schlagwurf: Aushol · Beschleunigung · Release. Biomechanische Kette Beine→Rumpf→Arm→Hand. Beschleunigungsprinzip. Sachanalyse-Standard fuer BUV.' },
              { didaktik: 'Spiral-Progression Sport (LP+ Bayern Sport)', verweis: 'Vertikale Progression: Jgst. 5/6 Kleine Spiele + Goalchaball-Anbahnung → Jgst. 7 Handball-Techniken (DIESE Sequenz) → Jgst. 8/9 Handball-Gruppentaktik + Turnierform. Spiralcurricular nicht linear.' },
              { didaktik: 'Selbstwirksamkeit (LP+ Bayern Sport)', verweis: 'Sport nutzt SELBSTWIRKSAMKEITSSPRACHE statt Personifikation: SuS formulieren "ich kann · ich erreiche · ich verbessere". Verankert im LP+-Schwerpunkt Erziehung IM Sport.' },
              { didaktik: 'Aufgabenkultur differenziert + Leistungsmessung', verweis: 'UE 6 LNW Drehwurf mit AFB-Stufung. Kompetenzorientiertes Beurteilen LP+ Sport. Veraenderte Leistungsmessung.' },
              { didaktik: 'Fairplay-Erziehung als Querschnitt (LB 2)', verweis: 'In jeder UE explizit (Partnerkorrektur respektvoll · Helfen + Sichern · Turnier-Fairplay-Reflexion UE 8). Fairplay als uebergeordnetes Ziel (KE J7-FAIR-01).' },
            ]
          }
        },
        { ke_id: 'J7-SP-02', thema: 'Rückschlagspiele + alternative Spiele',
          ke_wortlaut: 'erweitern Erfahrungen in Rückschlagspielen und alternativen Spielen.',
          ke_wortlaut_quelle: 'Jahresplanung_Sport7_2025-26',
          inhalte_lp: ['Badminton-Grundtechniken · Tchoukball · alternative Spiele Tag-Rugby (optional)'],
          fundort: 'Jahresplanung_Sport7_2025-26.md' },
      ],
    },
    'J7_TU': { ke_anzahl: 1, jgst: 'J7', lb: 'TU', lb_titel: 'Turnen', quelle_status: 'verbatim',
      kes: [{ ke_id: 'J7-TU-01', thema: 'Geräteturnen + Elementverbindung',
        ke_wortlaut: 'turnen an Geräten und verbinden Elemente, wenden Sicherheits- und Hilfestellungsregeln an.',
        ke_wortlaut_quelle: 'Jahresplanung_Sport7_2025-26 · verbatim LP+',
        inhalte_lp: ['Grundfertigkeiten an 2 Geraeten (Boden · Reck/Barren) · Partner-Akrobatik · Helfen + Sichern'],
        fundort: 'Jahresplanung_Sport7_2025-26.md' }],
    },
    'J7_GT': { ke_anzahl: 1, jgst: 'J7', lb: 'GT', lb_titel: 'Gymnastik + Tanz', quelle_status: 'verbatim',
      kes: [{ ke_id: 'J7-GT-01', thema: 'Gestalten mit Rhythmus + Gruppenchoreografie',
        ke_wortlaut: 'gestalten Bewegungen mit und ohne Handgerät zu verschiedenen Rhythmen und präsentieren Gruppenchoreografien.',
        ke_wortlaut_quelle: 'Jahresplanung_Sport7_2025-26 · verbatim LP+',
        inhalte_lp: ['Rope Skipping · rhythmische Bewegungsformen · Gruppenchoreografien'],
        fundort: 'Jahresplanung_Sport7_2025-26.md' }],
    },
    'J7_FAIR': { ke_anzahl: 1, jgst: 'J7', lb: 'FAIR', lb_titel: 'Fairness', quelle_status: 'verbatim',
      kes: [{ ke_id: 'J7-FAIR-01', thema: 'Fairplay + Kooperation + Selbstreflexion',
        ke_wortlaut: 'hinterfragen Spielregeln, bewerten Verstöße und schätzen Fairplay; respektieren Mitschüler:innen-Bedürfnisse auch unter Wettbewerbsbedingungen.',
        ke_wortlaut_quelle: 'Jahresplanung_Sport7_2025-26 · verbatim LP+',
        ke_wortlaut_anker: ['Spielregeln', 'Fairplay', 'Mitschüler:innen-Bedürfnisse', 'Wettbewerbsbedingungen'],
        inhalte_lp: ['Spielsituationsanalyse · Kooperationsaufgaben · gegenseitige Korrektur · Konflikte konstruktiv loesen'],
        fundort: 'Jahresplanung_Sport7_2025-26.md (LB 2 Querschnitt)' }],
    },
    'J7_GES': { ke_anzahl: 1, jgst: 'J7', lb: 'GES', lb_titel: 'Gesundheit', quelle_status: 'verbatim',
      kes: [{ ke_id: 'J7-GES-01', thema: 'Ausdauer + Ernährung + Funktionsuebungen',
        ke_wortlaut: 'achten auf gesunde Ernährung, setzen sich kritisch mit Gewichtsregulation auseinander und führen abwechslungsreiche aerobe Belastungsformen durch.',
        ke_wortlaut_quelle: 'Jahresplanung_Sport7_2025-26 · verbatim LP+',
        inhalte_lp: ['Ausdauertraining (Schwimmen · Walking) · funktionelle Uebungen (Bauch + Ruecken) · Ernaehrung · Fluessigkeitshaushalt'],
        fundort: 'Jahresplanung_Sport7_2025-26.md (LB 3 Querschnitt)' }],
    },

    // ─── J8/J9/J10 — alle als kompakte KE-Zellen (Stubs) ──────────────
    'J8_LA': { ke_anzahl: 1, jgst: 'J8', lb: 'LA', lb_titel: 'Leichtathletik', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J8-LA-01', thema: 'LA-Mehrkampf + Bundesjugendspiele',
        ke_wortlaut: 'absolvieren einen leichtathletischen Mehrkampf und bewerten ihre Leistung anhand von Bundesjugendspiel-Tabellen.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 8 · sekundaer',
        inhalte_lp: ['Sprint · Weitwurf · Hochsprung · Weitsprung · Ausdauerlauf · Mehrkampf-Wertung'],
        fundort: 'Sport-Anleitungen Jgst. 8' }],
    },
    'J8_SC': { ke_anzahl: 1, jgst: 'J8', lb: 'SC', lb_titel: 'Schwimmen', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J8-SC-01', thema: '2 Schwimmarten + Streckenschwimmen',
        ke_wortlaut: 'schwimmen zwei Schwimmarten sicher und bewältigen eine Strecke von 100 m.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 8 · sekundaer',
        inhalte_lp: ['Brust + Kraul (oder Brust + Rücken) · 100 m am Stück · Schwimmabzeichen Silber'],
        fundort: 'Sport-Anleitungen Jgst. 8' }],
    },
    'J8_SP': { ke_anzahl: 1, jgst: 'J8', lb: 'SP', lb_titel: 'Sportspiele', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J8-SP-01', thema: 'Handball/Fußball Gruppentaktik vertieft',
        ke_wortlaut: 'wenden gruppentaktische Verhaltensweisen im Handball/Fussball gezielt an und uebernehmen Spielpositionen verantwortungsbewusst.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 8 · sekundaer',
        inhalte_lp: ['Positionsspiel · Raumdeckung · Spielzuege · 6:0/3:2:1-Abwehr (Handball-Anbahnung)'],
        fundort: 'Sport-Anleitungen Jgst. 8' }],
    },
    'J8_TU': { ke_anzahl: 1, jgst: 'J8', lb: 'TU', lb_titel: 'Turnen', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J8-TU-01', thema: 'Komplexere Geräte-Verbindungen',
        ke_wortlaut: 'turnen komplexere Geräte-Verbindungen mit eigener Choreografie und uebernehmen Helferfunktionen kompetent.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 8 · sekundaer',
        inhalte_lp: ['Boden-Choreografie · Reck-Hueftaufschwung · Sprung · Partner-Akrobatik · Helfen verantwortlich'],
        fundort: 'Sport-Anleitungen Jgst. 8' }],
    },
    'J8_GT': { ke_anzahl: 1, jgst: 'J8', lb: 'GT', lb_titel: 'Gymnastik + Tanz', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J8-GT-01', thema: 'Tanzformen + Choreografien selbst gestalten',
        ke_wortlaut: 'gestalten eigene Tanzchoreografien in Gruppen und praesentieren diese im Plenum.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 8 · sekundaer',
        inhalte_lp: ['Aktuelle Tanzformen · HipHop / Modern · Gruppenchoreografie · Praesentation'],
        fundort: 'Sport-Anleitungen Jgst. 8' }],
    },
    'J8_FAIR': { ke_anzahl: 1, jgst: 'J8', lb: 'FAIR', lb_titel: 'Fairness', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J8-FAIR-01', thema: 'Selbstkonzept + Stärken-Schwächen reflektieren',
        ke_wortlaut: 'reflektieren ihre eigene sportliche Entwicklung und akzeptieren Staerken sowie Schwaechen im Team.',
        ke_wortlaut_quelle: 'LP+ Sport · Querschnitts-LB',
        inhalte_lp: ['Selbstkonzept · Staerken-Schwaechen-Profil · Teamrollen'],
        fundort: 'Sport-Anleitungen Jgst. 8' }],
    },
    'J8_GES': { ke_anzahl: 1, jgst: 'J8', lb: 'GES', lb_titel: 'Gesundheit', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J8-GES-01', thema: 'Cooper-Test + Fitness-Diagnostik',
        ke_wortlaut: 'absolvieren einen Cooper-Test und entwickeln ein persoenliches Fitness-Programm.',
        ke_wortlaut_quelle: 'LP+ Sport · Querschnitts-LB',
        inhalte_lp: ['12-Minuten-Lauf · Pulsmessung · Trainingsplanung · Trainingsbereiche aerob/anaerob'],
        fundort: 'Sport-Anleitungen Jgst. 8' }],
    },

    // ─── J9 ─────────────────────────────────────────────────────────────
    'J9_LA': { ke_anzahl: 1, jgst: 'J9', lb: 'LA', lb_titel: 'Leichtathletik', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J9-LA-01', thema: 'LA-Wettkampf + Trainingsplanung',
        ke_wortlaut: 'planen einen leichtathletischen Trainingsprozess und absolvieren einen Wettkampf.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 9 · sekundaer',
        inhalte_lp: ['Trainingsplanung 4 Wochen · Wettkampf-Vorbereitung · Reflexion Leistungsentwicklung'],
        fundort: 'Sport-Anleitungen Jgst. 9' }],
    },
    'J9_SC': { ke_anzahl: 1, jgst: 'J9', lb: 'SC', lb_titel: 'Schwimmen', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J9-SC-01', thema: '3 Schwimmarten + Rettungsschwimmen',
        ke_wortlaut: 'schwimmen drei Schwimmarten und kennen Grundlagen des Rettungsschwimmens.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 9 · sekundaer',
        inhalte_lp: ['Brust + Kraul + Rueckenschwimmen · 200 m am Stueck · Rettungsschwimm-Grundlagen · Schwimmabzeichen Gold'],
        fundort: 'Sport-Anleitungen Jgst. 9' }],
    },
    'J9_SP': { ke_anzahl: 1, jgst: 'J9', lb: 'SP', lb_titel: 'Sportspiele', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J9-SP-01', thema: 'Sportspiele Wettkampf + Schiedsrichtertaetigkeit',
        ke_wortlaut: 'fuehren Sportspiele in Wettkampfform durch und uebernehmen Schiedsrichter- und Organisationsaufgaben.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 9 · sekundaer',
        inhalte_lp: ['Handball-Turnier · Schiedsrichter-Zeichen · Spielprotokoll · Tabellenfuehrung'],
        fundort: 'Sport-Anleitungen Jgst. 9' }],
    },
    'J9_TU': { ke_anzahl: 1, jgst: 'J9', lb: 'TU', lb_titel: 'Turnen', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J9-TU-01', thema: 'Kreative Boden- und Gerätechoreografie',
        ke_wortlaut: 'gestalten eigene Choreografien an Boden und Geraet und praesentieren diese.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 9 · sekundaer',
        inhalte_lp: ['Choreografie · Boden + 1 Geraet · Gruppenpraesentation'],
        fundort: 'Sport-Anleitungen Jgst. 9' }],
    },
    'J9_GT': { ke_anzahl: 1, jgst: 'J9', lb: 'GT', lb_titel: 'Gymnastik + Tanz', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J9-GT-01', thema: 'Choreografische Eigenproduktion',
        ke_wortlaut: 'entwickeln und praesentieren eine eigene tänzerische Komposition in der Gruppe.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 9 · sekundaer',
        inhalte_lp: ['Choreografische Eigenproduktion · Musikauswahl · Praesentation · Bewertungsraster'],
        fundort: 'Sport-Anleitungen Jgst. 9' }],
    },
    'J9_FAIR': { ke_anzahl: 1, jgst: 'J9', lb: 'FAIR', lb_titel: 'Fairness', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J9-FAIR-01', thema: 'Vereinssport + Engagement',
        ke_wortlaut: 'reflektieren das eigene Sportengagement im Verein/Freizeit und planen langfristige Sport-Routinen.',
        ke_wortlaut_quelle: 'LP+ Sport · Querschnitts-LB',
        inhalte_lp: ['Vereinssport · Ehrenamt · Sport als Lebenslang-Aufgabe'],
        fundort: 'Sport-Anleitungen Jgst. 9' }],
    },
    'J9_GES': { ke_anzahl: 1, jgst: 'J9', lb: 'GES', lb_titel: 'Gesundheit', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J9-GES-01', thema: 'Trainingsplanung + Doping-Reflexion',
        ke_wortlaut: 'planen ein persoenliches Fitness-Programm und reflektieren kritisch Doping und Risikoverhalten.',
        ke_wortlaut_quelle: 'LP+ Sport · Querschnitts-LB',
        inhalte_lp: ['Trainingsplanung 6 Wochen · Doping-Praevention · Risikoverhalten Sportlehrer-Begleitung'],
        fundort: 'Sport-Anleitungen Jgst. 9' }],
    },

    // ─── J10 (M-Zug) ────────────────────────────────────────────────────
    'J10_LA': { ke_anzahl: 1, jgst: 'J10', lb: 'LA', lb_titel: 'Leichtathletik', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J10-LA-01', thema: 'LA-Wettkampf höheres Niveau',
        ke_wortlaut: 'absolvieren einen leichtathletischen Wettkampf auf Mittlerer-Reife-Niveau.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 10 M · sekundaer',
        inhalte_lp: ['Wettkampf · Mehrkampf · Reflexion · Vorbereitung Berufseinstieg'],
        fundort: 'Sport-Anleitungen Jgst. 10' }],
    },
    'J10_SC': { ke_anzahl: 1, jgst: 'J10', lb: 'SC', lb_titel: 'Schwimmen', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J10-SC-01', thema: 'Schwimmen Anwendung + Rettung',
        ke_wortlaut: 'wenden Schwimmtechniken in Rettungssituationen an und uebernehmen Verantwortung in Aufsichtssituationen.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 10 M · sekundaer',
        inhalte_lp: ['Rettungsschwimmen · Tauch-Bergen · Aufsicht (Anbahnung)'],
        fundort: 'Sport-Anleitungen Jgst. 10' }],
    },
    'J10_SP': { ke_anzahl: 1, jgst: 'J10', lb: 'SP', lb_titel: 'Sportspiele', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J10-SP-01', thema: 'Sportspiele - Verein-Anschluss',
        ke_wortlaut: 'spielen Sportspiele auf vereinsnahem Niveau und reflektieren Anschlussmoeglichkeiten im Verein.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 10 M · sekundaer',
        inhalte_lp: ['Vereinsanschluss · Trainerausbildung-Anbahnung · ehrenamtliche Tätigkeit'],
        fundort: 'Sport-Anleitungen Jgst. 10' }],
    },
    'J10_TU': { ke_anzahl: 1, jgst: 'J10', lb: 'TU', lb_titel: 'Turnen', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J10-TU-01', thema: 'Geräteturnen Wettkampf',
        ke_wortlaut: 'turnen vollständige Übungsverbindungen an Geräten auf Wettkampf-Niveau.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 10 M · sekundaer',
        inhalte_lp: ['Verbundenes Turnen Wettkampf · Bewertung · Helferqualifikation'],
        fundort: 'Sport-Anleitungen Jgst. 10' }],
    },
    'J10_GT': { ke_anzahl: 1, jgst: 'J10', lb: 'GT', lb_titel: 'Gymnastik + Tanz', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J10-GT-01', thema: 'Choreografie Wettkampf-Niveau',
        ke_wortlaut: 'praesentieren eine choreografische Wettkampfproduktion auf Mittlerer-Reife-Niveau.',
        ke_wortlaut_quelle: 'LP+ Sport · Jgst. 10 M · sekundaer',
        inhalte_lp: ['Choreografie Wettkampf · Musikauswahl · Bewertungsraster · Praesentation'],
        fundort: 'Sport-Anleitungen Jgst. 10' }],
    },
    'J10_FAIR': { ke_anzahl: 1, jgst: 'J10', lb: 'FAIR', lb_titel: 'Fairness', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J10-FAIR-01', thema: 'Sport als Lebenslang-Aufgabe',
        ke_wortlaut: 'reflektieren Sport als Lebenslang-Aufgabe und planen den Übergang in Beruf/Freizeit.',
        ke_wortlaut_quelle: 'LP+ Sport · Querschnitts-LB',
        inhalte_lp: ['Beruf + Sport · Vereinsanschluss · ehrenamtliches Engagement'],
        fundort: 'Sport-Anleitungen Jgst. 10' }],
    },
    'J10_GES': { ke_anzahl: 1, jgst: 'J10', lb: 'GES', lb_titel: 'Gesundheit', quelle_status: 'sekundaer',
      kes: [{ ke_id: 'J10-GES-01', thema: 'Persönliches Gesundheitskonzept',
        ke_wortlaut: 'entwickeln ein persoenliches Gesundheitskonzept fuer Beruf und Freizeit.',
        ke_wortlaut_quelle: 'LP+ Sport · Querschnitts-LB',
        inhalte_lp: ['Gesundheitskonzept · Beruf-Sport-Balance · Stressmanagement · Rückenfreundlich Arbeiten'],
        fundort: 'Sport-Anleitungen Jgst. 10' }],
    },
  },
};
